Energine: Energine\share\gears\ComponentConfig Class Reference
Energine\share\gears\ComponentConfig Class Reference
Component configuration manager.
Public Member Functions
__construct ($config, $className, $moduleName)
Initialize configuration.
setCurrentState ($methodName)
Set current state.
getCurrentStateConfig ()
Get configuration of current state.
isEmpty ()
Check if configuration is empty.
getActionByURI ($path)
Get action name from configuration.
getStateConfig ($methodName)
Get state configuration for specific state.
getCurrentStateParams ()
Get list of current state parameters from configuration file.
Public Attributes
const SITE_CONFIG_DIR = '/modules/%s/config/'
Site configuration directory.
const CORE_CONFIG_DIR = '/modules/%s/config/'
Core configuration directory.
Protected Member Functions
registerState ($methodName, $patterns, $rights=false)
Register state.
Private Member Functions
getConfigPath ($configFilename, $moduleName)
Get full path to the configuration file.
Private Attributes
$config = false
Configuration file.
$currentState = false
Configuration of the current state.
Detailed Description
Component configuration manager.
class ComponentConfig;
Definition at line 24 of file ComponentConfig.php.
Constructor & Destructor Documentation
Energine\share\gears\ComponentConfig::__construct ($config, $className, $moduleName)
Initialize configuration.
Parameters
mixed $config Configuration or configuration filename.
string $className Class name.
string $moduleName Module name.
Returns
ComponentConfig
Exceptions
SystemException 'ERR_DEV_BAD_CONFIG_FILE'
SystemException 'ERR_DEV_STRANGE'
Definition at line 65 of file ComponentConfig.php.
{
         //Если это строка(с именем файла) или false
         if (!$config || is_string($config)) {
             $config = ($param = $this->getConfigPath($config, $moduleName)) ? $param
                     : $this->getConfigPath(simplifyClassName($className) . '.component.xml', $moduleName);
             if ($config) {
                 try {
                     $this->config = simplexml_load_file($config /*, 'ConfigElement'*/);
                 } catch (\Exception  $e) {
                     throw new SystemException('ERR_DEV_BAD_CONFIG_FILE', SystemException::ERR_DEVELOPER, $config);
                 }
             }
         } //А может это конфиг из шаблона?
         elseif (is_a($config, 'SimpleXMLElement')) {
             $this->config = $config;
         } else {
             //Этого не может быть
             throw new SystemException('ERR_DEV_STRANGE', SystemException::ERR_DEVELOPER, func_get_args());
             //поскольку быть этого не может никогда
         }
     }
Member Function Documentation
Energine\share\gears\ComponentConfig::getActionByURI ($path)
Get action name from configuration.
It based on URI request.
Parameters
string $path URI path.
Returns
array
Definition at line 174 of file ComponentConfig.php.
{
         $actionName = false;
         $actionParams = array();
         $path = '/' . $path;
         $patterns = array();
         //счетчик приоритета паттерна
         $weightInc = $maxWeightInc = sizeof($this->config->state);
         //Дальше идет что то мутное
         //наша цель расставиьт приоритеты паттернов состояний
         foreach ($this->config->state as $method) {
             if (isset($method->uri_patterns->pattern)) {
                 $weightInc--;
                 //А это счетчик приоритета внутри набора паттернов
                 $maxPatternPriority = sizeof($method->uri_patterns->pattern) - 1;
                 //вообщем в результате мы получаем что у нас приоритеты выставлены как нужно
                 //то есть чем выше - тем важнее
                 foreach ($method->uri_patterns->pattern as $pattern) {
                     $patterns[(string)$pattern] = array(
                         'method' => (string)$method['name'],
                         //'rights' => ((isset($method['rights']))?(int)$method['rights']),
                         'weight' => ((!isset($method['weight'])) ? ($weightInc + $maxPatternPriority * 0.1) : ($maxWeightInc++))
                     );
                     $maxPatternPriority--;
                 }
             }
         }
         //сортируем  по приоритету
         uasort($patterns, function ($a, $b) {
             return $a['weight'] < $b['weight'];
         });
         foreach ($patterns as $pattern => $methodInfo) {
             $methodName = $methodInfo['method'];
             try {
                 $resPattern = preg_replace(
                     array('/\[any\]\//', '/\//', '/\[[a-zA-Z_]+\]/'),
                     array('(.*)', '\/', '([^\/]+)'),
                     $pattern
                 );
             } catch (Exception $e) {
                 $resPattern = $pattern;
             }
             $matches = array();
             if (preg_match($resPattern = "/^$resPattern$/", $path, $matches)) {
                 $useSegments = sizeof(array_filter(explode('/', $pattern)));
                 if ($useSegments) {
                     if (strpos($pattern, '[any]') !== false) {
                         $useSegments--;
                     }
                     E()->getRequest()->useSegments(E()->getRequest()->getUsedSegments() + $useSegments);
                 }
                 array_shift($matches);
                 $actionName = $methodName;
                 if (!empty($matches)) {
                     preg_match($resPattern, $pattern, $varNames);
                     array_shift($varNames);
                     $varNames = str_replace(array('[', ']'), '', $varNames);
                     $actionParams = array_combine($varNames, $matches);
                 }
                 break;
             }
         }
         if ($actionName == false) {
             return false;
         }
         return array('name' => $actionName, 'params' => $actionParams);
     }
Energine\share\gears\ComponentConfig::getConfigPath ($configFilename, $moduleName) private
Get full path to the configuration file.
It will return false if the file was not found.
Parameters
string $configFilename Configuration file name.
string $moduleName Module name.
Returns
string|bool
Definition at line 97 of file ComponentConfig.php.
Referenced by Energine\share\gears\ComponentConfig\__construct().
{
         $file = false;
         if ($configFilename && !file_exists($file = $configFilename)) {
             //Смотрим в директории текущего сайта с пользовательскими конфигами
             if (!file_exists($file = sprintf(SITE_DIR . self::SITE_CONFIG_DIR . $configFilename, E()->getSiteManager()->getCurrentSite()->folder))) {
                 if (!file_exists($file = sprintf(CORE_DIR . self::CORE_CONFIG_DIR, $moduleName) . $configFilename)) {
                     //если файла с указанным именем нет ни в папке с пользовательскими конфигами, ни в папке модуля с конфигами
                     //throw new SystemException('ERR_DEV_NO_CONFIG', SystemException::ERR_DEVELOPER, $configFilename);
                     $file = false;
                 }
             }
         }
         return $file;
     }
Energine\share\gears\ComponentConfig::getCurrentStateConfig ()
Get configuration of current state.
Returns
Definition at line 154 of file ComponentConfig.php.
{
         return $this->currentState;
     }
Energine\share\gears\ComponentConfig::getCurrentStateParams ()
Get list of current state parameters from configuration file.
Returns
array|bool
Definition at line 271 of file ComponentConfig.php.
{
         $result = false;
         //Если уже задано текущее состояние
         // и конфиг не пуст
         //и в нем есть узел параметров
         //и в этом узле есть дочерние
         if ($this->currentState && !$this->isEmpty() && isset($this->currentState->params) && sizeof($this->currentState->params->children())) {
             $result = array();
             foreach ($this->currentState->params->param as $tagName => $param) {
                 if (($tagName == 'param') && isset($param['name'])) {
                     $result[(string)$param['name']] = (string)$param;
                 }
             }
         }
         return $result;
     }
Energine\share\gears\ComponentConfig::getStateConfig ($methodName)
Get state configuration for specific state.
Parameters
string $methodName Method name.
Returns
|false
Definition at line 255 of file ComponentConfig.php.
Referenced by Energine\share\gears\ComponentConfig\setCurrentState().
{
         $result = false;
         if (!$this->isEmpty()) {
             $methodConfig = $this->config->xpath(sprintf('state[@name=\'%s\'][parent::configuration]', $methodName));
             if (!empty($methodConfig)) {
                 $result = $methodConfig[0];
             }
         }
         return $result;
     }
Energine\share\gears\ComponentConfig::isEmpty ()
Check if configuration is empty.
Returns
boolean
Definition at line 163 of file ComponentConfig.php.
Referenced by Energine\share\gears\ComponentConfig\getCurrentStateParams(), and Energine\share\gears\ComponentConfig\getStateConfig().
{
         return ($this->config) ? false : true;
     }
Energine\share\gears\ComponentConfig::registerState ($methodName, $patterns, $rights = false) protected
Register state.
Parameters
string $methodName Method name.
array | string $patterns Set of patterns.
bool | int $rights Rights.
Definition at line 133 of file ComponentConfig.php.
Referenced by Energine\share\gears\DataSetConfig\__construct(), Energine\share\gears\GridConfig\__construct(), and Energine\share\gears\SiteEditorConfig\__construct().
{
         if ($this->config) {
             $newState = $this->config->addChild('state');
             $newState->addAttribute('name', $methodName);
             $newState->addAttribute('weight', true);
             if ($rights) {
                 $newState->addAttribute('rights', $rights);
             }
             if (!is_array($patterns)) $patterns = array($patterns);
             $uriPatterns = $newState->addChild('uri_patterns');
             foreach ($patterns as $pattern) {
                 $uriPatterns->addChild('pattern', $pattern);
             }
         }
     }
Energine\share\gears\ComponentConfig::setCurrentState ($methodName)
Set current state.
Parameters
string $methodName Method name.
Exceptions
SystemException 'ERR_NO_METHOD '
Definition at line 119 of file ComponentConfig.php.
{
         if (!($this->currentState = $this->getStateConfig($methodName))) {
             //inspect($this->c, $this->config->xpath(sprintf('/configuration/state[@name=\'%s\']', $methodName)));
             throw new SystemException('ERR_NO_METHOD ' . $methodName, SystemException::ERR_DEVELOPER, $methodName);
         }
     }
Member Data Documentation
SimpleXMLElement Energine\share\gears\ComponentConfig::$config = false private
Configuration file.
Definition at line 46 of file ComponentConfig.php.
Referenced by Energine\share\gears\DataSetConfig\__construct(), Energine\share\gears\GridConfig\__construct(), Energine\share\gears\SiteEditorConfig\__construct(), and Energine\share\gears\ComponentConfig\__construct().
SimpleXMLElement Energine\share\gears\ComponentConfig::$currentState = false private
Configuration of the current state.
Definition at line 52 of file ComponentConfig.php.
Referenced by Energine\share\gears\ComponentConfig\getCurrentStateConfig().
string Energine\share\gears\ComponentConfig::CORE_CONFIG_DIR = '/modules/%s/config/'
Core configuration directory.
Path to the directory, that contains configuration files for standard components.
Note
s will be substituted to the module name, that contains the component.
Definition at line 40 of file ComponentConfig.php.
Referenced by Energine\share\components\Grid\defineParams(), and Energine\share\components\Grid\fkEditor().
string Energine\share\gears\ComponentConfig::SITE_CONFIG_DIR = '/modules/%s/config/'
Site configuration directory.
Path to the directory, that contains configuration files for the component.
Definition at line 30 of file ComponentConfig.php.
Referenced by Energine\share\components\Grid\defineParams().
The documentation for this class was generated from the following file:
core/modules/share/gears/ComponentConfig.php