Energine: Energine\share\gears\DBStructureInfo Class Reference
Energine\share\gears\DBStructureInfo Class Reference
Data base structure information.
Public Member Functions
__construct (\PDO $pdo)
tableExists ($tableName)
Check if some table exist.
getTableMeta ($tableName)
Get table meta data.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Private Member Functions
collectDBInfo ()
Collect the table structure information of all tables in the DB.
analyzeView ($viewName)
Analyze view structure.
analyzeTable ($tableName)
Analyze table structure.
Static Private Member Functions
static convertType ($mysqlType)
Convert MySQL field types to the Energine field types.
Private Attributes
$structure
Structure information.
$pdo
PDO (PHP Data Objects).
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
Data base structure information.
final class DBStructureInfo;
It can holds an information in cache.
Attention
This is final.
Definition at line 28 of file DBStructureInfo.php.
Constructor & Destructor Documentation
Energine\share\gears\DBStructureInfo::__construct (\PDO $pdo)
Parameters
\PDO $pdo PDO instance.
Definition at line 57 of file DBStructureInfo.php.
{
         $this->pdo = $pdo;
         $mc = E()->getCache();
         if($mc->isEnabled()){
             if(!($this->structure = $mc->retrieve(Cache::DB_STRUCTURE_KEY))){
                 $mc->store(Cache::DB_STRUCTURE_KEY, $this->structure = $this->collectDBInfo());
             }
         }
     }
Member Function Documentation
Energine\share\gears\DBStructureInfo::analyzeTable ($tableName) private
Analyze table structure.
Parameters
string $tableName Table name.
Returns
array|PDOStatement|string
Exceptions
SystemException
Definition at line 179 of file DBStructureInfo.php.
Referenced by Energine\share\gears\DBStructureInfo\getTableMeta().
{
         $dTableName = DBA::getFQTableName($tableName, true);
         $query = '/*ms=slave*/SHOW CREATE TABLE '.implode('.', $dTableName);
         $dbName = '';
         if(sizeof($dTableName) == 2){
             $dbName = $dTableName[0];
         }
         $res = $this->pdo->query($query);
         if(!$res){
             throw new SystemException('BAD_TABLE_NAME '.$tableName, SystemException::ERR_DB, $query);
         }
         $sql = $res->fetchColumn(1);
         $res = array();
         $s = strpos($sql, '(');
         $l = strrpos($sql, ')') - $s;
         // работаем только с полями и индексами
         $fields = substr($sql, $s + 1, $l);
         $trimQ = function($s) {
             return trim($s, '`');
         };
         $row = '(?:^\s*`(?<name>\w+)`' . // field name
                 '\s+(?<type>\w+)' . //field type
                 '(?:\((?<len>\w+)\))?' . //field len
                 '(?:\s+(?<unsigned>unsigned))?' .
                 '(?:\s*(?<is_null>(?:NOT )?NULL))?' .
                 '(?:\s+DEFAULT (?<default>(?:NULL|\'[^\']+\')))?' .
                 '.*$)';
         $constraint =
                 '(?:^\s*CONSTRAINT `(?<constraint>\w+)` FOREIGN KEY \(`(?<cname>\w+)`\) REFERENCES `(?<tableName>\w+)` \(`(?<fieldName>\w+)`\)' .
                         '.*$)';
         $mul = '(?:^\s*(?:UNIQUE\s*)?KEY\s+`\w+`\s+\((?<muls>.*)\),?$)';
         $pri = '(?:PRIMARY KEY\s+\((?<pri>[^\)]*)\))';
         $pattern = "/(?:$row|$constraint|$mul|$pri)/im";
         if (preg_match_all($pattern, trim($fields), $matches)) {
             if ($matches['name']) {
                 // список полей в первичном ключе
                 $pri = array();
                 if (isset($matches['pri'])) {
                     foreach ($matches['pri'] as $priField) {
                         if ($priField) {
                             $pri = array_map($trimQ, explode(',', $priField));
                             break;
                         }
                     }
                 }
                 // список полей входящих в индексы
                 $muls = array();
                 if (isset($matches['muls'])) {
                     $mulStr = '';
                     foreach ($matches['muls'] as $s) {
                         if ($s) $mulStr .= ($mulStr ? ',' : '') . $s;
                     }
                     $muls = array_map($trimQ, explode(',', $mulStr));
                 }
                 foreach ($matches['name'] as $index => $fieldName) {
                     if (!$fieldName) continue;
                     $res[$fieldName] = array(
                         'nullable' => (
                                 $matches['is_null'][$index] != 'NOT NULL'),
                         'length' => (int)$matches['len'][$index],
                         'default' => (strcasecmp(trim($matches['default'][$index], "'"), 'null') == 0)? null: trim($matches['default'][$index], "'"),
                         'key' => false,
                         'type' => self::convertType($matches['type'][$index]),
                         'index' => false,
                     );
                     // входит ли поле в индекс
                     if (in_array($fieldName, $pri)) {
                         $res[$fieldName]['index'] = 'PRI';
                         $res[$fieldName]['key'] = true;
                     }
                     elseif (in_array($fieldName, $muls)) {
                         $res[$fieldName]['index'] = 'MUL';
                     }
                     // внешний ключ
                     $cIndex = array_search($fieldName, $matches['cname']);
                     if ($cIndex !== false) {
                         $res[$fieldName]['key'] = array(
                             'tableName' => (($dbName) ? $dbName.'.' : '').$matches['tableName'][$cIndex],
                             'fieldName' => $matches['fieldName'][$cIndex],
                             'constraint' => $matches['constraint'][$cIndex],
                         );
                     }
                 }
             }
         }
         return $res;
     }
Energine\share\gears\DBStructureInfo::analyzeView ($viewName) private
Analyze view structure.
Parameters
string $viewName View name.
Returns
array|bool
Definition at line 149 of file DBStructureInfo.php.
Referenced by Energine\share\gears\DBStructureInfo\getTableMeta().
{
         if(!($res = $this->pdo->query('/*ms=slave*/SHOW COLUMNS FROM `'.$viewName.'`')->fetchAll(\PDO::FETCH_ASSOC))) return false;
         //Считаем что первое поле - PK
         $result = array();
         foreach($res as $rowIndex => $fieldData){
             $matches = array();
             preg_match('/\w+/', $fieldData['Type'], $matches);
             $type = self::convertType($matches[0]);
             $result[$fieldData['Field']] = array(
                 'key' => ($rowIndex === 0)?true:false,
                 'nullable' => (strtolower($fieldData['Null']) == 'yes')?true: false,
                 'type'=> $type,
                 'length' => ($type == DBA::COLTYPE_STRING)?100:10,
                 'index' => ($rowIndex === 0)?'PRI': false,
                 'default' => ''
             );
         }
         return $result;
     }
Energine\share\gears\DBStructureInfo::collectDBInfo () private
Collect the table structure information of all tables in the DB.
This can be called only by using cache.
Returns
array
Definition at line 74 of file DBStructureInfo.php.
Referenced by Energine\share\gears\DBStructureInfo\__construct().
{
         $result = array();
         $res = $this->pdo->query('/*ms=slave*/SHOW TABLES');
         if ($res) {
             while ($tableName = $res->fetchColumn()) {
                 $result[$tableName] = $this->getTableMeta($tableName);
             }
         }
         return $result;
     }
static Energine\share\gears\DBStructureInfo::convertType ($mysqlType) static private
Convert MySQL field types to the Energine field types.
Parameters
string $mysqlType MySQL type
Returns
string
Definition at line 286 of file DBStructureInfo.php.
{
         $result = $mysqlType = strtoupper($mysqlType);
         switch ($mysqlType) {
             case 'TINYINT':
             case 'MEDIUM':
             case 'SMALLINT':
             case 'INT':
             case 'BIGINT':
                 $result = DBA::COLTYPE_INTEGER;
                 break;
             case 'FLOAT':
             case 'DOUBLE':
             case 'DECIMAL':
             case 'NUMERIC':
                 $result = DBA::COLTYPE_FLOAT;
                 break;
             case 'DATE':
                 $result = DBA::COLTYPE_DATE;
                 break;
             case 'TIME':
                 $result = DBA::COLTYPE_TIME;
                 break;
             case 'TIMESTAMP':
                 $result = DBA::COLTYPE_TIMESTAMP;
                 break;
             case 'DATETIME':
                 $result = DBA::COLTYPE_DATETIME;
                 break;
             case 'VARCHAR':
             case 'CHAR':
                 $result = DBA::COLTYPE_STRING;
                 break;
             case 'TEXT':
             case 'TINYTEXT':
             case 'MEDIUMTEXT':
             case 'LONGTEXT':
                 $result = DBA::COLTYPE_TEXT;
                 break;
             case 'BLOB':
             case 'TINYBLOB':
             case 'MEDIUMBLOB':
             case 'LONGBLOB':
                 $result = DBA::COLTYPE_BLOB;
                 break;
             default: // не используется
         }
         return $result;
     }
Energine\share\gears\DBStructureInfo::getTableMeta ($tableName)
Get table meta data.
Parameters
string $tableName Table name.
Returns
mixed
Definition at line 125 of file DBStructureInfo.php.
Referenced by Energine\share\gears\DBStructureInfo\collectDBInfo().
{
         if (!isset($this->structure[$tableName]) ||
                 ($this->structure[$tableName] === array())) {
             //@todo тут все нужно свести только к вызову метода анализа таблицы
             $this->structure[$tableName] = $this->analyzeTable($tableName);
             if(empty($this->structure[$tableName])){
                 //Скорее всего это view
                 //анализируем его
                 $this->structure[$tableName] = $this->analyzeView($tableName);
             }
             $this->structure[$tableName] = array_map(function($row) use($tableName){ $row['tableName'] = $tableName; return $row;}, $this->structure[$tableName]);
         }
         return $this->structure[$tableName];
     }
Energine\share\gears\DBStructureInfo::tableExists ($tableName)
Check if some table exist.
Parameters
string $tableName Table name.
Returns
bool
Definition at line 92 of file DBStructureInfo.php.
{
         $result = false;
         //Если не существует в кеше
         if (!isset($this->structure[$tableName])) {
             $FQTableName = DBA::getFQTableName($tableName, true);
             $query = '/*ms=slave*/SHOW TABLES '.((sizeof($FQTableName) == 2)?' FROM `'.reset($FQTableName).'` ':'').' LIKE \''.end($FQTableName).'\'';
             //если существует в списке таблиц
             if ($this->pdo->query($query) && $this->pdo->query($query)->rowCount()) {
                 $result = true;
                 $this->structure[$tableName] = array();
             }
             else {
                 //в списке таблиц  - не значится
                 $this->structure[$tableName] = false;
             }
         }
         else {
             $result = is_array($this->structure[$tableName]) ;
         }
         return $result;
     }
Member Data Documentation
PDO Energine\share\gears\DBStructureInfo::$pdo private
PDO (PHP Data Objects).
Definition at line 52 of file DBStructureInfo.php.
Referenced by Energine\share\gears\DBStructureInfo\__construct().
array Energine\share\gears\DBStructureInfo::$structure private
Structure information.
Structure:
array(
    $tableName => false| null | array(
        $coulmnName => array(
            $columnPropName => $columnPropValue
        )
    )
)
Definition at line 45 of file DBStructureInfo.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/DBStructureInfo.php