Energine: Energine\share\components\Grid Class Reference
Energine\share\components\Grid Class Reference
Grid.
Public Member Functions
__construct ($name, $module, array $params=null)
build ()
Build block.
Public Member Functions inherited from Energine\share\components\DBDataSet
__construct ($name, $module, array $params=null)
getTableName ()
Get table name.
getFilter ()
Get filter.
addFilterCondition ($filter)
Add filter condition.
getPK ()
Get filed name of primary key.
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const DIR_UP = '<'
Direction: up.
const DIR_DOWN = '>'
Direction: dowm.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
getConfig ()
add ()
Show add form.
edit ()
Show edit form.
delete ()
Delete.
deleteData ($id)
Delete record.
getDataLanguage ()
Get data language.
getRawData ()
Show data in JSON format for AJAX.
fkEditor ()
Single mode state that show Grid for select field values.
fkValues ()
Single mode state for gettting latest values from FK table.
save ()
Save.
createData ()
Create data.
createDataDescription ()
Create data description.
getFKData ($fkTableName, $fkKeyName)
Get data from linked table.
generateError ($errorType, $errorMessage, $errorCustomInfo=false)
Generate error.
getSaver ()
Get saver.
setSaver (Saver $saver)
Set saver.
saveData ()
Save data.
loadData ()
Load data.
exportCSV ()
Export the list into CSV file.
printData ()
Prepare the list for printing.
prepareCSVString (Array $nextValue)
Prepare CSV string.
attachments ()
Show image manager.
tags ()
Show component: tag editor.
generateThumbnail ($sourceFileName, $destFieldName, $width, $height, $filter, $rewrite=true)
Generate thumbnails and save them in data base.
setOrderColumn ($columnName)
Set column name for user sorting.
getOrderColumn ()
Get column name for user sorting.
move ()
Show GRID for moving element.
moveTo ()
Move the record.
up ()
Change the moving direction to Grid::DIR_UP.
down ()
Change the moving direction to Grid::DIR_DOWN.
changeOrder ($direction)
Change order.
applyUserFilter ()
Apply user filter.
applyUserSort ()
Apply user sorting.
linkExtraManagers ($tableName, $data=false)
Build the list of additional files.
autoCompleteTags ()
Autocomplete tag names.
prepare ()
Prepare data.
createFilter ()
Create Grid filter.
Protected Member Functions inherited from Energine\share\components\DBDataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
loadDataDescription ()
Load data description.
loadData ()
Load data.
getDataLanguage ()
Get data language.
setTableName ($tableName)
Set table name.
setParam ($name, $value)
Set component parameter if such exist.
setFilter ($filter)
Set filter.
clearFilter ()
Reset filter.
getOrder ()
Get sort order.
setOrder (array $order)
Set sort order.
getLimit ()
Get limit.
setLimit (array $limit)
Set limit.
setPK ($primaryColumnName)
Set primary key.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
getFKData ($fkTableName, $fkKeyName)
Get data from linked table.
getTranslationTableName ()
Get table name with translations.
view ()
Show view form.
recordExists ($id, $fieldName=false)
Detect if the specific record exist.
buildJS ()
Create description of JS objects.
getPreviousState ()
Get previous state.
saveText ()
Save text.
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Protected Attributes
$attachmentEditor
Component: attachment editor manager.
$tagEditor
Tag editor.
$saver
Saver.
$filter_control
Filter.
$fkCRUDEditor = null
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Member Functions
addToolbarTranslations ()
Add translations for WYSIWYG.
Private Attributes
$orderColumn = null
Column name for user sorting.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Grid.
class Grid;
Definition at line 33 of file Grid.php.
Constructor & Destructor Documentation
Energine\share\components\Grid::__construct ($name, $module, array $params = null)
Parameters
string $name Component name.
string $module Module name.
array $params Component parameters.
Definition at line 84 of file Grid.php.
{
         parent::__construct($name, $module, $params);
         $this->setProperty('exttype', 'grid');
         if (!$this->getParam('recordsPerPage')) {
             $this->setParam('recordsPerPage', DataSet::RECORD_PER_PAGE);
         }
         if (!$this->getTitle())
             $this->setTitle($this->translate(
                 'TXT_' . strtoupper($this->getName())));
         if ($this->getParam('order')) {
             if (in_array($this->getParam('order'), array_keys($this->dbh->getColumnsInfo($this->getTableName())))) {
                 $this->orderColumn = $this->getParam('order');
             }
         }
     }
Member Function Documentation
Energine\share\components\Grid::add () protected
Show add form.
Definition at line 148 of file Grid.php.
{
         $this->setType(self::COMPONENT_TYPE_FORM_ADD);
         $this->prepare();
         $this->addToolbarTranslations();
         $this->linkExtraManagers($this->getTableName());
         foreach ($this->getDataDescription() as $fdName => $fieldDescription) {
             if (($default = $fieldDescription->getPropertyValue('default')) || ($default === '0')) {
                 if (!($f = $this->getData()->getFieldByName($fdName))) {
                     $f = new Field($fdName);
                     $this->getData()->addField($f);
                 }
                 $f->setData($default, true);
             }
         }
     }
Energine\share\components\Grid::addToolbarTranslations () private
Add translations for WYSIWYG.
Definition at line 1190 of file Grid.php.
Referenced by Energine\share\components\Grid\add(), and Energine\share\components\Grid\edit().
{
         foreach ($this->getDataDescription() as $fd) {
             if (($fd->getType() == FieldDescription::FIELD_TYPE_HTML_BLOCK)) {
                 $this->addWYSIWYGTranslations();
                 break;
             }
         }
     }
Energine\share\components\Grid::applyUserFilter () protected
Apply user filter.
Definition at line 1169 of file Grid.php.
Referenced by Energine\share\components\Grid\changeOrder(), and Energine\share\components\Grid\getRawData().
{
         $filter = new Filter();
         $filter->apply($this);
     }
Energine\share\components\Grid::applyUserSort () protected
Apply user sorting.
Definition at line 1177 of file Grid.php.
Referenced by Energine\share\components\Grid\getRawData().
{
         $actionParams = $this->getStateParams(true);
         if (isset($actionParams['sortField']) &&
             isset($actionParams['sortDir'])
         ) {
             //  sortDir -
             $this->setOrder(array($actionParams['sortField'] => $actionParams['sortDir']));
         }
     }
Energine\share\components\Grid::attachments () protected
Show image manager.
Get file library.
Show component: attachments.
Definition at line 861 of file Grid.php.
{
         $sp = $this->getStateParams(true);
         $attachmentEditorParams = array(
             'origTableName' => $this->getTableName(),
             'pk' => $this->getPK(),
             'tableName' => $this->getTableName() . AttachmentManager::ATTACH_TABLE_SUFFIX,
         );
         if (isset($sp['id'])) {
             $this->request->shiftPath(2);
             $attachmentEditorParams['linkedID'] = $sp['id'];
         } else {
             $this->request->shiftPath(1);
         }
         $this->attachmentEditor = $this->document->componentManager->createComponent(
             'attachmentEditor', 'share', 'AttachmentEditor', $attachmentEditorParams
         );
         $this->attachmentEditor->run();
     }
Energine\share\components\Grid::autoCompleteTags () protected
Autocomplete tag names.
Exceptions
SystemException 'ERR_NO_DATA'
Definition at line 1241 of file Grid.php.
{
         $b = new JSONCustomBuilder();
         $this->setBuilder($b);
         try {
             if (!isset($_POST['value'])) {
                 throw new SystemException('ERR_NO_DATA', SystemException::ERR_CRITICAL);
             } else {
                 $tags = TagManager::getTagStartedWith($_POST['value'], 10);
                 $result['result'] = true;
                 if (is_array($tags) && !empty($tags)) {
                     foreach ($tags as $tag) {
                         $result['data'][] = array(
                             'key' => $tag,
                             'value' => $tag
                         );
                     }
                 }
             }
         } catch (\Exception $e) {
             $result = array(
                 'result' => false,
                 'data' => false,
                 'errors' => array()
             );
         }
         $b->setProperties($result);
     }
Energine\share\components\Grid::build ()
Build block.
Returns
Exceptions
SystemException
Note
It includes translations and information about tabs.
Implements Energine\share\gears\IBlock.
Definition at line 595 of file Grid.php.
Referenced by Energine\apps\components\NewsRepository\build().
{
         switch ($this->getState()) {
             /*case 'imageManager':
                 return $this->imageManager->build();
                 break;
             case 'fileLibrary':
             case 'put':
                 return $this->fileLibrary->build();
                 break;*/
             case 'attachments':
                 return $this->attachmentEditor->build();
                 break;
             case 'tags':
                 return $this->tagEditor->build();
                 break;
             case 'fkEditor':
                 return $this->fkCRUDEditor->build();
                 break;
             default:
                 // do nothing
         }
         if ($this->getType() == self::COMPONENT_TYPE_LIST) {
             $this->addTranslation('MSG_CONFIRM_DELETE');
         }
         /*elseif($this->getTranslationTableName()) {
             $this->addTranslation('TXT_COPY_DATA_TO_ANOTHER_TAB');
         }*/
         $result = parent::build();
         if (!empty($this->filter_control)) {
             if ($f = $this->filter_control->build()) {
                 $result->documentElement->appendChild(
                     $result->importNode($f, true)
                 );
             }
         }
         return $result;
     }
Energine\share\components\Grid::changeOrder ($direction) protected
Change order.
Parameters
string $direction Direction.
Exceptions
SystemException 'ERR_NO_ORDER_COLUMN'
Definition at line 1094 of file Grid.php.
Referenced by Energine\apps\components\NewsRepository\changeOrder(), Energine\share\components\Grid\down(), and Energine\share\components\Grid\up().
{
         $this->applyUserFilter();
         if (!$this->getOrderColumn()) {
             //
             throw new SystemException('ERR_NO_ORDER_COLUMN', SystemException::ERR_DEVELOPER);
         }
         $currentID = $this->getStateParams();
         list($currentID) = $currentID;
         // order_num
         $currentOrderNum = simplifyDBResult(
             $this->dbh->selectRequest(
                 'SELECT ' . $this->getOrderColumn() . ' ' .
                 'FROM ' . $this->getTableName() . ' ' .
                 'WHERE ' . $this->getPK() . ' = %s',
                 $currentID
             ),
             $this->getOrderColumn(),
             true
         );
         $orderDirection = ($direction == Grid::DIR_DOWN) ? QAL::ASC : QAL::DESC;
         $baseFilter = $this->getFilter();
         if (!empty($baseFilter)) {
             $baseFilter = ' AND ' .
                 str_replace('WHERE', '', $this->dbh->buildWhereCondition($this->getFilter()));
         } else {
             $baseFilter = '';
         }
         //
         $request =
             'SELECT ' . $this->getPK() . ' as neighborID, ' .
             $this->getOrderColumn() . ' as neighborOrderNum ' .
             'FROM ' . $this->getTableName() . ' ' .
             'WHERE ' . $this->getOrderColumn() . ' ' . $direction .
             ' ' . $currentOrderNum . ' ' . $baseFilter .
             'ORDER BY ' . $this->getOrderColumn() . ' ' .
             $orderDirection . ' Limit 1';
         $data =
             convertDBResult($this->dbh->selectRequest($request), 'neighborID');
         if ($data) {
             $neighborID = null;
             $neighborOrderNum = 0;
             extract(current($data));
             $this->dbh->beginTransaction();
             $this->dbh->modify(
                 QAL::UPDATE,
                 $this->getTableName(),
                 array($this->getOrderColumn() => $neighborOrderNum),
                 array($this->getPK() => $currentID)
             );
             $this->dbh->modify(
                 QAL::UPDATE,
                 $this->getTableName(),
                 array($this->getOrderColumn() => $currentOrderNum),
                 array($this->getPK() => $neighborID)
             );
             $this->dbh->commit();
         }
         $b = new JSONCustomBuilder();
         $b->setProperties(array(
             'result' => true,
             'dir' => $direction
         ));
         $this->setBuilder($b);
     }
Energine\share\components\Grid::createData () protected
Create data.
Returns
Exceptions
SystemException 'ERR_DEV_LOAD_DATA_IS_FUNCTION'
Definition at line 390 of file Grid.php.
Referenced by Energine\apps\components\NewsRepository\createData(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\share\components\Grid\getRawData(), Energine\share\components\DivisionEditor\getRawData(), and Energine\share\components\FileRepository\putVideo().
{
         if (in_array($this->getType(), array(self::COMPONENT_TYPE_FORM_ADD, self::COMPONENT_TYPE_FORM_ALTER, self::COMPONENT_TYPE_FORM))) {
             $dd = $this->getDataDescription();
             if ($selects = $dd->getFieldDescriptionsByType(FieldDescription::FIELD_TYPE_SELECT)) {
                 foreach ($selects as $select) {
                     //is null - use default
                     //is empty - no editor
                     //string - check for class existance
                     $editorClassName = $select->getPropertyValue('editor');
                     if (is_null($editorClassName)) {
                         $select->setProperty('editor', 'Grid');
                     } elseif (empty($editorClassName)) {
                         $select->removeProperty('editor');
                     } else {
                         $editorClassName = explode('\\', $editorClassName);
                         if (sizeof($editorClassName) > 1) {
                             $editorClassName = $editorClassName[1];
                         } else {
                             list($editorClassName) = $editorClassName;
                         }
                         try {
                             class_exists($editorClassName);
                         } catch (SystemException $e) {
                             throw new SystemException('ERR_NO_EDITOR_CLASS', SystemException::ERR_DEVELOPER, $editorClassName);
                         }
                     }
                 }
             }
         }
         $r = parent::createData();
         return $r;
     }
Energine\share\components\Grid::createDataDescription () protected
Create data description.
Returns
DataDescription
Exceptions
SystemException 'ERR_DEV_LOAD_DATA_DESCR_IS_FUNCTION'
Definition at line 426 of file Grid.php.
Referenced by Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\apps\components\NewsRepository\createDataDescription(), Energine\share\components\FileRepository\editFile(), Energine\share\components\Grid\exportCSV(), Energine\share\components\Grid\getRawData(), and Energine\share\components\FileRepository\putVideo().
{
         //  OrderColumn   ,
         if (in_array($this->getState(), array('printData' /*, 'exportCSV'*/))) {
             $previousAction = $this->getState();
             $this->getConfig()->setCurrentState(self::DEFAULT_STATE_NAME);
             $result = parent::createDataDescription();
             $this->getConfig()->setCurrentState($previousAction);
         } else {
             $result = parent::createDataDescription();
         }
         if (($col = $this->getOrderColumn())
             && ($field = $result->getFieldDescriptionByName($col))
         ) {
             $result->removeFieldDescription($field);
         }
         return $result;
     }
Energine\share\components\Grid::createFilter () protected
Create Grid filter.
Definition at line 1286 of file Grid.php.
Referenced by Energine\share\components\Grid\prepare().
{
         if ($config = $this->getConfig()->getCurrentStateConfig()) {
             $this->filter_control = new Filter();
             $cInfo = $this->dbh->getColumnsInfo($this->getTableName());
             if ($this->getTranslationTableName()) {
                 $cInfo = array_merge($cInfo, $this->dbh->getColumnsInfo($this->getTranslationTableName()));
             }
             if ($config->filter) {
                 $this->filter_control->load($config->filter, $cInfo);
             } else {
                 foreach ($this->getDataDescription() as $fName => $fAttributes) {
                     if (in_array($fAttributes->getType(), array(FieldDescription::FIELD_TYPE_DATETIME, FieldDescription::FIELD_TYPE_DATE, FieldDescription::FIELD_TYPE_INT, FieldDescription::FIELD_TYPE_SELECT, FieldDescription::FIELD_TYPE_PHONE, FieldDescription::FIELD_TYPE_EMAIL, FieldDescription::FIELD_TYPE_STRING, FieldDescription::FIELD_TYPE_TEXT, FieldDescription::FIELD_TYPE_HTML_BLOCK, FieldDescription::FIELD_TYPE_BOOL))
                         && ($fAttributes->getPropertyValue('index') != 'PRI')
                         && !strpos($fName, '_num')
                         && array_key_exists($fName, $cInfo)
                     ) {
                         $ff = new FilterField($fName, $fAttributes->getType());
                         $ff->setAttribute('tableName', $cInfo[$fName]['tableName']);
                         $ff->setAttribute('title', 'FIELD_' . $fName);
                         $this->filter_control->attachField($ff);
                     }
                 }
             }
         }
     }
Energine\share\components\Grid::defineParams () protected
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
Returns
array
Definition at line 104 of file Grid.php.
{
         $params = array();
         if (!$this->params['config']) {
             $fileName = simplifyClassName(get_class($this)) . '.component.xml';
             $fileConf =
                 sprintf(SITE_DIR . ComponentConfig::SITE_CONFIG_DIR, E()->getSiteManager()->getCurrentSite()->folder) .
                 $fileName;
             $coreConf =
                 sprintf(CORE_DIR . ComponentConfig::CORE_CONFIG_DIR, $this->module) .
                 $fileName;
             if (file_exists($fileConf)) {
                 $params['config'] = $fileConf;
             } elseif (file_exists($coreConf)) {
                 $params['config'] = $coreConf;
             } else {
                 $params['config'] =
                     sprintf(CORE_DIR . ComponentConfig::CORE_CONFIG_DIR, 'share/') .
                     'Grid.component.xml';
             }
         }
         $params['active'] = true;
         $params['thumbnail'] =
             array($this->getConfigValue('thumbnail.width'), $this->getConfigValue('thumbnail.height'));
         $params['order'] = false;
         return array_merge(parent::defineParams(), $params);
     }
Energine\share\components\Grid::delete () protected
Delete.
Returns
mixed
See also
Grid::save()
Exceptions
SystemException 'ERR_404'
Definition at line 192 of file Grid.php.
{
         $transactionStarted = $this->dbh->beginTransaction();
         try {
             list($id) = $this->getStateParams();
             if (!$this->recordExists($id)) {
                 throw new SystemException('ERR_404', SystemException::ERR_404);
             }
             $this->deleteData($id);
             $b = new JSONCustomBuilder();
             $b->setProperty('result', true)->setProperty('mode', 'delete');
             $this->setBuilder($b);
             $this->dbh->commit();
         } catch (SystemException $e) {
             if ($transactionStarted) {
                 $this->dbh->rollback();
             }
             throw $e;
         }
     }
Energine\share\components\Grid::deleteData ($id) protected
Delete record.
Parameters
int $id Record ID.
Definition at line 220 of file Grid.php.
Referenced by Energine\share\components\Grid\delete().
{
         if ($orderColumn = $this->getOrderColumn()) {
             $deletedOrderNum =
                 simplifyDBResult($this->dbh->select($this->getTableName(), $this->getOrderColumn(), array($this->getPK() => $id)), $this->getOrderColumn(), true);
             $ids =
                 simplifyDBResult($this->dbh->select($this->getTableName(), array($this->getPK()), array_merge($this->getFilter(), array(
                     $orderColumn .
                     ' > ' .
                     $deletedOrderNum)), array($orderColumn => QAL::ASC)), $this->getPK());
         }
         $this->dbh->modify(QAL::DELETE, $this->getTableName(), null, array($this->getPK() => $id));
         //
         if ($orderColumn && $ids) {
             $this->addFilterCondition(array($this->getPK() => $ids));
             $request =
                 'UPDATE ' . $this->getTableName() . ' SET ' . $orderColumn .
                 ' = ' . $orderColumn . ' - 1 ' .
                 $this->dbh->buildWhereCondition($this->getFilter());
             $this->dbh->modifyRequest($request);
         }
     }
Energine\share\components\Grid::down () protected
Change the moving direction to Grid::DIR_DOWN.
Definition at line 1083 of file Grid.php.
{
         $this->changeOrder(Grid::DIR_DOWN);
     }
Energine\share\components\Grid::edit () protected
Show edit form.
Exceptions
SystemException 'ERR_404'
Definition at line 169 of file Grid.php.
{
         $this->setType(self::COMPONENT_TYPE_FORM_ALTER);
         $id = $this->getStateParams();
         list($id) = $id;
         if (!$this->recordExists($id)) {
             throw new SystemException('ERR_404', SystemException::ERR_404);
         }
         $this->setFilter($id);
         $this->prepare();
         $this->addToolbarTranslations();
         $this->linkExtraManagers($this->getTableName());
     }
Energine\share\components\Grid::exportCSV () protected
Export the list into CSV file.
Exceptions
SystemException 'ERR_CANT_EXPORT'
Todo:
,
Definition at line 681 of file Grid.php.
{
         $sp = $this->getStateParams(true);
         if (isset($sp['encoding'])) {
             $encoding = $sp['encoding'];
         } else {
             $encoding = 'utf-8';
         }
         //
         if ($this->getTranslationTableName()) {
             throw new SystemException('ERR_CANT_EXPORT', SystemException::ERR_DEVELOPER);
         }
         $this->setDataDescription($dd = $this->createDataDescription());
         $selectFields = $multiFields = array();
         //
         if ($sf = $dd->getFieldDescriptionsByType(FieldDescription::FIELD_TYPE_SELECT)) {
             foreach ($sf as $name => $fd) {
                 $selectFields[$name] = $fd->getAvailableValues();
             }
         }
         //
         if ($mf = $dd->getFieldDescriptionsByType(FieldDescription::FIELD_TYPE_MULTI)) {
             foreach ($mf as $name => $fd) {
                 //
                 $multiFieldsData[$name] = $fd;
                 //
                 $multiFields[$name] = 'GROUP_CONCAT(' . $name . '.fk_id) as ' . $name;
             }
         }
         $data = '';
         $titles = array();
         // ( )
         foreach ($dd as $fieldInfo) {
             $titles[] = $fieldInfo->getPropertyValue('title');
         }
         $data .= $this->prepareCSVString($titles);
         if ($fields = $dd->getFieldDescriptionList()) {
             //
             $fields = array_values(
                 array_merge(
                     array_combine(
                         $fields, $fields
                     ),
                     $multiFields
                 )
             );
             $request = 'SELECT ' . implode(',', $fields) . ' FROM ' . $this->getTableName() . '';
             //   JOIN     ,       GROUP_CONCAT
             if (!empty($multiFields)) {
                 foreach (array_values($multiFieldsData) as $fieldProps) {
                     $mTableName = $fieldProps->getPropertyValue('key');
                     $mTableName = $mTableName['tableName'];
                     $request .= ' LEFT JOIN ' . $mTableName . ' USING(' . $this->getPK() . ')';
                 }
                 $request .= ' GROUP BY ' . $this->getPK();
             }
             // $data
             $res = $this->dbh->get($request);
             if ($res && $res->rowCount()) {
                 while ($row = $res->fetch(\PDO::FETCH_LAZY)) {
                     $tmpRow = array();
                     foreach ($row as $fieldName => $fieldValue) {
                         if ($fd = $dd->getFieldDescriptionByName($fieldName)) {
                             switch ($fd->getType()) {
                                 case FieldDescription::FIELD_TYPE_DATE:
                                 case FieldDescription::FIELD_TYPE_TIME:
                                 case FieldDescription::FIELD_TYPE_DATETIME:
                                     if ($format = $fieldInfo->getPropertyValue('outputFormat')) {
                                         $fieldValue = AbstractBuilder::enFormatDate($fieldValue, $format, $fd->getType());
                                     }
                                     break;
                                 case FieldDescription::FIELD_TYPE_SELECT:
                                     if (isset($selectFields[$fieldName][$fieldValue])) {
                                         $fieldValue = $selectFields[$fieldName][$fieldValue]['value'];
                                     }
                                     break;
                                 case FieldDescription::FIELD_TYPE_BOOL:
                                     $fieldValue = ($fieldValue) ? $this->translate('TXT_YES') : $this->translate('TXT_NO');
                                     break;
                                 case FieldDescription::FIELD_TYPE_MULTI:
                                     if ($fieldValue && isset($multiFieldsData[$fieldName])) {
                                         $value = explode(',', $fieldValue);
                                         $fieldValue = array();
                                         $multiFieldValues = $multiFieldsData[$fieldName]->getAvailableValues();
                                         foreach ($value as $v) {
                                             if (isset($multiFieldValues[$v])) {
                                                 array_push($fieldValue, $multiFieldValues[$v]['value']);
                                             }
                                         }
                                         $fieldValue = implode(', ', $fieldValue);
                                     }
                                     break;
                             }
                             $tmpRow[] = $fieldValue;
                         }
                     }
                     if ($tmpRow)
                         $data .= $this->prepareCSVString($tmpRow);
                 }
             }
         }
         $filename = $this->getTitle() . '.csv';
         $MIMEType = 'application/csv';
         if ($encoding != 'utf-8') {
             $data = iconv('utf-8', $encoding . '//TRANSLIT', $data);
         }
         $this->downloadFile($data, $MIMEType, $filename);
     }
Energine\share\components\Grid::fkEditor () protected
Single mode state that show Grid for select field values.
Definition at line 285 of file Grid.php.
{
         list($fkField, $className) = $this->getStateParams();
         $className = explode('\\', urldecode($className));
         //Using tmp variable $class because list() cannot  modify variable it is working with
         if (sizeof($className) > 1) {
             list($module, $class) = $className;
         } else {
             $module = $this->module;
             list($class) = $className;
         }
         unset($className);
         $params = array();
         if ($class == 'Grid') {
             $cols = $this->dbh->getColumnsInfo($this->getTableName());
             if (!in_array($fkField, array_keys($cols)) && $this->getTranslationTableName()) {
                 $cols = $this->dbh->getColumnsInfo($this->getTranslationTableName());
                 if (!in_array($fkField, array_keys($cols))) {
                     throw new SystemException('ERR_NO_COLUMN', SystemException::ERR_DEVELOPER, $fkField);
                 }
             } elseif (!$this->getTranslationTableName()) {
                 throw new SystemException('ERR_NO_COLUMN', SystemException::ERR_DEVELOPER, $fkField);
             }
             if (!is_array($cols[$fkField]['key'])) {
                 throw new SystemException('ERR_BAD_FK_COLUMN', SystemException::ERR_DEVELOPER, $fkField);
             }
             $params['tableName'] = $cols[$fkField]['key']['tableName'];
         } else {
             try {
                 class_exists($class);
             } catch (SystemException $e) {
                 throw new SystemException('ERR_BAD_CLASS', SystemException::ERR_DEVELOPER, $class);
             }
             if (!is_subclass_of($class, 'Grid')) {
                 throw new SystemException('ERR_BAD_CLASS', SystemException::ERR_DEVELOPER, $class);
             }
         }
         //Search for modal component config
         if (!file_exists($config = CORE_REL_DIR . sprintf(ComponentConfig::CORE_CONFIG_DIR, $module) . $class . 'Modal.component.xml')) {
             if (!file_exists($config = CORE_REL_DIR . sprintf(ComponentConfig::CORE_CONFIG_DIR, $module) . $class . '.component.xml')) {
                 $config = CORE_REL_DIR . sprintf(ComponentConfig::CORE_CONFIG_DIR, 'share') . 'GridModal.component.xml';
             }
         }
         $params['config'] = $config;
         $this->request->shiftPath(2);
         $this->fkCRUDEditor = $this->document->componentManager->createComponent('fkEditor', $module, $class, $params);
         $this->fkCRUDEditor->run();
     }
Energine\share\components\Grid::fkValues () protected
Single mode state for gettting latest values from FK table.
Definition at line 338 of file Grid.php.
{
         list($fkField) = $this->getStateParams();
         $cols = $this->dbh->getColumnsInfo($this->getTableName());
         if (!in_array($fkField, array_keys($cols)) && $this->getTranslationTableName()) {
             $cols = $this->dbh->getColumnsInfo($this->getTranslationTableName());
             if (!in_array($fkField, array_keys($cols))) {
                 throw new SystemException('ERR_NO_COLUMN', SystemException::ERR_DEVELOPER, $fkField);
             }
         } elseif (!$this->getTranslationTableName()) {
             throw new SystemException('ERR_NO_COLUMN', SystemException::ERR_DEVELOPER, $fkField);
         }
         if (!is_array($cols[$fkField]['key'])) {
             throw new SystemException('ERR_BAD_FK_COLUMN', SystemException::ERR_DEVELOPER, $fkField);
         }
         $builder = new JSONCustomBuilder();
         $builder->setProperty('result', $this->getFKData($cols[$fkField]['key']['tableName'], $cols[$fkField]['key']['fieldName']));
         $this->setBuilder($builder);
     }
Energine\share\components\Grid::generateError ($errorType, $errorMessage, $errorCustomInfo = false) protected
Generate error.
Parameters
string $errorType Error type.
string $errorMessage Error message.
mixed $errorCustomInfo Optional additional info about error.
Returns
array
Definition at line 467 of file Grid.php.
{
         $message['errors'][] = array('message' => $errorMessage);
         $response =
             array_merge(array('result' => false, 'header' => $this->translate('TXT_SHIT_HAPPENS')), $message);
         return $response;
     }
Energine\share\components\Grid::generateThumbnail ($sourceFileName, $destFieldName, $width, $height, $filter, $rewrite = true) protected
Generate thumbnails and save them in data base.
Parameters
string $sourceFileName Source filename.
string $destFieldName Destination filed name.
int $width Width
int $height Height.
array $filter Filter.
bool $rewrite Overwrite existed?
Returns
bool|string
Definition at line 902 of file Grid.php.
{
         $destFileName = false;
         if (!empty($sourceFileName)) {
             list($dirname, $basename, $extension, $filename) =
                 array_values(pathinfo($sourceFileName));
             $destFileName =
                 $dirname . '/' . '.' . $filename . '.' . $width . '-' .
                 $height . '.' . $extension;
             if ((
                     file_exists($fullDestFileName =
                         dirname($_SERVER['SCRIPT_FILENAME']) .
                         '/' .
                         $destFileName)
                     && $rewrite
                 )
                 || !file_exists($fullDestFileName)
             ) {
                 $image = new Image();
                 $image->loadFromFile($sourceFileName);
                 $image->resize($width, $height);
                 $image->saveToFile($destFileName);
                 //
                 $this->dbh->modify(QAL::UPDATE, $this->getTableName(), array($destFieldName => $destFileName), $filter);
             }
         }
         return $destFileName;
     }
Energine\share\components\Grid::getConfig () protected
Definition at line 134 of file Grid.php.
Referenced by Energine\share\components\Grid\createDataDescription(), Energine\share\components\Grid\createFilter(), Energine\share\components\Grid\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), and Energine\share\components\DivisionEditor\showPageToolbar().
{
         if (!$this->config) {
             $this->config = new GridConfig(
                 $this->getParam('config'),
                 get_class($this),
                 $this->module
             );
         }
         return $this->config;
     }
Energine\share\components\Grid::getDataLanguage () protected
Get data language.
Returns
int|false
Definition at line 249 of file Grid.php.
{
         if (isset($_POST['languageID']) && $this->getState() == 'getRawData') {
             $langID = $_POST['languageID'];
             if (!E()->getLanguage()->isValidLangID($langID)) {
                 throw new SystemException('ERR_BAD_LANG_ID', SystemException::ERR_WARNING);
             }
             $result = $langID;
         } else $result = parent::getDataLanguage();
         return $result;
     }
Energine\share\components\Grid::getFKData ($fkTableName, $fkKeyName) protected
Get data from linked table.
Parameters
string $fkTableName Linked table name.
string $fkKeyName Key name.
Returns
array
Definition at line 449 of file Grid.php.
Referenced by Energine\share\components\Grid\fkValues().
{
         //  main     ,
         $result = array();
         if ($this->getState() !== self::DEFAULT_STATE_NAME)
             $result =
                 $this->dbh->getForeignKeyData($fkTableName, $fkKeyName, $this->document->getLang());
         return $result;
     }
Energine\share\components\Grid::getOrderColumn () protected
Get column name for user sorting.
Returns
string
See also
Grid::setOrderColumn
Definition at line 951 of file Grid.php.
Referenced by Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\share\components\Grid\createDataDescription(), Energine\share\components\Grid\deleteData(), Energine\share\components\Grid\move(), Energine\share\components\Grid\moveTo(), Energine\share\components\AttachmentEditor\saveData(), and Energine\share\components\Grid\saveData().
{
         if (is_null($this->orderColumn)) {
             $this->orderColumn = false;
             $columns = $this->dbh->getColumnsInfo($this->getTableName());
             foreach (array_keys($columns) as $columnName) {
                 if (strpos($columnName, '_order_num')) {
                     $this->setOrderColumn($columnName);
                     break;
                 }
             }
         }
         return $this->orderColumn;
     }
Energine\share\components\Grid::getRawData () protected
Show data in JSON format for AJAX.
Definition at line 264 of file Grid.php.
{
         $this->setParam('onlyCurrentLang', true);
         $this->getConfig()->setCurrentState(self::DEFAULT_STATE_NAME);
         $this->setBuilder(new JSONBuilder());
         $this->setDataDescription($this->createDataDescription());
         $this->createPager();
         $this->applyUserFilter();
         $this->applyUserSort();
         $data = $this->createData();
         if ($data instanceof Data) {
             $this->setData($data);
         }
         if ($this->pager) $this->getBuilder()->setPager($this->pager);
     }
Energine\share\components\Grid::getSaver () final protected
Get saver.
Returns
Saver
Attention
This is final.
Note
There is only reason to call this function inside save/saveSate, in other cases it will return false.
Definition at line 483 of file Grid.php.
Referenced by Energine\share\components\DivisionEditor\save(), Energine\share\components\AttachmentEditor\saveData(), and Energine\share\components\Grid\saveData().
{
         if (is_null($this->saver)) {
             $this->saver = new ExtendedSaver();
         }
         return $this->saver;
     }
Energine\share\components\Grid::linkExtraManagers ($tableName, $data = false) protected
Build the list of additional files.
Parameters
string $tableName Table name.
bool $data Data.
See also
DivisionEditor
ProductEditor
Note
It is used for the cases when additional tab with attached files to the record should be created.
Definition at line 1212 of file Grid.php.
Referenced by Energine\share\components\Grid\add(), and Energine\share\components\Grid\edit().
{
         if ($this->dbh->tableExists($tableName . AttachmentManager::ATTACH_TABLE_SUFFIX) && $this->getState() != 'attachments') {
             $fd = new FieldDescription('attached_files');
             $fd->setType(FieldDescription::FIELD_TYPE_TAB);
             $fd->setProperty('title', $this->translate('TAB_ATTACHED_FILES'));
             $fd->setProperty('tableName', $tableName . AttachmentManager::ATTACH_TABLE_SUFFIX);
             $this->getDataDescription()->addFieldDescription($fd);
             $field = new Field('attached_files');
             $state = $this->getState();
             $tab_url = (($state != 'add') ? $this->getData()->getFieldByName($this->getPK())->getRowData(0) : '') . '/attachments/';
             $field->setData($tab_url, true);
             $this->getData()->addField($field);
         }
         if ($this->dbh->tableExists($this->getTableName() . TagManager::TAGS_TABLE_SUFFIX)) {
             $tm = new TagManager($this->getDataDescription(), $this->getData(), $this->getTableName());
             $tm->createFieldDescription();
             $tm->createField();
         }
     }
Energine\share\components\Grid::loadData () protected
Load data.
Returns
mixed
Definition at line 640 of file Grid.php.
Referenced by Energine\share\components\Grid\saveData().
{
         //   main
         //   save
         if ($this->getState() == self::DEFAULT_STATE_NAME or $this->getState() == 'move') {
             $result = false;
         } elseif ($this->getState() == 'save') {
             if (!isset($_POST[$this->getTableName()])) {
                 throw new SystemException('ERR_NO_DATA', SystemException::ERR_CRITICAL);
             }
             $data = $_POST[$this->getTableName()];
             //
             $result = array($data);
             if ($this->getTranslationTableName()) {
                 if (!isset($_POST[$this->getTranslationTableName()])) {
                     throw new SystemException('ERR_NO_DATA', SystemException::ERR_CRITICAL);
                 }
                 $result = array();
                 $multidata = $_POST[$this->getTranslationTableName()];
                 foreach ($multidata as $langID => $langValues) {
                     $idx = arrayPush($result, $data);
                     $result[$idx]['lang_id'] = $langID;
                     foreach ($langValues as $fieldName => $fieldValue) {
                         $result[$idx][$fieldName] = $fieldValue;
                     }
                 }
             }
         } else {
             $result = parent::loadData();
         }
         return $result;
     }
Energine\share\components\Grid::move () protected
Show GRID for moving element.
Exceptions
SystemException 'ERR_NO_ORDER_COLUMN'
SystemException 'ERR_404'
Definition at line 971 of file Grid.php.
{
         if (!$this->getOrderColumn()) {
             //
             throw new SystemException('ERR_NO_ORDER_COLUMN', SystemException::ERR_DEVELOPER);
         }
         $id = $this->getStateParams();
         list($id) = $id;
         if (!$this->recordExists($id)) {
             throw new SystemException('ERR_404', SystemException::ERR_404);
         }
         $this->setType(self::COMPONENT_TYPE_LIST);
         $this->setProperty('moveFromId', $id);
         //$this->addTranslation('TXT_FILTER', 'BTN_APPLY_FILTER', 'TXT_RESET_FILTER', 'TXT_FILTER_SIGN_BETWEEN', 'TXT_FILTER_SIGN_CONTAINS', 'TXT_FILTER_SIGN_NOT_CONTAINS');
         $this->prepare();
     }
Energine\share\components\Grid::moveTo () protected
Move the record.
Allowed movement:
above
below
top
bottom
Todo:
: , .. 0. move above.
Exceptions
SystemException 'ERR_NO_ORDER_COLUMN'
Definition at line 1001 of file Grid.php.
{
         if (!$this->getOrderColumn()) {
             //
             throw new SystemException('ERR_NO_ORDER_COLUMN', SystemException::ERR_DEVELOPER);
         }
         $params = $this->getStateParams();
         list($firstItem, $direction) = $params;
         $allowed_directions = array('first', 'last', 'above', 'below');
         if (in_array($direction, $allowed_directions) && $firstItem == intval($firstItem)) {
             switch ($direction) {
                 //    id=$firstItem
                 case 'first':
                     $oldFirstItem = (int)$this->dbh->getScalar('SELECT MIN(' . $this->getOrderColumn() . ') FROM ' . $this->getTableName() . ' LIMIT 1');
                     if ($oldFirstItem != $firstItem) {
                         $this->dbh->modify(
                             QAL::UPDATE,
                             $this->getTableName(),
                             array($this->getOrderColumn() => $oldFirstItem - 1),
                             array($this->getPK() => $firstItem)
                         );
                     }
                     break;
                 //    id=$firstItem
                 case 'last':
                     $oldLastItem = (int)$this->dbh->getScalar('SELECT MAX(' . $this->getOrderColumn() . ') FROM ' . $this->getTableName() . ' LIMIT 1');
                     if ($oldLastItem != $firstItem) {
                         $this->dbh->modify(
                             QAL::UPDATE,
                             $this->getTableName(),
                             array($this->getOrderColumn() => $oldLastItem + 1),
                             array($this->getPK() => $firstItem)
                         );
                     }
                     break;
                 //      id=$secondItem
                 case 'above':
                 case 'below':
                     $secondItem = (!empty($params[2])) ? $params[2] : null;
                     if ($secondItem == intval($secondItem) && $firstItem != $secondItem) {
                         $secondItemOrderNum = $this->dbh->getScalar(
                             'SELECT ' . $this->getOrderColumn() . ' as secondItemOrderNum ' .
                             'FROM ' . $this->getTableName() . ' ' .
                             'WHERE ' . $this->getPK() . ' = ' . $secondItem
                         );
                         $this->dbh->beginTransaction();
                         //        id
                         $this->dbh->select(
                             'UPDATE ' . $this->getTableName() . ' ' .
                             'SET ' . $this->getOrderColumn() . ' = ' .
                             $this->getOrderColumn() . (($direction == 'below') ? ' +2 ' : ' -2 ') .
                             'WHERE ' . $this->getOrderColumn() . (($direction == 'below') ? ' > ' : ' < ') .
                             intval($secondItemOrderNum)
                         );
                         //      id
                         $this->dbh->modify(
                             QAL::UPDATE,
                             $this->getTableName(),
                             array($this->getOrderColumn() => (($direction == 'below') ? $secondItemOrderNum + 1 : $secondItemOrderNum - 1)),
                             array($this->getPK() => $firstItem)
                         );
                         $this->dbh->commit();
                     }
                     break;
             }
         }
         $b = new JSONCustomBuilder();
         $b->setProperty('result', true);
         $this->setBuilder($b);
     }
Energine\share\components\Grid::prepare () protected
Prepare data.
Note
It calls at the beginning of the method, that realize main action.
Definition at line 1276 of file Grid.php.
Referenced by Energine\share\components\Grid\add(), Energine\share\components\Grid\edit(), Energine\share\components\Grid\move(), Energine\share\components\Grid\printData(), and Energine\share\components\WidgetsRepository\showNewTemplateForm().
{
         parent::prepare();
         if ($this->getType() == self::COMPONENT_TYPE_LIST)
             $this->createFilter();
     }
Energine\share\components\Grid::prepareCSVString (Array $nextValue) protected
Prepare CSV string.
Parameters
array $nextValue Next value.
Returns
string
Definition at line 822 of file Grid.php.
Referenced by Energine\share\components\Grid\exportCSV().
{
         $separator = '"';
         $delimiter = ';';
         $rowDelimiter = "\r\n";
         $row = '';
         foreach ($nextValue as $fieldValue) {
             $row .= $separator .
                 //mb_convert_encoding(str_replace(array($separator, $delimiter), array("''", ','), $fieldValue), 'Windows-1251', 'UTF-8') .
                 str_replace(array($separator, $delimiter), array("''", ','), $fieldValue) .
                 $separator . $delimiter;
         }
         $row = substr($row, 0, -1);
         return $row . $rowDelimiter;
     }
Energine\share\components\Grid::printData () protected
Prepare the list for printing.
Definition at line 807 of file Grid.php.
{
         $this->setParam('recordsPerPage', false);
         if (E()->getController()->getViewMode() ==
             DocumentController::TRANSFORM_HTML
         )
             E()->getController()->getTransformer()->setFileName('print.xslt');
         $this->prepare();
     }
Energine\share\components\Grid::save () protected
Save.
Note
This is 'external' method that calls 'internal' Grid::saveData.
Definition at line 364 of file Grid.php.
{
         $transactionStarted = $this->dbh->beginTransaction();
         try {
             $result = $this->saveData();
             $transactionStarted = !($this->dbh->commit());
             $b = new JSONCustomBuilder();
             $b->setProperties(array(
                 'data' => (is_int($result)) ? $result
                         : (int)$_POST[$this->getTableName()][$this->getPK()],
                 'result' => true,
                 'mode' => (is_int($result)) ? 'insert' : 'update'
             ));
             $this->setBuilder($b);
         } catch (SystemException $e) {
             if ($transactionStarted) {
                 $this->dbh->rollback();
             }
             throw $e;
         }
     }
Energine\share\components\Grid::saveData () protected
Save data.
Returns
mixed
Exceptions
SystemException 'ERR_NO_ACTION'
SystemException 'ERR_VALIDATE_FORM'
Todo:
, ,
See also
Grid::createDataDescription
Definition at line 508 of file Grid.php.
Referenced by Energine\share\components\DivisionEditor\save(), Energine\share\components\Grid\save(), and Energine\apps\components\NewsRepository\saveData().
{
         $result = false;
         //  POST       -
         if (isset($_POST[$this->getTableName()][$this->getPK()]) &&
             !empty($_POST[$this->getTableName()][$this->getPK()])
         ) {
             $mode = self::COMPONENT_TYPE_FORM_ALTER;
             $this->setFilter(array($this->getPK() => $_POST[$this->getTableName()][$this->getPK()]));
         } else {
             $mode = self::COMPONENT_TYPE_FORM_ADD;
         }
         //
         $dataDescriptionObject = new DataDescription();
         if (!method_exists($this, $this->getPreviousState())) {
             throw new SystemException('ERR_NO_ACTION', SystemException::ERR_CRITICAL);
         }
         //
         $configDataDescription =
             $this->getConfig()->getStateConfig($this->getPreviousState());
         //        -
         if (isset($configDataDescription->fields)) {
             $dataDescriptionObject->loadXML($configDataDescription->fields);
         }
         //
         $DBDataDescription = new DataDescription();
         //
         $DBDataDescription->load($this->loadDataDescription());
         $this->setDataDescription($dataDescriptionObject->intersect($DBDataDescription));
         //
         /**
          * @todo       ,
          *         ,
          * @see Grid::createDataDescription
          */
         if (($col = $this->getOrderColumn()) && ($field =
                 $this->getDataDescription()->getFieldDescriptionByName($col))
         ) {
             $this->getDataDescription()->removeFieldDescription($field);
         }
         $dataObject = new Data();
         $dataObject->load($this->loadData());
         $this->setData($dataObject);
         //
         $saver = $this->getSaver();
         //
         $saver->setMode($mode);
         $saver->setDataDescription($this->getDataDescription());
         $saver->setData($this->getData());
         if ($saver->validate() === true) {
             $saver->setFilter($this->getFilter());
             $saver->save();
             $result = $saver->getResult();
         } else {
             // exception     save
             throw new SystemException('ERR_VALIDATE_FORM', SystemException::ERR_WARNING, $this->saver->getErrors());
         }
         //          ,
         if (($orderColumn = $this->getOrderColumn()) &&
             ($mode == self::COMPONENT_TYPE_FORM_ADD)
         ) {
             $this->addFilterCondition(array($this->getPK() . '!=' . $result));
             $request =
                 'UPDATE ' . $this->getTableName() . ' SET ' . $orderColumn .
                 '=' . $orderColumn . '+1 ' .
                 $this->dbh->buildWhereCondition($this->getFilter());
             $this->dbh->modifyRequest($request);
         }
         return $result;
     }
Energine\share\components\Grid::setOrderColumn ($columnName) protected
Set column name for user sorting.
Parameters
string $columnName Column name.
See also
Grid::getOrderColumn
Definition at line 939 of file Grid.php.
Referenced by Energine\share\components\Grid\getOrderColumn().
{
         $this->orderColumn = $columnName;
         $this->setOrder(array($columnName => QAL::ASC));
     }
Energine\share\components\Grid::setSaver (Saver $saver) final protected
Set saver.
Parameters
Saver $saver Saver.
Definition at line 496 of file Grid.php.
Referenced by Energine\apps\components\NewsEditor\__construct(), Energine\share\components\SitePropertiesEditor\__construct(), Energine\apps\components\NewsRepository\__construct(), Energine\apps\components\ExtendedFeedEditor\__construct(), Energine\forms\components\FormsEditor\__construct(), Energine\share\components\SiteEditor\__construct(), and Energine\share\components\DivisionEditor\save().
{
         $this->saver = $saver;
     }
Energine\share\components\Grid::tags () protected
Show component: tag editor.
Definition at line 885 of file Grid.php.
{
         $this->request->setPathOffset($this->request->getPathOffset() + 1);
         $this->tagEditor = $this->document->componentManager->createComponent('tageditor', 'share', 'TagEditor', array('config' => 'core/modules/share/config/TagEditorModal.component.xml'));
         $this->tagEditor->run();
     }
Energine\share\components\Grid::up () protected
Change the moving direction to Grid::DIR_UP.
Definition at line 1076 of file Grid.php.
{
         $this->changeOrder(Grid::DIR_UP);
     }
Member Data Documentation
AttachmentEditor Energine\share\components\Grid::$attachmentEditor protected
Component: attachment editor manager.
Definition at line 49 of file Grid.php.
Filter Energine\share\components\Grid::$filter_control protected
Filter.
Definition at line 73 of file Grid.php.
Energine\share\components\Grid::$fkCRUDEditor = null protected
Definition at line 79 of file Grid.php.
string Energine\share\components\Grid::$orderColumn = null private
Column name for user sorting.
Definition at line 67 of file Grid.php.
Referenced by Energine\share\components\Grid\deleteData(), Energine\share\components\Grid\getOrderColumn(), Energine\share\components\AttachmentEditor\saveData(), and Energine\share\components\Grid\saveData().
Saver Energine\share\components\Grid::$saver protected
Saver.
Definition at line 61 of file Grid.php.
Referenced by Energine\share\components\Grid\getSaver(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), and Energine\share\components\Grid\setSaver().
TagEditor Energine\share\components\Grid::$tagEditor protected
Tag editor.
Definition at line 55 of file Grid.php.
string Energine\share\components\Grid::DIR_DOWN = '>'
Direction: dowm.
Definition at line 43 of file Grid.php.
Referenced by Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\forms\components\FormEditor\down(), and Energine\share\components\Grid\down().
string Energine\share\components\Grid::DIR_UP = '<'
Direction: up.
Definition at line 38 of file Grid.php.
Referenced by Energine\forms\gears\FormConstructor\changeOrder(), Energine\share\components\DivisionEditor\changeOrder(), Energine\forms\components\FormEditor\up(), and Energine\share\components\Grid\up().
The documentation for this class was generated from the following file:
core/modules/share/components/Grid.php