Energine: Energine\forms\components\FormEditor Class Reference
Energine\forms\components\FormEditor Class Reference
Form editor.
Public Member Functions
__construct ($name, $module, array $params=null)
build ()
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Member Functions
defineParams ()
createDataDescription ()
Create data description.
createBuilder ()
Create builder.
loadData ()
Load data.
createData ()
Create data.
getRawData ()
Get raw data.
add ()
Add.
edit ()
Edit.
main ()
Default action.
up ()
Up.
down ()
Down.
editSelector ()
Edit selector.
delete ()
Delete.
save ()
saveField ()
Save field.
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
Возвращает описание данных
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Private Member Functions
getFieldInfoByIndex ($fieldIndex, $asArray=false)
Get field information by his ID.
Private Attributes
$SVEditor
Editor of selector values.
$constructor
Form constructor.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Form editor.
class FormEditor;
Definition at line 27 of file FormEditor.php.
Constructor & Destructor Documentation
Energine\forms\components\FormEditor::__construct ($name, $module, array $params = null)
Definition at line 43 of file FormEditor.php.
{
         parent::__construct($name, $module, $params);
         if (!$this->getParam('form_id')) {
             throw new SystemException('ERR_BAD_FORM_ID');
         }
         $this->constructor = new FormConstructor($this->getParam('form_id'));
         $this->setProperty('exttype', 'grid');
         $this->setType(self::COMPONENT_TYPE_LIST);
     }
Member Function Documentation
Energine\forms\components\FormEditor::add () protected
Add.
Definition at line 175 of file FormEditor.php.
{
         $this->setType(self::COMPONENT_TYPE_FORM_ADD);
         $this->setBuilder($this->createBuilder());
         $this->setDataDescription($this->createDataDescription());
         $this->setData(new Data());
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
     }
Energine\forms\components\FormEditor::build ()
Exceptions
SystemException
Implements Energine\share\gears\IBlock.
Definition at line 366 of file FormEditor.php.
{
         if ($this->getState() == 'editSelector') {
             $result = $this->SVEditor->build();
         } else {
             $result = parent::build();
         }
         return $result;
     }
Energine\forms\components\FormEditor::createBuilder () protected
Create builder.
Returns
AbstractBuilder
Definition at line 135 of file FormEditor.php.
Referenced by Energine\forms\components\FormEditor\add(), Energine\forms\components\FormEditor\edit(), and Energine\forms\components\FormEditor\main().
{
         return new MultiLanguageBuilder();
     }
Energine\forms\components\FormEditor::createData () protected
Create data.
Returns
Exceptions
SystemException 'ERR_DEV_LOAD_DATA_IS_FUNCTION'
Definition at line 149 of file FormEditor.php.
Referenced by Energine\forms\components\FormEditor\getRawData().
{
         return $this->constructor->getData((isset($_POST['languageID'])) ? $_POST['languageID']
             : E()->getLanguage()->getDefault());
     }
Energine\forms\components\FormEditor::createDataDescription () protected
Create data description.
Returns
DataDescription
Exceptions
SystemException 'ERR_DEV_LOAD_DATA_DESCR_IS_FUNCTION'
Definition at line 70 of file FormEditor.php.
Referenced by Energine\forms\components\FormEditor\add(), Energine\forms\components\FormEditor\edit(), Energine\forms\components\FormEditor\getRawData(), and Energine\forms\components\FormEditor\main().
{
         //We work with other fields when we edit field - so create other DataDescription.
         if (in_array($this->getState(), array('edit'))) {
             $dd = new DataDescription();
             $dd->load(array(
                 'ltag_id' => array(
                     'nullable' => false,
                     'length' => 10,
                     'default' => '',
                     'key' => true,
                     'type' => FieldDescription::FIELD_TYPE_INT,
                     'index' => 'PRI',
                     'tableName' => 'share_lang_tags',
                     'languageID' => false,
                 ),
                 'lang_id' => array(
                     'nullable' => false,
                     'length' => 10,
                     'default' => '',
                     'key' => false,
                     'type' => FieldDescription::FIELD_TYPE_INT,
                     'index' => 'PRI',
                     'tableName' => 'share_lang_tags_translation',
                     'languageID' => true,
                     'isMultilanguage' => true
                 ),
                 'field_type' => array(
                     'nullable' => false,
                     'length' => 255,
                     'default' => '',
                     'key' => false,
                     'type' => FieldDescription::FIELD_TYPE_HIDDEN,
                     'mode' => FieldDescription::FIELD_MODE_READ,
                     'index' => false,
                     'languageID' => false
                 ),
                 'ltag_name' => array(
                     'nullable' => false,
                     'length' => 255,
                     'default' => '',
                     'key' => false,
                     'type' => FieldDescription::FIELD_TYPE_STRING,
                     'index' => false,
                     'languageID' => false
                 ),
                 'ltag_value_rtf' => array(
                     'nullable' => false,
                     'length' => 1024,
                     'default' => '',
                     'key' => false,
                     'type' => FieldDescription::FIELD_TYPE_TEXT,
                     'index' => false,
                     'tableName' => 'share_lang_tags_translation',
                     'isMultilanguage' => true
                 )));
             $dd->getFieldDescriptionByName('ltag_name')->setMode(FieldDescription::FIELD_MODE_READ);
             return $dd;
         } else {
             return $this->constructor->getDataDescription();
         }
     }
Energine\forms\components\FormEditor::defineParams () protected
Definition at line 57 of file FormEditor.php.
{
         return array_merge(
             parent::defineParams(),
             array(
                 'form_id' => false,
                 'active' => true
             )
         );
     }
Energine\forms\components\FormEditor::delete () protected
Delete.
Definition at line 321 of file FormEditor.php.
{
         list($fieldIndex) = $this->getStateParams();
         $this->constructor->delete($this->getFieldInfoByIndex($fieldIndex));
         $this->setBuilder(new JSONCustomBuilder());
     }
Energine\forms\components\FormEditor::down () protected
Down.
Definition at line 286 of file FormEditor.php.
{
         list($fieldIndex) = $this->getStateParams();
         $this->constructor->changeOrder(Grid::DIR_DOWN, $fieldIndex);
         $b = new JSONCustomBuilder();
         $b->setProperties(array(
             'result' => true,
             'dir' => Grid::DIR_DOWN
         ));
         $this->setBuilder($b);
     }
Energine\forms\components\FormEditor::edit () protected
Edit.
Get information about selected field to modal form, so user can edit it.
Definition at line 191 of file FormEditor.php.
{
         $this->setType(self::COMPONENT_TYPE_FORM_ALTER);
         $this->setBuilder($this->createBuilder());
         $fieldID = $this->getStateParams();
         if (!is_array($fieldID) || !$fieldID[0]) {
             throw new SystemException('ERR_WRONG_FIELD_ID');
         }
         $fieldName = $this->getFieldInfoByIndex($fieldID[0]);
         //Get field translations
         $this->setDataDescription($this->createDataDescription());
         $this->setData(new Data());
         //Load information about field type.
         $fieldsInfo = $this->dbh->getColumnsInfo(FormConstructor::getDatabase() . '.form_' . $this->getParam('form_id'));
         $fieldInfo = $fieldsInfo[strtolower($fieldName)];
         $fieldInfo = FieldDescription::convertType($fieldInfo['type'], $fieldName, $fieldInfo['length']);
         $fieldInfo = 'FIELD_TYPE_' . strtoupper($fieldInfo);
         //Destroy unused variables.
         //Create field FIELD_TYPE.
         $f = new Field('field_type');
         for ($i = 0, $l = sizeof(E()->getLanguage()->getLanguages()); $i < $l; $i++) {
             $f->setRowData($i, $this->translate($fieldInfo));
         }
         $this->getData()->addField($f);
         $this->getDataDescription()->getFieldDescriptionByName('field_type')->setProperty('tabName', 'TXT_PROPERTIES');
         $this->getDataDescription()->getFieldDescriptionByName('ltag_name')->setType(FieldDescription::FIELD_TYPE_HIDDEN);
         $result = $this->dbh->select(
             'SELECT * FROM share_lang_tags lt
                     LEFT JOIN share_lang_tags_translation ltt ON lt.ltag_id=ltt.ltag_id
                     WHERE lt.ltag_name = %s', $ltagName = 'FIELD_' . strtoupper($fieldName));
         if (!is_array($result)) {
             $result = array();
             $ltagID = $this->dbh->modify(QAL::INSERT, 'share_lang_tags', array('ltag_name' => $ltagName));
             foreach (array_keys(E()->getLanguage()->getLanguages()) as $langID) {
                 $this->dbh->modify(QAL::INSERT, 'share_lang_tags_translation', array('lang_id' => $langID, 'ltag_id' => $ltagID, 'ltag_value_rtf' => $ltagName));
                 $result[] = array('ltag_id' => $ltagID, 'lang_id' => $langID, 'ltag_value_rtf' => $ltagName, 'ltag_name' => $ltagName);
             }
         }
         unset($fieldsInfo, $fieldName, $fieldID);
         if (is_array($result)) {
             //Load field translations, translation tag and ID.
             $this->getData()->load($result);
         }
         //Create toolbar and JS.
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
         //inspect($this->getDataDescription());
     }
Energine\forms\components\FormEditor::editSelector () protected
Edit selector.
Definition at line 300 of file FormEditor.php.
{
         list($fieldIndex) = $this->getStateParams();
         E()->getRequest()->shiftPath(2);
         $fieldInfo = $this->getFieldInfoByIndex($fieldIndex, true);
         $fieldName = key($fieldInfo);
         $tableName = current($fieldInfo);
         if (!strpos($fieldName, '_multi')) {
             $tableName = $tableName['key']['tableName'];
         } else {
             $tableName = FormConstructor::getDatabase() . '.' . $fieldName . '_values';
         }
         $this->SVEditor = $this->document->componentManager->createComponent('form', 'forms', 'SelectorValuesEditor', array('table_name' => $tableName));
         $this->SVEditor->run();
     }
Energine\forms\components\FormEditor::getFieldInfoByIndex ($fieldIndex, $asArray = false) private
Get field information by his ID.
Parameters
int $fieldIndex Field ID.
bool $asArray Return as an array?
Returns
array
Exceptions
SystemException 'ERR_BAD_REQUEST'
Definition at line 385 of file FormEditor.php.
Referenced by Energine\forms\components\FormEditor\delete(), Energine\forms\components\FormEditor\edit(), and Energine\forms\components\FormEditor\editSelector().
{
         if ($fieldIndex == 1) {
             throw new SystemException('ERR_BAD_REQUEST', SystemException::ERR_WARNING);
         }
         $colsInfo = $this->dbh->getColumnsInfo($this->constructor->getTableName());
         $cols = array_keys($colsInfo);
         if (!isset($cols[$fieldIndex - 1])) {
             throw new SystemException('ERR_BAD_REQUEST', SystemException::ERR_WARNING);
         }
         if ($asArray) {
             return array(
                 $cols[$fieldIndex - 1] => $colsInfo[$cols[$fieldIndex - 1]]
             );
         } else {
             return $cols[$fieldIndex - 1];
         }
     }
Energine\forms\components\FormEditor::getRawData () protected
Get raw data.
Definition at line 158 of file FormEditor.php.
{
         $this->setBuilder(new JSONBuilder());
         $this->setDataDescription($this->createDataDescription());
         $this->createPager();
         //$this->applyUserFilter();
         //$this->applyUserSort();
         $this->setData($this->createData());
         if ($this->pager) $this->getBuilder()->setPager($this->pager);
     }
Energine\forms\components\FormEditor::loadData () protected
Load data.
Returns
mixed
Definition at line 142 of file FormEditor.php.
{
         return false;
     }
Energine\forms\components\FormEditor::main () protected
Default action.
Returns
boolean
Definition at line 254 of file FormEditor.php.
{
         $this->setBuilder($this->createBuilder());
         $this->setDataDescription($this->createDataDescription());
         $this->createPager();
         $this->setData(new Data());
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
         //$this->addTranslation('TXT_FILTER', 'BTN_APPLY_FILTER', 'TXT_RESET_FILTER', 'TXT_FILTER_SIGN_BETWEEN', 'TXT_FILTER_SIGN_CONTAINS', 'TXT_FILTER_SIGN_NOT_CONTAINS');
     }
Energine\forms\components\FormEditor::save () protected
Definition at line 328 of file FormEditor.php.
{
         if ($_POST['componentAction'] != 'edit') {
             $this->constructor->save($_POST);
         } else {
             $this->saveField();
         }
         $c = E()->getCache();
         if ($c->isEnabled()) {
             $c->dispose(Cache::TRANSLATIONS_KEY);
         }
         $this->setBuilder(new JSONCustomBuilder());
     }
Energine\forms\components\FormEditor::saveField () protected
Save field.
Definition at line 346 of file FormEditor.php.
Referenced by Energine\forms\components\FormEditor\save().
{
         $tableName = 'share_lang_tags_translation';
         if (isset($_POST) && isset($_POST[$tableName]) && isset($_POST['share_lang_tags'])) {
             $translations = $_POST[$tableName];
             if (is_array($translations)) {
                 foreach ($translations as $value) {
                     $this->dbh->modify(
                         QAL::UPDATE,
                         $tableName,
                         array('ltag_value_rtf' => $value['ltag_value_rtf']),
                         array('ltag_id' => $_POST['share_lang_tags'], 'lang_id' => $value['lang_id']));
                 }
             }
         }
     }
Energine\forms\components\FormEditor::up () protected
Up.
Definition at line 271 of file FormEditor.php.
{
         list($fieldIndex) = $this->getStateParams();
         $this->constructor->changeOrder(Grid::DIR_UP, $fieldIndex);
         $b = new JSONCustomBuilder();
         $b->setProperties(array(
             'result' => true,
             'dir' => Grid::DIR_UP
         ));
         $this->setBuilder($b);
     }
Member Data Documentation
FormConstructor Energine\forms\components\FormEditor::$constructor private
Form constructor.
Definition at line 38 of file FormEditor.php.
SelectorValuesEditor Energine\forms\components\FormEditor::$SVEditor private
Editor of selector values.
Definition at line 32 of file FormEditor.php.
The documentation for this class was generated from the following file:
core/modules/forms/components/FormEditor.php