Energine: Energine\share\gears\TreeConverter Class Reference
Energine\share\gears\TreeConverter Class Reference
Convert Tree.
Static Public Member Functions
static convert (array $data, $keyName, $parentKeyName)
Run converting.
Private Member Functions
__construct ()
Static Private Member Functions
static validate (array $data)
Validate data.
static iterate (array $data, $parent)
Recursive iteration over tree-like array.
Static Private Attributes
static $keyName
Key name.
static $parentKeyName
Parent key name.
static $treeNodeList
Tree's node list.
Detailed Description
Convert Tree.
final class TreeConverter;
It casts tree-like array into Tree object.
Note
It represents a container of static methods.
Attention
This is final.
Definition at line 33 of file TreeConverter.php.
Constructor & Destructor Documentation
Energine\share\gears\TreeConverter::__construct () private
Definition at line 53 of file TreeConverter.php.
 {}
Member Function Documentation
static Energine\share\gears\TreeConverter::convert (array $data, $keyName, $parentKeyName) static
Run converting.
Parameters
array $data Loaded data.
string $keyName Field name that holds an ID.
string $parentKeyName Field name that holds an parent ID.
Returns
TreeNodeList
Exceptions
Exception 'Неправильный формат древовидных данных'
Definition at line 65 of file TreeConverter.php.
Referenced by Energine\share\gears\Sitemap\__construct(), Energine\comments\gears\CommentsHelper\buildComments(), Energine\user\components\RoleEditor\buildDivRightsData(), Energine\share\components\NavigationMenu\createBuilder(), and Energine\comments\components\CommentsList\createBuilder().
{
         self::$keyName = $keyName;
         self::$parentKeyName = $parentKeyName;
         //Проверяем данные на правильность
         if (!self::validate($data)) {
             throw new \Exception('Неправильный формат древовидных данных');
         }
         return self::iterate($data, self::$treeNodeList = new TreeNodeList());
     }
static Energine\share\gears\TreeConverter::iterate (array $data, $parent) static private
Recursive iteration over tree-like array.
Parameters
array $data Data array in the form
array(array('$keyName'=>$key, '$parentKeyName'=>$parentKey))
.
TreeNode | TreeNodeList $parent Parent object.
Returns
TreeNodeList
Definition at line 104 of file TreeConverter.php.
{
         foreach ($data as $key => $value) {
             //Если родителем является TreeNodeList  - значит мы на начальном шаге итерации и ключ - пустой, во всех других случаях - ключом является идентификатор узла родителя
             if ($parent instanceof TreeNodeList) {
                $parentKey = '';
                $methodName = 'add';
             }
             else {
                $parentKey = $parent->getID();
                $methodName = 'addChild';
             }
             if ($value[self::$parentKeyName] == $parentKey) {
                 //добавляем узел к родителю
                 $addedNode = $parent->$methodName(new TreeNode($value[self::$keyName]));
                 //удаляем из массива данных
                 unset($data[$key]);
                 //делаем рекурсивный вызов, передавая изменившийся набор данных, и родительский узел
                 self::iterate($data, $addedNode);
             }
         }
         return $parent;
     }
static Energine\share\gears\TreeConverter::validate (array $data) static private
Validate data.
Parameters
array $data Data.
Returns
bool
Todo:
реализовать
Definition at line 85 of file TreeConverter.php.
{
         foreach ($data as $value) {
             if (!array_key_exists(self::$parentKeyName, $value) || !array_key_exists(self::$parentKeyName, $value)) {
                 return false;
             }
             elseif($value[self::$keyName] === $value[self::$parentKeyName]) {
                 return false;
             }
         }
         return true;
     }
Member Data Documentation
string Energine\share\gears\TreeConverter::$keyName static private
Key name.
Definition at line 38 of file TreeConverter.php.
Referenced by Energine\share\gears\TreeConverter\convert().
string Energine\share\gears\TreeConverter::$parentKeyName static private
Parent key name.
Definition at line 44 of file TreeConverter.php.
Referenced by Energine\share\gears\TreeConverter\convert().
TreeNodeList Energine\share\gears\TreeConverter::$treeNodeList static private
Tree's node list.
Definition at line 50 of file TreeConverter.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/TreeConverter.php