Energine: Energine\share\gears\FilterField Class Reference
Energine\share\gears\FilterField Class Reference
Filter control.
Public Member Functions
__construct ($name, $type=FieldDescription::FIELD_TYPE_STRING)
attach ($filter)
Attach filter.
setIndex ($index)
Set element ID.
getIndex ()
Get element ID.
load (\SimpleXMLElement $description, array $meta=null)
Load element from XML description.
getType ()
Get element type.
setAttribute ($attrName, $attrValue)
Set attribute.
getAttribute ($attrName)
Get attribute.
build ()
Build element.
translate ($attrs=array('title'))
Translate language-dependent attributes.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const TAG_NAME = 'field'
Element tag name.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
getFilter ()
Get attached filter.
Protected Attributes
$doc
Document.
$type = FieldDescription::FIELD_TYPE_STRING
Element type.
Private Attributes
$attributes = array()
Additional attributes.
$filter
Filter that holds this control element.
$index = false
Element ID.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Filter control.
class FilterField;
Definition at line 27 of file FilterField.php.
Constructor & Destructor Documentation
Energine\share\gears\FilterField::__construct ($name, $type = FieldDescription::FIELD_TYPE_STRING)
Parameters
string $name Name.
string
Definition at line 69 of file FilterField.php.
{
         $this->setAttribute('name', $name);
         $this->type = $type;
         $this->doc = new \DOMDocument('1.0', 'UTF-8');
     }
Member Function Documentation
Energine\share\gears\FilterField::attach ($filter)
Attach filter.
Parameters
Filter $filter Filter.
Definition at line 80 of file FilterField.php.
Referenced by Energine\share\gears\Filter\attachField().
{
         $this->filter = $filter;
     }
Energine\share\gears\FilterField::build ()
Build element.
Returns
DOMNode
Definition at line 188 of file FilterField.php.
{
         $controlElem = $this->doc->createElement(self::TAG_NAME);
         foreach ($this->attributes as $attrName => $attrValue) {
             $controlElem->setAttribute($attrName, $attrValue);
         }
         $controlElem->setAttribute('type', $this->getType());
         $this->doc->appendChild($controlElem);
         return $this->doc->documentElement;
     }
Energine\share\gears\FilterField::getAttribute ($attrName)
Get attribute.
Parameters
string $attrName Attribute name.
Returns
mixed
Definition at line 176 of file FilterField.php.
Referenced by Energine\share\gears\FilterField\load(), and Energine\share\gears\FilterField\translate().
{
         if (isset($this->attributes[$attrName])) {
             return $this->attributes[$attrName];
         }
         return false;
     }
Energine\share\gears\FilterField::getFilter () protected
Get attached filter.
Returns
Filter
Definition at line 89 of file FilterField.php.
{
         return $this->filter;
     }
Energine\share\gears\FilterField::getIndex ()
Get element ID.
Returns
int
Exceptions
SystemException 'ERR_DEV_NO_CONTROL_INDEX'
Definition at line 109 of file FilterField.php.
Referenced by Energine\share\gears\Filter\detachField().
{
         if ($this->index === false) {
             throw new SystemException('ERR_DEV_NO_CONTROL_INDEX', SystemException::ERR_DEVELOPER);
         }
         return $this->index;
     }
Energine\share\gears\FilterField::getType ()
Get element type.
Returns
string
Exceptions
SystemException 'ERR_DEV_NO_CONTROL_TYPE'
Definition at line 156 of file FilterField.php.
Referenced by Energine\share\gears\FilterField\build().
{
         return $this->type;
     }
Energine\share\gears\FilterField::load (\SimpleXMLElement $description, array $meta = null)
Load element from XML description.
Parameters
\SimpleXMLElement $description Element description.
array $meta DB column meta data
Exceptions
SystemException 'ERR_DEV_NO_CONTROL_TYPE'
Definition at line 123 of file FilterField.php.
{
         //Получили список аттрибутов заданных в филдах фильтра
         //Get the attributes list form filter fields
         $attrs = (array)$description->attributes();
         $attrs = $attrs['@attributes'];
         //we do no need name attribute
         unset($attrs['name']);
         if ($meta) {
             if(!isset($attrs['title'])){
                 $attrs['title'] = 'FIELD_'.$this->getAttribute('name');
             }
             $attrs['type'] = FieldDescription::convertType($meta['type'], $this->getAttribute('name'), $meta['length'], $meta);
             $attrs['tableName'] = $meta['tableName'];
         }
         foreach ($attrs as $key => $value) {
             if (isset($this->$key)) {
                 $this->$key = $value;
             } else {
                 $this->setAttribute($key, $value);
             }
         }
     }
Energine\share\gears\FilterField::setAttribute ($attrName, $attrValue)
Set attribute.
Parameters
string $attrName Attribute name.
mixed $attrValue Attribute value.
Definition at line 166 of file FilterField.php.
Referenced by Energine\share\gears\FilterField\__construct(), Energine\share\components\Grid\createFilter(), Energine\share\gears\FilterField\load(), and Energine\share\gears\FilterField\translate().
{
         $this->attributes[$attrName] = $attrValue;
     }
Energine\share\gears\FilterField::setIndex ($index)
Set element ID.
Parameters
int $index ID.
Definition at line 98 of file FilterField.php.
Referenced by Energine\share\gears\Filter\attachField().
{
         $this->index = $index;
     }
Energine\share\gears\FilterField::translate ($attrs = array('title'))
Translate language-dependent attributes.
Parameters
array $attrs Set of attributes for translation.
Definition at line 206 of file FilterField.php.
{
         foreach ($attrs as $attrName) {
             $attrValue = (string)$this->getAttribute($attrName);
             if ($attrValue) {
                 $this->setAttribute($attrName, DBWorker::_translate($attrValue));
             }
         }
     }
Member Data Documentation
array Energine\share\gears\FilterField::$attributes = array() private
Additional attributes.
Definition at line 51 of file FilterField.php.
DOMDocument Energine\share\gears\FilterField::$doc protected
Document.
Definition at line 38 of file FilterField.php.
Filter Energine\share\gears\FilterField::$filter private
Filter that holds this control element.
Definition at line 57 of file FilterField.php.
Referenced by Energine\share\gears\FilterField\attach(), and Energine\share\gears\FilterField\getFilter().
int Energine\share\gears\FilterField::$index = false private
Element ID.
Definition at line 63 of file FilterField.php.
Referenced by Energine\share\gears\FilterField\getIndex(), and Energine\share\gears\FilterField\setIndex().
string Energine\share\gears\FilterField::$type = FieldDescription::FIELD_TYPE_STRING protected
Element type.
Definition at line 45 of file FilterField.php.
Referenced by Energine\share\gears\FilterField\__construct(), and Energine\share\gears\FilterField\getType().
string Energine\share\gears\FilterField::TAG_NAME = 'field'
Element tag name.
Definition at line 32 of file FilterField.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/FilterField.php