Energine: Energine\share\gears\DBWorker Class Reference
Energine\share\gears\DBWorker Class Reference
Provide the derived classes the reference to the object for work with DB.
Public Member Functions
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Protected Attributes
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes
static $dbhInstance
QAL object.
Static Private Attributes
static $translationsCache = null
Translation cache.
static $findTranslationSQL
Request to find translation.
Additional Inherited Members
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
Provide the derived classes the reference to the object for work with DB.
abstract class DBWorker;
Attention
This is abstract.
Definition at line 25 of file DBWorker.php.
Constructor & Destructor Documentation
Energine\share\gears\DBWorker::__construct ()
Definition at line 53 of file DBWorker.php.
{
         $this->dbh = E()->getDB();
         self::$findTranslationSQL = $this->dbh->getPDO()->prepare('SELECT trans.ltag_value_rtf AS translation FROM share_lang_tags ltag  LEFT JOIN share_lang_tags_translation trans ON trans.ltag_id = ltag.ltag_id  WHERE (ltag.ltag_name = ?) AND (lang_id = ?)');
     }
Member Function Documentation
static Energine\share\gears\DBWorker::_dateToString ($year, $month, $day) static
Transform date to the string.
Parameters
int $year Year value.
int $month Month value.
int $day Day value
Returns
string
Definition at line 108 of file DBWorker.php.
{
         $result = (int)$day . ' ' . self::_translate('TXT_MONTH_' . (int)$month) . ' ' . $year;
         return $result;
     }
static Energine\share\gears\DBWorker::_translate ($const, $langId = null) static
Get the translation of the text constant.
Get the translation of the text constant from the translation table for specific language. If the language not provided, then current language will be used.
Parameters
string $const Text constant
int $langId Language ID.
Returns
string
Definition at line 68 of file DBWorker.php.
Referenced by Energine\share\gears\Filter\__construct(), Energine\share\gears\SystemException\__construct(), Energine\share\gears\Select\addItem(), Energine\share\gears\Pager\build(), Energine\share\gears\Filter\build(), Energine\share\components\DivisionEditor\buildRightsTab(), Energine\share\gears\AbstractBuilder\enFormatDate(), Energine\calendar\gears\CalendarObject\getPeriod(), Energine\share\gears\FilterField\translate(), and Energine\share\gears\Control\translate().
{
         if (empty($const)) return $const;
         $const = strtoupper($const);
         if(is_null($langId)){
             $langId = intval(E()->getLanguage()->getCurrent());
         }
         $result = $const;
         //Мы еще не обращались за этим переводом
         if(!isset(self::$translationsCache[$langId][$const])){
             //Если что то пошло не так - нет смысл генерить ошибку, отдадим просто константу
             if(self::$findTranslationSQL->execute(array($const, $langId))){
                 //записали в кеш
                 if($result = self::$findTranslationSQL->fetchColumn()){
                     self::$translationsCache[$langId][$const] = $result;
                 }
                 else {
                     $result = $const;
                 }
             }
         }
         //За переводом уже обращались  Он есть
         elseif(self::$translationsCache[$langId][$const]){
             $result = self::$translationsCache[$langId][$const];
         }
         //Неявный случай - за переводом уже обращались но его нету
         //Отдаем константу
         return $result;
     }
Energine\share\gears\DBWorker::dateToString ($date, $format = '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Parameters
string $date Date.
string $format Date format.
Returns
string
Definition at line 133 of file DBWorker.php.
{
         list($year, $month, $day) = sscanf($date, $format);
         return self::_dateToString($year, $month, $day);
     }
Energine\share\gears\DBWorker::translate ($const, $langID = null)
Non-static wrapper method over DBWorker::_translate.
This is for using inside derived class.
Parameters
string $const Text constant.
mixed $langID Language ID.
Returns
string
Definition at line 122 of file DBWorker.php.
Referenced by Energine\apps\components\FeedbackForm\__construct(), Energine\share\components\LanguageEditor\__construct(), Energine\user\components\UserEditor\__construct(), Energine\user\components\LoginForm\__construct(), Energine\user\components\Register\__construct(), Energine\apps\components\Feed\__construct(), Energine\user\components\RoleEditor\__construct(), Energine\share\components\DivisionEditor\__construct(), Energine\share\components\Grid\__construct(), Energine\share\components\DataSet\__construct(), Energine\share\gears\Saver\addError(), Energine\share\gears\Document\build(), Energine\user\components\RoleEditor\buildDivRightsData(), Energine\forms\components\Form\buildForm(), Energine\share\components\TextBlock\buildJS(), Energine\share\components\DBDataSet\buildJS(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\share\components\DivisionEditor\buildRightsTab(), Energine\comments\components\CommentsEditor\changeTableName(), Energine\user\components\Register\checkCaptcha(), Energine\apps\components\FeedbackForm\checkCaptcha(), Energine\forms\components\Form\checkCaptcha(), Energine\comments\components\CommentsForm\checkCaptcha(), Energine\user\components\Register\checkLogin(), Energine\share\components\ImageManager\createDataDescription(), Energine\user\components\RoleEditor\createDataDescription(), Energine\user\components\UserEditor\createDataDescription(), Energine\user\components\UserProfile\createDataDescription(), Energine\comments\components\CommentsList\createPager(), Energine\share\components\DataSet\createPager(), Energine\share\components\FileRepository\createThumbFields(), Energine\comments\components\CommentsForm\deleteComment(), Energine\forms\components\FormEditor\edit(), Energine\share\components\DivisionEditor\edit(), Energine\user\components\UserProfile\error(), Energine\share\components\Grid\exportCSV(), Energine\share\components\Grid\generateError(), Energine\forms\gears\FormConstructor\getData(), Energine\forms\gears\FormConstructor\getDataDescription(), Energine\share\gears\JSONBuilder\getResult(), Energine\share\components\DivisionEditor\getTemplateInfo(), Energine\share\components\Grid\linkExtraManagers(), Energine\share\gears\FieldDescription\loadAvailableXMLValues(), Energine\share\components\DivisionEditor\loadTemplateData(), Energine\user\components\UserProfile\main(), Energine\apps\components\NewsFeed\main(), Energine\apps\components\VoteEditor\prepare(), Energine\share\components\SiteEditor\prepare(), Energine\forms\components\FormResults\returnEmptyRecordset(), Energine\share\gears\MultiLanguageBuilder\run(), Energine\share\gears\Builder\run(), Energine\comments\components\CommentsForm\saveComment(), Energine\user\components\Register\saveData(), Energine\user\components\RestorePassword\send(), Energine\apps\components\FeedbackForm\send(), Energine\forms\components\Form\send(), Energine\share\gears\FieldDescription\setProperty(), Energine\user\components\SocialLoginForm\showLoginForm(), Energine\user\components\LoginForm\showLoginForm(), Energine\user\components\UserProfile\success(), Energine\user\components\Register\success(), Energine\apps\components\FeedbackForm\success(), Energine\forms\components\Form\success(), and Energine\apps\components\NewsFeed\tag().
{
         return self::_translate($const, $langID);
     }
Member Data Documentation
QAL Energine\share\gears\DBWorker::$dbh protected
Reference to the DBWorker::$dbhInstance for derived classes.
Definition at line 36 of file DBWorker.php.
QAL Energine\share\gears\DBWorker::$dbhInstance static protected
QAL object.
Definition at line 30 of file DBWorker.php.
PDOStatement Energine\share\gears\DBWorker::$findTranslationSQL static private
Request to find translation.
Definition at line 51 of file DBWorker.php.
array Energine\share\gears\DBWorker::$translationsCache = null static private
Translation cache.
(получается за ними по отдельности очень часто нужно обращаться)
Definition at line 45 of file DBWorker.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/DBWorker.php