Energine: Energine\share\components\DataSet Class Reference
Energine\share\components\DataSet Class Reference
Abstract data set.
Public Member Functions
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
Возвращает описание данных
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Protected Attributes
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Attributes
$source
Source.
$dataDescription = false
Data description.
$data = false
Data.
$toolbar = array()
Array of toolbars.
$type
Component type.
Additional Inherited Members
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Abstract data set.
abstract class DataSet;
This is a parent class for form, list and tree; it contains methods to work with toolbar and data sets.
Attention
This is abstract.
Definition at line 30 of file DataSet.php.
Constructor & Destructor Documentation
Energine\share\components\DataSet::__construct ($name, $module, array $params = null)
Parameters
string $name Component name.
string $module Module name.
array $params Component parameters.
Definition at line 123 of file DataSet.php.
{
         parent::__construct($name, $module, $params);
         $this->setType(self::COMPONENT_TYPE_FORM);
         if (!$this->getParam('recordsPerPage')) $this->setParam('recordsPerPage', self::RECORD_PER_PAGE);
         if ($this->getParam('template')) {
             $this->setProperty('template', $this->getParam('template') . '/');
         }
         if ($this->getParam('title'))
             $this->setTitle(
                 $this->translate($this->getParam('title')
                 )
             );
     }
Member Function Documentation
Energine\share\components\DataSet::addToolbar ($toolbar) protected
Add toolbar.
Parameters
mixed $toolbar New toolbar.
Exceptions
SystemException 'ERR_BAD_TOOLBAR'
Definition at line 196 of file DataSet.php.
Referenced by Energine\forms\components\FormEditor\add(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\forms\components\FormEditor\edit(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\share\components\LinkingEditor\main(), Energine\forms\components\FormEditor\main(), Energine\share\components\DataSet\prepare(), Energine\share\components\FileRepository\putVideo(), Energine\share\components\DivisionEditor\showPageToolbar(), and Energine\apps\components\NewsFeed\view().
{
         if (!is_array($toolbar)) {
             $toolbar = array($toolbar);
         }
         foreach ($toolbar as $tb)
             if ($tb instanceof Toolbar) {
                 $this->toolbar[$tb->getName()] = $tb;
             } else {
                 throw new SystemException('ERR_BAD_TOOLBAR', SystemException::ERR_DEVELOPER);
             }
     }
Energine\share\components\DataSet::addTranslation () final protected
Add translation.
Attention
This is final.
Definition at line 592 of file DataSet.php.
Referenced by Energine\apps\components\FeedbackForm\__construct(), Energine\user\components\Register\__construct(), Energine\forms\components\Form\__construct(), Energine\share\components\PageList\__construct(), Energine\share\components\FileRepository\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\comments\components\CommentsForm\__construct(), Energine\share\components\DataSet\build(), Energine\share\components\Grid\build(), Energine\share\components\DivisionEditor\main(), Energine\share\components\DivisionEditor\prepare(), Energine\comments\components\CommentsForm\prepare(), Energine\share\components\DivisionEditor\selector(), Energine\apps\components\ExtendedFeedEditor\setParam(), Energine\user\components\LoginForm\showLogoutForm(), and Energine\apps\components\ExtendedFeed\view().
{
         foreach (func_get_args() as $tag) {
             $this->document->addTranslation($tag, $this);
         }
     }
Energine\share\components\DataSet::addWYSIWYGTranslations () final protected
Add translations for WYSIWYG toolbar.
Note
It is called from children.
Attention
This is final.
Definition at line 634 of file DataSet.php.
Referenced by Energine\share\components\TextBlockSource\__construct(), Energine\share\components\TextBlock\__construct(), Energine\share\components\Grid\addToolbarTranslations(), and Energine\share\components\DBDataSet\buildJS().
{
         $translations = array(
             'BTN_ITALIC',
             'BTN_HREF',
             'BTN_UL',
             'BTN_OL',
             'BTN_ALIGN_LEFT',
             'TXT_PREVIEW',
             'BTN_FILE_LIBRARY',
             'BTN_INSERT_IMAGE',
             'BTN_INSERT_IMAGE_URL',
             'BTN_VIEWSOURCE',
             'TXT_PREVIEW',
             'TXT_RESET',
             'TXT_H1',
             'TXT_H2',
             'TXT_H3',
             'TXT_H4',
             'TXT_H5',
             'TXT_H6',
             'TXT_ADDRESS',
             'TXT_ERROR_NOT_VIDEO_FILE',
             'BTN_SAVE',
             'BTN_BOLD',
             'BTN_ALIGN_CENTER',
             'BTN_ALIGN_RIGHT',
             'BTN_ALIGN_JUSTIFY',
             'BTN_EXT_FLASH',
             'BTN_ACTIVATE'
         );
         call_user_func_array(array($this, 'addTranslation'), $translations);
     }
Energine\share\components\DataSet::build ()
Build block.
Returns
Exceptions
SystemException
Implements Energine\share\gears\IBlock.
Definition at line 378 of file DataSet.php.
{
         if ($this->getState() == 'fileLibrary') {
             $result = $this->fileLibrary->build();
         } elseif ($this->getState() == 'imageManager') {
             $result = $this->imageManager->build();
         } elseif ($this->getState() == 'source') {
             $result = $this->source->build();
         } else {
             if (!$this->getBuilder()) {
                 throw new SystemException(
                     'ERR_DEV_NO_BUILDER:' . $this->getName() . ': ' .
                     $this->getState(), SystemException::ERR_CRITICAL, $this->getName());
             }
             // передаем данные и описание данных построителю
             if ($this->getData() && method_exists($this->getBuilder(), 'setData')) {
                 $this->getBuilder()->setData($this->getData());
             }
             if (method_exists($this->getBuilder(), 'setDataDescription'))
                 $this->getBuilder()->setDataDescription($this->getDataDescription());
             // вызываем родительский метод построения
             $result = parent::build();
             if ($this->js) {
                 $result->documentElement->appendChild($result->importNode($this->js, true));
             }
             $toolbars = $this->getToolbar();
             if (!empty($toolbars))
                 foreach ($toolbars as $tb)
                     if ($toolbar = $tb->build()) {
                         $result->documentElement->appendChild(
                             $result->importNode($toolbar, true)
                         );
                     }
             if (
                 $this->pager && $this->getType() == self::COMPONENT_TYPE_LIST
                 &&
                 $pagerData = $this->pager->build()
             ) {
                 $pager = $result->importNode($pagerData, true);
                 $result->documentElement->appendChild($pager);
             }
             //Работа с константами переводов
             if (($methodConfig = $this->getConfig()->getCurrentStateConfig()) &&
                 $methodConfig->translations
             ) {
                 foreach ($methodConfig->translations->translation as $translation) {
                     $this->addTranslation((string)$translation['const']);
                 }
             }
         }
         return $result;
     }
Energine\share\components\DataSet::buildJS () protected
Create description of JS objects.
Returns
DOMNode
Definition at line 477 of file DataSet.php.
Referenced by Energine\forms\components\FormEditor\add(), Energine\forms\components\FormEditor\edit(), Energine\share\components\DataSet\embedPlayer(), Energine\apps\components\Vote\main(), Energine\forms\components\FormEditor\main(), and Energine\share\components\DataSet\prepare().
{
         $result = false;
         if (($config = $this->getConfig()->getCurrentStateConfig()) &&
             $config->javascript
         ) {
             $result = $this->doc->createElement('javascript');
             foreach ($config->javascript->behavior as $value) {
                 $JSObjectXML = $this->doc->createElement('behavior');
                 $JSObjectXML->setAttribute('name', $value['name']);
                 $JSObjectXML->setAttribute('path', ($value['path']) ?
                     $value['path'] . '/' : '');
                 $result->appendChild($JSObjectXML);
             }
             foreach ($config->javascript->variable as $value) {
                 $JSObjectXML = $this->doc->createElement('variable');
                 $JSObjectXML->setAttribute('name', $value['name']);
                 $JSObjectXML->setAttribute('type', ($value['type']) ?
                     $value['type'] : 'string');
                 $JSObjectXML->appendChild(new \DomText((string)$value));
                 $result->appendChild($JSObjectXML);
             }
         }
         return $result;
     }
Energine\share\components\DataSet::cleanup () protected
Clean up.
Definition at line 619 of file DataSet.php.
{
         $data = isset($_POST['data']) ? $_POST['data'] : '';
         $data = self::cleanupHTML($data);
         $this->response->setHeader('Content-Type', 'text/html; charset=utf-8');
         $this->response->write($data);
         $this->response->commit();
     }
static Energine\share\components\DataSet::cleanupHTML ($data) static
Remove malicious and redundant HTML code.
Parameters
string $data Data.
Returns
string
Definition at line 749 of file DataSet.php.
Referenced by Energine\share\gears\Saver\save(), Energine\share\components\TextBlock\save(), and Energine\share\components\DBDataSet\saveText().
{
         $aggressive = Object::_getConfigValue('site.aggressive_cleanup', false);
         //Если подключено расширение tidy
         if (function_exists('tidy_get_output') && $aggressive) {
             try {
                 $tidy = new \tidy();
                 $config = array(
                     'bare' => true,
                     'drop-font-tags' => true,
                     'drop-proprietary-attributes' => true,
                     'hide-comments' => true,
                     'logical-emphasis' => true,
                     'numeric-entities' => true,
                     'show-body-only' => true,
                     'quote-nbsp' => false,
                     'indent' => 'auto',
                     'wrap' => 72,
                     'output-html' => true,
                 );
                 //if ($aggressive) {
                 $config = array_merge(
                     $config,
                     array(
                         //'clean' => true,
                         'word-2000' => true,
                         'drop-empty-paras' => true
                     )
                 );
                 //}
                 $data = $tidy->repairString($data, $config, 'utf8');
             } catch (\Exception $dummyError) {
                 //inspect($dummyError);
             }
             unset($tidy);
         }
         $base = E()->getSiteManager()->getCurrentSite()->base;
         $data = str_replace((strpos($data, '%7E')) ? str_replace('~', '%7E', $base) : $base, '', $data);
         return $data;
     }
Energine\share\components\DataSet::createBuilder () protected
Create builder.
Returns
AbstractBuilder
Definition at line 268 of file DataSet.php.
Referenced by Energine\share\components\DataSet\prepare().
{
         if (!isset($this->builder) || !$this->builder)
             return new Builder($this->getTitle());
         else return $this->builder;
     }
Energine\share\components\DataSet::createData () protected
Create data.
Returns
Exceptions
SystemException 'ERR_DEV_LOAD_DATA_IS_FUNCTION'
Definition at line 458 of file DataSet.php.
Referenced by Energine\share\components\BreadCrumbs\prepare(), and Energine\share\components\DataSet\prepare().
{
         $result = false;
         $data = $this->loadData();
         if (is_null($data)) {
             throw new SystemException('ERR_DEV_LOAD_DATA_IS_FUNCTION', SystemException::ERR_DEVELOPER);
         }
         $result = new Data();
         if (is_array($data)) {
             $result->load($data);
         }
         return $result;
     }
Energine\share\components\DataSet::createDataDescription () protected
Create data description.
Returns
DataDescription
Exceptions
SystemException 'ERR_DEV_LOAD_DATA_DESCR_IS_FUNCTION'
Definition at line 281 of file DataSet.php.
Referenced by Energine\share\components\DataSet\prepare().
{
         // описание данных из конфигурации
         $configDataDescriptionObject = new DataDescription();
         if ($this->getConfig()->getCurrentStateConfig()) {
             $configDataDescriptionObject->loadXML($this->getConfig()->getCurrentStateConfig()->fields);
         }
         // внешнее описание данных
         $externalDataDescription = $this->loadDataDescription();
         if (is_null($externalDataDescription)) {
             throw new SystemException('ERR_DEV_LOAD_DATA_DESCR_IS_FUNCTION', SystemException::ERR_DEVELOPER);
         }
         // если существует внешнее описание данных - пересекаем с описанием из конфиг
         if ($externalDataDescription) {
             $externalDataDescriptionObject = new DataDescription();
             $externalDataDescriptionObject->load($externalDataDescription);
             $configDataDescriptionObject =
                 $configDataDescriptionObject->intersect($externalDataDescriptionObject);
         }
         return $configDataDescriptionObject;
     }
Energine\share\components\DataSet::createPager () protected
Create pager.
Definition at line 334 of file DataSet.php.
Referenced by Energine\forms\components\FormEditor\getRawData(), Energine\share\components\Grid\getRawData(), Energine\forms\components\FormEditor\main(), Energine\share\components\DataSet\prepare(), and Energine\apps\components\NewsFeed\view().
{
         $recordsPerPage = intval($this->getParam('recordsPerPage'));
         if ($recordsPerPage > 0) {
             $this->pager = new Pager($recordsPerPage);
             if ($this->isActive() &&
                 $this->getType() == self::COMPONENT_TYPE_LIST
             ) {
                 $actionParams = $this->getStateParams(true);
                 if (!isset($actionParams['pageNumber']) ||
                     !($page = intval($actionParams['pageNumber']))
                 ) {
                     $page = 1;
                 }
                 $this->pager->setCurrentPage($page);
             }
             $this->pager->setProperty('title', $this->translate('TXT_PAGES'));
         }
     }
Energine\share\components\DataSet::createToolbar () protected
Create toolbar.
Returns
Toolbar|Toolbar[]
Definition at line 311 of file DataSet.php.
Referenced by Energine\forms\components\FormEditor\add(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\forms\components\FormEditor\edit(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\share\components\LinkingEditor\main(), Energine\forms\components\FormEditor\main(), Energine\share\components\DataSet\prepare(), Energine\share\components\FileRepository\putVideo(), Energine\share\components\DivisionEditor\showPageToolbar(), and Energine\apps\components\NewsFeed\view().
{
         $result = array();
         if ($config = $this->getConfig()->getCurrentStateConfig()) {
             foreach ($config->toolbar as $toolbarDescription) {
                 $toolbarName = ((string)$toolbarDescription['name']) ?
                     (string)$toolbarDescription['name'] :
                     self::TB_PREFIX . $this->getName();
                 $toolbar = new Toolbar($toolbarName);
                 $toolbar->attachToComponent($this);
                 $toolbar->loadXML($toolbarDescription);
                 $toolbar->translate();
                 $result[$toolbarName] = $toolbar;
             }
         }
         return $result;
     }
Energine\share\components\DataSet::defineParams () protected
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
Returns
array
Definition at line 140 of file DataSet.php.
{
         $this->setProperty('state', '');
         return array_merge(
             parent::defineParams(),
             array(
                 'datasetAction' => '',
                 'recordsPerPage' => false,
                 'title' => false,
                 'template' => false,
             )
         );
     }
Energine\share\components\DataSet::downloadFile ($data, $MIMEType, $fileName) final protected
Download file.
Parameters
string $data File data.
string $MIMEType File type.
string $fileName Filename.
Attention
This is final.
Definition at line 608 of file DataSet.php.
Referenced by Energine\share\components\Grid\exportCSV().
{
         $this->response->setHeader('Content-Type', $MIMEType);
         $this->response->setHeader('Content-Disposition',
             ': attachment; filename="' . $fileName . '"');
         $this->response->write($data);
         $this->response->commit();
     }
Energine\share\components\DataSet::embedPlayer () protected
Player for embedding in text areas.
Definition at line 697 of file DataSet.php.
{
         $sp = $this->getStateParams();
         list($uplId) = $sp;
         $fileInfo = $this->dbh->select(
             'share_uploads',
             array(
                 'upl_path',
                 'upl_name'
             ),
             array(
                 'upl_id' => intval($uplId),
                 'upl_internal_type' => \Energine\share\gears\FileRepoInfo::META_TYPE_VIDEO
             )
         );
         if(!is_array($fileInfo)) {
             throw new SystemException('ERROR_NO_VIDEO_FILE', SystemException::ERR_404);
         }
         // Using array_values to transform associative index to key index
         list($file, $name) = array_values($fileInfo[0]);
         $dd = new DataDescription();
         foreach(
             array(
                 'file' => FieldDescription::FIELD_TYPE_STRING,
                 'name' => FieldDescription::FIELD_TYPE_STRING
             ) as $fName => $fType
         ) {
             $fd = new FieldDescription($fName);
             $fd->setType($fType);
             $dd->addFieldDescription($fd);
         }
         $this->setBuilder(new SimpleBuilder());
         $this->setDataDescription($dd);
         $data = new Data();
         $data->load(
           array(
               array(
                   'file' => $file,
                   'name' => $name
               )
           )
         );
         $this->setData($data);
         $this->js = $this->buildJS();
         E()->getController()->getTransformer()->setFileName('core/modules/share/transformers/embed_player.xslt', true);
     }
Energine\share\components\DataSet::fileLibrary () protected
Get file library.
Definition at line 670 of file DataSet.php.
Referenced by Energine\share\components\DataSet\build().
{
         $this->request->shiftPath(1);
         $this->fileLibrary = $this->document->componentManager->createComponent('filelibrary', 'share', 'FileRepository', array('config' => 'core/modules/share/config/FileRepositorySelect.component.xml'));
         $this->fileLibrary->run();
     }
Energine\share\components\DataSet::getConfig () protected
Definition at line 440 of file DataSet.php.
Referenced by Energine\share\components\DataSet\build(), Energine\share\components\DataSet\buildJS(), Energine\share\components\DataSet\createDataDescription(), Energine\share\components\DataSet\createToolbar(), Energine\forms\components\Form\failure(), Energine\user\components\Register\failure(), Energine\apps\components\FeedbackForm\failure(), Energine\apps\components\FeedbackForm\saveData(), and Energine\forms\components\Form\saveData().
{
         if (!$this->config) {
             $this->config = new DataSetConfig(
                 $this->getParam('config'),
                 get_class($this),
                 $this->module
             );
         }
         return $this->config;
     }
Energine\share\components\DataSet::getData ()
Get data.
Returns
Data
Definition at line 168 of file DataSet.php.
Referenced by Energine\apps\components\NewsEditor\add(), Energine\apps\components\ExtendedFeedEditor\add(), Energine\apps\components\VoteEditor\add(), Energine\apps\components\VoteQuestionEditor\add(), Energine\share\components\Grid\add(), Energine\share\components\DivisionEditor\add(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\user\components\RoleEditor\build(), Energine\share\components\LanguageEditor\build(), Energine\share\components\DataSet\build(), Energine\forms\components\Form\buildForm(), Energine\share\components\DivisionEditor\buildRightsTab(), Energine\apps\components\ExtendedFeedEditor\edit(), Energine\apps\components\NewsRepository\edit(), Energine\comments\components\CommentsEditor\edit(), Energine\forms\components\FormEditor\edit(), Energine\share\components\DivisionEditor\edit(), Energine\forms\components\Form\failure(), Energine\user\components\Register\failure(), Energine\apps\components\FeedbackForm\failure(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\FileRepository\getRawData(), Energine\apps\components\Vote\getVote(), Energine\apps\components\Vote\getVoteResults(), Energine\share\components\Grid\linkExtraManagers(), Energine\share\components\PageMedia\main(), Energine\apps\components\Ads\main(), Energine\apps\components\SimilarNews\main(), Energine\apps\components\ExtendedFeed\main(), Energine\share\components\PageList\main(), Energine\apps\components\Feed\main(), Energine\seo\components\GoogleSitemap\map(), Energine\apps\components\VoteEditor\prepare(), Energine\share\components\DomainEditor\prepare(), Energine\share\components\SiteEditor\prepare(), Energine\share\components\BreadCrumbs\prepare(), Energine\share\components\AttachmentEditor\prepare(), Energine\comments\components\CommentsForm\prepare(), Energine\apps\components\NewsFeed\rss(), Energine\apps\components\FeedbackForm\saveData(), Energine\forms\components\Form\saveData(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), Energine\user\components\RestorePassword\send(), Energine\user\components\SocialLoginForm\showLoginForm(), Energine\user\components\LoginForm\showLoginForm(), Energine\apps\components\ExtendedFeed\view(), and Energine\apps\components\NewsFeed\view().
{
         return $this->data;
     }
Energine\share\components\DataSet::getDataDescription () final protected
Возвращает описание данных
Returns
DataDescription
Attention
This is final.
Exceptions
SystemException 'ERR_DEV_NO_DATA_DESCRIPTION'
Definition at line 225 of file DataSet.php.
Referenced by Energine\apps\components\NewsEditor\add(), Energine\share\components\LanguageEditor\add(), Energine\apps\components\ExtendedFeedEditor\add(), Energine\share\components\Grid\add(), Energine\share\components\DivisionEditor\add(), Energine\share\components\Grid\addToolbarTranslations(), Energine\user\components\RoleEditor\build(), Energine\share\components\LanguageEditor\build(), Energine\share\components\DataSet\build(), Energine\forms\components\Form\buildForm(), Energine\share\components\DBDataSet\commonLoadData(), Energine\share\components\Grid\createData(), Energine\share\components\Grid\createFilter(), Energine\share\components\FileRepository\createThumbFields(), Energine\apps\components\ExtendedFeedEditor\edit(), Energine\comments\components\CommentsEditor\edit(), Energine\forms\components\FormEditor\edit(), Energine\share\components\DivisionEditor\edit(), Energine\share\components\FileRepository\editFile(), Energine\forms\components\Form\failure(), Energine\user\components\Register\failure(), Energine\apps\components\FeedbackForm\failure(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\FileRepository\getRawData(), Energine\apps\components\Vote\getVoteResults(), Energine\share\components\Grid\linkExtraManagers(), Energine\user\components\LoginForm\loadData(), Energine\share\components\PageList\loadData(), Energine\share\components\DivisionEditor\loadData(), Energine\share\components\PageMedia\main(), Energine\apps\components\Ads\main(), Energine\apps\components\SimilarNews\main(), Energine\apps\components\ExtendedFeed\main(), Energine\share\components\PageList\main(), Energine\comments\components\CommentsEditor\main(), Energine\share\components\DBDataSet\modify(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\TranslationEditor\prepare(), Energine\apps\components\VoteEditor\prepare(), Energine\share\components\DomainEditor\prepare(), Energine\share\components\SiteEditor\prepare(), Energine\share\components\AttachmentEditor\prepare(), Energine\user\components\Register\prepare(), Energine\apps\components\FeedbackForm\prepare(), Energine\share\components\DivisionEditor\prepare(), Energine\comments\components\CommentsForm\prepare(), Energine\user\components\UserProfile\save(), Energine\apps\components\FeedbackForm\saveData(), Energine\forms\components\Form\saveData(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), Energine\forms\components\Form\send(), Energine\user\components\SocialLoginForm\showLoginForm(), Energine\user\components\LoginForm\showLoginForm(), Energine\apps\components\ExtendedFeed\view(), Energine\apps\components\NewsFeed\view(), and Energine\share\components\DBDataSet\view().
{
         // Существует ли описание данных?
         // Без описания данных компонент не сможет нормально работать.
         if (!$this->dataDescription) {
             throw new SystemException('ERR_DEV_NO_DATA_DESCRIPTION', SystemException::ERR_DEVELOPER, $this->getName());
         }
         // Описание данных не должно быть пустым
         /*if ($this->dataDescription->isEmpty()) {
               //throw new SystemException('ERR_DEV_EMPTY_DATA_DESCRIPTION', SystemException::ERR_DEVELOPER, $this->getName());
           }*/
         return $this->dataDescription;
     }
Energine\share\components\DataSet::getDataSetAction () final protected
Get an address of form processor.
Returns
string
Attention
This is final.
Definition at line 535 of file DataSet.php.
{
         return $this->getParam('datasetAction');
     }
Energine\share\components\DataSet::getTitle () final protected
Get component title.
Returns
string
Attention
This is final.
Definition at line 583 of file DataSet.php.
Referenced by Energine\user\components\Register\__construct(), Energine\share\components\Grid\__construct(), Energine\share\components\DivisionEditor\buildRightsTab(), Energine\share\components\DataSet\createBuilder(), and Energine\share\components\Grid\exportCSV().
{
         return $this->getProperty('title');
     }
Energine\share\components\DataSet::getToolbar ($toolbarName = false) protected
Get toolbar(s).
Parameters
string | bool $toolbarName Toolbar name.
Returns
Toolbar|array
Definition at line 178 of file DataSet.php.
Referenced by Energine\share\components\LinkingEditor\build(), Energine\share\components\DataSet\build(), Energine\share\components\DivisionEditor\build(), Energine\user\components\SocialLoginForm\showLoginForm(), Energine\user\components\LoginForm\showLoginForm(), and Energine\share\components\DivisionEditor\showPageToolbar().
{
         $result = array();
         if (!$toolbarName) {
             $result = $this->toolbar;
         } elseif (isset($this->toolbar[$toolbarName])) {
             $result = $this->toolbar[$toolbarName];
         }
         return $result;
     }
Energine\share\components\DataSet::getType () final protected
Get component type.
Returns
string
Attention
This is final.
Definition at line 561 of file DataSet.php.
Referenced by Energine\user\components\RoleEditor\build(), Energine\share\components\LanguageEditor\build(), Energine\share\components\LinkingEditor\build(), Energine\share\components\DataSet\build(), Energine\share\components\Grid\build(), Energine\share\components\DBDataSet\commonLoadData(), Energine\apps\components\FeedEditor\createData(), Energine\user\components\RoleEditor\createData(), Energine\user\components\UserEditor\createData(), Energine\share\components\Grid\createData(), Energine\apps\components\FeedEditor\createDataDescription(), Energine\share\components\LanguageEditor\createDataDescription(), Energine\user\components\RoleEditor\createDataDescription(), Energine\user\components\UserEditor\createDataDescription(), Energine\share\components\DivisionEditor\createDataDescription(), Energine\comments\components\CommentsList\createPager(), Energine\share\components\DataSet\createPager(), Energine\share\components\DBDataSet\multiLoadData(), and Energine\share\components\Grid\prepare().
{
         return $this->type;
     }
Energine\share\components\DataSet::imageManager () protected
Show image manager.
Definition at line 689 of file DataSet.php.
Referenced by Energine\share\components\DataSet\build().
{
         $this->imageManager = $this->document->componentManager->createComponent('imagemanager', 'share', 'ImageManager', null);
         $this->imageManager->run();
     }
Energine\share\components\DataSet::loadData () protected
Load data.
Returns
mixed
Definition at line 359 of file DataSet.php.
Referenced by Energine\share\components\DataSet\createData().
{
         return false;
     }
Energine\share\components\DataSet::loadDataDescription () protected
Load data description.
Use this to load external data description (not from configurations).
Returns
mixed
Definition at line 369 of file DataSet.php.
Referenced by Energine\share\components\DataSet\createDataDescription().
{
         return false;
     }
Energine\share\components\DataSet::prepare () protected
Prepare data.
Note
It calls at the beginning of the method, that realize main action.
Definition at line 243 of file DataSet.php.
Referenced by Energine\forms\components\Form\failure(), Energine\share\components\PageMedia\main(), Energine\user\components\UserProfile\main(), Energine\share\components\TextBlock\main(), Energine\seo\components\GoogleSitemap\map(), Energine\user\components\UserProfile\save(), Energine\user\components\RestorePassword\send(), Energine\user\components\SocialLoginForm\showLoginForm(), Energine\user\components\LoginForm\showLoginForm(), Energine\user\components\LoginForm\showLogoutForm(), and Energine\share\components\DBDataSet\view().
{
         $this->setBuilder($this->createBuilder());
         //$this->setDataDescription($this->createDataDescription());
         $this->setDataDescription($this->createDataDescription());
         $this->createPager();
         $data = $this->createData();
         if ($data instanceof Data) {
             $this->setData($data);
         }
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
     }
Energine\share\components\DataSet::setAction ($action, $isFullURI = false) final protected
Set action for form processor.
Parameters
string $action Action name.
bool $isFullURI Is the URI full?
Attention
This is final.
Definition at line 510 of file DataSet.php.
Referenced by Energine\apps\components\FeedbackForm\__construct(), Energine\user\components\RestorePassword\__construct(), Energine\user\components\LoginForm\__construct(), Energine\user\components\Register\__construct(), Energine\forms\components\Form\__construct(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\user\components\UserProfile\main(), and Energine\share\components\FileRepository\putVideo().
{
         // если у нас не полностью сформированный путь, то добавляем информацию о языке + путь к шаблону
         if (!$isFullURI) {
             $action = $this->request->getLangSegment() .
                 $this->request->getPath(\Energine\share\gears\Request::PATH_TEMPLATE, true) .
                 $action;
             // если в конце нет слеша - добавляем его
             if (substr($action, -1) != '/') {
                 $action .= '/';
             }
         }
         $this->setParam('datasetAction', $action);
         $this->setProperty('action', $action);
     }
Energine\share\components\DataSet::setData (Data $data) final protected
Set Data object.
Parameters
Data $data
Attention
This is final.
Definition at line 158 of file DataSet.php.
Referenced by Energine\forms\components\FormEditor\add(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\comments\components\CommentsForm\buildResult(), Energine\forms\components\FormEditor\edit(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\share\components\DataSet\embedPlayer(), Energine\user\components\UserProfile\error(), Energine\forms\components\FormEditor\getRawData(), Energine\share\components\Grid\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\forms\components\FormEditor\main(), Energine\share\components\BreadCrumbs\prepare(), Energine\apps\components\Vote\prepare(), Energine\share\components\DataSet\prepare(), Energine\share\components\FileRepository\putVideo(), Energine\share\components\BreadCrumbs\replaceData(), Energine\forms\components\FormResults\returnEmptyRecordset(), Energine\forms\components\Form\returnEmptyRecordset(), Energine\apps\components\FeedbackForm\saveData(), Energine\forms\components\Form\saveData(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), Energine\user\components\UserProfile\success(), Energine\user\components\Register\success(), Energine\apps\components\FeedbackForm\success(), Energine\forms\components\Form\success(), Energine\apps\components\NewsFeed\tag(), and Energine\apps\components\NewsFeed\view().
{
         $this->data = $data;
     }
Energine\share\components\DataSet::setDataDescription (DataDescription $dataDescription) final protected
Set data description.
Attention
This is final.
Definition at line 213 of file DataSet.php.
Referenced by Energine\forms\components\FormEditor\add(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\comments\components\CommentsForm\buildResult(), Energine\forms\components\FormEditor\edit(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\share\components\DataSet\embedPlayer(), Energine\user\components\UserProfile\error(), Energine\share\components\Grid\exportCSV(), Energine\forms\components\FormEditor\getRawData(), Energine\share\components\Grid\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\forms\components\FormEditor\main(), Energine\seo\components\GoogleSitemap\map(), Energine\share\components\BreadCrumbs\prepare(), Energine\apps\components\Vote\prepare(), Energine\share\components\DataSet\prepare(), Energine\share\components\FileRepository\putVideo(), Energine\forms\components\FormResults\returnEmptyRecordset(), Energine\forms\components\Form\returnEmptyRecordset(), Energine\apps\components\FeedbackForm\saveData(), Energine\forms\components\Form\saveData(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), Energine\user\components\UserProfile\success(), Energine\user\components\Register\success(), Energine\apps\components\FeedbackForm\success(), Energine\forms\components\Form\success(), and Energine\apps\components\NewsFeed\view().
{
         $this->dataDescription = $dataDescription;
     }
Energine\share\components\DataSet::setTitle ($title) final protected
Set component title.
Parameters
string $title Title.
Attention
This is final.
Definition at line 572 of file DataSet.php.
Referenced by Energine\apps\components\FeedbackForm\__construct(), Energine\share\components\ImageManager\__construct(), Energine\share\components\LanguageEditor\__construct(), Energine\user\components\UserEditor\__construct(), Energine\user\components\LoginForm\__construct(), Energine\user\components\Register\__construct(), Energine\user\components\RoleEditor\__construct(), Energine\share\components\DivisionEditor\__construct(), Energine\share\components\Grid\__construct(), Energine\share\components\DataSet\__construct(), Energine\forms\components\Form\buildForm(), Energine\comments\components\CommentsEditor\changeTableName(), Energine\user\components\UserProfile\main(), and Energine\forms\components\Form\success().
{
         $this->setProperty('title', $title);
     }
Energine\share\components\DataSet::setType ($type) final protected
Set component type.
Parameters
string $type Component type.
Attention
This is final.
Definition at line 546 of file DataSet.php.
Referenced by Energine\apps\components\FeedbackForm\__construct(), Energine\share\components\LangSwitcher\__construct(), Energine\share\components\SiteList\__construct(), Energine\user\components\UserProfile\__construct(), Energine\user\components\Register\__construct(), Energine\share\components\BreadCrumbs\__construct(), Energine\forms\components\FormEditor\__construct(), Energine\forms\components\Form\__construct(), Energine\share\components\PageList\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\share\components\DBDataSet\__construct(), Energine\comments\components\CommentsList\__construct(), Energine\share\components\DataSet\__construct(), Energine\share\components\Grid\add(), Energine\forms\components\FormEditor\add(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\share\components\Grid\edit(), Energine\forms\components\FormEditor\edit(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\comments\components\CommentsList\loadData(), Energine\share\components\Grid\move(), Energine\share\components\FileRepository\putVideo(), Energine\forms\components\FormResults\returnEmptyRecordset(), Energine\share\components\WidgetsRepository\showNewTemplateForm(), Energine\apps\components\NewsFeed\view(), and Energine\share\components\DBDataSet\view().
{
         $this->type = $type;
         if (in_array($type, array(self::COMPONENT_TYPE_FORM_ADD, self::COMPONENT_TYPE_FORM_ALTER))) {
             $type = self::COMPONENT_TYPE_FORM;
         }
         $this->setProperty('type', $type);
     }
Energine\share\components\DataSet::source () protected
Run source.
Definition at line 681 of file DataSet.php.
Referenced by Energine\share\components\DataSet\build().
{
         $this->source = $this->document->componentManager->createComponent('textblocksource', 'share', 'TextBlockSource', null);
         $this->source->run();
     }
Member Data Documentation
Data DataSet::$data = false private
Data.
Definition at line 88 of file DataSet.php.
Referenced by Energine\comments\components\CommentsList\addUsersInfo(), Energine\user\components\RoleEditor\buildDivRightsData(), Energine\share\components\DivisionEditor\buildRightsTab(), Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\share\components\FileRepository\cleanFileData(), Energine\share\components\DataSet\cleanup(), Energine\share\components\DataSet\cleanupHTML(), Energine\share\components\DBDataSet\commonLoadData(), Energine\comments\components\CommentsList\createBuilder(), Energine\share\components\SitePropertiesEditor\createData(), Energine\share\components\TextBlock\createData(), Energine\user\components\UserEditor\createData(), Energine\share\components\DataSet\createData(), Energine\user\components\UserEditor\createDataDescription(), Energine\share\components\FileRepository\createThumbFields(), Energine\share\components\DataSet\downloadFile(), Energine\share\components\DataSet\embedPlayer(), Energine\share\components\Grid\exportCSV(), Energine\forms\components\Form\failure(), Energine\user\components\Register\failure(), Energine\apps\components\FeedbackForm\failure(), Energine\share\components\DataSet\getData(), Energine\share\components\Grid\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\FileRepository\getRawData(), Energine\comments\components\CommentsList\getUsersByComments(), Energine\apps\components\Vote\getVoteResults(), Energine\share\components\LangSwitcher\loadData(), Energine\share\components\SitePropertiesEditor\loadData(), Energine\share\components\NavigationMenu\loadData(), Energine\share\components\DBDataSet\loadData(), Energine\share\components\PageList\loadData(), Energine\share\components\AttachmentEditor\loadData(), Energine\share\components\Grid\loadData(), Energine\share\components\DBDataSet\modify(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\BreadCrumbs\prepare(), Energine\apps\components\Vote\prepare(), Energine\share\components\DataSet\prepare(), Energine\share\components\BreadCrumbs\replaceData(), Energine\user\components\UserProfile\save(), Energine\share\components\FileRepository\save(), Energine\apps\components\FeedbackForm\saveData(), Energine\forms\components\Form\saveData(), Energine\share\components\FileRepository\saveDir(), Energine\apps\components\FeedbackForm\send(), Energine\forms\components\Form\send(), Energine\share\components\DataSet\setData(), Energine\user\components\Register\success(), Energine\apps\components\FeedbackForm\success(), and Energine\forms\components\Form\success().
DataDescription DataSet::$dataDescription = false private
Data description.
Definition at line 82 of file DataSet.php.
Referenced by Energine\comments\components\CommentsForm\buildResult(), Energine\share\components\LanguageEditor\createDataDescription(), Energine\comments\components\CommentsList\createDataDescription(), Energine\share\components\DataSet\getDataDescription(), Energine\apps\components\Vote\prepare(), Energine\share\components\DataSet\setDataDescription(), Energine\user\components\Register\success(), Energine\apps\components\FeedbackForm\success(), and Energine\forms\components\Form\success().
FileRepository DataSet::$fileLibrary protected
File library.
Definition at line 35 of file DataSet.php.
ImageManager DataSet::$imageManager protected
Image manager.
Definition at line 41 of file DataSet.php.
DOMNode DataSet::$js protected
JavaScript.
Definition at line 100 of file DataSet.php.
Pager DataSet::$pager protected
List of pages (pager).
Definition at line 112 of file DataSet.php.
Referenced by Energine\share\components\DataSet\build().
TextBlockSource DataSet::$source private
Source.
Definition at line 46 of file DataSet.php.
array DataSet::$toolbar = array() private
Array of toolbars.
Definition at line 94 of file DataSet.php.
Referenced by Energine\share\components\DataSet\addToolbar(), Energine\share\components\LinkingEditor\build(), Energine\share\components\DataSet\build(), Energine\share\components\DivisionEditor\build(), Energine\calendar\components\Calendar\createToolbar(), Energine\share\components\DataSet\createToolbar(), and Energine\share\components\DataSet\getToolbar().
string DataSet::$type private
Component type.
Definition at line 106 of file DataSet.php.
Referenced by Energine\share\components\DivisionEditor\add(), Energine\share\components\DivisionEditor\edit(), Energine\share\components\DataSet\getType(), Energine\share\components\DivisionEditor\loadTemplateData(), Energine\forms\components\Form\send(), and Energine\share\components\DataSet\setType().
string DataSet::COMPONENT_TYPE_FORM = 'form'
Component type: form.
Definition at line 58 of file DataSet.php.
string DataSet::COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
Definition at line 64 of file DataSet.php.
string DataSet::COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
Definition at line 70 of file DataSet.php.
string DataSet::COMPONENT_TYPE_LIST = 'list'
Component type: list.
Definition at line 52 of file DataSet.php.
int DataSet::RECORD_PER_PAGE = 50
Default amount of records per page.
Definition at line 117 of file DataSet.php.
Referenced by Energine\share\components\Grid\__construct().
string DataSet::TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
Definition at line 76 of file DataSet.php.
The documentation for this class was generated from the following file:
core/modules/share/components/DataSet.php