Energine: Energine\share\gears\Component Class Reference
Energine\share\gears\Component Class Reference
Page component.
Public Member Functions
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Protected Attributes
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Member Functions
determineState ()
Determine current state.
Private Attributes
$rights
Rights level required for running component's method.
$name
Component name.
$enabled = true
Indicator, that indicates whether the component is active.
$stateParams = false
State parameters.
$properties = array()
Component properties.
$errors = array()
List of errors, that occurs by component work.
$state = self::DEFAULT_STATE_NAME
Name of the current component state.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Page component.
class Component;
Definition at line 25 of file Component.php.
Constructor & Destructor Documentation
Energine\share\gears\Component::__construct ($name, $module, array $params = null)
Parameters
string $name Component name.
string $module Module name.
array $params Component parameters.
Todo:
, build
Definition at line 130 of file Component.php.
{
         parent::__construct();
         $this->name = $name;
         $this->module = $module;
         $this->document = E()->getDocument();
         $this->params = $this->defineParams();
         if (is_array($params)) {
             foreach ($params as $name => $value) {
                 $this->setParam($name, $value);
             }
         }
         $this->rights = $this->getParam('rights');
         $this->response = E()->getResponse();
         $this->request = E()->getRequest();
         /**
          * @todo ,     build
          */
         $this->doc = new \DOMDocument('1.0', 'UTF-8');
         $this->document->componentManager->register($this);
         $this->setProperty('template',
             $template = $this->request->getPath(Request::PATH_TEMPLATE, true));
         $this->setProperty(
             'single_template',
             ($this->document->getProperty('single') ? $template :
                 $template . 'single/' . $this->getName() . '/')
         );
         //$this->config = new ComponentConfig($this->getParam('config'), get_class($this), $this->module);
         $this->determineState();
         // sample
         $ifs = class_implements($this);
         if (!empty($ifs)) {
             foreach ($ifs as $iname){
                 $iname = simplifyClassName($iname);
                 if(strtolower(substr($iname, 0, 6)) == 'sample'){
                     $this->setProperty('sample', substr($iname, 6));
                     break;
                 }
             }
         }
     }
Member Function Documentation
Energine\share\gears\Component::build ()
Build block.
Returns
Implements Energine\share\gears\IBlock.
Definition at line 474 of file Component.php.
Referenced by Energine\share\components\LinkingEditor\build(), and Energine\share\components\DivisionEditor\build().
{
         $result = $this->doc->createElement('component');
         $result->setAttribute('name', $this->getName());
         $result->setAttribute('module', $this->module);
         $result->setAttribute('componentAction', $this->getState());
         $result->setAttribute('class', simplifyClassName(get_class($this)));
         foreach ($this->properties as $propName => $propValue) {
             $result->setAttribute($propName, $propValue);
         }
         /*
         *        ?
         *    ,        .
         */
         if ($this->getBuilder() && $this->getBuilder()->build()) {
             $builderResult = $this->getBuilder()->getResult();
             if ($builderResult instanceof \DOMNode) {
                 $result->appendChild(
                     $this->doc->importNode(
                         $builderResult,
                         true
                     )
                 );
             } else {
                 $el = $this->doc->createElement('result', $builderResult);
                 $el->setAttribute('xml:id', 'result');
                 $result->appendChild($el);
             }
         }
         $this->doc->appendChild($result);
         $result = $this->doc;
         return $result;
     }
Energine\share\gears\Component::defineParams () protected
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
Returns
array
Definition at line 226 of file Component.php.
Referenced by Energine\share\gears\Component\__construct().
{
         return array(
             'state' => $this->state,
             'rights' => $this->document->getRights(),
             'config' => false,
             'active' => false,
         );
     }
Energine\share\gears\Component::determineState () final private
Determine current state.
Todo:
- state - ,
Attention
This is final.
Definition at line 295 of file Component.php.
Referenced by Energine\share\gears\Component\__construct().
{
         //
         //    self::DEFAULT_STATE_NAME
         $this->state = $this->getParam('state');
         //     ,
         if ($this->isActive()) {
             if ($this->getConfig()->isEmpty()) {
                 throw new SystemException('ERR_DEV_NO_COMPONENT_CONFIG', SystemException::ERR_DEVELOPER, $this->getName());
             }
             //     URI
             $action =
                 $this->getConfig()->getActionByURI($this->request->getPath(Request::PATH_ACTION, true));
             if ($action !== false) {
                 $this->state = $action['name'];
                 $this->stateParams = $action['params'];
             }
         } //      POST- -
         elseif (isset($_POST[$this->getName()]['state'])) {
             $this->state = $_POST[$this->getName()]['state'];
         }
         //      ,
         if (!$this->getConfig()->isEmpty()) {
             $this->getConfig()->setCurrentState($this->getState());
             $sc = $this->getConfig()->getCurrentStateConfig();
             if (isset($sc['rights'])) {
                 $this->rights = (int)$sc['rights'];
             }
             if ($csp = $this->getConfig()->getCurrentStateParams()) {
                 if ($this->stateParams) {
                     $this->stateParams = array_merge($this->stateParams, $csp);
                 } else {
                     $this->stateParams = $csp;
                 }
             }
         }
     }
Energine\share\gears\Component::disable () final
Disable component.
Attention
This is final.
Definition at line 412 of file Component.php.
Referenced by Energine\share\components\LinkingEditor\__construct(), Energine\apps\components\Ads\__construct(), Energine\apps\components\SimilarNews\__construct(), Energine\apps\components\Vote\main(), and Energine\comments\components\CommentsForm\prepare().
{
         $this->enabled = false;
     }
Energine\share\gears\Component::enable () final
Enable component.
Attention
This is final.
Definition at line 421 of file Component.php.
Referenced by Energine\apps\components\NewsRepository\__construct().
{
         $this->enabled = true;
     }
Energine\share\gears\Component::enabled () final
Is enabled?
Returns
bool
Attention
This is final.
Implements Energine\share\gears\IBlock.
Definition at line 430 of file Component.php.
Referenced by Energine\share\gears\Component\disable(), and Energine\share\gears\Component\enable().
{
         return $this->enabled;
     }
Energine\share\gears\Component::getBuilder () final protected
Get component builder.
Returns
AbstractBuilder
Attention
This is final.
Definition at line 217 of file Component.php.
Referenced by Energine\share\components\DataSet\build(), Energine\share\gears\Component\build(), Energine\forms\components\FormEditor\getRawData(), Energine\share\components\Grid\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\FileRepository\getRawData(), Energine\share\components\PageList\loadData(), and Energine\share\components\DivisionEditor\save().
{
         return $this->builder;
     }
Energine\share\gears\Component::getConfig () protected
Get component configurations.
Returns
ComponentConfig
Note
This method was created for redefining configurations in the children.
Attention
This is final.
Definition at line 192 of file Component.php.
Referenced by Energine\share\gears\Component\determineState().
{
         if (!$this->config) {
             $this->config = new ComponentConfig($this->getParam('config'), get_class($this), $this->module);
         }
         return $this->config;
     }
Energine\share\gears\Component::getCurrentStateRights () final
Get current rights level of the user.
This is needed for running current action.
Returns
mixed
Attention
This is final.
Implements Energine\share\gears\IBlock.
Definition at line 355 of file Component.php.
{
         return (int)$this->rights;
     }
Energine\share\gears\Component::getName () final
Get name.
Returns
string
Attention
This is final.
Implements Energine\share\gears\IBlock.
Definition at line 364 of file Component.php.
Referenced by Energine\share\components\LinkingEditor\__construct(), Energine\user\components\Register\__construct(), Energine\apps\components\Feed\__construct(), Energine\share\components\Grid\__construct(), Energine\share\gears\Component\__construct(), Energine\share\components\DataSet\build(), Energine\share\gears\Component\build(), Energine\share\components\LinkingEditor\changeOrder(), Energine\share\components\TextBlock\createData(), Energine\share\components\TextBlock\createDataDescription(), Energine\share\components\DataSet\createToolbar(), Energine\share\gears\Component\determineState(), Energine\share\components\DataSet\getDataDescription(), Energine\share\components\LinkingEditor\main(), and Energine\share\gears\Component\run().
{
         return $this->name;
     }
Energine\share\gears\Component::getParam ($name) final protected
Get component parameter.
If such parameter is not exist null will be returned.
Parameters
string $name Parameter name.
Returns
mixed
Attention
This is final.
Definition at line 282 of file Component.php.
Referenced by Energine\apps\components\NewsCalendar\__construct(), Energine\share\components\DomainEditor\__construct(), Energine\apps\components\VoteQuestionEditor\__construct(), Energine\user\components\LoginForm\__construct(), Energine\forms\components\SelectorValuesEditor\__construct(), Energine\forms\components\FormResults\__construct(), Energine\apps\components\NewsFeed\__construct(), Energine\apps\components\Feed\__construct(), Energine\share\components\AttachmentEditor\__construct(), Energine\forms\components\Form\__construct(), Energine\forms\components\FormEditor\__construct(), Energine\comments\components\CommentsEditor\__construct(), Energine\share\components\PageList\__construct(), Energine\apps\components\SimilarNews\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\comments\components\CommentsForm\__construct(), Energine\share\components\Grid\__construct(), Energine\comments\components\CommentsList\__construct(), Energine\share\components\DataSet\__construct(), Energine\share\gears\Component\__construct(), Energine\share\components\SiteProperties\build(), Energine\share\components\LinkingEditor\build(), Energine\forms\components\Form\buildForm(), Energine\share\components\DBDataSet\buildJS(), Energine\share\components\PageList\createBuilder(), Energine\apps\components\NewsFeed\createCalendar(), Energine\share\components\SitePropertiesEditor\createData(), Energine\share\components\AttachmentEditor\createDataDescription(), Energine\comments\components\CommentsList\createPager(), Energine\share\components\DataSet\createPager(), Energine\comments\components\CommentsForm\deleteComment(), Energine\share\gears\Component\determineState(), Energine\forms\components\FormEditor\edit(), Energine\share\components\SiteEditor\getConfig(), Energine\share\components\Grid\getConfig(), Energine\share\gears\Component\getConfig(), Energine\share\components\DataSet\getConfig(), Energine\share\components\DBDataSet\getDataLanguage(), Energine\share\components\DataSet\getDataSetAction(), Energine\apps\components\FeedbackForm\getRecipientEmail(), Energine\user\components\SocialLoginForm\getReturnUrl(), Energine\apps\components\SimilarNews\getSimilarNewsIDs(), Energine\share\components\DBDataSet\getTableName(), Energine\comments\components\CommentsForm\isTargetEditable(), Energine\share\components\SiteList\loadData(), Energine\share\components\SitePropertiesEditor\loadData(), Energine\share\components\NavigationMenu\loadData(), Energine\share\components\PageList\loadData(), Energine\share\components\AttachmentEditor\loadDataDescription(), Energine\share\components\Remover\main(), Energine\seo\components\GoogleSitemap\main(), Energine\share\components\TextBlock\main(), Energine\comments\components\CommentsList\main(), Energine\seo\components\GoogleSitemap\map(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\AttachmentEditor\prepare(), Energine\comments\components\CommentsForm\prepare(), Energine\comments\components\CommentsForm\saveComment(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\AttachmentEditor\savequickupload(), Energine\share\components\DBDataSet\saveText(), Energine\apps\components\FeedbackForm\send(), Energine\forms\components\Form\send(), and Energine\comments\components\CommentsForm\showComments().
{
         return (array_key_exists($name, $this->params) ? $this->params[$name] : null);
     }
Energine\share\gears\Component::getProperty ($propName) final protected
Get property value.
Parameters
string $propName
Returns
mixed
Attention
This is final.
Definition at line 455 of file Component.php.
Referenced by Energine\apps\components\Feed\__construct(), and Energine\share\components\DataSet\getTitle().
{
         $result = false;
         if (isset($this->properties[$propName])) {
             $result = $this->properties[$propName];
         }
         return $result;
     }
Energine\share\gears\Component::getState () final
Get current state of the component.
Returns
string
Attention
This is final.
Definition at line 346 of file Component.php.
Referenced by Energine\share\components\LinkingEditor\__construct(), Energine\apps\components\Feed\__construct(), Energine\share\components\AttachmentEditor\__construct(), Energine\share\components\LinkingEditor\build(), Energine\apps\components\VoteEditor\build(), Energine\forms\components\FormsEditor\build(), Energine\apps\components\NewsRepository\build(), Energine\share\components\WidgetsRepository\build(), Energine\share\components\SiteEditor\build(), Energine\forms\components\FormEditor\build(), Energine\share\components\DataSet\build(), Energine\share\gears\Component\build(), Energine\share\components\Grid\build(), Energine\share\components\DivisionEditor\build(), Energine\comments\components\CommentsForm\build(), Energine\user\components\RoleEditor\buildDivRightsData(), Energine\share\components\DBDataSet\buildJS(), Energine\comments\components\CommentsEditor\changeTableName(), Energine\apps\components\NewsFeed\createCalendar(), Energine\share\components\SitePropertiesEditor\createData(), Energine\share\components\SitePropertiesEditor\createDataDescription(), Energine\share\components\WidgetsRepository\createDataDescription(), Energine\forms\components\FormsEditor\createDataDescription(), Energine\apps\components\NewsRepository\createDataDescription(), Energine\forms\components\FormEditor\createDataDescription(), Energine\forms\components\FormResults\createDataDescription(), Energine\apps\components\Feed\createDataDescription(), Energine\share\components\AttachmentEditor\createDataDescription(), Energine\user\components\UserEditor\createDataDescription(), Energine\share\components\DivisionEditor\createDataDescription(), Energine\user\components\UserProfile\createDataDescription(), Energine\share\components\Grid\createDataDescription(), Energine\share\gears\Component\determineState(), Energine\share\components\Grid\getDataLanguage(), Energine\share\components\Grid\getFKData(), Energine\share\components\Grid\linkExtraManagers(), Energine\user\components\RoleEditor\loadData(), Energine\share\components\SitePropertiesEditor\loadData(), Energine\share\components\LanguageEditor\loadData(), Energine\user\components\LoginForm\loadData(), Energine\user\components\UserEditor\loadData(), Energine\share\components\WidgetsRepository\loadData(), Energine\share\components\AttachmentEditor\loadData(), Energine\share\components\DivisionEditor\loadData(), Energine\share\components\FileRepository\loadData(), Energine\share\components\Grid\loadData(), Energine\apps\components\VoteQuestionEditor\loadDataDescription(), Energine\forms\components\FormResults\loadDataDescription(), Energine\comments\components\CommentsEditor\loadDataDescription(), Energine\user\components\UserEditor\loadDataDescription(), Energine\share\components\TranslationEditor\prepare(), Energine\apps\components\VoteEditor\prepare(), Energine\share\components\DomainEditor\prepare(), Energine\share\components\SiteEditor\prepare(), Energine\share\components\AttachmentEditor\prepare(), Energine\share\components\DivisionEditor\prepare(), Energine\comments\components\CommentsForm\prepare(), and Energine\share\gears\Component\run().
{
         return $this->state;
     }
Energine\share\gears\Component::getStateParams ($returnAsAssocArray = false)
Get state parameters.
Parameters
bool $returnAsAssocArray Return as an associative?
Returns
array
Todo:
, false array
Definition at line 519 of file Component.php.
Referenced by Energine\user\components\UserEditor\activate(), Energine\share\components\DivisionEditor\add(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\Grid\applyUserSort(), Energine\comments\components\CommentsEditor\approve(), Energine\share\components\Grid\attachments(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\apps\components\NewsFeed\createCalendar(), Energine\comments\components\CommentsList\createPager(), Energine\share\components\DataSet\createPager(), Energine\share\components\Grid\delete(), Energine\comments\components\CommentsEditor\delete(), Energine\forms\components\FormEditor\delete(), Energine\share\components\SiteEditor\domains(), Energine\forms\components\FormEditor\down(), Energine\share\components\FileRepository\edit(), Energine\comments\components\CommentsEditor\edit(), Energine\share\components\Grid\edit(), Energine\forms\components\FormEditor\edit(), Energine\forms\components\FormsEditor\editForm(), Energine\forms\components\FormEditor\editSelector(), Energine\share\components\DataSet\embedPlayer(), Energine\share\components\Grid\exportCSV(), Energine\share\components\Grid\fkEditor(), Energine\share\components\Grid\fkValues(), Energine\share\components\TagEditor\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\FileRepository\getRawData(), Energine\apps\components\Vote\getVote(), Energine\share\components\SiteEditor\go(), Energine\share\components\DivisionEditor\loadData(), Energine\share\components\FileRepository\loadData(), Energine\share\components\TagEditor\main(), Energine\apps\components\NewsFeed\main(), Energine\share\components\DivisionEditor\main(), Energine\share\components\Grid\move(), Energine\share\components\Grid\moveTo(), Energine\share\components\DivisionEditor\prepare(), Energine\share\components\SiteEditor\properties(), Energine\apps\components\ExtendedFeedEditor\publish(), Energine\share\components\FileRepository\putVideo(), Energine\apps\components\VoteEditor\questionEditor(), Energine\share\components\DivisionEditor\resetTemplates(), Energine\share\gears\Component\run(), Energine\share\components\DivisionEditor\selector(), Energine\forms\components\FormsEditor\showResult(), Energine\apps\components\NewsFeed\tag(), Energine\forms\components\FormEditor\up(), Energine\seo\components\GoogleSitemap\videomap(), Energine\apps\components\NewsFeed\view(), Energine\share\components\DBDataSet\view(), and Energine\apps\components\Vote\vote().
{
         if (!$returnAsAssocArray && ($this->stateParams !== false)) {
             return array_values($this->stateParams);
         }
         return $this->stateParams;
     }
Energine\share\gears\Component::isActive () final protected
Get the 'active' parameter of the component.
Returns
bool
Attention
This is final.
Definition at line 179 of file Component.php.
Referenced by Energine\comments\components\CommentsList\createPager(), Energine\share\components\DataSet\createPager(), and Energine\share\gears\Component\determineState().
{
         return $this->params['active'];
     }
Energine\share\gears\Component::main () protected
Default action.
Returns
boolean
Definition at line 396 of file Component.php.
Referenced by Energine\apps\components\NewsRepository\main().
{
         $this->prepare(); //
         return true;
     }
Energine\share\gears\Component::prepare () protected
Prepare data.
Note
It calls at the beginning of the method, that realize main action.
Definition at line 405 of file Component.php.
Referenced by Energine\share\gears\Component\main().
 {}
Energine\share\gears\Component::removeProperty ($propName) final protected
Remove property.
Parameters
string $propName Property name.
Attention
This is final.
Definition at line 470 of file Component.php.
Referenced by Energine\forms\components\FormResults\returnEmptyRecordset().
{
         unset($this->properties[$propName]);
     }
Energine\share\gears\Component::run ()
Run current state method.
Exceptions
SystemException
Implements Energine\share\gears\IBlock.
Definition at line 373 of file Component.php.
{
         if (!$params = $this->getStateParams()) {
             $params = array();
         }
         if (method_exists($this, $this->getState() . 'State')) {
             call_user_func_array(array($this, $this->getState().'State'), $params);
         } elseif (method_exists($this, $this->getState() )) {
             call_user_func_array(array($this, $this->getState()), $params);
         } else {
             throw new SystemException(
                 'ERR_DEV_NO_ACTION',
                 SystemException::ERR_DEVELOPER,
                 array($this->getState(), $this->getName())
             );
         }
     }
Energine\share\gears\Component::setBuilder (IBuilder $builder) final protected
Set component builder.
Parameters
IBuilder $builder Builder.
Attention
This is final.
Definition at line 206 of file Component.php.
Referenced by Energine\user\components\UserEditor\activate(), Energine\forms\components\FormEditor\add(), Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\comments\components\CommentsEditor\approve(), Energine\apps\components\ExtendedFeedEditor\autoCompleteTags(), Energine\share\components\Grid\autoCompleteTags(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\user\components\Register\checkLogin(), Energine\share\components\Grid\delete(), Energine\forms\components\FormEditor\delete(), Energine\comments\components\CommentsForm\deleteComment(), Energine\forms\components\FormEditor\down(), Energine\forms\components\FormEditor\edit(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\share\components\DataSet\embedPlayer(), Energine\user\components\UserProfile\error(), Energine\share\components\Grid\fkValues(), Energine\share\components\DivisionEditor\getProperties(), Energine\forms\components\FormEditor\getRawData(), Energine\share\components\Grid\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\FileRepository\getRawData(), Energine\share\components\TagEditor\getTagIds(), Energine\share\components\TagEditor\getTags(), Energine\share\components\DivisionEditor\getTemplateInfo(), Energine\share\components\PageList\loadData(), Energine\seo\components\Robots\main(), Energine\apps\components\Vote\main(), Energine\seo\components\GoogleSitemap\main(), Energine\forms\components\FormEditor\main(), Energine\share\components\Grid\moveTo(), Energine\share\components\BreadCrumbs\prepare(), Energine\apps\components\Vote\prepare(), Energine\share\components\DataSet\prepare(), Energine\apps\components\ExtendedFeedEditor\publish(), Energine\share\components\FileRepository\putVideo(), Energine\share\components\DivisionEditor\resetTemplates(), Energine\forms\components\FormResults\returnEmptyRecordset(), Energine\forms\components\Form\returnEmptyRecordset(), Energine\share\components\WidgetsRepository\revertTemplate(), Energine\forms\components\FormEditor\save(), Energine\share\components\FileRepository\save(), Energine\share\components\DivisionEditor\save(), Energine\share\components\Grid\save(), Energine\comments\components\CommentsForm\saveComment(), Energine\share\components\WidgetsRepository\saveContent(), Energine\share\components\FileRepository\saveDir(), Energine\share\components\WidgetsRepository\saveNewTemplate(), Energine\share\components\AttachmentEditor\savequickupload(), Energine\share\components\WidgetsRepository\saveTemplate(), Energine\user\components\UserProfile\success(), Energine\user\components\Register\success(), Energine\apps\components\FeedbackForm\success(), Energine\forms\components\Form\success(), Energine\forms\components\FormEditor\up(), Energine\share\components\FileRepository\uploadTemporaryFile(), Energine\share\components\FileRepository\uploadZip(), and Energine\apps\components\NewsFeed\view().
{
         $this->builder = $builder;
     }
Energine\share\gears\Component::setParam ($name, $value) protected
Set component parameter if such exist.
If this parameter is not exist SystemException will be generated.
Parameters
string $name Parameter name.
mixed $value parameter value.
Exceptions
SystemException 'ERR_DEV_NO_PARAM'
Definition at line 245 of file Component.php.
Referenced by Energine\share\components\PageList\__construct(), Energine\share\components\DataSet\__construct(), Energine\share\gears\Component\__construct(), and Energine\share\components\DataSet\setAction().
{
         if (!array_key_exists($name, $this->params)) {
             throw new SystemException('ERR_DEV_NO_PARAM', SystemException::ERR_DEVELOPER, $name);
         }
         if ($name == 'active') {
             $value = (bool)$value;
         }
         /*if (in_array($name, array('state','configFilename', 'active'))) {
             throw new SystemException('ERR_DEV_INVARIANT_PARAM', SystemException::ERR_DEVELOPER, $name);
         }*/
         //     -   -
         if (!empty($value) || $value === false) {
             if (is_scalar($value)) {
                 //   -
                 $value = explode('|', $value);
                 $this->params[$name] =
                     (sizeof($value) == 1) ? current($value) : $value;
             } elseif (is_array($value)) {
                 //$this->params[$name] = array_values($value);
                 $this->params[$name] = $value;
             } else {
                 $this->params[$name] = $value;
             }
         }
     }
Energine\share\gears\Component::setProperty ($propName, $propValue) final protected
Set/update property value.
Parameters
string $propName Property name.
mixed $propValue Property value.
Attention
This is final.
Definition at line 442 of file Component.php.
Referenced by Energine\share\components\LinkingEditor\__construct(), Energine\share\components\TextBlockSource\__construct(), Energine\share\components\CrossDomainAuth\__construct(), Energine\calendar\components\Calendar\__construct(), Energine\apps\components\NewsRepository\__construct(), Energine\apps\components\Feed\__construct(), Energine\share\components\AttachmentEditor\__construct(), Energine\share\components\BreadCrumbs\__construct(), Energine\forms\components\FormEditor\__construct(), Energine\apps\components\Vote\__construct(), Energine\share\components\TextBlock\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\comments\components\CommentsForm\__construct(), Energine\share\components\Grid\__construct(), Energine\comments\components\CommentsList\__construct(), Energine\share\components\DataSet\__construct(), Energine\share\gears\Component\__construct(), Energine\share\components\LinkingEditor\build(), Energine\share\components\DBDataSet\buildJS(), Energine\share\components\DataSet\defineParams(), Energine\apps\components\Vote\getVote(), Energine\apps\components\Vote\getVoteResults(), Energine\comments\components\CommentsList\loadData(), Energine\share\components\TagEditor\main(), Energine\apps\components\Vote\main(), Energine\share\components\TextBlock\main(), Energine\share\components\DivisionEditor\main(), Energine\share\components\Grid\move(), Energine\comments\components\CommentsForm\prepare(), Energine\share\components\DivisionEditor\selector(), Energine\share\components\DataSet\setAction(), Energine\share\components\DataSet\setTitle(), Energine\share\components\DataSet\setType(), Energine\comments\components\CommentsForm\showComments(), and Energine\apps\components\Vote\vote().
{
         $this->properties[$propName] = $propValue;
     }
Energine\share\gears\Component::setStateParam ($paramName, $paramValue)
Set state parameter.
Usually this is required by dynamic component creation and assigning him state parameter from other component.
Parameters
string $paramName Parameter name.
mixed $paramValue Parameter value.
Definition at line 534 of file Component.php.
{
         $this->stateParams[$paramName] = $paramValue;
     }
Member Data Documentation
AbstractBuilder Energine\share\gears\Component::$builder = false protected
Builder of the component result.
Definition at line 117 of file Component.php.
Referenced by Energine\user\components\RoleEditor\buildDivRightsData(), Energine\comments\components\CommentsForm\buildResult(), Energine\share\components\DivisionEditor\buildRightsTab(), Energine\user\components\Register\checkLogin(), Energine\share\components\SitemapTree\createBuilder(), Energine\share\components\PageList\createBuilder(), Energine\share\components\NavigationMenu\createBuilder(), Energine\comments\components\CommentsList\createBuilder(), Energine\seo\components\GoogleSitemap\createBuilder(), Energine\share\components\DataSet\createBuilder(), Energine\comments\components\CommentsForm\deleteComment(), Energine\share\components\Grid\fkValues(), Energine\share\gears\Component\getBuilder(), Energine\share\components\TagEditor\getTagIds(), Energine\share\components\TagEditor\getTags(), Energine\comments\components\CommentsForm\saveComment(), Energine\share\gears\Component\setBuilder(), Energine\share\components\FileRepository\uploadTemporaryFile(), and Energine\share\components\FileRepository\uploadZip().
ComponentConfig Energine\share\gears\Component::$config protected
Component configurations.
Definition at line 123 of file Component.php.
Referenced by Energine\share\components\TextBlock\buildJS(), Energine\share\components\DataSet\buildJS(), Energine\share\components\DBDataSet\buildJS(), Energine\share\components\DataSet\cleanupHTML(), Energine\share\components\Grid\createFilter(), Energine\share\components\DataSet\createToolbar(), Energine\share\components\Grid\fkEditor(), Energine\share\components\SiteEditor\getConfig(), Energine\share\components\Grid\getConfig(), Energine\share\gears\Component\getConfig(), and Energine\share\components\DataSet\getConfig().
DOMDocument Energine\share\gears\Component::$doc protected
Document DOM of the component.
Definition at line 39 of file Component.php.
Referenced by Energine\share\gears\Component\build(), and Energine\share\components\DivisionEditor\edit().
Document Energine\share\gears\Component::$document
Page document.
Definition at line 57 of file Component.php.
boolean Energine\share\gears\Component::$enabled = true private
Indicator, that indicates whether the component is active.
Definition at line 87 of file Component.php.
Referenced by Energine\share\gears\Component\enabled().
array Energine\share\gears\Component::$errors = array() private
List of errors, that occurs by component work.
Definition at line 105 of file Component.php.
string Energine\share\gears\Component::$module protected
Module name that owns the component.
Definition at line 63 of file Component.php.
Referenced by Energine\apps\components\Branding\__construct(), Energine\apps\components\FeedbackForm\__construct(), Energine\apps\components\NewsEditor\__construct(), Energine\share\components\DomainEditor\__construct(), Energine\share\components\ImageManager\__construct(), Energine\share\components\LangSwitcher\__construct(), Energine\share\components\LanguageEditor\__construct(), Energine\share\components\LinkingEditor\__construct(), Energine\share\components\SiteList\__construct(), Energine\share\components\SitePropertiesEditor\__construct(), Energine\share\components\TagEditor\__construct(), Energine\apps\components\NewsCalendar\__construct(), Energine\seo\components\Robots\__construct(), Energine\share\components\SitemapTree\__construct(), Energine\share\components\TextBlockSource\__construct(), Energine\share\components\TranslationEditor\__construct(), Energine\user\components\RestorePassword\__construct(), Energine\apps\components\FeedbackList\__construct(), Energine\user\components\UserEditor\__construct(), Energine\user\components\UserProfile\__construct(), Energine\apps\components\VoteQuestionEditor\__construct(), Energine\user\components\LoginForm\__construct(), Energine\share\components\CrossDomainAuth\__construct(), Energine\apps\components\Ads\__construct(), Energine\forms\components\SelectorValuesEditor\__construct(), Energine\calendar\components\Calendar\__construct(), Energine\apps\components\VoteEditor\__construct(), Energine\user\components\Register\__construct(), Energine\apps\components\NewsRepository\__construct(), Energine\forms\components\FormResults\__construct(), Energine\share\components\WidgetsRepository\__construct(), Energine\apps\components\Feed\__construct(), Energine\apps\components\NewsFeed\__construct(), Energine\apps\components\ExtendedFeedEditor\__construct(), Energine\share\components\AttachmentEditor\__construct(), Energine\user\components\RoleEditor\__construct(), Energine\share\components\BreadCrumbs\__construct(), Energine\forms\components\FormsEditor\__construct(), Energine\forms\components\Form\__construct(), Energine\forms\components\FormEditor\__construct(), Energine\comments\components\CommentsEditor\__construct(), Energine\share\components\SiteEditor\__construct(), Energine\apps\components\Vote\__construct(), Energine\share\components\PageList\__construct(), Energine\apps\components\SimilarNews\__construct(), Energine\seo\components\GoogleSitemap\__construct(), Energine\share\components\FileRepository\__construct(), Energine\share\components\TextBlock\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\share\components\DivisionEditor\__construct(), Energine\share\components\DBDataSet\__construct(), Energine\comments\components\CommentsForm\__construct(), Energine\share\components\Grid\__construct(), Energine\comments\components\CommentsList\__construct(), Energine\share\components\DataSet\__construct(), Energine\share\gears\Component\__construct(), Energine\share\components\WidgetsRepository\createSymlink(), and Energine\share\components\Grid\fkEditor().
string Energine\share\gears\Component::$name private
Component name.
Definition at line 81 of file Component.php.
Referenced by Energine\apps\components\Branding\__construct(), Energine\apps\components\NewsCalendar\__construct(), Energine\apps\components\NewsEditor\__construct(), Energine\share\components\DomainEditor\__construct(), Energine\share\components\ImageManager\__construct(), Energine\share\components\LangSwitcher\__construct(), Energine\share\components\LanguageEditor\__construct(), Energine\apps\components\FeedbackForm\__construct(), Energine\share\components\LinkingEditor\__construct(), Energine\share\components\SiteList\__construct(), Energine\share\components\SitePropertiesEditor\__construct(), Energine\share\components\TagEditor\__construct(), Energine\seo\components\Robots\__construct(), Energine\apps\components\VoteQuestionEditor\__construct(), Energine\user\components\RestorePassword\__construct(), Energine\user\components\UserEditor\__construct(), Energine\user\components\UserProfile\__construct(), Energine\share\components\SitemapTree\__construct(), Energine\apps\components\FeedbackList\__construct(), Energine\share\components\TextBlockSource\__construct(), Energine\share\components\TranslationEditor\__construct(), Energine\share\components\CrossDomainAuth\__construct(), Energine\user\components\LoginForm\__construct(), Energine\apps\components\Ads\__construct(), Energine\forms\components\SelectorValuesEditor\__construct(), Energine\calendar\components\Calendar\__construct(), Energine\user\components\Register\__construct(), Energine\apps\components\VoteEditor\__construct(), Energine\forms\components\FormResults\__construct(), Energine\apps\components\NewsRepository\__construct(), Energine\share\components\WidgetsRepository\__construct(), Energine\apps\components\Feed\__construct(), Energine\apps\components\NewsFeed\__construct(), Energine\apps\components\ExtendedFeedEditor\__construct(), Energine\user\components\RoleEditor\__construct(), Energine\share\components\AttachmentEditor\__construct(), Energine\share\components\BreadCrumbs\__construct(), Energine\forms\components\FormsEditor\__construct(), Energine\forms\components\FormEditor\__construct(), Energine\forms\components\Form\__construct(), Energine\comments\components\CommentsEditor\__construct(), Energine\share\components\SiteEditor\__construct(), Energine\apps\components\Vote\__construct(), Energine\share\components\PageList\__construct(), Energine\apps\components\SimilarNews\__construct(), Energine\seo\components\GoogleSitemap\__construct(), Energine\share\components\FileRepository\__construct(), Energine\share\components\TextBlock\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\share\components\DivisionEditor\__construct(), Energine\share\components\DBDataSet\__construct(), Energine\comments\components\CommentsForm\__construct(), Energine\share\components\Grid\__construct(), Energine\comments\components\CommentsList\__construct(), Energine\share\components\DataSet\__construct(), Energine\share\gears\Component\__construct(), Energine\share\components\DivisionEditor\add(), Energine\share\components\FileRepository\createThumbFields(), Energine\share\components\DataSet\embedPlayer(), Energine\share\components\Grid\exportCSV(), Energine\share\gears\Component\getName(), Energine\share\gears\Component\getParam(), Energine\share\components\DivisionEditor\loadTemplateData(), Energine\share\components\DBDataSet\modify(), Energine\apps\components\ExtendedFeedEditor\setParam(), Energine\apps\components\NewsCalendar\setParam(), Energine\share\gears\Component\setParam(), and Energine\share\components\DBDataSet\setParam().
array Energine\share\gears\Component::$params protected
Component parameters.
Definition at line 51 of file Component.php.
Referenced by Energine\apps\components\Branding\__construct(), Energine\apps\components\FeedbackForm\__construct(), Energine\apps\components\NewsEditor\__construct(), Energine\share\components\DomainEditor\__construct(), Energine\share\components\ImageManager\__construct(), Energine\share\components\LangSwitcher\__construct(), Energine\share\components\LanguageEditor\__construct(), Energine\apps\components\NewsCalendar\__construct(), Energine\share\components\LinkingEditor\__construct(), Energine\share\components\SiteList\__construct(), Energine\share\components\SitePropertiesEditor\__construct(), Energine\share\components\TagEditor\__construct(), Energine\seo\components\Robots\__construct(), Energine\apps\components\VoteQuestionEditor\__construct(), Energine\user\components\RestorePassword\__construct(), Energine\user\components\UserEditor\__construct(), Energine\user\components\UserProfile\__construct(), Energine\share\components\TranslationEditor\__construct(), Energine\share\components\SitemapTree\__construct(), Energine\apps\components\FeedbackList\__construct(), Energine\share\components\TextBlockSource\__construct(), Energine\share\components\CrossDomainAuth\__construct(), Energine\user\components\LoginForm\__construct(), Energine\apps\components\Ads\__construct(), Energine\forms\components\SelectorValuesEditor\__construct(), Energine\calendar\components\Calendar\__construct(), Energine\user\components\Register\__construct(), Energine\apps\components\NewsRepository\__construct(), Energine\forms\components\FormResults\__construct(), Energine\apps\components\VoteEditor\__construct(), Energine\share\components\WidgetsRepository\__construct(), Energine\apps\components\NewsFeed\__construct(), Energine\apps\components\Feed\__construct(), Energine\apps\components\ExtendedFeedEditor\__construct(), Energine\user\components\RoleEditor\__construct(), Energine\share\components\AttachmentEditor\__construct(), Energine\share\components\BreadCrumbs\__construct(), Energine\forms\components\FormsEditor\__construct(), Energine\forms\components\FormEditor\__construct(), Energine\forms\components\Form\__construct(), Energine\comments\components\CommentsEditor\__construct(), Energine\share\components\SiteEditor\__construct(), Energine\share\components\PageList\__construct(), Energine\apps\components\Vote\__construct(), Energine\apps\components\SimilarNews\__construct(), Energine\seo\components\GoogleSitemap\__construct(), Energine\share\components\FileRepository\__construct(), Energine\share\components\TextBlock\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\share\components\DivisionEditor\__construct(), Energine\share\components\DBDataSet\__construct(), Energine\comments\components\CommentsForm\__construct(), Energine\share\components\Grid\__construct(), Energine\comments\components\CommentsList\__construct(), Energine\share\components\DataSet\__construct(), Energine\share\gears\Component\__construct(), Energine\share\components\Grid\defineParams(), Energine\share\components\Grid\fkEditor(), Energine\share\components\TagEditor\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\DivisionEditor\loadData(), Energine\share\components\TagEditor\main(), Energine\share\components\DivisionEditor\main(), Energine\share\components\Grid\moveTo(), Energine\apps\components\VoteEditor\questionEditor(), Energine\share\gears\Component\run(), Energine\share\components\DivisionEditor\selector(), and Energine\seo\components\GoogleSitemap\videomap().
array Energine\share\gears\Component::$properties = array() private
Component properties.
Definition at line 99 of file Component.php.
Referenced by Energine\comments\components\CommentsEditor\getForeinKeyFieldName().
Request Energine\share\gears\Component::$request protected
Instance of the Request object.
Definition at line 45 of file Component.php.
Referenced by Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\share\components\Grid\deleteData(), Energine\share\components\Grid\exportCSV(), Energine\comments\components\CommentsEditor\getForeignKeyData(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\AttachmentEditor\saveData(), and Energine\share\components\Grid\saveData().
Response Energine\share\gears\Component::$response protected
Response object exemplar.
Definition at line 69 of file Component.php.
Referenced by Energine\share\components\Grid\generateError(), Energine\share\components\TagEditor\getTagIds(), and Energine\share\components\FileRepository\uploadTemporaryFile().
int Energine\share\gears\Component::$rights private
Rights level required for running component's method.
Definition at line 75 of file Component.php.
Referenced by Energine\user\components\RoleEditor\buildDivRightsData(), and Energine\share\gears\Component\getCurrentStateRights().
string Energine\share\gears\Component::$state = self::DEFAULT_STATE_NAME private
Name of the current component state.
Definition at line 111 of file Component.php.
Referenced by Energine\share\gears\Component\getState(), Energine\share\components\Grid\linkExtraManagers(), Energine\apps\components\VoteEditor\prepare(), and Energine\share\components\SiteEditor\prepare().
array Energine\share\gears\Component::$stateParams = false private
State parameters.
Definition at line 93 of file Component.php.
Referenced by Energine\share\gears\Component\getStateParams().
string Energine\share\gears\Component::DEFAULT_STATE_NAME = 'main'
Default state name:
'main'
Definition at line 33 of file Component.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/Component.php