Energine: Energine\share\gears\Control Class Reference
Energine\share\gears\Control Class Reference
Toolbar control.
Public Member Functions
__construct ($id)
Constructor.
attach ($toolbar)
Attach control element to the toolbar.
setIndex ($index)
Set element index.
getIndex ()
Get element index.
loadFromXml (\SimpleXMLElement $description)
Load element from XML description.
disable ()
Disable element.
enable ()
Enable element.
getType ()
Get element type.
setAttribute ($attrName, $attrValue)
Set attribute.
getAttribute ($attrName)
Get attribute value.
getID ()
Get element ID.
build ()
Build control element.
translate ($attrs=array('title', 'tooltip'))
Translate language-dependent attributes.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const TAG_NAME = 'control'
Element tag name.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
getToolbar ()
Get toolbar.
Protected Attributes
$doc
Document.
$type = false
Element type.
Private Attributes
$disabled = false
Is element disabled?
$attributes = array()
Additional attributes.
$toolbar
Toolbar.
$index = false
Element index.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Toolbar control.
abstract class Control;
Attention
This is abstract.
Definition at line 27 of file Control.php.
Constructor & Destructor Documentation
Energine\share\gears\Control::__construct ($id)
Constructor.
Parameters
string $id Control ID.
Definition at line 76 of file Control.php.
{
         $this->setAttribute('id', $id);
         $this->doc = new \DOMDocument('1.0', 'UTF-8');
     }
Member Function Documentation
Energine\share\gears\Control::attach ($toolbar)
Attach control element to the toolbar.
Parameters
Toolbar $toolbar Toolbar.
Definition at line 86 of file Control.php.
Referenced by Energine\share\gears\Container\attachControl(), and Energine\share\gears\Toolbar\attachControl().
{
         $this->toolbar = $toolbar;
     }
Energine\share\gears\Control::build ()
Build control element.
Returns
DOMNode
Definition at line 223 of file Control.php.
{
         $controlElem = $this->doc->createElement(self::TAG_NAME);
         /*if (!isset($this->attributes['mode']) && ($this->type != 'separator')) {
             $this->attributes['mode'] = FieldDescription::computeRights($this->getToolbar()->getComponent()->document->getRights());
         }*/
         foreach ($this->attributes as $attrName => $attrValue) {
             $controlElem->setAttribute($attrName, $attrValue);
         }
         if ($this->disabled) {
             $controlElem->setAttribute('disabled', 'disabled');
         }
         $controlElem->setAttribute('type', $this->getType());
         $this->doc->appendChild($controlElem);
         return $this->doc->documentElement;
     }
Energine\share\gears\Control::disable ()
Disable element.
Definition at line 161 of file Control.php.
{
         $this->disabled = true;
     }
Energine\share\gears\Control::enable ()
Enable element.
Definition at line 168 of file Control.php.
{
         $this->disabled = false;
     }
Energine\share\gears\Control::getAttribute ($attrName)
Get attribute value.
Parameters
string $attrName Attribute name.
Returns
mixed
Definition at line 202 of file Control.php.
Referenced by Energine\share\gears\Link\getAction(), Energine\share\gears\Button\getAction(), Energine\share\gears\Control\getID(), Energine\share\gears\Button\getImage(), Energine\share\gears\Link\getTitle(), Energine\share\gears\Button\getTitle(), Energine\share\gears\Link\getTooltip(), Energine\share\gears\Button\getTooltip(), and Energine\share\gears\Control\translate().
{
         if (isset($this->attributes[$attrName])) {
             return $this->attributes[$attrName];
         }
         return false;
     }
Energine\share\gears\Control::getID ()
Get element ID.
Returns
string
Definition at line 214 of file Control.php.
{
         return $this->getAttribute('id');
     }
Energine\share\gears\Control::getIndex ()
Get element index.
Returns
int
Note
This is called from Toolbar.
Exceptions
SystemException 'ERR_DEV_NO_CONTROL_INDEX'
Definition at line 119 of file Control.php.
Referenced by Energine\share\gears\Toolbar\detachControl().
{
         if ($this->index === false) {
             throw new SystemException('ERR_DEV_NO_CONTROL_INDEX', SystemException::ERR_DEVELOPER);
         }
         return $this->index;
     }
Energine\share\gears\Control::getToolbar () protected
Get toolbar.
Returns
Toolbar
Definition at line 95 of file Control.php.
Referenced by Energine\share\gears\Container\attachControl(), and Energine\share\gears\Control\loadFromXml().
{
         return $this->toolbar;
     }
Energine\share\gears\Control::getType ()
Get element type.
Returns
string
Exceptions
SystemException 'ERR_DEV_NO_CONTROL_TYPE'
Definition at line 179 of file Control.php.
Referenced by Energine\share\gears\Control\build().
{
         if (!$this->type) {
             throw new SystemException('ERR_DEV_NO_CONTROL_TYPE', SystemException::ERR_DEVELOPER);
         }
         return $this->type;
     }
Energine\share\gears\Control::loadFromXml (\SimpleXMLElement $description)
Load element from XML description.
Parameters
\SimpleXMLElement $description Element description.
Exceptions
SystemException 'ERR_DEV_NO_CONTROL_TYPE'
Definition at line 133 of file Control.php.
{
         if (!isset($description['type'])) {
             throw new SystemException('ERR_DEV_NO_CONTROL_TYPE', SystemException::ERR_DEVELOPER);
         }
         $attr = $description->attributes();
         $this->setAttribute('mode',
             FieldDescription::computeRights(
                 $this->getToolbar()->getComponent()->document->getRights(),
                 !is_null($attr['ro_rights']) ? (int)$attr['ro_rights'] : null,
                 !is_null($attr['fc_rights']) ? (int)$attr['fc_rights'] : null
             )
         );
         unset($attr['ro_rights']);
         unset($attr['fc_rights']);
         foreach ($attr as $key => $value) {
             if (isset($this->$key)) {
                 $this->$key = (string)$value;
             } else {
                 $this->setAttribute($key, (string)$value);
             }
         }
     }
Energine\share\gears\Control::setAttribute ($attrName, $attrValue)
Set attribute.
Parameters
string $attrName Attribute name.
mixed $attrValue Attribute value.
Definition at line 192 of file Control.php.
Referenced by Energine\share\gears\Link\__construct(), Energine\share\gears\Button\__construct(), Energine\share\gears\Select\__construct(), Energine\share\gears\Container\__construct(), Energine\share\gears\Control\__construct(), Energine\share\gears\Switcher\build(), Energine\share\gears\Control\loadFromXml(), Energine\share\gears\Link\setTitle(), Energine\share\gears\Button\setTitle(), Energine\share\gears\Link\setTooltip(), Energine\share\gears\Button\setTooltip(), and Energine\share\gears\Control\translate().
{
         $this->attributes[$attrName] = $attrValue;
     }
Energine\share\gears\Control::setIndex ($index)
Set element index.
Parameters
int $index ID.
Note
This is called from Toolbar.
Definition at line 106 of file Control.php.
Referenced by Energine\share\gears\Container\attachControl(), and Energine\share\gears\Toolbar\attachControl().
{
         $this->index = $index;
     }
Energine\share\gears\Control::translate ($attrs = array('title', 'tooltip'))
Translate language-dependent attributes.
Parameters
array $attrs Set of attributes for translation.
Definition at line 246 of file Control.php.
{
         foreach ($attrs as $attrName) {
             $attrValue = (string)$this->getAttribute($attrName);
             if ($attrValue) {
                 $this->setAttribute($attrName, DBWorker::_translate($attrValue));
             }
         }
     }
Member Data Documentation
array Energine\share\gears\Control::$attributes = array() private
Additional attributes.
Definition at line 56 of file Control.php.
boolean Energine\share\gears\Control::$disabled = false private
Is element disabled?
Definition at line 50 of file Control.php.
DOMDocument Energine\share\gears\Control::$doc protected
Document.
Definition at line 38 of file Control.php.
int Energine\share\gears\Control::$index = false private
Element index.
It is assigned by toolbar after attaching.
Definition at line 69 of file Control.php.
Referenced by Energine\share\gears\Control\getIndex(), and Energine\share\gears\Control\setIndex().
ToolBar Energine\share\gears\Control::$toolbar private
Toolbar.
Definition at line 62 of file Control.php.
Referenced by Energine\share\gears\Control\attach(), and Energine\share\gears\Control\getToolbar().
string Energine\share\gears\Control::$type = false protected
Element type.
Definition at line 44 of file Control.php.
Referenced by Energine\share\gears\Control\getType().
string Energine\share\gears\Control::TAG_NAME = 'control'
Element tag name.
Definition at line 32 of file Control.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/Control.php