Energine: Energine\share\components\FileRepository Class Reference
Energine\share\components\FileRepository Class Reference
File repository.
Public Member Functions
__construct ($name, $module, array $params=null)
Public Member Functions inherited from Energine\share\components\Grid
__construct ($name, $module, array $params=null)
build ()
Build block.
Public Member Functions inherited from Energine\share\components\DBDataSet
__construct ($name, $module, array $params=null)
getTableName ()
Get table name.
getFilter ()
Get filter.
addFilterCondition ($filter)
Add filter condition.
getPK ()
Get filed name of primary key.
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static getTmpFilePath ($filename)
Get path of temporary file.
static generateFilename ($dirPath, $fileExtension)
Generate filename.
static cleanFileData ($data, $maxFileSize=5242880)
Clean incoming from JS FileReader.
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes
const TEMPORARY_DIR = 'uploads/temp/'
Path to temporary directory.
const TYPE_FOLDER_UP = 'folderup'
Fake type to go to the upper folder.
const STORED_PID = 'NRGNFRPID'
Cookie name.
Public Attributes inherited from Energine\share\components\Grid
const DIR_UP = '<'
Direction: up.
const DIR_DOWN = '>'
Direction: dowm.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
edit ()
Proxy method for editing.
putVideo ()
Method for adding video in text blocks.
addDir ()
Add directory.
saveDir ()
Save data in directory.
save ()
Save.
add ()
Show add form.
loadData ()
Load data.
getRawData ()
Show data in JSON format for AJAX.
uploadZip ()
Show form to upload Zip file.
uploadTemporaryFile ()
Upload temporary file.
Protected Member Functions inherited from Energine\share\components\Grid
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
getConfig ()
add ()
Show add form.
edit ()
Show edit form.
delete ()
Delete.
deleteData ($id)
Delete record.
getDataLanguage ()
Get data language.
getRawData ()
Show data in JSON format for AJAX.
fkEditor ()
Single mode state that show Grid for select field values.
fkValues ()
Single mode state for gettting latest values from FK table.
save ()
Save.
createData ()
Create data.
createDataDescription ()
Create data description.
getFKData ($fkTableName, $fkKeyName)
Get data from linked table.
generateError ($errorType, $errorMessage, $errorCustomInfo=false)
Generate error.
getSaver ()
Get saver.
setSaver (Saver $saver)
Set saver.
saveData ()
Save data.
loadData ()
Load data.
exportCSV ()
Export the list into CSV file.
printData ()
Prepare the list for printing.
prepareCSVString (Array $nextValue)
Prepare CSV string.
attachments ()
Show image manager.
tags ()
Show component: tag editor.
generateThumbnail ($sourceFileName, $destFieldName, $width, $height, $filter, $rewrite=true)
Generate thumbnails and save them in data base.
setOrderColumn ($columnName)
Set column name for user sorting.
getOrderColumn ()
Get column name for user sorting.
move ()
Show GRID for moving element.
moveTo ()
Move the record.
up ()
Change the moving direction to Grid::DIR_UP.
down ()
Change the moving direction to Grid::DIR_DOWN.
changeOrder ($direction)
Change order.
applyUserFilter ()
Apply user filter.
applyUserSort ()
Apply user sorting.
linkExtraManagers ($tableName, $data=false)
Build the list of additional files.
autoCompleteTags ()
Autocomplete tag names.
prepare ()
Prepare data.
createFilter ()
Create Grid filter.
Protected Member Functions inherited from Energine\share\components\DBDataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
loadDataDescription ()
Load data description.
loadData ()
Load data.
getDataLanguage ()
Get data language.
setTableName ($tableName)
Set table name.
setParam ($name, $value)
Set component parameter if such exist.
setFilter ($filter)
Set filter.
clearFilter ()
Reset filter.
getOrder ()
Get sort order.
setOrder (array $order)
Set sort order.
getLimit ()
Get limit.
setLimit (array $limit)
Set limit.
setPK ($primaryColumnName)
Set primary key.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
getFKData ($fkTableName, $fkKeyName)
Get data from linked table.
getTranslationTableName ()
Get table name with translations.
view ()
Show view form.
recordExists ($id, $fieldName=false)
Detect if the specific record exist.
buildJS ()
Create description of JS objects.
getPreviousState ()
Get previous state.
saveText ()
Save text.
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Protected Attributes
$repoinfo
Repository info.
Protected Attributes inherited from Energine\share\components\Grid
$attachmentEditor
Component: attachment editor manager.
$tagEditor
Tag editor.
$saver
Saver.
$filter_control
Filter.
$fkCRUDEditor = null
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Member Functions
editDir ($uplID)
Edit directory.
editFile ($uplID)
Edit file.
createThumbFields ()
Create tab for thumbs.
saveThumbs ($thumbsData, $baseFileName, $repo)
Save thumbs.
Additional Inherited Members
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
File repository.
class FileRepository;
Definition at line 25 of file FileRepository.php.
Constructor & Destructor Documentation
Energine\share\components\FileRepository::__construct ($name, $module, array $params = null)
Parameters
string $name Component name.
string $module Module name.
array $params Component parameters.
Definition at line 54 of file FileRepository.php.
{
         parent::__construct($name, $module, $params);
         $this->repoinfo = E()->FileRepoInfo;
         $this->setTableName('share_uploads');
         $this->setFilter(array('upl_is_active' => 1));
         $this->setOrder(array('upl_publication_date' => QAL::DESC));
         $this->addTranslation('TXT_NOT_READY', 'FIELD_UPL_IS_READY', 'ERR_UPL_NOT_READY');
         //
         if (isset($_POST['modalBoxData']) && ($d = json_decode($_POST['modalBoxData']))) {
             if ((isset($d->upl_pid) && ($uplPID = ($this->dbh->getScalar($this->getTableName(), 'upl_id', array('upl_id' => $d->upl_pid)))))
                 || (isset($d->upl_path) && ($uplPID = ($this->dbh->getScalar($this->getTableName(), 'upl_pid', array('upl_path' => $d->upl_path)))))
             ) {
                 $this->response->addCookie(self::STORED_PID, $uplPID, 0, E()->getSiteManager()->getCurrentSite()->host, E()->getSiteManager()->getCurrentSite()->root);
             }
         }
     }
Member Function Documentation
Energine\share\components\FileRepository::add () protected
Show add form.
Definition at line 459 of file FileRepository.php.
{
         $sp = $this->getStateParams(true);
         if (isset($sp['pid'])) {
             $uplPID = (int)$sp['pid'];
         } else {
             $uplPID = '';
         }
         $this->setType(self::COMPONENT_TYPE_FORM_ADD);
         $this->setBuilder($this->createBuilder());
         $this->setDataDescription($this->createDataDescription());
         $this->setData(new Data());
         $f = new Field('upl_pid');
         $f->setData($uplPID);
         $this->getData()->addField($f);
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
         $this->setAction('save/');
         $this->createThumbFields();
     }
Energine\share\components\FileRepository::addDir () protected
Add directory.
Definition at line 200 of file FileRepository.php.
{
         $sp = $this->getStateParams(true);
         if (isset($sp['pid'])) {
             $uplPID = (int)$sp['pid'];
         } else {
             $uplPID = '';
         }
         $this->setType(self::COMPONENT_TYPE_FORM_ADD);
         $this->setBuilder($this->createBuilder());
         $this->setDataDescription($this->createDataDescription());
         $this->setData(new Data());
         $f = new Field('upl_pid');
         $f->setData($uplPID);
         $this->getData()->addField($f);
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
         $this->setAction('save-dir/');
     }
static Energine\share\components\FileRepository::cleanFileData ($data, $maxFileSize = 5242880) static
Clean incoming from JS FileReader.
Parameters
string $data Data.
int $maxFileSize maximum file size (5mB default)
Returns
object
Exceptions
SystemException
Definition at line 770 of file FileRepository.php.
{
         ini_set('pcre.backtrack_limit', $maxFileSize);
         if (!preg_match('/data\:(.*);base64\,(.*)$/', $data, $matches)) {
             switch (preg_last_error()) {
                 case PREG_NO_ERROR:
                     $errorMessage = 'ERR_BAD_FILE';
                     break;
                 case PREG_INTERNAL_ERROR:
                     $errorMessage = 'ERR_PREG_INTERNAL';
                     break;
                 case PREG_BACKTRACK_LIMIT_ERROR:
                     $errorMessage = 'ERR_PREG_BACKTRACK_LIMIT';
                     break;
                 case PREG_RECURSION_LIMIT_ERROR:
                     $errorMessage = 'ERR_PREG_RECURSION_LIMIT';
                     break;
                 case PREG_BAD_UTF8_ERROR:
                     $errorMessage = 'ERR_PREG_BAD_UTF8_ERROR';
                     break;
             }
             throw new SystemException($errorMessage, SystemException::ERR_WARNING);
         }
         $mime = $matches[1];
         $string = $matches[2];
         unset($matches);
         //http://j-query.blogspot.com/2011/02/save-base64-encoded-canvas-image-to-png.html?showComment=1402329668513#c517521780203205620
         $string = str_replace_opt(' ', '+', $string);
         return (object)array('mime' => $mime, 'data' => base64_decode($string));
     }
Energine\share\components\FileRepository::createThumbFields () private
Create tab for thumbs.
Definition at line 181 of file FileRepository.php.
Referenced by Energine\share\components\FileRepository\add(), and Energine\share\components\FileRepository\editFile().
{
         if ($thumbs = $this->getConfigValue('thumbnails')) {
             $tabName = $this->translate('TXT_THUMBS');
             foreach ($thumbs as $name => $data) {
                 $fd = new FieldDescription($name);
                 $fd->setType(FieldDescription::FIELD_TYPE_THUMB);
                 $this->getDataDescription()->addFieldDescription($fd);
                 $fd->setProperty('tabName', $tabName);
                 $fd->setProperty('tableName', 'thumbs');
                 foreach ($data as $attrName => $attrValue) {
                     $fd->setProperty($attrName, $attrValue);
                 }
             }
         }
     }
Energine\share\components\FileRepository::edit () protected
Proxy method for editing.
Definition at line 76 of file FileRepository.php.
{
         $sp = $this->getStateParams();
         $uplID = $sp[0];
         if ($this->dbh->getScalar($this->getTableName(),
                 'upl_internal_type',
                 array('upl_id' => $uplID)) == FileRepoInfo::META_TYPE_FOLDER
         ) {
             $this->editDir($uplID);
         } else {
             $this->editFile($uplID);
         }
     }
Energine\share\components\FileRepository::editDir ($uplID) private
Edit directory.
Parameters
int $uplID Upload ID.
Definition at line 114 of file FileRepository.php.
Referenced by Energine\share\components\FileRepository\edit().
{
         $this->setFilter(array('upl_id' => $uplID));
         $this->setType(self::COMPONENT_TYPE_FORM_ALTER);
         $this->setBuilder($this->createBuilder());
         $dd = new DataDescription();
         $f = new FieldDescription('upl_id');
         $f->setProperty('tableName', $this->getTableName());
         $f->setType(FieldDescription::FIELD_TYPE_HIDDEN);
         $f->setProperty('key', true);
         $dd->addFieldDescription($f);
         $f = new FieldDescription('upl_pid');
         $f->setProperty('tableName', $this->getTableName());
         $f->setType(FieldDescription::FIELD_TYPE_HIDDEN);
         $dd->addFieldDescription($f);
         $f = new FieldDescription('upl_title');
         $f->setProperty('tableName', $this->getTableName());
         $f->setType(FieldDescription::FIELD_TYPE_STRING);
         $dd->addFieldDescription($f);
         $this->setDataDescription($dd);
         $this->setData($this->createData());
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
         $this->setAction('save-dir/');
     }
Energine\share\components\FileRepository::editFile ($uplID) private
Edit file.
Parameters
int $uplID Upload ID.
Definition at line 150 of file FileRepository.php.
Referenced by Energine\share\components\FileRepository\edit().
{
         $this->setType(self::COMPONENT_TYPE_FORM_ALTER);
         $this->setBuilder($this->createBuilder());
         $this->setDataDescription($this->createDataDescription());
         $this->addFilterCondition(array('upl_id' => $uplID));
         $repository = $this->repoinfo->getRepositoryInstanceById($uplID);
         //  mode     ,   RO
         if (!$repository->allowsUploadFile()) {
             $fd = $this->getDataDescription()->getFieldDescriptionByName('upl_path');
             if ($fd) {
                 $fd->setMode(1);
                 $fd->setProperty('title', 'FIELD_UPL_PATH_READ');
             }
         }
         $this->setData($this->createData());
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
         $this->setAction('save/');
         $this->createThumbFields();
     }
static Energine\share\components\FileRepository::generateFilename ($dirPath, $fileExtension) static
Generate filename.
Parameters
string $dirPath Directory path.
string $fileExtension File extension.
Returns
string
Definition at line 669 of file FileRepository.php.
{
         /*
          *    .
          */
         $c = ''; //        '0'
         do {
             $filename = time() . rand(1, 10000) . "$c.{$fileExtension}";
             $c++; //     $c   integer(1)
         } while (file_exists($dirPath . $filename));
         return $filename;
     }
Energine\share\components\FileRepository::getRawData () protected
Show data in JSON format for AJAX.
Definition at line 518 of file FileRepository.php.
{
         $sp = $this->getStateParams(true);
         if (!isset($sp['pid'])) {
             jump:
             $this->addFilterCondition('(upl_pid IS NULL)');
             $uplPID = '';
         } else {
             $uplPID = (int)$sp['pid'];
             if (isset($_COOKIE[self::STORED_PID])) {
                 //    ?
                 if (!($this->dbh->getScalar($this->getTableName(), 'upl_id', array('upl_id' => $uplPID)))) {
                     goto jump;
                 }
             }
             $this->addFilterCondition(array('upl_pid' => $uplPID));
         }
         parent::getRawData();
         //
         $this->setBuilder(new JSONRepoBuilder());
         if ($this->pager) $this->getBuilder()->setPager($this->pager);
         if ($uplPID) {
             $data = $this->getData();
             $uplID = $this->dbh->getScalar($this->getTableName(), 'upl_pid', array('upl_id' => $sp['pid']));
             if (is_null($uplID)) {
                 $uplID = 0;
             }
             //  IFileRepository   $uplPID
             $repo = $this->repoinfo->getRepositoryInstanceById($uplPID);
             $newData = array(
                 'upl_id' => $uplID,
                 'upl_pid' => $uplPID,
                 'upl_title' => '...',
                 'upl_internal_type' => self::TYPE_FOLDER_UP,
                 //   upl_allows_*    folderup
                 'upl_allows_create_dir' => $repo->allowsCreateDir(),
                 'upl_allows_upload_file' => $repo->allowsUploadFile(),
                 'upl_allows_edit_dir' => $repo->allowsEditDir(),
                 'upl_allows_edit_file' => $repo->allowsEditFile(),
                 'upl_allows_delete_dir' => $repo->allowsDeleteDir(),
                 'upl_allows_delete_file' => $repo->allowsDeleteFile(),
             );
             //   uplPID   ,  uplID -
             $p = array($uplPID);
             $res = $this->dbh->call('proc_get_upl_pid_list', $p);
             unset($p);
             if (!empty($res)) {
                 $breadcrumbsData = array();
                 foreach ($res as $row) {
                     $breadcrumbsData[$row['id']] = $row['title'];
                 }
                 $this->getBuilder()->setBreadcrumbs(array_reverse($breadcrumbsData, true));
             }
             if (!$data->isEmpty())
                 foreach ($this->getDataDescription()->getFieldDescriptionList() as $fieldName) {
                     if ($f = $data->getFieldByName($fieldName))
                         $f->addRowData(((isset($newData[$fieldName])) ? $newData[$fieldName] : ''), false);
                 }
             else {
                 $data->load(array($newData));
             }
         }
     }
static Energine\share\components\FileRepository::getTmpFilePath ($filename) static
Get path of temporary file.
Parameters
string $filename Filename.
Returns
string
Definition at line 658 of file FileRepository.php.
Referenced by Energine\share\components\FileRepository\uploadTemporaryFile().
{
         return self::TEMPORARY_DIR . basename($filename);
     }
Energine\share\components\FileRepository::loadData () protected
Load data.
Returns
mixed
Definition at line 488 of file FileRepository.php.
{
         $result = parent::loadData();
         if ($this->getState() == 'getRawData') {
             $sp = $this->getStateParams(true);
             $uplPID = (!empty($sp['pid'])) ? (int)$sp['pid'] : null;
             if (!$uplPID) return $result;
             //  IFileRepository   $uplPID
             $repo = $this->repoinfo->getRepositoryInstanceById($uplPID);
             $repo->prepare($result);
             if ($result) {
                 foreach ($result as $i => $row) {
                     $result[$i]['upl_allows_create_dir'] = $repo->allowsCreateDir();
                     $result[$i]['upl_allows_upload_file'] = $repo->allowsUploadFile();
                     $result[$i]['upl_allows_edit_dir'] = $repo->allowsEditDir();
                     $result[$i]['upl_allows_edit_file'] = $repo->allowsEditFile();
                     $result[$i]['upl_allows_delete_dir'] = $repo->allowsDeleteDir();
                     $result[$i]['upl_allows_delete_file'] = $repo->allowsDeleteFile();
                 }
             }
         }
         return $result;
     }
Energine\share\components\FileRepository::putVideo () protected
Method for adding video in text blocks.
Definition at line 92 of file FileRepository.php.
{
         $sp = $this->getStateParams();
         $uplID = intval($sp[0]);
         $this->setType(self::COMPONENT_TYPE_FORM_ALTER);
         $this->setBuilder($this->createBuilder());
         $this->setDataDescription($this->createDataDescription());
         $this->addFilterCondition(array('upl_id' => $uplID));
         $this->setData($this->createData());
         $toolbars = $this->createToolbar();
         if (!empty($toolbars)) {
             $this->addToolbar($toolbars);
         }
         $this->js = $this->buildJS();
         $this->setAction('save/');
     }
Energine\share\components\FileRepository::save () protected
Save.
Note
This is 'external' method that calls 'internal' Grid::saveData.
Exceptions
SystemException 'ERR_NO_DATA'
SystemException 'ERR_BAD_PID'
SystemException 'ERR_SAVE_FILE'
SystemException 'ERR_INCORRECT_MIME'
Definition at line 331 of file FileRepository.php.
{
         $transactionStarted = $this->dbh->beginTransaction();
         try {
             if (!isset($_POST[$this->getTableName()]) || !isset($_POST[$this->getTableName()][$this->getPK()]) || !isset($_POST[$this->getTableName()]['upl_title']) || !isset($_POST[$this->getTableName()]['upl_pid'])) {
                 throw new SystemException('ERR_NO_DATA');
             }
             $data = $_POST[$this->getTableName()];
             if (!$data['upl_pid']) {
                 throw new SystemException('ERR_BAD_PID');
             }
             //  instance IFileRepository
             $repository = $this->repoinfo->getRepositoryInstanceById($data['upl_pid']);
             $mode = (empty($data[$this->getPK()])) ? QAL::INSERT : QAL::UPDATE;
             //
             if ($mode == QAL::INSERT) {
                 $tmpFileName = $data['upl_path'];
                 $uplPath = $this->dbh->getScalar($this->getTableName(), array('upl_path'), array('upl_id' => $data['upl_pid']));
                 if ($uplPath && substr($uplPath, -1) == '/') $uplPath = substr($uplPath, 0, -1);
                 if (empty($uplPath)) {
                     throw new SystemException('ERR_BAD_PID');
                 }
                 unset($data[$this->getPK()]);
                 $data['upl_filename'] = self::generateFilename($uplPath, pathinfo($data['upl_filename'], PATHINFO_EXTENSION));
                 $data['upl_path'] = $uplPath . ((substr($uplPath, -1) != '/') ? '/' : '') . $data['upl_filename'];
                 if (!($fi = $repository->uploadFile($tmpFileName, $data['upl_path']))) {
                     throw new SystemException('ERR_SAVE_FILE');
                 }
                 $data['upl_mime_type'] = $fi->mime;
                 $data['upl_internal_type'] = $fi->type;
                 $data['upl_width'] = $fi->width;
                 $data['upl_height'] = $fi->height;
                 $data['upl_is_ready'] = $fi->ready;
                 $data['upl_publication_date'] = date('Y-m-d H:i:s');
                 $ext = strtolower(pathinfo($data['upl_filename'], PATHINFO_EXTENSION));
                 switch ($ext) {
                     case 'mp4':
                         $data['upl_is_mp4'] = '1';
                         break;
                     case 'webm':
                         $data['upl_is_webm'] = '1';
                         break;
                     case 'flv':
                         $data['upl_is_flv'] = '1';
                         break;
                 }
                 $result = $this->dbh->modify($mode, $this->getTableName(), $data);
             } //
             elseif ($mode == QAL::UPDATE) {
                 $pk = $data[$this->getPK()];
                 $old_upl_path = $this->dbh->getScalar($this->getTableName(), 'upl_path', array($this->getPK() => $pk));
                 $new_upl_path = $data['upl_path'];
                 unset($data['upl_path']);
                 //    tmpfile   upl_path
                 if ($new_upl_path != $old_upl_path) {
                     $old_mime = $this->dbh->getScalar($this->getTableName(), 'upl_mime_type', array($this->getPK() => $pk));
                     $new_info = $repository->analyze($new_upl_path);
                     if ($new_info && $new_info->mime != $old_mime) {
                         throw new SystemException('ERR_INCORRECT_MIME');
                     }
                     if (!$repository->updateFile($new_upl_path, $old_upl_path)) {
                         throw new SystemException('ERR_SAVE_FILE');
                     }
                     $fi = $repository->analyze($new_upl_path);
                     if ($fi) {
                         $data['upl_width'] = $fi->width;
                         $data['upl_height'] = $fi->height;
                     }
                     $data['upl_publication_date'] = date('Y-m-d H:i:s');
                 }
                 $result = $this->dbh->modify($mode, $this->getTableName(), $data, array($this->getPK() => $pk));
                 $data['upl_path'] = $old_upl_path;
             }
             if (isset($_POST['thumbs'])) {
                 $this->saveThumbs($_POST['thumbs'], $data['upl_path'], $repository);
             }
             $transactionStarted = !($this->dbh->commit());
             $uplID = (is_int($result)) ? $result : (int)$_POST[$this->getTableName()][$this->getPK()];
             if ($mode == QAL::INSERT) {
                 $args = array($uplID, $data['upl_publication_date']);
                 $this->dbh->call('proc_update_dir_date', $args);
             }
             $b = new JSONCustomBuilder();
             $b->setProperties(array(
                 'data' => $uplID,
                 'result' => true,
                 'mode' => (is_int($result)) ? 'insert' : 'update'
             ));
             $this->setBuilder($b);
         } catch (SystemException $e) {
             if ($transactionStarted) {
                 $this->dbh->rollback();
             }
             throw $e;
         }
     }
Energine\share\components\FileRepository::saveDir () protected
Save data in directory.
Exceptions
SystemException 'ERR_NO_DATA'
SystemException 'ERR_BAD_PID'
Definition at line 230 of file FileRepository.php.
{
         $transactionStarted = $this->dbh->beginTransaction();
         try {
             if (!isset($_POST[$this->getTableName()]) || !isset($_POST[$this->getTableName()][$this->getPK()]) || !isset($_POST[$this->getTableName()]['upl_title']) || !isset($_POST[$this->getTableName()]['upl_pid'])) {
                 throw new SystemException('ERR_NO_DATA');
             }
             $data = $_POST[$this->getTableName()];
             if (!$data['upl_pid']) {
                 throw new SystemException('ERR_BAD_PID');
             }
             //  instance IFileRepository
             $repository = $this->repoinfo->getRepositoryInstanceById($data['upl_pid']);
             $mode = (empty($data[$this->getPK()])) ? QAL::INSERT : QAL::UPDATE;
             if ($mode == QAL::INSERT) {
                 $parentData = $this->dbh->select($this->getTableName(), array('upl_path'), array('upl_id' => $data['upl_pid']));
                 if (empty($parentData)) {
                     throw new SystemException('ERR_BAD_PID');
                 }
                 list($parentData) = $parentData;
                 unset($data[$this->getPK()]);
                 $data['upl_name'] = $data['upl_filename'] = Translit::asURLSegment($data['upl_title']);
                 $data['upl_mime_type'] = 'unknown/mime-type';
                 $data['upl_internal_type'] = FileRepoInfo::META_TYPE_FOLDER;
                 $data['upl_childs_count'] = 0;
                 $data['upl_publication_date'] = date('Y-m-d H:i:s');
                 $data['upl_path'] = $parentData['upl_path'] . ((substr($parentData['upl_path'], -1) != '/') ? '/' : '') . $data['upl_filename'];
                 $where = false;
                 $repository->createDir($data['upl_path']);
             } else {
                 $where = array('upl_id' => $data['upl_id']);
                 /*$currentUplPath = simplifyDBResult($this->dbh->select($this->getTableName(), array('upl_path'), array('upl_id' => $data['upl_id'])), 'upl_path', true);
                 $data['upl_name'] = $data['upl_filename'] = Translit::asURLSegment($data['upl_title']);
                 if($currentUplPath != $data['upl_path']){
                     rename($currentUplPath, $data['upl_path']);
                 }*/
             }
             $result = $this->dbh->modify($mode, $this->getTableName(), $data, $where);
             $transactionStarted = !($this->dbh->commit());
             $uplID = (is_int($result)) ? $result : (int)$_POST[$this->getTableName()][$this->getPK()];
             $args = array($uplID, date('Y-m-d H:i:s'));
             $this->dbh->call('proc_update_dir_date', $args);
             $b = new JSONCustomBuilder();
             $b->setProperties(array(
                 'data' => $uplID,
                 'result' => true,
                 'mode' => (is_int($result)) ? 'insert' : 'update'
             ));
             $this->setBuilder($b);
         } catch (SystemException $e) {
             if ($transactionStarted) {
                 $this->dbh->rollback();
             }
             throw $e;
         }
     }
Energine\share\components\FileRepository::saveThumbs ($thumbsData, $baseFileName, $repo) private
Save thumbs.
Parameters
array $thumbsData Thumbs data in the form
name -> tmp_filename
.
string $baseFileName Base file name.
IFileRepository $repo Repository.
Exceptions
SystemException 'ERR_SAVE_THUMBNAIL'
Definition at line 306 of file FileRepository.php.
Referenced by Energine\share\components\FileRepository\save().
{
         $thumbProps = $this->getConfigValue('thumbnails');
         foreach ($thumbsData as $thumbName => $thumbTmpName) {
             if ($thumbTmpName) {
                 $w = (!empty($thumbProps[$thumbName]['width'])) ? (int)$thumbProps[$thumbName]['width'] : 0;
                 $h = (!empty($thumbProps[$thumbName]['height'])) ? (int)$thumbProps[$thumbName]['height'] : 0;
                 try {
                     // todo: thumbName == preview ?
                     $repo->uploadAlt($thumbTmpName, $baseFileName, $w, $h);
                 } catch (\Exception $e) {
                     throw new SystemException('ERR_SAVE_THUMBNAIL', SystemException::ERR_CRITICAL, (string)$e);
                 }
             }
         }
     }
Energine\share\components\FileRepository::uploadTemporaryFile () protected
Upload temporary file.
Definition at line 685 of file FileRepository.php.
{
         $builder = new JSONCustomBuilder();
         $this->setBuilder($builder);
         if (!empty($_SERVER['HTTP_ORIGIN'])) {
             header('Access-Control-Allow-Origin: ' . $_SERVER['HTTP_ORIGIN']);
             header('Access-Control-Allow-Methods: POST, GET, OPTIONS');
             header('Access-Control-Allow-Headers: Origin, X-Requested-With');
         }
         if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
             exit();
         }
         $response = array(
             'name' => '',
             'type' => '',
             'tmp_name' => '',
             'error' => false,
             'error_message' => '',
             'size' => 0,
             'preview' => ''
         );
         try {
             if (strtoupper($_SERVER['REQUEST_METHOD']) == 'POST') {
                 header('HTTP/1.1 201 Created');
                 $key = (isset($_POST['key'])) ? $_POST['key'] : 'unknown';
                 // $pid = (isset($_POST['pid'])) ? (int) $_POST['pid']: false;
                 // $repo = $this->getRepositoryInstance($pid);
                 if (isset($_FILES[$key]) and is_uploaded_file($_FILES[$key]['tmp_name'])) {
                     $tmp_name = $this->getTmpFilePath($_FILES[$key]['name']);
                     if (!is_writeable(dirname($tmp_name))) {
                         throw new SystemException('ERR_TEMP_DIR_WRITE', SystemException::ERR_CRITICAL, dirname($tmp_name));
                     }
                     if (move_uploaded_file($_FILES[$key]['tmp_name'], $tmp_name)) {
                         $response['name'] = $_FILES[$key]['name'];
                         $response['type'] = $_FILES[$key]['type'];
                         $response['tmp_name'] = $tmp_name;
                         $response['error'] = $_FILES[$key]['error'];
                         $response['size'] = $_FILES[$key]['size'];
                     } else {
                         $response['error'] = true;
                         $response['error_message'] = 'ERR_NO_FILE';
                     }
                 } else {
                     $response['error'] = true;
                     $response['error_message'] = 'ERR_NO_FILE';
                 }
             } else {
                 $response['error'] = true;
                 $response['error_message'] = 'ERR_INVALID_REQUEST_METHOD';
             }
         } catch (\Exception $e) {
             $response['error'] = true;
             $response['result'] = false;
             $response['error_message'] = (string)$e->getMessage();
         }
         // IE9 no-flash / iframe upload (fallback)
         $jsonp = isset($_REQUEST['callback']) ? trim($_REQUEST['callback']) : null;
         if (!empty($jsonp)) {
             echo '<script type="text/javascript">'
                 . '(function(ctx,jsonp){'
                 . 'if(ctx&&ctx[jsonp]){'
                 . 'ctx[jsonp](200, "OK", "' . addslashes(json_encode($response)) . '")'
                 . '}'
                 . '})(this.parent, "' . $jsonp . '")'
                 . '</script>';
             exit();
         }
         $builder->setProperties($response);
     }
Energine\share\components\FileRepository::uploadZip () protected
Show form to upload Zip file.
Todo:
Definition at line 592 of file FileRepository.php.
{
         $builder = new JSONCustomBuilder();
         $this->setBuilder($builder);
         $transactionStarted = false;
         try {
             if (!isset($_POST['data']) || !isset($_POST['PID'])) {
                 throw new SystemException('ERR_BAD_DATA', SystemException::ERR_CRITICAL);
             }
             $fileName = tempnam(self::TEMPORARY_DIR, "zip");
             $tmpFileName = $_POST['data'];
             if (!copy($tmpFileName, $fileName)) {
                 throw new SystemException('ERR_CANT_CREATE_FILE', SystemException::ERR_CRITICAL);
             }
             $uplPID = $_POST['PID'];
             $transactionStarted = $this->dbh->beginTransaction();
             $extractPath = $this->dbh->getScalar($this->getTableName(), 'upl_path', array('upl_id' => $uplPID));
             $zip = new \ZipArchive();
             $zip->open($fileName);
             for ($i = 0; $i < $zip->numFiles; $i++) {
                 $currentFile = $zip->statIndex($i);
                 $currentFile = $currentFile['name'];
                 $fileInfo = pathinfo($currentFile);
                 inspect($fileInfo);
                 if (
                 !((substr($fileInfo['filename'], 0, 1) === '.') || (strpos($currentFile, 'MACOSX') !== false)
                 )
                 ) {
                     if ($fileInfo['dirname'] == '.') {
                         $path = '';
                     } else {
                         $path = Translit::transliterate(addslashes($fileInfo['dirname'])) . '/';
                     }
                     //Directory
                     if (!isset($fileInfo['extension'])) {
                         $zip->renameIndex(
                             $i,
                             $currentFile = $path .
                                 Translit::transliterate($fileInfo['filename'])
                         );
                     } else {
                         $zip->renameIndex(
                             $i,
                             $currentFile = $path . self::generateFilename('', $fileInfo['extension'])
                         );
                     }
                 }
             }
             $zip->close();
             throw new SystemException('ERR_FAKE');
             $this->dbh->commit();
         } catch (SystemException $e) {
             if ($transactionStarted) {
                 $this->dbh->rollback();
             }
         }
     }
Member Data Documentation
FileRepoInfo Energine\share\components\FileRepository::$repoinfo protected
Repository info.
Definition at line 49 of file FileRepository.php.
string Energine\share\components\FileRepository::STORED_PID = 'NRGNFRPID'
Cookie name.
It holds the last viewed folder ID.
Definition at line 43 of file FileRepository.php.
string Energine\share\components\FileRepository::TEMPORARY_DIR = 'uploads/temp/'
Path to temporary directory.
Definition at line 30 of file FileRepository.php.
Referenced by Energine\share\gears\FileRepositoryFTP\putFile().
string Energine\share\components\FileRepository::TYPE_FOLDER_UP = 'folderup'
Fake type to go to the upper folder.
Definition at line 35 of file FileRepository.php.
The documentation for this class was generated from the following file:
core/modules/share/components/FileRepository.php