Energine: Energine\forms\components\Form Class Reference
Energine\forms\components\Form Class Reference
Form.
Public Member Functions
__construct ($name, $module, array $params=null)
Public Member Functions inherited from Energine\share\components\DBDataSet
__construct ($name, $module, array $params=null)
getTableName ()
Get table name.
getFilter ()
Get filter.
addFilterCondition ($filter)
Add filter condition.
getPK ()
Get filed name of primary key.
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Member Functions
defineParams ()
failure ($errorMessage, $data)
Call this by failure with captcha.
saveData (&$data)
Save data.
send ()
Send.
checkCaptcha ()
Check captcha.
success ()
Call this by successful captcha.
getRecipientEmail ($options=false)
Get recipient E-Mail from form.
main ()
Default action.
Protected Member Functions inherited from Energine\share\components\DBDataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
loadDataDescription ()
Load data description.
loadData ()
Load data.
getDataLanguage ()
Get data language.
setTableName ($tableName)
Set table name.
setParam ($name, $value)
Set component parameter if such exist.
setFilter ($filter)
Set filter.
clearFilter ()
Reset filter.
getOrder ()
Get sort order.
setOrder (array $order)
Set sort order.
getLimit ()
Get limit.
setLimit (array $limit)
Set limit.
setPK ($primaryColumnName)
Set primary key.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
getFKData ($fkTableName, $fkKeyName)
Get data from linked table.
getTranslationTableName ()
Get table name with translations.
view ()
Show view form.
recordExists ($id, $fieldName=false)
Detect if the specific record exist.
buildJS ()
Create description of JS objects.
getPreviousState ()
Get previous state.
saveText ()
Save text.
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Protected Attributes
$formID
Form ID.
$saver
Form info.
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Member Functions
returnEmptyRecordset ()
Return empty recordset.
buildForm ()
Build form.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Form.
class Form;
Definition at line 27 of file Form.php.
Constructor & Destructor Documentation
Energine\forms\components\Form::__construct ($name, $module, array $params = null)
Definition at line 43 of file Form.php.
{
         parent::__construct($name, $module, $params);
         $filter = array('form_is_active' => 1);
         if ($formID = $this->getParam('id')) {
             $filter['form_id'] = $formID;
         }
         $this->formID = simplifyDBResult(
             $this->dbh->select('frm_forms', 'form_id', $filter, 'RAND()', 1),
             'form_id',
             true
         );
         //If formID is actual number, but we don't have table with name form_$formID, then set formID to false.
         //Otherwiste setTableName.
         if (!$this->formID || !$this->dbh->tableExists($tableName =
                 FormConstructor::getDatabase() .
                 '.' .
                 FormConstructor::TABLE_PREFIX .
                 $this->formID)
         )
             $this->formID = false;
         else
             $this->setTableName($tableName);
         $this->setType(self::COMPONENT_TYPE_FORM_ADD);
         $this->setAction('send');
         $this->addTranslation('TXT_ENTER_CAPTCHA');
     }
Member Function Documentation
Energine\forms\components\Form::buildForm () private
Build form.
It adds form name and information about the form.
Definition at line 397 of file Form.php.
Referenced by Energine\forms\components\Form\failure(), and Energine\forms\components\Form\main().
{
         $result = $this->dbh->select('frm_forms_translation',
             array('form_name', 'form_annotation_rtf', 'form_post_annotation_rtf'),
             array('form_id' => $this->formID, 'lang_id' => E()->getLanguage()->getCurrent()));
         if (is_array($result)) {
             $this->setTitle($result[0]['form_name']);
             //    -
             if (!($field = $this->getData()->getFieldByName('form_date'))) {
                 $field = new Field(('form_date'));
                 $this->getData()->addField($field);
             }
             //
             $field->setData(date('Y-m-d H:i:s'));
             //    -
             if (!($fd = $this->getDataDescription()->getFieldDescriptionByName('form_date'))) {
                 $fd = new FieldDescription('form_date');
                 $this->getDataDescription()->addFieldDescription($fd);
             } else {
                 //
                 //
                 $this->getDataDescription()->removeFieldDescription($fd);
                 $this->getDataDescription()->addFieldDescription($fd);
             }
             $fd->setType(FieldDescription::FIELD_TYPE_HIDDEN)->removeProperty('pattern');
             $f = new Field('form_description');
             $f->setData($result[0]['form_annotation_rtf'], true);
             $fd = new FieldDescription('form_description');
             $fd->setType(FieldDescription::FIELD_TYPE_HIDDEN)->setMode(FieldDescription::FIELD_MODE_READ);
             $this->getData()->addField($f);
             $this->getDataDescription()->addFieldDescription($fd);
             $f = new Field('form_post_description');
             $f->setData($result[0]['form_post_annotation_rtf'], true);
             $fd = new FieldDescription('form_post_description');
             $fd->setType(FieldDescription::FIELD_TYPE_HIDDEN)->setMode(FieldDescription::FIELD_MODE_READ);
             $this->getData()->addField($f);
             $this->getDataDescription()->addFieldDescription($fd);
             if (
             !($this->document->getUser()->isAuthenticated()
                 ||
                 $this->getParam('noCaptcha'))
             ) {
                 $fd = new FieldDescription('captcha');
                 $fd->setType(FieldDescription::FIELD_TYPE_CAPTCHA);
                 $this->getDataDescription()->addFieldDescription($fd);
             }
             foreach ($this->getDataDescription() as $fd) {
                 if ($fd->getType() == FieldDescription::FIELD_TYPE_BOOL) {
                     $fd->setProperty('yes', $this->translate('TXT_YES'))->setProperty('no', $this->translate('TXT_NO'));
                 }
             }
         }
     }
Energine\forms\components\Form::checkCaptcha () protected
Check captcha.
Exceptions
SystemException
Definition at line 298 of file Form.php.
Referenced by Energine\forms\components\Form\send().
{
         require_once('core/modules/share/gears/recaptchalib.php');
         $privatekey = $this->getConfigValue('recaptcha.private');
         $resp = recaptcha_check_answer($privatekey,
             $_SERVER["REMOTE_ADDR"],
             $_POST["recaptcha_challenge_field"],
             $_POST["recaptcha_response_field"]);
         if (!$resp->is_valid) {
             throw new SystemException($this->translate('TXT_BAD_CAPTCHA'), SystemException::ERR_CRITICAL);
         }
     }
Energine\forms\components\Form::defineParams () protected
Definition at line 74 of file Form.php.
{
         return array_merge(
             parent::defineParams(),
             array(
                 'id' => false,
                 'active' => true,
                 'noCaptcha' => false
             )
         );
     }
Energine\forms\components\Form::failure ($errorMessage, $data) protected
Call this by failure with captcha.
Parameters
$errorMessage
$data
Definition at line 91 of file Form.php.
Referenced by Energine\forms\components\Form\send().
{
         $data = array_values($data);
         $this->getConfig()->setCurrentState('main');
         $this->prepare();
         $data[0]['form_error_message'] = $errorMessage;
         $this->getData()->load($data);
         $eFD = new FieldDescription('form_error_message');
         $eFD->setMode(FieldDescription::FIELD_MODE_READ);
         $eFD->setType(FieldDescription::FIELD_TYPE_CUSTOM);
         //$eFD->removeProperty('title');
         $this->getDataDescription()->addFieldDescription($eFD);
         $this->buildForm();
     }
Energine\forms\components\Form::getRecipientEmail ($options = false) protected
Get recipient E-Mail from form.
Parameters
bool $options Options.
Returns
string
Definition at line 349 of file Form.php.
Referenced by Energine\forms\components\Form\send().
{
         $result =
             simplifyDBResult($this->dbh->select('frm_forms', array('form_email_adresses'), array('form_id' => $this->formID)),
                 'form_email_adresses',
                 true);
         return $result;
     }
Energine\forms\components\Form::main () protected
Default action.
Returns
boolean
Definition at line 360 of file Form.php.
{
         //If we don't have such form - return recodset with error
         //Otherwise run main method
         if (!$this->formID)
             $this->returnEmptyRecordset();
         else {
             parent::main();
             $this->buildForm();
         }
     }
Energine\forms\components\Form::returnEmptyRecordset () private
Return empty recordset.
Definition at line 374 of file Form.php.
Referenced by Energine\forms\components\Form\main().
{
         $f = new Field('error_msg');
         $fd = new FieldDescription('error_msg');
         $fd->setType(FieldDescription::FIELD_TYPE_STRING);
         $fd->setMode(FieldDescription::FIELD_MODE_READ);
         $f->setData('ERROR_NO_FORM', true);
         $d = new Data();
         $dd = new DataDescription();
         $d->addField($f);
         $dd->addFieldDescription($fd);
         $this->setData($d);
         $this->setDataDescription($dd);
         $this->setBuilder(new SimpleBuilder());
     }
Energine\forms\components\Form::saveData (& $data) protected
Save data.
Parameters
array $data Data.
Returns
mixed
Exceptions
SystemException 'ERR_VALIDATE_FORM'
Definition at line 116 of file Form.php.
Referenced by Energine\forms\components\Form\send().
{
         //
         $result = false;
         if (isset($_FILES) && !empty($_FILES)) {
             list($dbName, $tName) =
                 DBA::getFQTableName($this->getTableName(), true);
             if (isset($_FILES[$phpTableName = $dbName . '_' . $tName])) {
                 $fileData = array();
                 //
                 foreach ($_FILES[$phpTableName] as $fParam => $fileInfo) {
                     foreach ($fileInfo as $fName => $val) {
                         $fileData[$fName][$fParam] = $val;
                     }
                 }
                 $uploader = new FileUploader();
                 foreach ($fileData as $fieldName => $fileInfo) {
                     //
                     if (!empty($fileInfo['name']) && $fileInfo['size'] > 0) {
                         $uploader->setFile($fileInfo);
                         $uploader->upload('uploads/forms');
                         $data[$this->getTableName()][$fieldName] =
                             $uploader->getFileObjectName();
                         $uploader->cleanUp();
                     }
                 }
             }
         }
         //
         $dataDescriptionObject = new DataDescription();
         //
         $configDataDescription =
             $this->getConfig()->getStateConfig($this->getPreviousState());
         //        -
         if (isset($configDataDescription->fields)) {
             $dataDescriptionObject->loadXML($configDataDescription->fields);
         }
         //
         $DBDataDescription = new DataDescription();
         //
         $DBDataDescription->load($this->loadDataDescription());
         $this->setDataDescription($dataDescriptionObject->intersect($DBDataDescription));
         $this->getDataDescription()->getFieldDescriptionByName('form_date')->removeProperty('pattern');
         $dataObject = new Data();
         foreach ($data[$this->getTableName()] as $key => $value) {
             if (is_scalar($value))
                 $data[$this->getTableName()][$key] = strip_tags($value);
         }
         $dataObject->load($data);
         $this->setData($dataObject);
         //
         $this->saver = new Saver();
         //
         $this->saver->setMode(self::COMPONENT_TYPE_FORM_ADD);
         $this->saver->setDataDescription($this->getDataDescription());
         $this->saver->setData($this->getData());
         if ($this->saver->validate() === true) {
             $this->saver->setFilter($this->getFilter());
             $this->saver->save();
             $result = $this->saver->getResult();
         } else {
             //  exception     save
             // exception     save
             throw new SystemException('ERR_VALIDATE_FORM', SystemException::ERR_WARNING, $this->saver->getErrors());
         }
         return $result;
     }
Energine\forms\components\Form::send () protected
Send.
Exceptions
Exception
Definition at line 197 of file Form.php.
{
         $postTableName = str_replace('.', '_', $this->getTableName());
         if (!isset($_POST[$postTableName])) {
             E()->getResponse()->redirectToCurrentSection();
         }
         try {
             $data[$this->getTableName()] = $_POST[$postTableName];
             if (!$this->document->getUser()->isAuthenticated() && !$this->getParam('noCaptcha')) {
                 $this->checkCaptcha();
             }
             if ($result = $this->saveData($data)) {
                 $data = $data[$this->getTableName()];
                 //Unset pk_id field, because we don't need it in body of message to send
                 $data['pk_id'] = $result;
                 foreach ($data as $key => $value) {
                     $data[$key] = array('translation' => $this->translate(
                             'FIELD_' . $key),
                         'value' => $value);
                     if ($fd = $this->saver->getDataDescription()->getFieldDescriptionByName($key)) {
                         if (($fd->getType() == FieldDescription::FIELD_TYPE_MULTI) && is_array($keyInfo = $fd->getPropertyValue('key'))) {
                             $m2mTableName = $keyInfo['tableName'];
                             $m2mPKName = $keyInfo['fieldName'];
                             //
                             if ($this->dbh->tableExists($m2mTableName)) {
                                 $tableInfo = $this->dbh->getColumnsInfo($m2mTableName);
                                 unset($tableInfo[$m2mPKName]);
                                 $m2mValueFieldInfo = current($tableInfo);
                                 if (isset($m2mValueFieldInfo['key']) && is_array($m2mValueFieldInfo)) {
                                     list($values, ,) = $this->dbh->getForeignKeyData($m2mValueFieldInfo['key']['tableName'], $m2mValueFieldInfo['key']['fieldName'], E()->getLanguage()->getCurrent(), array($m2mValueFieldInfo['key']['tableName'] . '.' . $m2mValueFieldInfo['key']['fieldName'] => $value));
                                     if (is_array($values)) {
                                         $data[$key]['value'] = implode(',', array_map(function ($row) {
                                             return $row['fk_name'];
                                         }, $values));
                                     }
                                 }
                             }
                         }
                     }
                 }
                 try {
                     $mailer = new Mail();
                     //Get subject
                     $subject = simplifyDBResult(
                         $this->dbh->select(
                             'frm_forms_translation',
                             array('form_name'),
                             array('form_id' => $this->formID, 'lang_id' => E()->getLanguage()->getCurrent())),
                         'form_name',
                         true);
                     $subject = $this->translate('TXT_EMAIL_FROM_FORM') . ' ' .
                         $subject;
                     //Create text to send. The last one will contain: translations of variables and  variables.
                     $body = '';
 //                    if (!($url = $this->getConfigValue('site.media')))
                     $url = E()->getSiteManager()->getCurrentSite()->base;
                     foreach ($data as $fieldname => $value) {
                         $type = $this->getDataDescription()->getFieldDescriptionByName($fieldname)->getType();
                         if ($type == FieldDescription::FIELD_TYPE_FILE) {
                             $val = $url . $value['value'];
                         } elseif ($type == FieldDescription::FIELD_TYPE_BOOL) {
                             $val = $this->translate(((int)$value['value'] === 0) ? 'TXT_NO' : 'TXT_YES');
                         } else {
                             $val = $value['value'];
                         }
                         $body .=
                             '<strong>' . $value['translation'] . '</strong>: ' . $val .
                             '<br>';
                     }
                     $mailer->setFrom($this->getConfigValue('mail.from'))->
                         setSubject($subject)->
                         setText($body)->
                         addTo(($recp =
                             $this->getRecipientEmail()) ? $recp
                             : $this->getConfigValue('mail.manager'))->send();
                 } catch (\Exception $e) {
                 }
             }
             //$this->prepare();
             $this->response->redirectToCurrentSection('send/success/');
         } catch (\Exception $e) {
             $this->failure($e->getMessage(), $data);
         }
     }
Energine\forms\components\Form::success () protected
Call this by successful captcha.
Definition at line 315 of file Form.php.
{
         $this->setBuilder($this->createBuilder());
         $dataDescription = new DataDescription();
         $ddi = new FieldDescription('result');
         $ddi->setType(FieldDescription::FIELD_TYPE_TEXT);
         $ddi->setMode(FieldDescription::FIELD_MODE_READ);
         $ddi->removeProperty('title');
         $dataDescription->addFieldDescription($ddi);
         $data = new Data();
         $di = new Field('result');
         $di->setData($this->translate('TXT_FORM_SUCCESS_SEND'));
         $data->addField($di);
         $this->setDataDescription($dataDescription);
         $this->setData($data);
         if ($result = simplifyDBResult(
             $this->dbh->select('frm_forms_translation',
                 array('form_name'),
                 array('form_id' => $this->formID, 'lang_id' => E()->getLanguage()->getCurrent())), 'form_name', true)
         ) {
         }
         $this->setTitle($result);
     }
Member Data Documentation
bool Energine\forms\components\Form::$formID protected
Form ID.
Definition at line 32 of file Form.php.
Referenced by Energine\forms\components\Form\__construct().
Saver Energine\forms\components\Form::$saver protected
Form info.
Definition at line 37 of file Form.php.
The documentation for this class was generated from the following file:
core/modules/forms/components/Form.php