Energine: Energine\share\gears\AbstractBuilder Class Reference
Energine\share\gears\AbstractBuilder Class Reference
Builder.
Public Member Functions
__construct ()
setDataDescription (DataDescription $dataDescription)
Set meta-data.
setData (Data $data)
Set data.
build ()
Build XML-document.
getResult ()
Get result document.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static enFormatDate ($date, $format, $type=FieldDescription::FIELD_TYPE_DATE)
Format date.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Protected Member Functions
run ()
Run building.
createField ($fieldName, FieldDescription $fieldInfo, $fieldValue=false, $fieldProperties=false)
Create data filed XML-description.
buildFieldValue (\DOMElement $result, FieldDescription $fieldInfo, $fieldValue)
Create field value.
fixUrl ($url)
Fix URL.
createOptions (FieldDescription $fieldInfo, $data=false)
Create the set of possible field values with type 'select'.
createTextBoxItems ($data=array())
Create the set of field values with type 'textbox'.
Protected Attributes
$dataDescription
Meta-data.
$data
Data.
$result
Result document.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Additional Inherited Members
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Builder.
abstract class AbstractBuilder;
Create XML-document based on meta-data.
Attention
This is abstract.
Definition at line 28 of file AbstractBuilder.php.
Constructor & Destructor Documentation
Energine\share\gears\AbstractBuilder::__construct ()
Definition at line 50 of file AbstractBuilder.php.
{
         parent::__construct();
         $this->dataDescription = false;
         $this->data = false;
     }
Member Function Documentation
Energine\share\gears\AbstractBuilder::build ()
Build XML-document.
Returns
boolean
Exceptions
SystemException 'ERR_DEV_NO_DATA_DESCRIPTION'
Implements Energine\share\gears\IBuilder.
Definition at line 83 of file AbstractBuilder.php.
{
         $this->result = new \DOMDocument('1.0', 'UTF-8');
         // если отсутствует описание данных - построение невозможно
         if ($this->dataDescription == false) {
             throw new SystemException('ERR_DEV_NO_DATA_DESCRIPTION', SystemException::ERR_DEVELOPER);
         }
         $this->run();
         return ($this->result instanceof \DOMDocument ? true : false);
     }
Energine\share\gears\AbstractBuilder::buildFieldValue (\DOMElement $result, FieldDescription $fieldInfo, $fieldValue) protected
Create field value.
The value is processed and stored in passed DOM-element.
Parameters
\DOMElement $result DOM-element.
FieldDescription $fieldInfo Field description.
$fieldValue Field value.
Returns
Definition at line 220 of file AbstractBuilder.php.
Referenced by Energine\share\gears\AbstractBuilder\createField().
{
         if (($fieldValue instanceof \DOMNode) ||
             ($fieldValue instanceof \DOMElement)
         ) {
             try {
                 $result->appendChild($fieldValue);
             } catch (\Exception $e) {
                 $result->appendChild($this->result->importNode($fieldValue, true));
             }
         } elseif ($fieldInfo->getType() ==
             FieldDescription::FIELD_TYPE_TEXTBOX_LIST
         ) {
             if ($fieldValue = $this->createTextBoxItems($fieldValue)) {
                 try {
                     $result->appendChild($fieldValue);
                 } catch (\Exception $e) {
                     $result->appendChild($this->result->importNode($fieldValue, true));
                 }
             }
         } elseif (($fieldInfo->getType() == FieldDescription::FIELD_TYPE_MEDIA) &&
             $fieldValue
         ) {
             try {
                 $result->nodeValue = $fieldValue;
                 if ($info = E()->FileRepoInfo->analyze($fieldValue)) {
                     $result->setAttribute('media_type', $info->type);
                     $result->setAttribute('mime', $info->mime);
                 }
             } catch (SystemException $e) {
             }
         }
         elseif ($fieldValue !== false) {
             // empty() не пропускает значиния 0 и '0'
             if (!empty($fieldValue) || ($fieldValue === 0) || ($fieldValue === '0')) {
                 switch ($fieldInfo->getType()) {
                     case FieldDescription::FIELD_TYPE_DATETIME:
                     case FieldDescription::FIELD_TYPE_DATE:
                     case FieldDescription::FIELD_TYPE_TIME:
                         $result->setAttribute('date', $fieldValue);
                         $fieldValue =
                             self::enFormatDate($fieldValue, $fieldInfo->getPropertyValue('outputFormat'), $fieldInfo->getType());
                         break;
                     case FieldDescription::FIELD_TYPE_STRING:
                     case FieldDescription::FIELD_TYPE_TEXT:
                     case FieldDescription::FIELD_TYPE_HTML_BLOCK:
                         //$fieldValue = str_replace('&', '&amp;', $fieldValue);
                         break;
                     default: // not used
                 }
                 $result->appendChild(new \DomText($fieldValue));
             }
         }
         return $result;
     }
Energine\share\gears\AbstractBuilder::createField ($fieldName, FieldDescription $fieldInfo, $fieldValue = false, $fieldProperties = false) protected
Create data filed XML-description.
Parameters
string $fieldName Field name.
FieldDescription $fieldInfo Filed description.
mixed $fieldValue Field value.
mixed $fieldProperties Field properties.
Returns
Definition at line 119 of file AbstractBuilder.php.
Referenced by Energine\share\gears\MultiLanguageBuilder\run(), and Energine\share\gears\Builder\run().
{
         $result = $this->result->createElement('field');
         $result->setAttribute('name', $fieldName);
         $result->setAttribute('type', $fieldInfo->getType());
         $length = $fieldInfo->getLength();
         if ($length !== true) {
             $result->setAttribute('length', $length);
         }
         $result->setAttribute('mode', $fieldInfo->getMode());
         if($fieldInfo->getMode() == FieldDescription::FIELD_MODE_READ){
             $fieldInfo->removeProperty('message');
             $fieldInfo->removeProperty('pattern');
         }
         if (in_array($fieldInfo->getType(), array(FieldDescription::FIELD_TYPE_FILE))) {
             if (
                 (E()->getDocument()->getRights() > ACCESS_READ)
                 &&
                 ($fieldInfo->getMode() > ACCESS_READ)
             ) {
                 E()->getDocument()->addTranslation('TXT_CLEAR');
                 E()->getDocument()->addTranslation('BTN_QUICK_UPLOAD');
                 $quick_upload_path = $this->getConfigValue('repositories.quick_upload_path', 'uploads/public');
                 $quick_upload_pid = $this->dbh->getScalar('SELECT upl_id FROM share_uploads WHERE upl_path=%s LIMIT 1', $quick_upload_path);
                 $quick_upload_enabled = true;
                 if($quick_upload_pid){
                     $result->setAttribute('quickUploadPath', $quick_upload_path);
                     $result->setAttribute('quickUploadPid', $quick_upload_pid);
                     $result->setAttribute('quickUploadEnabled', $quick_upload_enabled);
                 }
             }
             if ($fieldValue) {
                 $repoPath = E()->FileRepoInfo->getRepositoryRoot($fieldValue);
                 $is_secure = (E()->getConfigValue('repositories.ftp.' . $repoPath . '.secure', 0)) ? true : false;
                 $result->setAttribute('secure', $is_secure);
                 try {
                     if ($info = E()->FileRepoInfo->analyze($fieldValue)) {
                         $result->setAttribute('media_type', $info->type);
                         $result->setAttribute('mime', $info->mime);
                         $playlist = array();
                         $base = pathinfo($fieldValue, PATHINFO_DIRNAME) . '/' . pathinfo($fieldValue, PATHINFO_FILENAME);
                         if ($info->is_mp4) {
                             $playlist[] = $base . '.mp4';
                         }
                         if ($info->is_webm) {
                             $playlist[] = $base . '.webm';
                         }
                         if ($info->is_flv) {
                             $playlist[] = $base . '.flv';
                         }
                         if ($playlist) {
                             $result->setAttribute('playlist', implode(',', $playlist));
                         }
                     }
                 } catch (SystemException $e) {
                 }
             }
         }
         elseif(($fieldInfo->getType() == FieldDescription::FIELD_TYPE_SMAP_SELECTOR) && $fieldValue){
             $result->setAttribute('smap_name', E()->getSiteManager()->getSiteByPage($fieldValue)->name.' : '.$this->dbh->getScalar('share_sitemap_translation', 'smap_name', array('smap_id' => $fieldValue, 'lang_id' => E()->getLanguage()->getCurrent())));
         }
         elseif ($fieldInfo->getType() == FieldDescription::FIELD_TYPE_CAPTCHA) {
             require_once(CORE_DIR . '/modules/share/gears/recaptchalib.php');
             $fieldValue = recaptcha_get_html($this->getConfigValue('recaptcha.public'));
         }
         elseif($fieldInfo->getType() == FieldDescription::FIELD_TYPE_VALUE){
             $value = $this->result->createElement('value', $fieldValue['value']);
             $value->setAttribute('id', $fieldValue['id']);
             $fieldValue = $value;
         }
         foreach ($fieldInfo as $propName => $propValue) {
             if ($propValue && !is_array($propValue)) {
                 $result->setAttribute($propName, $propValue);
             }
         }
         if ($fieldProperties) {
             foreach ($fieldProperties as $propName => $propValue) {
                 $result->setAttribute($propName, $propValue);
             }
         }
         return $this->buildFieldValue($result, $fieldInfo, $fieldValue);
     }
Energine\share\gears\AbstractBuilder::createOptions (FieldDescription $fieldInfo, $data = false) protected
Create the set of possible field values with type 'select'.
Parameters
FieldDescription $fieldInfo Field description.
mixed $data Data.
Returns
DOMNode
Definition at line 395 of file AbstractBuilder.php.
Referenced by Energine\share\gears\MultiLanguageBuilder\run(), Energine\share\gears\Builder\run(), and Energine\share\gears\TreeBuilder\treeBuild().
{
         $fieldValue = $this->result->createElement('options');
         if (is_array($fieldInfo->getAvailableValues()))
             foreach ($fieldInfo->getAvailableValues() as $key => $option) {
                 $dom_option =
                     $this->result->createElement('option', str_replace('&', '&amp;', $option['value']));
                 $dom_option->setAttribute('id', $key);
                 if ($option['attributes']) {
                     foreach ($option['attributes'] as $attrName => $attrValue) {
                         $dom_option->setAttribute($attrName, $attrValue);
                     }
                 }
                 // для поля типа multi-select
                 if (is_array($data) && in_array($key, $data)) {
                     $dom_option->setAttribute('selected', 'selected');
                 }
                 $fieldValue->appendChild($dom_option);
             }
         return $fieldValue;
     }
Energine\share\gears\AbstractBuilder::createTextBoxItems ($data = array()) protected
Create the set of field values with type 'textbox'.
Parameters
array $data Data.
Returns
mixed
Definition at line 422 of file AbstractBuilder.php.
Referenced by Energine\share\gears\AbstractBuilder\buildFieldValue().
{
         $fieldValue = false;
         if ($data === false) {
             return false;
         } elseif (!is_array($data)) {
             $data = array($data);
         }
         if (!empty($data)) {
             $fieldValue = $this->result->createElement('items');
             foreach ($data as $itemId => $itemData) {
                 $item = $this->result->createElement('item', (string)$itemData);
                 $item->setAttribute('id', $itemId);
                 $fieldValue->appendChild($item);
             }
         }
         return $fieldValue;
     }
static Energine\share\gears\AbstractBuilder::enFormatDate ($date, $format, $type = FieldDescription::FIELD_TYPE_DATE) static
Format date.
Pseudo modifiers:
E - Today|Yesterday|Tomorrow|After tomorrow|Weekday_abbreviation $Date $month_name, $time[$Year(if not current)]
f - Weekday name $Date $month_name, $time[$Year(if not current)]
o - [Today,] $Date $month_name, $time[$Year(if not current)]
q
Parameters
int $date Timestamp.
string $format Format.
string $type Type.
Returns
string
Definition at line 309 of file AbstractBuilder.php.
Referenced by Energine\share\components\Grid\exportCSV(), Energine\apps\components\Vote\getVote(), and Energine\apps\components\Vote\getVoteResults().
{
         if (!$date) return '';
         $date = strtotime($date);
         if (!in_array($format, array('%E', '%f', '%o', '%q'))) {
             $result = @strftime($format, $date);
             if (!$result) {
                 $result = $date;
             }
         } else {
             $result = '';
             $today = strtotime("midnight");
             $tomorrow = strtotime("midnight +1 day");
             $dayAfterTomorrow = strtotime("midnight +2 day");
             $tomorrowPlus3 = strtotime("midnight +3 day");
             $yesterday = strtotime("midnight -1 day");
             $beforeYesterday = strtotime("midnight -2 day");
             switch ($format) {
                 case '%E':
                     if ($date >= $today and $date < $tomorrow) {
                         $result .= DBWorker::_translate('TXT_TODAY');
                     } elseif ($date < $today and $date >= $yesterday) {
                         $result .= DBWorker::_translate('TXT_YESTERDAY');
                     } elseif ($date < $yesterday and $date >= $beforeYesterday) {
                         $result .= DBWorker::_translate('TXT_BEFORE_YESTERDAY');
                     } elseif ($date >= $tomorrow && $date < $dayAfterTomorrow) {
                         $result .= DBWorker::_translate('TXT_TOMORROW');
                     } elseif ($date >= $dayAfterTomorrow && $date < $tomorrowPlus3) {
                         $result .= DBWorker::_translate('TXT_AFTER_TOMORROW');
                     } else {
                         $dayNum = date('w', $date);
                         if ($dayNum == 0) {
                             $dayNum = 7;
                         }
                         $result .= DBWorker::_translate('TXT_WEEKDAY_SHORT_' . $dayNum);
                     }
                     $result .= ', ' . date('j', $date) . ' ' . (DBWorker::_translate('TXT_MONTH_' . date('n', $date)));
                     if (date('Y', $date) != date('Y')) {
                         $result .= ' ' . date('Y', $date);
                     }
                     break;
                 case '%f':
                     $dayNum = date('w', $date);
                     if ($dayNum == 0) {
                         $dayNum = 7;
                     }
                     $result .= DBWorker::_translate('TXT_WEEKDAY_' . $dayNum) . ', ' . date('j', $date) . ' ' . (DBWorker::_translate('TXT_MONTH_' . date('n', $date)));
                     if (date('Y', $date) != date('Y')) {
                         $result .= ' ' . date('Y', $date);
                     }
                     break;
                 case '%o':
                     if ($date >= $today and $date < $tomorrow) {
                         $result .= DBWorker::_translate('TXT_TODAY') . ', ';
                     }
                     $result .= date('j', $date) . ' ' . (DBWorker::_translate('TXT_MONTH_' . date('n', $date)));
                     if (date('Y', $date) != date('Y')) {
                         $result .= ' ' . date('Y', $date);
                     }
                     break;
                 case '%q':
                     $result .= date('j', $date) . ' ' . (DBWorker::_translate('TXT_MONTH_' . date('n', $date)));
                     if (date('Y', $date) != date('Y')) {
                         $result .= ' ' . date('Y', $date);
                     }
                     break;
             }
             //Если часы и минуты = 0, считаем что это просто дата, без времени
             if (in_array($type, array(FieldDescription::FIELD_TYPE_DATETIME, FieldDescription::FIELD_TYPE_TIME, FieldDescription::FIELD_TYPE_HIDDEN))) {
                 $result .= ', ';
                 $result .= date('G', $date) . ':' . date('i', $date);
             }
         }
         return $result;
     }
Energine\share\gears\AbstractBuilder::fixUrl ($url) protected
Fix URL.
Parameters
string $url URL.
Returns
string
Definition at line 286 of file AbstractBuilder.php.
{
         return str_replace(
             array('%2F', '+'),
             array('/', '%20'),
             urlencode($url)
         );
     }
Energine\share\gears\AbstractBuilder::getResult ()
Get result document.
Returns
DOMNode
Implements Energine\share\gears\IBuilder.
Definition at line 98 of file AbstractBuilder.php.
{
         return $this->result->documentElement;
     }
Energine\share\gears\AbstractBuilder::run () protected
Run building.
Note
This is used in the derived classes to build a result. That result should be stored in Builder::$result
Definition at line 107 of file AbstractBuilder.php.
Referenced by Energine\share\gears\AbstractBuilder\build().
{
     }
Energine\share\gears\AbstractBuilder::setData (Data $data)
Set data.
Parameters
Data $data Data.
Definition at line 71 of file AbstractBuilder.php.
{
         $this->data = $data;
     }
Energine\share\gears\AbstractBuilder::setDataDescription (DataDescription $dataDescription)
Set meta-data.
Parameters
DataDescription $dataDescription Meta-data.
Definition at line 62 of file AbstractBuilder.php.
{
         $this->dataDescription = $dataDescription;
     }
Member Data Documentation
Data Energine\share\gears\AbstractBuilder::$data protected
Data.
Definition at line 39 of file AbstractBuilder.php.
Referenced by Energine\share\gears\AbstractBuilder\createOptions(), Energine\share\gears\AbstractBuilder\createTextBoxItems(), Energine\share\gears\MultiLanguageBuilder\run(), Energine\share\gears\Builder\run(), Energine\share\gears\AbstractBuilder\setData(), and Energine\share\gears\TreeBuilder\treeBuild().
DataDescription Energine\share\gears\AbstractBuilder::$dataDescription protected
Meta-data.
Definition at line 33 of file AbstractBuilder.php.
Referenced by Energine\share\gears\AbstractBuilder\setDataDescription().
DOMDocument Energine\share\gears\AbstractBuilder::$result protected
Result document.
Definition at line 45 of file AbstractBuilder.php.
Referenced by Energine\comments\gears\CommentsJSONBuilder\build(), Energine\share\gears\JSONRepoBuilder\build(), Energine\share\gears\JSONBuilder\build(), Energine\share\gears\AbstractBuilder\buildFieldValue(), Energine\calendar\gears\CalendarBuilder\createField(), Energine\share\gears\AbstractBuilder\createField(), Energine\share\gears\AbstractBuilder\enFormatDate(), Energine\share\gears\JSONDivBuilder\getResult(), Energine\share\gears\JSONUploadBuilder\getResult(), and Energine\share\gears\JSONBuilder\getResult().
The documentation for this class was generated from the following file:
core/modules/share/gears/AbstractBuilder.php