Energine: Energine\share\gears\DBA Class Reference
Energine\share\gears\DBA Class Reference
Database Abstraction Layer.
Public Member Functions
__construct ($dsn, $username, $password, array $driverOptions, $charset= 'utf8')
getPDO ()
Get DBA::$pdo.
selectRequest ($query)
Execute SELECT request.
modifyRequest ($query)
Execute modification request like INSERT, UPDATE, DELETE.
call ($name, &$args=null)
Call procedure.
get ($query)
Get data for further iteration.
quote ($string)
Process string.
getLastRequest ()
Get the last query.
getLastError ()
Get last error message.
beginTransaction ()
Begin an transaction.
commit ()
Execute commit transaction.
rollback ()
Open transaction.
getColumnsInfo ($tableName)
Get columns info of the table.
getTranslationTablename ($tableName)
Get the table name with translations.
tableExists ($tableName)
Check whether some table name exist.
procExists ($procName)
Check whether some procedure exist.
funcExists ($funcName)
Check whether some function exist.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static getFQTableName ($tableName, $returnAsArray=false)
Get the fully qualified table name in MySQL quotes.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes
const COLTYPE_INTEGER = 'INT'
Column type: INTEGER.
const COLTYPE_FLOAT = 'FLOAT'
Column type: FLOAT.
const COLTYPE_DATE = 'DATE'
Column type: DATE.
const COLTYPE_TIME = 'TIME'
Column type: TIME.
const COLTYPE_TIMESTAMP = 'TIMESTAMP'
Column type: TIMESTAMP.
const COLTYPE_DATETIME = 'DATETIME'
Column type: DATETIME.
const COLTYPE_STRING = 'VARCHAR'
Column type: VARCHAR.
const COLTYPE_TEXT = 'TEXT'
Column type: TEXT.
const COLTYPE_BLOB = 'BLOB'
Column type: BLOB Binary data.
const ERR_BAD_REQUEST = 'ERR_DATABASE_ERROR'
Error type of the column.
const PRIMARY_INDEX = 'PRI'
Primary index.
const UNIQUE_INDEX = 'UNI'
Unique index.
const INDEX = 'MUL'
Index.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
fulfill ($request)
Execute the request.
constructQuery (array $args)
Construct query.
runQuery (array $args)
Run query.
Protected Attributes
$pdo
Instance of PDO class (PHP Data Objects).
$lastQuery
Last query to the data base.
Private Attributes
$dbCache
Data base cache.
Detailed Description
Database Abstraction Layer.
abstract class DBA;
Attention
This is abstract.
Definition at line 28 of file DBA.php.
Constructor & Destructor Documentation
Energine\share\gears\DBA::__construct ($dsn, $username, $password, array $driverOptions, $charset = 'utf8')
Parameters
string $dsn Data Source Name; for connecting to the data base.
string $username User name.
string $password Password.
array $driverOptions Specific DB driver parameters.
string $charset Encoding.
Exceptions
SystemException Unable to connect. The site is temporarily unavailable.
Definition at line 141 of file DBA.php.
{
         try {
             $this->pdo = new \PDO($dsn, $username, $password, $driverOptions);
             $this->pdo->query('SET NAMES ' . $charset);
             $this->dbCache = new DBStructureInfo($this->pdo);
         } catch (\PDOException $e) {
             throw new SystemException('Unable to connect. The site is temporarily unavailable.', SystemException::ERR_DB, 'The site is temporarily unavailable');
         }
     }
Member Function Documentation
Energine\share\gears\DBA::beginTransaction ()
Begin an transaction.
Returns
boolean
Definition at line 341 of file DBA.php.
{
         return $this->pdo->beginTransaction();
     }
Energine\share\gears\DBA::call ($name, & $args = null)
Call procedure.
Parameters
string $name Procedure name.
array $args Procedure arguments.
Returns
array|bool
Definition at line 254 of file DBA.php.
{
         if (!$args) {
             $res = $this->pdo->query("call $name();", \PDO::FETCH_NAMED);
         } else {
             $argString = implode(',', array_fill(0, count($args), '?'));
             $stmt = $this->pdo->prepare("CALL $name($argString)");
             foreach ($args as $index => &$value) {
                 $stmt->bindParam($index + 1, $value);
             }
             if ($res = $stmt->execute()) {
                 $res = $stmt->fetchAll(\PDO::FETCH_ASSOC);
             }
         }
         return $res;
     }
Energine\share\gears\DBA::commit ()
Execute commit transaction.
Returns
boolean
Definition at line 350 of file DBA.php.
{
         return $this->pdo->commit();
     }
Energine\share\gears\DBA::constructQuery (array $args) protected
Construct query.
If the number of the arguments is > 1, then this method behaves like printf() function.
Parameters
array $args Array from which the single query string will be built.
Returns
string
Deprecated:
See also
DBA::selectRequest()
DBA::modifyRequest()
Definition at line 485 of file DBA.php.
Referenced by Energine\share\gears\DBA\fulfill().
{
         if (sizeof($args) > 1) {
             $query = array_shift($args); //    $query
             foreach ($args as &$arg) {
                 if(!is_null($arg))
                     $arg = $this->pdo->quote($arg);
                 else {
                     $arg = 'NULL';
                 }
             }
             array_unshift($args, $query);
             $query = call_user_func_array('sprintf', $args);
         } else {
             $query = $args[0];
         }
         return $query;
     }
Energine\share\gears\DBA::fulfill ($request) protected
Execute the request.
Parameters
string $request Request.
Returns
bool|
Definition at line 290 of file DBA.php.
{
         if (!is_string($request) || empty($request)) {
             return false;
         }
         if ($this->getConfigValue('database.prepare')) {
             $res = $this->runQuery(func_get_args());
             if ($res instanceof \PDOStatement)
                 $this->lastQuery = $res->queryString;
         } else {
             $request = $this->constructQuery(func_get_args());
             $res = $this->pdo->query($request);
             $this->lastQuery = $request;
         }
         return $res;
     }
Energine\share\gears\DBA::funcExists ($funcName)
Check whether some function exist.
Parameters
string $funcName Function name.
Returns
boolean
Definition at line 437 of file DBA.php.
{
         return ($this->getScalar(
             'SELECT ROUTINE_NAME
             FROM information_schema.ROUTINES
             WHERE
             ROUTINE_TYPE="FUNCTION"
             AND ROUTINE_SCHEMA=%s
             AND ROUTINE_NAME=%s',
             E()->getConfigValue('database.db'),
             $funcName
         )) ? true : false;
     }
Energine\share\gears\DBA::get ($query)
Get data for further iteration.
Parameters
string $query SQL request.
Returns
bool|
Definition at line 276 of file DBA.php.
{
         $res = call_user_func_array(array($this, 'fulfill'), func_get_args());
         if ($res instanceof \PDOStatement) {
             return $res;
         }
         return false;
     }
Energine\share\gears\DBA::getColumnsInfo ($tableName)
Get columns info of the table.
The returned array looks like:
array(
    'columnName' => array(
        'type'      => column type,
        'length'    => length,
        'nullable'  => accept NULL?,
        'key'       => description of the columns key (if exist),
        'default'   => default value,
        'index'     => index type
    )
)
Parameters
string $tableName Table name.
Returns
array
Definition at line 383 of file DBA.php.
Referenced by Energine\share\gears\QAL\getForeignKeyData().
{
         $result = $this->dbCache->getTableMeta($tableName);
         return $result;
     }
static Energine\share\gears\DBA::getFQTableName ($tableName, $returnAsArray = false) static
Get the fully qualified table name in MySQL quotes.
Parameters
string $tableName Table name.
bool $returnAsArray Return as array?
Returns
string | array
Definition at line 457 of file DBA.php.
Referenced by Energine\forms\gears\FormConstructor\__construct(), Energine\share\gears\DBStructureInfo\analyzeTable(), Energine\share\gears\QAL\buildSQL(), Energine\forms\gears\FormConstructor\createMultiField(), Energine\forms\gears\FormConstructor\createSelectField(), Energine\forms\gears\FormConstructor\delete(), Energine\forms\gears\FormConstructor\getFieldLTag(), Energine\share\gears\QAL\getForeignKeyData(), Energine\share\gears\QAL\modify(), Energine\forms\gears\FormConstructor\save(), Energine\forms\components\Form\saveData(), and Energine\share\gears\DBStructureInfo\tableExists().
{
         $result = array();
         $tableName = str_replace('`', '', $tableName);
         if ($pos = strpos($tableName, '.')) {
             array_push($result, substr($tableName, 0, $pos));
             $tableName = substr($tableName, $pos + 1);
         }
         array_push($result, $tableName);
         return (!$returnAsArray) ? implode('.', array_map(function ($row) {
             return '`' . $row . '`';
         }, $result)) : $result;
     }
Energine\share\gears\DBA::getLastError ()
Get last error message.
Returns
string
Definition at line 332 of file DBA.php.
{
         return $this->pdo->errorInfo();
     }
Energine\share\gears\DBA::getLastRequest ()
Get the last query.
Returns
string
Definition at line 323 of file DBA.php.
Referenced by Energine\share\gears\DBA\modifyRequest(), and Energine\share\gears\DBA\selectRequest().
{
         return $this->lastQuery;
     }
Energine\share\gears\DBA::getPDO ()
Get DBA::$pdo.
Use this for direct work with DB.
Returns
Definition at line 161 of file DBA.php.
{
         return $this->pdo;
     }
Energine\share\gears\DBA::getTranslationTablename ($tableName)
Get the table name with translations.
Get the table name with translations for some table name, if such exist. Otherwise false will be returned.
Parameters
string $tableName
Returns
string|bool
Definition at line 398 of file DBA.php.
Referenced by Energine\share\gears\QAL\getForeignKeyData().
{
         return $this->tableExists($tableName . '_translation');
     }
Energine\share\gears\DBA::modifyRequest ($query)
Execute modification request like INSERT, UPDATE, DELETE.
It returns one from the following:
last generated ID for field type AUTO_INCREMENT;
true by success;
false by fail.
Parameters
string $query Query.
Returns
mixed
Note
If the total amount of arguments is more than 1, then this function process the input arguments like printf function.
See also
DBA::constructQuery
Exceptions
SystemException
Definition at line 231 of file DBA.php.
{
         $res = call_user_func_array(array($this, 'fulfill'), func_get_args());
         if (!($res instanceof \PDOStatement)) {
             $errorInfo = $this->pdo->errorInfo();
             throw new SystemException($errorInfo[2], SystemException::ERR_DB, array($this->getLastRequest(),));
         }
         $result = intval($this->pdo->lastInsertId());
         if ($result == 0) {
             $result = true;
         }
         return $result;
     }
Energine\share\gears\DBA::procExists ($procName)
Check whether some procedure exist.
Parameters
string $procName Procedure name.
Returns
boolean
Definition at line 418 of file DBA.php.
{
         return ($this->getScalar(
             'SELECT ROUTINE_NAME
             FROM information_schema.ROUTINES
             WHERE
             ROUTINE_TYPE="PROCEDURE"
             AND ROUTINE_SCHEMA=%s
             AND ROUTINE_NAME=%s',
             E()->getConfigValue('database.db'),
             $procName
         )) ? true : false;
     }
Energine\share\gears\DBA::quote ($string)
Process string.
Place, if needed, double quotes around the input string and isolates special symbols inside the string.
Parameters
string $string Some string.
Returns
string
Definition at line 314 of file DBA.php.
Referenced by Energine\share\gears\QAL\buildWhereCondition().
{
         return $this->pdo->quote($string);
     }
Energine\share\gears\DBA::rollback ()
Open transaction.
Returns
boolean
Definition at line 359 of file DBA.php.
{
         return $this->pdo->rollBack();
     }
Energine\share\gears\DBA::runQuery (array $args) protected
Run query.
Parameters
array $args Query arguments. First argument is SQL string
Returns
Exceptions
SystemException 'ERR_BAD_REQUEST'
Definition at line 511 of file DBA.php.
Referenced by Energine\share\gears\DBA\fulfill().
{
         if (empty($args)) {
             throw new SystemException('ERR_BAD_REQUEST');
         }
         $query = array_shift($args);
         $query = str_replace('%%', '%', $query);
         if (!empty($args)) {
             if (preg_match_all('(%(?:(\d)\$)?s)', $query, $matches)) {
                 $query = preg_replace('(%(?:(\d)\$)?s)', '?', $query);
                 $argIndex = 0;
                 foreach ($matches[1] as $a) {
                     if ($a = (int)$a) {
                         $data[] = $args[$a - 1];
                     } else {
                         $data[] = $args[$argIndex++];
                     }
                 }
             } else {
                 $data = $args;
             }
             if (!($result = $this->pdo->prepare($query))) {
                 throw new SystemException('ERR_PREPARE_REQUEST', SystemException::ERR_DB, $query);
             }
             if (!$result->execute($data)) {
                 throw new SystemException('ERR_EXECUTE_REQUEST', SystemException::ERR_DB, array($query, $data));
             }
         } else {
             $result = $this->pdo->query($query);
         }
         return $result;
     }
Energine\share\gears\DBA::selectRequest ($query)
Execute SELECT request.
It returns one from the following:
an array for non-empty result like
array(
    rowID => array(
                   fieldName => fieldValue,
                   ...
                  )
)
true for empty result;
false by fail.
Parameters
string $query SELECT query.
Returns
mixed
Exceptions
SystemException
See also
DBA::constructQuery
Note
If the total amount of arguments is more than 1, then this function process the input arguments like printf function.
Deprecated:
Definition at line 194 of file DBA.php.
Referenced by Energine\share\gears\QAL\getForeignKeyData().
{
         $res = call_user_func_array(array($this, 'fulfill'), func_get_args());
         if (!($res instanceof \PDOStatement)) {
             $errorInfo = $this->pdo->errorInfo();
             throw new SystemException($errorInfo[2], SystemException::ERR_DB, array($this->getLastRequest()));
         }
         $result = array();
         while ($row = $res->fetch(\PDO::FETCH_ASSOC)) {
             array_push($result, $row);
         }
         if (empty($result)) {
             $result = true;
         }
         return $result;
     }
Energine\share\gears\DBA::tableExists ($tableName)
Check whether some table name exist.
Parameters
$tableName string Table name.
Returns
string|bool
Definition at line 408 of file DBA.php.
Referenced by Energine\share\gears\DBA\getTranslationTablename().
{
         return ($this->dbCache->tableExists($tableName)) ? $tableName : false;
     }
Member Data Documentation
DBStructureInfo Energine\share\gears\DBA::$dbCache private
Data base cache.
Definition at line 45 of file DBA.php.
string Energine\share\gears\DBA::$lastQuery protected
Last query to the data base.
Definition at line 39 of file DBA.php.
Referenced by Energine\share\gears\DBA\getLastRequest().
PDO Energine\share\gears\DBA::$pdo protected
Instance of PDO class (PHP Data Objects).
Definition at line 33 of file DBA.php.
Referenced by Energine\share\gears\DBA\getPDO().
string Energine\share\gears\DBA::COLTYPE_BLOB = 'BLOB'
Column type: BLOB Binary data.
Definition at line 106 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\convertType().
string Energine\share\gears\DBA::COLTYPE_DATE = 'DATE'
Column type: DATE.
Definition at line 64 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\convertType(), and Energine\share\gears\FieldDescription\convertType().
string Energine\share\gears\DBA::COLTYPE_DATETIME = 'DATETIME'
Column type: DATETIME.
Definition at line 82 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\convertType(), and Energine\share\gears\FieldDescription\convertType().
string Energine\share\gears\DBA::COLTYPE_FLOAT = 'FLOAT'
Column type: FLOAT.
Definition at line 58 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\convertType(), and Energine\share\gears\FieldDescription\convertType().
string Energine\share\gears\DBA::COLTYPE_INTEGER = 'INT'
Column type: INTEGER.
Definition at line 52 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\convertType(), and Energine\share\gears\FieldDescription\convertType().
string Energine\share\gears\DBA::COLTYPE_STRING = 'VARCHAR'
Column type: VARCHAR.
Definition at line 88 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\analyzeView(), Energine\share\gears\DBStructureInfo\convertType(), Energine\share\gears\FieldDescription\convertType(), and Energine\comments\components\CommentsEditor\loadDataDescription().
string Energine\share\gears\DBA::COLTYPE_TEXT = 'TEXT'
Column type: TEXT.
Definition at line 98 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\convertType(), Energine\share\gears\FieldDescription\convertType(), and Energine\share\gears\QAL\getForeignKeyData().
string Energine\share\gears\DBA::COLTYPE_TIME = 'TIME'
Column type: TIME.
Definition at line 70 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\convertType(), and Energine\share\gears\FieldDescription\convertType().
string Energine\share\gears\DBA::COLTYPE_TIMESTAMP = 'TIMESTAMP'
Column type: TIMESTAMP.
Definition at line 76 of file DBA.php.
Referenced by Energine\share\gears\DBStructureInfo\convertType(), and Energine\share\gears\FieldDescription\convertType().
string Energine\share\gears\DBA::ERR_BAD_REQUEST = 'ERR_DATABASE_ERROR'
Error type of the column.
Definition at line 112 of file DBA.php.
string Energine\share\gears\DBA::INDEX = 'MUL'
Index.
Definition at line 130 of file DBA.php.
string Energine\share\gears\DBA::PRIMARY_INDEX = 'PRI'
Primary index.
Definition at line 118 of file DBA.php.
Referenced by Energine\share\gears\User\create().
string Energine\share\gears\DBA::UNIQUE_INDEX = 'UNI'
Unique index.
Definition at line 124 of file DBA.php.
Referenced by Energine\share\gears\User\create().
The documentation for this class was generated from the following file:
core/modules/share/gears/DBA.php