Energine: Energine\share\gears\ExtendedSaver Class Reference
Energine\share\gears\ExtendedSaver Class Reference
Extended Saver.
Public Member Functions
setDataDescription (DataDescription $dd)
Set data description and main table name.
save ()
Save data into the table of uploads and tags.
Public Member Functions inherited from Energine\share\gears\Saver
__construct ()
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
Get data description.
getData ()
Get data.
setData (Data $data)
Set data.
setMode ($mode)
Set save mode.
getMode ()
Get save mode.
getFilter ()
Get condition for save SQL-request.
setFilter ($filter)
Set condition for save SQL-request.
validate ()
Validate date before saving.
getErrors ()
Get fields with errors.
addError ($fieldName)
Add field name where an error occurred.
save ()
Save data.
getResult ()
Get result of saving.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Member Functions
getTableName ()
Get main table name.
getPK ()
Get primary key.
Private Attributes
$pk
Primary key of the table.
$mainTableName
Main table name.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Attributes inherited from Energine\share\gears\Saver
$dataDescription = false
Data description.
$data = false
Data.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Extended Saver.
class ExtendedSaver;
Definition at line 23 of file ExtendedSaver.php.
Member Function Documentation
Energine\share\gears\ExtendedSaver::getPK () protected
Get primary key.
Returns
string
Definition at line 66 of file ExtendedSaver.php.
Referenced by Energine\share\gears\ExtendedSaver\save(), and Energine\apps\gears\NewsEditorSaver\setData().
{
         return $this->pk;
     }
Energine\share\gears\ExtendedSaver::getTableName () protected
Get main table name.
Returns
string
Definition at line 57 of file ExtendedSaver.php.
Referenced by Energine\share\gears\DivisionSaver\save(), and Energine\share\gears\ExtendedSaver\save().
{
         return $this->mainTableName;
     }
Energine\share\gears\ExtendedSaver::save ()
Save data into the table of uploads and tags.
Definition at line 73 of file ExtendedSaver.php.
{
         $result = parent::save();
         $entityID = ($this->getMode() == QAL::INSERT) ? $result
             : $this->getData()->getFieldByName($this->pk)->getRowData(0);
         $tm = new TagManager($this->dataDescription, $this->data, $this->mainTableName);
         $tm->save($entityID);
         // обновление записей из _uploads таблицы, в которых PK = NULL по ID сессии
         if ($result && $this->dbh->tableExists($this->getTableName() . AttachmentManager::ATTACH_TABLE_SUFFIX)) {
             $id = (is_int($result)) ? $result : (int)$_POST[$this->getTableName()][$this->getPK()];
             //throw new SystemException($id);
             $this->dbh->modify(
                 QAL::UPDATE,
                 $this->getTableName() . AttachmentManager::ATTACH_TABLE_SUFFIX,
                 array(
                     $this->getPK() => $id
                 ),
                 array(
                     $this->getPK() => null,
                     'session_id' => session_id()
                 )
             );
         }
         return $result;
     }
Energine\share\gears\ExtendedSaver::setDataDescription (DataDescription $dd)
Set data description and main table name.
Parameters
DataDescription $dd Data description.
Definition at line 41 of file ExtendedSaver.php.
{
         parent::setDataDescription($dd);
         foreach ($dd as $fieldName => $fieldInfo) {
             if ($fieldInfo->getPropertyValue('key') === true) {
                 $this->pk = $fieldName;
                 $this->mainTableName = $fieldInfo->getPropertyValue('tableName');
                 break;
             }
         }
     }
Member Data Documentation
string Energine\share\gears\ExtendedSaver::$mainTableName private
Main table name.
Definition at line 34 of file ExtendedSaver.php.
Referenced by Energine\share\gears\ExtendedSaver\getTableName().
string Energine\share\gears\ExtendedSaver::$pk private
Primary key of the table.
Definition at line 28 of file ExtendedSaver.php.
Referenced by Energine\share\gears\ExtendedSaver\getPK().
The documentation for this class was generated from the following file:
core/modules/share/gears/ExtendedSaver.php