Energine: Energine\share\gears\Cache Class Reference
Energine\share\gears\Cache Class Reference
File cache.
Public Member Functions
__construct ()
isEnabled ()
Get cache state.
store ($key, $value)
Store data in cache.
retrieve ($key)
Get data from cache.
dispose ($key)
Remove data from cache.
Public Attributes
const CACHE_DIR = '../cache/'
Path to the cache.
const TRANSLATIONS_KEY = 'translations'
Translation key.
const CLASS_STRUCTURE_KEY = 'class_structure'
Cache filename, that stores information about paths.
const DB_STRUCTURE_KEY = 'db_structure'
Cache filename, that stores an array with data base structure.
Private Member Functions
getCacheFileByKey ($key)
Get cache file by data key.
cacheFileExists ($key)
Check if cache file for specific data key exist.
Detailed Description
File cache.
class Cache;
Cache represent files placed in cache directory. Cache file name (without ".cache.php") is used as a key.
Definition at line 26 of file Cache.php.
Constructor & Destructor Documentation
Energine\share\gears\Cache::__construct ()
Definition at line 51 of file Cache.php.
{
         $this->enabled =
                 (bool)Object::_getConfigValue('site.cache')
                         && (!(bool)Object::_getConfigValue('site.debug'))
                         && is_dir(self::CACHE_DIR)
                         && is_writable(self::CACHE_DIR);
     }
Member Function Documentation
Energine\share\gears\Cache::cacheFileExists ($key) private
Check if cache file for specific data key exist.
Parameters
string $key Data key.
Returns
string|false
Definition at line 123 of file Cache.php.
Referenced by Energine\share\gears\Cache\dispose(), and Energine\share\gears\Cache\retrieve().
{
         if (file_exists($fileName = $this->getCacheFileByKey($key))) {
             return $fileName;
         }
         return false;
     }
Energine\share\gears\Cache::dispose ($key)
Remove data from cache.
Parameters
string $key Data key.
Definition at line 100 of file Cache.php.
{
         if ($fileName = $this->cacheFileExists($key)) {
             @unlink($fileName);
         }
     }
Energine\share\gears\Cache::getCacheFileByKey ($key) private
Get cache file by data key.
Parameters
string $key Data key.
Returns
string
Definition at line 112 of file Cache.php.
Referenced by Energine\share\gears\Cache\cacheFileExists(), and Energine\share\gears\Cache\store().
{
         return self::CACHE_DIR . str_replace(DIRECTORY_SEPARATOR, '_', $key) . '.cache.php';
     }
Energine\share\gears\Cache::isEnabled ()
Get cache state.
Returns
bool
Definition at line 64 of file Cache.php.
{
         return $this->enabled;
     }
Energine\share\gears\Cache::retrieve ($key)
Get data from cache.
Parameters
string $key Data key.
Returns
mixed
Definition at line 86 of file Cache.php.
{
         $result = null;
         if ($fileName = $this->cacheFileExists($key)) {
             $result = include_once($fileName);
         }
         return $result;
     }
Energine\share\gears\Cache::store ($key, $value)
Store data in cache.
Parameters
string $key Data key.
mixed $value Data value.
Returns
bool
Definition at line 75 of file Cache.php.
{
         $content = '<?php' . PHP_EOL . 'return ' . var_export($value, true) . ';';
         return (bool)file_put_contents($this->getCacheFileByKey($key), $content);
     }
Member Data Documentation
string Energine\share\gears\Cache::CACHE_DIR = '../cache/'
Path to the cache.
Definition at line 31 of file Cache.php.
string Energine\share\gears\Cache::CLASS_STRUCTURE_KEY = 'class_structure'
Cache filename, that stores information about paths.
Definition at line 44 of file Cache.php.
string Energine\share\gears\Cache::DB_STRUCTURE_KEY = 'db_structure'
Cache filename, that stores an array with data base structure.
Definition at line 49 of file Cache.php.
Referenced by Energine\share\gears\DBStructureInfo\__construct().
string Energine\share\gears\Cache::TRANSLATIONS_KEY = 'translations'
Translation key.
Deprecated:
Definition at line 38 of file Cache.php.
Referenced by Energine\forms\components\FormEditor\save(), and Energine\share\components\TranslationEditor\saveData().
The documentation for this class was generated from the following file:
core/modules/share/gears/Cache.php