Energine: Energine\share\components\DBDataSet Class Reference
Energine\share\components\DBDataSet Class Reference
Class that shows the data from data base.
Public Member Functions
__construct ($name, $module, array $params=null)
getTableName ()
Get table name.
getFilter ()
Get filter.
addFilterCondition ($filter)
Add filter condition.
getPK ()
Get filed name of primary key.
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Member Functions
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
loadDataDescription ()
Load data description.
loadData ()
Load data.
getDataLanguage ()
Get data language.
setTableName ($tableName)
Set table name.
setParam ($name, $value)
Set component parameter if such exist.
setFilter ($filter)
Set filter.
clearFilter ()
Reset filter.
getOrder ()
Get sort order.
setOrder (array $order)
Set sort order.
getLimit ()
Get limit.
setLimit (array $limit)
Set limit.
setPK ($primaryColumnName)
Set primary key.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
getFKData ($fkTableName, $fkKeyName)
Get data from linked table.
getTranslationTableName ()
Get table name with translations.
view ()
Show view form.
recordExists ($id, $fieldName=false)
Detect if the specific record exist.
buildJS ()
Create description of JS objects.
getPreviousState ()
Get previous state.
saveText ()
Save text.
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Private Member Functions
modify ($data)
Modify data set by adding the values from "m2m" table.
commonLoadData ()
Load data from the common table.
multiLoadData ()
Load multilingual data.
Private Attributes
$translationTableName = false
Table name with translations.
$pk = false
Primary key.
$filter = array()
Filter.
$order = null
Sort order.
$limit = null
Limit of the record's amount.
$previousState = false
Previous state.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Class that shows the data from data base.
class DBDataSet;
Definition at line 25 of file DBDataSet.php.
Constructor & Destructor Documentation
Energine\share\components\DBDataSet::__construct ($name, $module, array $params = null)
Parameters
string $name Component name.
string $module Module name.
array $params Component parameters.
Definition at line 80 of file DBDataSet.php.
{
         parent::__construct($name, $module, $params);
         $this->setType(self::COMPONENT_TYPE_LIST);
     }
Member Function Documentation
Energine\share\components\DBDataSet::addFilterCondition ($filter)
Add filter condition.
Definition at line 512 of file DBDataSet.php.
Referenced by Energine\share\components\SitePropertiesEditor\__construct(), Energine\apps\components\Feed\__construct(), Energine\apps\components\NewsFeed\__construct(), Energine\share\components\AttachmentEditor\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\share\gears\Filter\apply(), Energine\apps\components\NewsFeed\createCalendar(), Energine\apps\components\NewsFeed\createData(), Energine\share\components\Grid\deleteData(), Energine\share\components\FileRepository\editFile(), Energine\share\components\TagEditor\getRawData(), Energine\share\components\FileRepository\getRawData(), Energine\share\components\TagEditor\main(), Energine\apps\components\SimilarNews\main(), Energine\apps\components\NewsFeed\main(), Energine\share\components\FileRepository\putVideo(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), Energine\share\components\DBDataSet\setFilter(), Energine\apps\components\NewsFeed\tag(), Energine\apps\components\ExtendedFeed\view(), Energine\apps\components\NewsFeed\view(), Energine\apps\components\Feed\view(), and Energine\share\components\DBDataSet\view().
{
         if (is_numeric($filter)) {
             $filter = array($this->getTableName() . '.' . $this->getPK() => $filter);
         } elseif (is_string($filter)) {
             $filter = array($filter);
         }
         $this->filter = array_merge($this->filter, $filter);
     }
Energine\share\components\DBDataSet::buildJS () protected
Create description of JS objects.
Returns
DOMNode
Definition at line 740 of file DBDataSet.php.
Referenced by Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\WidgetsRepository\buildParamsForm(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\share\components\LinkingEditor\main(), Energine\share\components\FileRepository\putVideo(), and Energine\apps\components\NewsFeed\view().
{
         $result = parent::buildJS();
         if ((($this->getState() == 'view') && $this->document->isEditable() && $this->getParam('editable')) || in_array($this->getState(), array('add', 'edit'))) {
             if ($this->document->isEditable())
                 $this->setProperty('editable', 'editable');
             $this->addWYSIWYGTranslations();
             if ($config = E()->getConfigValue('wysiwyg.styles')) {
                 if (!$result) {
                     $result = $this->doc->createElement('javascript');
                 }
                 $JSObjectXML = $this->doc->createElement('variable');
                 $JSObjectXML->setAttribute('name', 'wysiwyg_styles');
                 $JSObjectXML->setAttribute('type', 'json');
                 foreach ($config as $key => $value) {
                     if (isset($value['caption'])) $config[$key]['caption'] = $this->translate($value['caption']);
                 }
                 $JSObjectXML->appendChild(new \DomText(json_encode($config)));
                 $result->appendChild($JSObjectXML);
             }
         }
         return $result;
     }
Energine\share\components\DBDataSet::clearFilter () final protected
Reset filter.
Attention
This is final.
Definition at line 526 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\setFilter().
{
         $this->filter = array();
     }
Energine\share\components\DBDataSet::commonLoadData () private
Load data from the common table.
Returns
array | bool
Definition at line 261 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\loadData().
{
         $dbFields = array();
         $data = false;
         foreach ($this->getDataDescription() as $fieldName => $field) {
             if (is_null($field->getPropertyValue('customField')) && ($field->getType() != FieldDescription::FIELD_TYPE_TAB)) {
                 if (
                 ($field->getPropertyValue('origType') && ($field->getType() == FieldDescription::FIELD_TYPE_BOOL))
                 ) {
                     $fieldName = ' IF((' . $fieldName . ' IS NOT NULL) AND (' . $fieldName . ' <> ""), 1, 0) AS ' . $fieldName;
                 }
                 array_push($dbFields, $fieldName);
             }
         }
         //
         if (!empty($dbFields)) {
             if ($this->getType() == self::COMPONENT_TYPE_FORM_ADD) {
                 $dbFields = array_flip($dbFields);
                 foreach ($dbFields as $key => $value) {
                     $dbFields[$key] = '';
                 }
                 $res = array($dbFields);
             } else {
                 $res = $this->dbh->select($this->getTableName(), (($this->pager) ? ' SQL_CALC_FOUND_ROWS '
                         : '') . implode(',', $dbFields), $this->getFilter(), $this->getOrder(), $this->getLimit());
             }
             if (is_array($res)) {
                 $data = $res;
                 if ($this->pager) {
                     if (!($recordsCount = simplifyDBResult($this->dbh->selectRequest('SELECT FOUND_ROWS() as c'), 'c', true))) {
                         $recordsCount = 0;
                     }
                     $this->pager->setRecordsCount($recordsCount);
                 }
             }
         }
         return $data;
     }
Energine\share\components\DBDataSet::createBuilder () protected
Create builder.
Returns
AbstractBuilder
Definition at line 633 of file DBDataSet.php.
Referenced by Energine\share\components\FileRepository\add(), Energine\share\components\FileRepository\addDir(), Energine\share\components\FileRepository\editDir(), Energine\share\components\FileRepository\editFile(), Energine\user\components\UserProfile\error(), Energine\share\components\FileRepository\putVideo(), Energine\user\components\UserProfile\success(), Energine\user\components\Register\success(), Energine\apps\components\FeedbackForm\success(), and Energine\forms\components\Form\success().
{
         if (!$this->getTranslationTableName()) {
             $result = parent::createBuilder();
         } else {
             $result = new MultiLanguageBuilder();
         }
         return $result;
     }
Energine\share\components\DBDataSet::createDataDescription () protected
Create data description.
Returns
DataDescription
Exceptions
SystemException 'ERR_DEV_LOAD_DATA_DESCR_IS_FUNCTION'
Definition at line 645 of file DBDataSet.php.
Referenced by Energine\apps\components\ExtendedFeed\createDataDescription().
{
         $result = parent::createDataDescription();
         foreach ($result as $fieldMetaData) {
             $keyInfo = $fieldMetaData->getPropertyValue('key');
             $values = false;
             //
             if (is_array($keyInfo)) {
                 if ($fieldMetaData->getType() == FieldDescription::FIELD_TYPE_SELECT) {
                     $fkTableName = $keyInfo['tableName'];
                     $fkKeyName = $keyInfo['fieldName'];
                     //
                     $values = $this->getFKData($fkTableName, $fkKeyName);
                 } elseif ($fieldMetaData->getType() == FieldDescription::FIELD_TYPE_MULTI) {
                     $m2mTableName = $keyInfo['tableName'];
                     $m2mPKName = $keyInfo['fieldName'];
                     //
                     if ($this->dbh->tableExists($m2mTableName)) {
                         $tableInfo = $this->dbh->getColumnsInfo($m2mTableName);
                         unset($tableInfo[$m2mPKName]);
                         $m2mValueFieldInfo = current($tableInfo);
                         if (isset($m2mValueFieldInfo['key']) && is_array($m2mValueFieldInfo)) {
                             $values = $this->getFKData($m2mValueFieldInfo['key']['tableName'], $m2mValueFieldInfo['key']['fieldName']);
                         }
                     }
                     //
                 }
                 if (!empty($values))
                     call_user_func_array(array($fieldMetaData, 'loadAvailableValues'), $values);
             }
         }
         return $result;
     }
Energine\share\components\DBDataSet::defineParams () protected
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
Returns
array
Definition at line 88 of file DBDataSet.php.
{
         return array_merge(
             parent::defineParams(),
             array(
                 'tableName' => false,
                 'onlyCurrentLang' => false,
                 'editable' => false
             )
         );
     }
Energine\share\components\DBDataSet::getDataLanguage () protected
Get data language.
Returns
int|false
Definition at line 154 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\multiLoadData().
{
         $result = false;
         if ($this->getParam('onlyCurrentLang')) {
             $result = E()->getLanguage()->getCurrent();
         }
         return $result;
     }
Energine\share\components\DBDataSet::getFilter () final
Get filter.
Returns
mixed
Attention
This is final.
Definition at line 489 of file DBDataSet.php.
Referenced by Energine\user\components\RoleEditor\buildDivRightsData(), Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\share\components\DBDataSet\commonLoadData(), Energine\apps\components\NewsFeed\createCalendar(), Energine\user\components\UserEditor\createData(), Energine\share\components\Grid\deleteData(), Energine\share\components\LinkingEditor\main(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\DivisionEditor\save(), Energine\user\components\UserEditor\saveData(), Energine\apps\components\FeedbackForm\saveData(), Energine\forms\components\Form\saveData(), Energine\user\components\RoleEditor\saveData(), Energine\share\components\AttachmentEditor\saveData(), and Energine\share\components\Grid\saveData().
{
         return $this->filter;
     }
Energine\share\components\DBDataSet::getFKData ($fkTableName, $fkKeyName) protected
Get data from linked table.
Parameters
string $fkTableName Linked table name.
string $fkKeyName Key name.
Returns
array
Definition at line 687 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\createDataDescription().
{
         return $this->dbh->getForeignKeyData($fkTableName, $fkKeyName, E()->getLanguage()->getCurrent());
     }
Energine\share\components\DBDataSet::getLimit () final protected
Get limit.
Returns
array
Attention
This is final.
Definition at line 575 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\commonLoadData(), and Energine\share\components\DBDataSet\multiLoadData().
{
         return $this->limit;
     }
Energine\share\components\DBDataSet::getOrder () final protected
Get sort order.
Returns
array
Attention
This is final.
Definition at line 537 of file DBDataSet.php.
Referenced by Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\DBDataSet\commonLoadData(), and Energine\share\components\DBDataSet\multiLoadData().
{
         if (is_null($this->order)) {
             $this->order = false;
             $columns = $this->dbh->getColumnsInfo($this->getTableName());
             foreach (array_keys($columns) as $columnName) {
                 if (strpos($columnName, '_order_num')) {
                     $this->setOrder(array($columnName => QAL::ASC));
                     break;
                 }
             }
         }
         return $this->order;
     }
Energine\share\components\DBDataSet::getPK () final
Get filed name of primary key.
Returns
string
Attention
This is final.
Exceptions
SystemException 'ERR_DEV_NO_PK'
Definition at line 600 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\addFilterCondition(), Energine\share\components\Grid\attachments(), Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\share\components\Grid\deleteData(), Energine\share\components\DivisionEditor\deleteData(), Energine\share\components\Grid\exportCSV(), Energine\share\components\Grid\linkExtraManagers(), Energine\share\components\DBDataSet\loadDataDescription(), Energine\apps\components\SimilarNews\main(), Energine\apps\components\ExtendedFeed\main(), Energine\share\components\DBDataSet\modify(), Energine\share\components\Grid\moveTo(), Energine\share\components\DBDataSet\multiLoadData(), Energine\apps\components\VoteEditor\prepare(), Energine\share\components\SiteEditor\prepare(), Energine\apps\components\ExtendedFeedEditor\publish(), Energine\share\components\DBDataSet\recordExists(), Energine\share\components\FileRepository\save(), Energine\share\components\Grid\save(), Energine\share\components\LanguageEditor\saveData(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), Energine\share\components\FileRepository\saveDir(), Energine\share\components\AttachmentEditor\savequickupload(), Energine\share\components\DBDataSet\saveText(), Energine\apps\components\FeedbackForm\send(), Energine\apps\components\NewsFeed\view(), and Energine\share\components\DBDataSet\view().
{
         if (!$this->pk) {
             $res = $this->dbh->getColumnsInfo($this->getTableName());
             if (is_array($res)) {
                 foreach ($res as $fieldName => $fieldInfo) {
                     if ($fieldInfo['key'] === true) {
                         $this->pk = $fieldName;
                     }
                 }
                 if (!isset($this->pk)) {
                     throw new SystemException('ERR_DEV_NO_PK', SystemException::ERR_DEVELOPER);
                 }
             } else {
                 throw new SystemException('ERR_DEV_NO_PK', SystemException::ERR_DEVELOPER);
             }
         }
         return $this->pk;
     }
Energine\share\components\DBDataSet::getPreviousState () final protected
Get previous state.
Returns
string
Exceptions
SystemException ERR_NO_COMPONENT_ACTION
Attention
This is final.
Definition at line 776 of file DBDataSet.php.
Referenced by Energine\user\components\UserEditor\saveData(), Energine\apps\components\FeedbackForm\saveData(), Energine\forms\components\Form\saveData(), Energine\share\components\AttachmentEditor\saveData(), and Energine\share\components\Grid\saveData().
{
         if (!$this->previousState) {
             if (!isset($_POST['componentAction'])) {
                 throw new SystemException('ERR_NO_COMPONENT_ACTION', SystemException::ERR_CRITICAL);
             } else {
                 $this->previousState = $_POST['componentAction'];
             }
         }
         return $this->previousState;
     }
Energine\share\components\DBDataSet::getTableName () final
Get table name.
Returns
string
Attention
This is final.
Exceptions
SystemException 'ERR_DEV_NO_TABLENAME'
Definition at line 474 of file DBDataSet.php.
Referenced by Energine\share\components\AttachmentEditor\__construct(), Energine\share\components\FileRepository\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\user\components\UserEditor\activate(), Energine\apps\components\ExtendedFeedEditor\add(), Energine\share\components\Grid\add(), Energine\share\components\DivisionEditor\add(), Energine\share\components\DBDataSet\addFilterCondition(), Energine\share\components\Grid\attachments(), Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\share\components\DBDataSet\commonLoadData(), Energine\apps\components\NewsFeed\createCalendar(), Energine\apps\components\ExtendedFeed\createDataDescription(), Energine\apps\components\Feed\createDataDescription(), Energine\share\components\DivisionEditor\createDataDescription(), Energine\share\components\Grid\createFilter(), Energine\share\components\Grid\deleteData(), Energine\apps\components\ExtendedFeedEditor\edit(), Energine\share\components\Grid\edit(), Energine\share\components\DivisionEditor\edit(), Energine\share\components\FileRepository\editDir(), Energine\share\components\Grid\exportCSV(), Energine\share\components\Grid\fkEditor(), Energine\share\components\Grid\fkValues(), Energine\share\components\Grid\generateThumbnail(), Energine\share\components\DBDataSet\getOrder(), Energine\share\components\Grid\getOrderColumn(), Energine\share\components\DBDataSet\getPK(), Energine\share\components\FileRepository\getRawData(), Energine\apps\components\SimilarNews\getSimilarNewsIDs(), Energine\share\components\Grid\linkExtraManagers(), Energine\user\components\RoleEditor\loadData(), Energine\share\components\LanguageEditor\loadData(), Energine\share\components\Grid\loadData(), Energine\share\components\DBDataSet\loadDataDescription(), Energine\apps\components\SimilarNews\main(), Energine\apps\components\ExtendedFeed\main(), Energine\share\components\Grid\moveTo(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\SiteEditor\prepare(), Energine\apps\components\ExtendedFeedEditor\publish(), Energine\share\components\DBDataSet\recordExists(), Energine\share\components\DivisionEditor\resetTemplates(), Energine\user\components\UserProfile\save(), Energine\user\components\Register\save(), Energine\share\components\FileRepository\save(), Energine\share\components\DivisionEditor\save(), Energine\share\components\Grid\save(), Energine\share\components\TranslationEditor\saveData(), Energine\user\components\UserEditor\saveData(), Energine\apps\components\FeedEditor\saveData(), Energine\share\components\DomainEditor\saveData(), Energine\share\components\LanguageEditor\saveData(), Energine\forms\components\Form\saveData(), Energine\user\components\Register\saveData(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), Energine\share\components\FileRepository\saveDir(), Energine\share\components\AttachmentEditor\savequickupload(), Energine\apps\components\FeedbackForm\send(), Energine\forms\components\Form\send(), Energine\apps\components\NewsFeed\tag(), Energine\share\components\FileRepository\uploadZip(), Energine\apps\components\ExtendedFeed\view(), Energine\apps\components\NewsFeed\view(), and Energine\share\components\DBDataSet\view().
{
         if (!$this->getParam('tableName')) {
             throw new SystemException('ERR_DEV_NO_TABLENAME', SystemException::ERR_DEVELOPER);
         }
         return $this->getParam('tableName');
     }
Energine\share\components\DBDataSet::getTranslationTableName () protected
Get table name with translations.
Returns
string
Definition at line 696 of file DBDataSet.php.
Referenced by Energine\share\components\DivisionEditor\add(), Energine\share\components\DBDataSet\createBuilder(), Energine\share\components\Grid\createFilter(), Energine\share\components\Grid\exportCSV(), Energine\share\components\Grid\fkEditor(), Energine\share\components\Grid\fkValues(), Energine\share\components\DBDataSet\loadData(), Energine\share\components\Grid\loadData(), Energine\share\components\DBDataSet\loadDataDescription(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\TranslationEditor\saveData(), and Energine\share\components\DBDataSet\saveText().
{
         return $this->translationTableName;
     }
Energine\share\components\DBDataSet::loadData () protected
Load data.
Returns
mixed
Definition at line 132 of file DBDataSet.php.
{
         if ($this->pager) {
             // pager  --    ,
             $this->setLimit($this->pager->getLimit());
         }
         //     ,
         //   -   ()
         $data = $this->modify(
             (!$this->getTranslationTableName()) ?
                 $this->commonLoadData() :
                 $this->multiLoadData()
         );
         return $data;
     }
Energine\share\components\DBDataSet::loadDataDescription () protected
Load data description.
Use this to load external data description (not from configurations).
Returns
mixed
Exceptions
SystemException 'ERR_DEV_NO_LANG_ID'
It returns the information about columns in main table and table of translations.
Definition at line 106 of file DBDataSet.php.
Referenced by Energine\apps\components\FeedbackForm\saveData(), Energine\forms\components\Form\saveData(), and Energine\share\components\Grid\saveData().
{
         $result = $this->dbh->getColumnsInfo($this->getTableName());
         if ($this->getTranslationTableName()) {
             $transColumnsDescription = $this->dbh->getColumnsInfo($this->getTranslationTableName());
             foreach (array_keys($transColumnsDescription) as $fieldName) {
                 //            isMultiLanguage
                 if (!in_array($fieldName, array($this->getPK(), 'lang_id'))) {
                     $transColumnsDescription[$fieldName]['isMultilanguage'] = true;
                 } elseif ($fieldName === 'lang_id' && $this->getPK() !== 'lang_id') {
                     $transColumnsDescription[$fieldName]['languageID'] = true;
                 }
             }
             $result += $transColumnsDescription;
             if (isset($result['lang_id'])) {
                 $result['lang_id']['key'] = false;
             } else {
                 throw new SystemException('ERR_DEV_NO_LANG_ID', SystemException::ERR_DEVELOPER);
             }
         }
         return $result;
     }
Energine\share\components\DBDataSet::modify ($data) private
Modify data set by adding the values from "m2m" table.
Parameters
array $data Data.
Returns
array|false
Definition at line 168 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\loadData().
{
        if(is_array($data)){
            //
            $multiFields = $this->getDataDescription()->getFieldDescriptionsByType(FieldDescription::FIELD_TYPE_MULTI);
            //   2
            if (!empty($multiFields)) {
                $m2mData = array();
                $primaryKeyName = $this->getPK();
                $pks = simplifyDBResult($data, $primaryKeyName);
                //  $m2mData
                // array($MultiFieldName => array($pk => $values))
                foreach ($multiFields as $mfd) {
                    $relInfo = $mfd->getPropertyValue('key');
                    if (is_array($relInfo) && $this->dbh->tableExists($relInfo['tableName'])) {
                        $res = $this->dbh->select(
                            $relInfo['tableName'],
                            true,
                            array(
                                $primaryKeyName => $pks
                            )
                        );
                        if (is_array($res)) {
                            foreach ($res as $row) {
                                $pk = $row[$relInfo['fieldName']];
                                unset($row[$relInfo['fieldName']]);
                                $m2mData[$mfd->getName()][$pk][] = current($row);
                            }
                        }
                    }
                }
                //
                foreach ($data as $key => $row) {
                    //  multi
                    foreach ($m2mData as $fieldName => $m2mValues) {
                        //
                        if (array_key_exists($fieldName, $row)) {
                            //
                            foreach ($m2mValues as $pk => $values) {
                                if ($row[$primaryKeyName] == $pk) {
                                    $data[$key][$fieldName] = $values;
                                }
                            }
                        }
                    }
                }
            }
            $valueFields = $this->getDataDescription()->getFieldDescriptionsByType(FieldDescription::FIELD_TYPE_VALUE);
            if (!empty($valueFields)) {
                //
                foreach ($valueFields as $valueFieldName => $valueField) {
                    $relInfo = $valueField->getPropertyValue('key');
                    if (is_array($relInfo)) {
                        $langTable = $this->dbh->getTranslationTablename($relInfo['tableName']);
                        $relations[$valueFieldName] = array(
                            'table' => (!$langTable) ? $relInfo['tableName'] : $langTable,
                            'field' => $relInfo['fieldName'],
                            'lang' => ($langTable) ? E()->getLanguage()->getCurrent() : false,
                            'valueField' => substr($relInfo['fieldName'], 0, strrpos($relInfo['fieldName'], '_')) . '_name'
                        );
                        $cond = array(
                            $relations[$valueFieldName]['field'] => simplifyDBResult($data, $relations[$valueFieldName]['field'])
                        );
                        if ($relations[$valueFieldName]['lang']) {
                            $cond['lang_id'] = $relations[$valueFieldName]['lang'];
                        }
                        $values[$valueFieldName] = convertDBResult($this->dbh->select($relations[$valueFieldName]['table'], array($relations[$valueFieldName]['field'], $relations[$valueFieldName]['valueField']), $cond), $relations[$valueFieldName]['field'], true);
                    }
                }
                unset($valueFields, $langTable, $relInfo);
                foreach ($data as $key => $row) {
                    foreach ($row as $name => $value) {
                        if (in_array($name, array_keys($relations)) && array_key_exists($value, $values[$name])) {
                            $data[$key][$name] = array(
                                'id' => $value,
                                'value' => $values[$name][$value][$relations[$name]['valueField']]
                            );
                        }
                    }
                }
            }
        }
         return $data;
     }
Energine\share\components\DBDataSet::multiLoadData () private
Load multilingual data.
Returns
array|bool|mixed
Definition at line 305 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\loadData().
{
         $data = false;
         $lang = E()->getLanguage();
         $lang = $lang->getLanguages();
         $dbFields = array();
         $filter = $order = $limit = '';
         //      array('  ' => array(' '=>' . '), ' ' => array(' '=>' . '))
         foreach ($this->getDataDescription() as $fieldName => $field) {
             //       PK
             if (!$field->getPropertyValue('languageID') && $field->getPropertyValue('key') !== true) {
                 //
                 if (is_null($field->getPropertyValue('customField'))) {
                     //
                     if (
                     !($field->getPropertyValue('origType') && ($field->getType() == FieldDescription::FIELD_TYPE_BOOL))
                     ) {
                         $dbFields[$field->getPropertyValue('tableName')][$fieldName] = $field->getPropertyValue('tableName') . '.' . $fieldName;
                     } //
                     else {
                         $dbFields[$field->getPropertyValue('tableName')][$fieldName] =
                             ' IF((' . $field->getPropertyValue('tableName') . '.' . $fieldName . ' IS NOT NULL) AND (' . $field->getPropertyValue('tableName') . '.' . $fieldName . ' <> ""), 1, 0) AS ' . $fieldName;
                     }
                 }
             }
         }
         $filterCondition = $this->getFilter();
         if (!empty($filterCondition)) {
             $filter = $this->dbh->buildWhereCondition($filterCondition) . ($this->getParam('onlyCurrentLang')
                     ? ' AND lang_id = ' . $this->getDataLanguage() : '');
         } elseif ($this->getDataLanguage() && $this->getParam('onlyCurrentLang')) {
             $filter = ' WHERE lang_id = ' . $this->getDataLanguage();
         }
         if ($this->getOrder()) {
             //inspect($this->getOrder());
             $order = $this->dbh->buildOrderCondition($this->getOrder());
         }
         if (!is_null($this->getLimit())) {
             $limit = $this->getLimit();
             $limit = $this->dbh->buildLimitStatement($limit);
         }
         //
         if ($this->getType() != self::COMPONENT_TYPE_FORM_ADD) {
             $request = sprintf(
                 'SELECT ' . (($this->pager) ? ' SQL_CALC_FOUND_ROWS ' : '') .
                 ' %s.%s, %s.lang_id,
                    %s
                    %s
                    FROM %1$s
                    LEFT JOIN %3$s ON %3$s.%2$s = %1$s.%2$s
                    %s
                    %s
                    %s
                    ',
                 $this->getTableName(), $this->getPK(), $this->getTranslationTableName(),
                 (isset($dbFields[$this->getTableName()])) ? implode(',', $dbFields[$this->getTableName()]) : '',
                 isset($dbFields[$this->getTranslationTableName()]) ? ((isset($dbFields[$this->getTableName()])) ? ','
                         : '') . implode(',', $dbFields[$this->getTranslationTableName()]) : '',
                 $filter,
                 $order,
                 $limit
             );
             $data = $this->dbh->selectRequest($request);
             if ($this->pager) {
                 if (!($recordsCount = simplifyDBResult($this->dbh->selectRequest('SELECT FOUND_ROWS() as c'), 'c', true))) {
                     $recordsCount = 0;
                 }
                 $this->pager->setRecordsCount($recordsCount);
             }
             //
             if (is_array($data) && (!$this->getDataLanguage() || $this->getDataLanguage() && !$this->getParam('onlyCurrentLang') && isset($dbFields[$this->getTranslationTableName()]))) {
                 //
                 foreach ($data as $row) {
                     $matrix[$row[$this->getPK()]][$row['lang_id']] = $row;
                 }
                 //
                 //      null
                 foreach (array_keys($dbFields[$this->getTranslationTableName()]) as $fieldName) {
                     $translationColumns[] = 'NULL as ' . $fieldName;
                 }
                 $request = sprintf('
                     SELECT %s, %s %s
                     FROM %s
                     WHERE %s IN(%s)
                 ',
                     $this->getPK(), (isset($dbFields[$this->getTableName()]))
                         ? implode(',', $dbFields[$this->getTableName()]) . ','
                         : '', implode(',', $translationColumns),
                     $this->getTableName(),
                     $this->getPK(), implode(',', array_keys($matrix)));
                 $res = $this->dbh->selectRequest($request);
                 foreach ($res as $row) {
                     $template[$row[$this->getPK()]] = $row;
                 }
                 $data = array();
                 if ($this->getDataLanguage() && !$this->getParam('onlyCurrentLang')) {
                     $lang = array($this->getDataLanguage() => $lang[$this->getDataLanguage()]);
                 }
                 foreach ($matrix as $ltagID => $langVersions) {
                     foreach (array_keys($lang) as $langID) {
                         if (isset($langVersions[$langID])) {
                             $data[] = $langVersions[$langID];
                         } else {
                             $data[arrayPush($data, $template[$ltagID])]['lang_id'] = $langID;
                         }
                     }
                 }
             }
         } else {
             $i = 0;
             $dbFields = array_merge(
                 (isset($dbFields[$this->getTableName()])) ? array_keys($dbFields[$this->getTableName()]) : array(),
                 array_keys($dbFields[$this->getTranslationTableName()])
             );
             $dbFields = array_flip($dbFields);
             foreach ($dbFields as $key => $value) {
                 $dbFields[$key] = '';
             }
             foreach (array_keys($lang) as $langID) {
                 $data[$i][$this->getPK()] = null;
                 $data[$i]['lang_id'] = $langID;
                 $data[$i] = array_merge($data[$i], $dbFields);
                 $i++;
             }
         }
         return $data;
     }
Energine\share\components\DBDataSet::recordExists ($id, $fieldName = false) protected
Detect if the specific record exist.
Parameters
string $id ID.
mixed $fieldName Field name.
Returns
bool
Definition at line 728 of file DBDataSet.php.
Referenced by Energine\user\components\UserEditor\activate(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\delete(), Energine\share\components\Grid\edit(), Energine\share\components\DivisionEditor\getProperties(), Energine\share\components\Grid\move(), and Energine\share\components\DBDataSet\view().
{
         if (!$fieldName) {
             $fieldName = $this->getPK();
         }
         $res = $this->dbh->select($this->getTableName(), array($fieldName), array($fieldName => $id));
         return is_array($res);
     }
Energine\share\components\DBDataSet::saveText () protected
Save text.
Definition at line 791 of file DBDataSet.php.
{
         $result = '';
         if ($this->getParam('editable') && isset($_POST['ID']) && isset($_POST['num']) && isset($_POST['data'])) {
             $result = DataSet::cleanupHTML($_POST['data']);
             $langID = E()->getLanguage()->getCurrent();
             $entityId = (int)$_POST['ID'];
             $field = $_POST['num'];
             $this->dbh->modify(gears\QAL::UPDATE, $this->getTranslationTableName(), array($field => $result), array('lang_id' => $langID, $this->getPK() => $entityId));
         }
         $this->response->setHeader('Content-Type', 'application/xml; charset=utf-8');
         $this->response->write($result);
         $this->response->commit();
     }
Energine\share\components\DBDataSet::setFilter ($filter) final protected
Set filter.
Parameters
mixed $filter Filter.
Attention
This is final.
See also
QAL::select()
Definition at line 502 of file DBDataSet.php.
Referenced by Energine\apps\components\Branding\__construct(), Energine\share\components\DomainEditor\__construct(), Energine\apps\components\VoteQuestionEditor\__construct(), Energine\share\components\FileRepository\__construct(), Energine\share\components\LinkingEditor\changeOrder(), Energine\share\components\DivisionEditor\deleteData(), Energine\share\components\Grid\edit(), Energine\share\components\FileRepository\editDir(), Energine\share\components\DivisionEditor\getProperties(), Energine\share\components\DivisionEditor\getRawData(), Energine\user\components\UserProfile\main(), Energine\share\components\DivisionEditor\main(), Energine\share\components\AttachmentEditor\saveData(), Energine\share\components\Grid\saveData(), and Energine\share\components\DivisionEditor\selector().
{
         $this->clearFilter();
         if (!empty($filter)) {
             $this->addFilterCondition($filter);
         }
     }
Energine\share\components\DBDataSet::setLimit (array $limit) final protected
Set limit.
Parameters
array $limit Limit.
Attention
This is final.
Definition at line 586 of file DBDataSet.php.
Referenced by Energine\apps\components\Feed\__construct(), and Energine\share\components\DBDataSet\loadData().
{
         $this->limit = $limit;
     }
Energine\share\components\DBDataSet::setOrder (array $order) final protected
Set sort order.
Parameters
array $order Sort order in the form
array($orderFieldName => $orderDirection)
Attention
This is final.
Definition at line 559 of file DBDataSet.php.
Referenced by Energine\apps\components\NewsEditor\__construct(), Energine\apps\components\FeedbackList\__construct(), Energine\share\components\TranslationEditor\__construct(), Energine\share\components\WidgetsRepository\__construct(), Energine\forms\components\FormResults\__construct(), Energine\apps\components\Feed\__construct(), Energine\apps\components\NewsFeed\__construct(), Energine\forms\components\FormsEditor\__construct(), Energine\comments\components\CommentsEditor\__construct(), Energine\share\components\FileRepository\__construct(), Energine\share\components\Grid\applyUserSort(), Energine\share\components\DBDataSet\getOrder(), Energine\apps\components\SimilarNews\main(), and Energine\share\components\Grid\setOrderColumn().
{
         /*$orderDirection = strtoupper($orderDirection);
         if (!in_array($orderDirection, array(QAL::ASC, QAL::DESC))) {
             $orderDirection = QAL::ASC;
         }
         */
         $this->order = $order;
     }
Energine\share\components\DBDataSet::setParam ($name, $value) protected
Set component parameter if such exist.
If this parameter is not exist SystemException will be generated.
Parameters
string $name Parameter name.
mixed $value parameter value.
Exceptions
SystemException 'ERR_DEV_NO_PARAM'
Definition at line 456 of file DBDataSet.php.
Referenced by Energine\apps\components\Branding\__construct(), Energine\apps\components\Feed\__construct(), Energine\comments\components\CommentsEditor\__construct(), Energine\apps\components\SimilarNews\__construct(), Energine\share\components\DivisionEditor\__construct(), Energine\share\components\Grid\__construct(), Energine\share\components\Grid\getRawData(), Energine\share\components\DivisionEditor\getRawData(), Energine\share\components\Grid\printData(), Energine\apps\components\NewsFeed\rss(), and Energine\share\components\DBDataSet\setTableName().
{
         //   tableName
         if ($name == 'tableName') {
             $this->translationTableName = $this->dbh->getTranslationTablename($value);
         }
         parent::setParam($name, $value);
     }
Energine\share\components\DBDataSet::setPK ($primaryColumnName) final protected
Set primary key.
Parameters
string $primaryColumnName Primary column name.
Definition at line 626 of file DBDataSet.php.
{
         $this->pk = $primaryColumnName;
     }
Energine\share\components\DBDataSet::setTableName ($tableName) protected
Set table name.
Parameters
string $tableName Table name.
Definition at line 449 of file DBDataSet.php.
Referenced by Energine\apps\components\Branding\__construct(), Energine\apps\components\NewsEditor\__construct(), Energine\share\components\LanguageEditor\__construct(), Energine\share\components\SitePropertiesEditor\__construct(), Energine\share\components\TagEditor\__construct(), Energine\share\components\DomainEditor\__construct(), Energine\share\components\TranslationEditor\__construct(), Energine\user\components\UserEditor\__construct(), Energine\user\components\UserProfile\__construct(), Energine\apps\components\VoteQuestionEditor\__construct(), Energine\forms\components\SelectorValuesEditor\__construct(), Energine\forms\components\FormResults\__construct(), Energine\share\components\WidgetsRepository\__construct(), Energine\user\components\Register\__construct(), Energine\apps\components\VoteEditor\__construct(), Energine\apps\components\NewsFeed\__construct(), Energine\user\components\RoleEditor\__construct(), Energine\forms\components\FormsEditor\__construct(), Energine\forms\components\Form\__construct(), Energine\share\components\SiteEditor\__construct(), Energine\share\components\FileRepository\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\share\components\DivisionEditor\__construct(), Energine\comments\components\CommentsEditor\changeTableName(), and Energine\apps\components\SimilarNews\main().
{
         $this->setParam('tableName', $tableName);
     }
Energine\share\components\DBDataSet::view () protected
Show view form.
Exceptions
SystemException 'ERR_404'
Definition at line 705 of file DBDataSet.php.
Referenced by Energine\apps\components\ExtendedFeed\view().
{
         $this->setType(self::COMPONENT_TYPE_FORM);
         //$this->addCrumb('TXT_VIEW_ITEM');
         $id = $this->getStateParams();
         list($id) = $id;
         if (!$this->recordExists($id)) {
             throw new SystemException('ERR_404', SystemException::ERR_404);
         }
         $this->addFilterCondition(array($this->getTableName() . '.' . $this->getPK() => $id));
         $this->prepare();
         foreach ($this->getDataDescription() as $fieldDescription) {
             $fieldDescription->setMode(FieldDescription::FIELD_MODE_READ);
         }
     }
Member Data Documentation
array Energine\share\components\DBDataSet::$filter = array() private
Filter.
Definition at line 42 of file DBDataSet.php.
Referenced by Energine\share\components\DomainEditor\__construct(), Energine\apps\components\VoteQuestionEditor\__construct(), Energine\forms\components\Form\__construct(), Energine\share\components\DBDataSet\addFilterCondition(), Energine\share\components\Grid\applyUserFilter(), Energine\share\components\Grid\generateThumbnail(), Energine\share\components\DBDataSet\getFilter(), Energine\comments\components\CommentsEditor\getForeignKeyData(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\DivisionEditor\resetTemplates(), and Energine\share\components\DBDataSet\setFilter().
array Energine\share\components\DBDataSet::$limit = null private
Limit of the record's amount.
Definition at line 54 of file DBDataSet.php.
Referenced by Energine\apps\components\Feed\__construct(), Energine\share\components\DBDataSet\getLimit(), Energine\share\components\DBDataSet\multiLoadData(), and Energine\share\components\DBDataSet\setLimit().
mixed Energine\share\components\DBDataSet::$order = null private
Sort order.
Definition at line 48 of file DBDataSet.php.
Referenced by Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\DBDataSet\getOrder(), Energine\share\components\DBDataSet\multiLoadData(), and Energine\share\components\DBDataSet\setOrder().
string Energine\share\components\DBDataSet::$pk = false private
Primary key.
Definition at line 36 of file DBDataSet.php.
Referenced by Energine\share\components\AttachmentEditor\__construct(), Energine\share\components\DBDataSet\getPK(), Energine\share\components\DBDataSet\modify(), Energine\share\components\FileRepository\save(), and Energine\share\components\AttachmentEditor\saveData().
string Energine\share\components\DBDataSet::$previousState = false private
Previous state.
Note
This is used by saving.
Definition at line 62 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\getPreviousState().
string Energine\share\components\DBDataSet::$translationTableName = false private
Table name with translations.
Definition at line 30 of file DBDataSet.php.
Referenced by Energine\share\components\DBDataSet\getTranslationTableName().
The documentation for this class was generated from the following file:
core/modules/share/components/DBDataSet.php