Energine: Energine\share\gears\Field Class Reference
Energine\share\gears\Field Class Reference
Data field.
Public Member Functions
__construct ($name)
getName ()
Get the name.
setData ($data, $setForAll=false)
Set data for the field.
getData ()
Get field data.
getRowData ($rowIndex)
Get data from specific row.
removeRowData ($rowIndex)
Remove data from specific row.
addRowData ($data, $toEnd=true)
Add new data row.
setRowData ($rowIndex, $newData)
Set the data for specific row.
setRights ($rights)
Set rights for the field.
getRights ()
Get rights for the field.
getRowCount ()
Get the total amount of the rows.
setRowProperty ($index, $propertyName, $propertyValue)
Set additional property for the specific row.
getRowProperty ($index, $propertyName)
Get the additional property value of the specific row.
getRowProperties ($index)
Get all additional properties of the specific row.
rewind ()
Rewind the Iterator to the first element.
current ()
Get current element.
key ()
Return the key of the current element.
next ()
Move forward to next element.
valid ()
Checks if current position is valid.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Private Attributes
$properties = array()
Set of additional properties.
$name
Field name.
$data = array()
Data of the field.
$rights
User rights for the field.
$currentIndex = 0
Index of the current element.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
Data field.
class Field;
Definition at line 25 of file Field.php.
Constructor & Destructor Documentation
Energine\share\gears\Field::__construct ($name)
Parameters
string $name Field name.
Definition at line 64 of file Field.php.
{
         $this->name = $name;
     }
Member Function Documentation
Energine\share\gears\Field::addRowData ($data, $toEnd = true)
Add new data row.
Parameters
mixed $data Data.
bool $toEnd Defines, whether the data should be appended to the end. Otherwise they will be appended to the beginning.
Definition at line 142 of file Field.php.
{
         if ($toEnd)
             $this->data[] = $data;
         else {
             array_unshift($this->data, $data);
         }
     }
Energine\share\gears\Field::current ()
Get current element.
Returns
mixed
http://php.net/manual/en/iterator.current.php
Implements Iterator.
Definition at line 238 of file Field.php.
{
         return $this->data[$this->currentIndex];
     }
Energine\share\gears\Field::getData ()
Get field data.
Returns
array
Definition at line 107 of file Field.php.
Referenced by Energine\share\gears\Field\getRowCount().
{
         return $this->data;
     }
Energine\share\gears\Field::getName ()
Get the name.
Returns
string
Definition at line 73 of file Field.php.
Referenced by Energine\share\gears\Data\addField(), and Energine\share\gears\Data\removeField().
{
         return $this->name;
     }
Energine\share\gears\Field::getRights ()
Get rights for the field.
Returns
int
Definition at line 181 of file Field.php.
{
         return $this->rights;
     }
Energine\share\gears\Field::getRowCount ()
Get the total amount of the rows.
Returns
int
Definition at line 190 of file Field.php.
Referenced by Energine\share\gears\Field\setData(), and Energine\share\gears\Field\valid().
{
         return sizeof($this->getData());
     }
Energine\share\gears\Field::getRowData ($rowIndex)
Get data from specific row.
Parameters
int $rowIndex Row index.
Returns
mixed
Definition at line 117 of file Field.php.
{
         $result = null;
         if (isset($this->data[$rowIndex])) {
             $result = $this->data[$rowIndex];
         }
         return $result;
     }
Energine\share\gears\Field::getRowProperties ($index)
Get all additional properties of the specific row.
Parameters
int $index Row index.
Returns
array
Definition at line 226 of file Field.php.
{
         $result = false;
         if (isset($this->properties[$index]) && !empty($this->properties[$index])) {
             $result = $this->properties[$index];
         }
         return $result;
     }
Energine\share\gears\Field::getRowProperty ($index, $propertyName)
Get the additional property value of the specific row.
Parameters
int $index Row index
string $propertyName Property value.
Returns
mixed
Definition at line 212 of file Field.php.
{
         $result = false;
         if (isset($this->properties[$index][$propertyName])) {
             $result = $this->properties[$index][$propertyName];
         }
         return $result;
     }
Energine\share\gears\Field::key ()
Return the key of the current element.
Returns
mixed
http://php.net/manual/en/iterator.key.php
Implements Iterator.
Definition at line 242 of file Field.php.
{
         return $this->currentIndex;
     }
Energine\share\gears\Field::next ()
Move forward to next element.
http://php.net/manual/en/iterator.next.php
Implements Iterator.
Definition at line 246 of file Field.php.
{
         $this->currentIndex++;
     }
Energine\share\gears\Field::removeRowData ($rowIndex)
Remove data from specific row.
Parameters
int $rowIndex Row index
Returns
bool
Definition at line 131 of file Field.php.
{
         unset($this->data[$rowIndex]);
         //$this->data = array_values($this->data);
     }
Energine\share\gears\Field::rewind ()
Rewind the Iterator to the first element.
Returns
bool
http://php.net/manual/en/iterator.rewind.php
Implements Iterator.
Definition at line 234 of file Field.php.
{
         $this->currentIndex = 0;
     }
Energine\share\gears\Field::setData ($data, $setForAll = false)
Set data for the field.
Parameters
mixed $data Data.
bool $setForAll Defines whether the data should be set for all rows (only for data overwriting). In the case that the field is newly created - fill it by using iterator.
Returns
Field
Definition at line 84 of file Field.php.
{
         if ($setForAll && $this->getRowCount()) {
             $data = array_fill(0, $this->getRowCount(), $data);
         }
         elseif ($setForAll && !$this->getRowCount() && !is_array($data)) {
             $rowData = $data;
             $data = array();
             for ($i = 0; $i < sizeof(E()->getLanguage()->getLanguages()); $i++) {
                 $data[$i] = $rowData;
             }
         }
         elseif (!is_array($data)) {
             $data = array($data);
         }
         $this->data = $data;
         return $this;
     }
Energine\share\gears\Field::setRights ($rights)
Set rights for the field.
Parameters
int $rights Rights.
Definition at line 172 of file Field.php.
{
         $this->rights = $rights;
     }
Energine\share\gears\Field::setRowData ($rowIndex, $newData)
Set the data for specific row.
Parameters
int $rowIndex Row index
mixed $newData New data.
Returns
boolean
Definition at line 158 of file Field.php.
Referenced by Energine\calendar\components\Calendar\createData().
{
         $result = false;
         //if (isset($this->data[$rowIndex])) {
         $this->data[$rowIndex] = $newData;
         $result = true;
         //}
         return $result;
     }
Energine\share\gears\Field::setRowProperty ($index, $propertyName, $propertyValue)
Set additional property for the specific row.
Parameters
int $index Row index
string $propertyName Property name.
mixed $propertyValue Property value.
Definition at line 201 of file Field.php.
{
         $this->properties[$index][$propertyName] = $propertyValue;
     }
Energine\share\gears\Field::valid ()
Checks if current position is valid.
Returns
bool
http://php.net/manual/en/iterator.valid.php
Implements Iterator.
Definition at line 250 of file Field.php.
{
         return ($this->currentIndex < $this->getRowCount());
     }
Member Data Documentation
int Energine\share\gears\Field::$currentIndex = 0 private
Index of the current element.
Used for iteration.
Definition at line 58 of file Field.php.
Referenced by Energine\share\gears\Field\current(), and Energine\share\gears\Field\key().
array Energine\share\gears\Field::$data = array() private
Data of the field.
Definition at line 42 of file Field.php.
Referenced by Energine\share\gears\Field\addRowData(), Energine\share\gears\Field\getData(), and Energine\share\gears\Field\setData().
string Energine\share\gears\Field::$name private
Field name.
Definition at line 36 of file Field.php.
Referenced by Energine\share\gears\Field\__construct(), and Energine\share\gears\Field\getName().
array Energine\share\gears\Field::$properties = array() private
Set of additional properties.
Definition at line 30 of file Field.php.
int Energine\share\gears\Field::$rights private
User rights for the field.
If the rights are not set, then the derived rights from FieldDescription will be used.
Definition at line 50 of file Field.php.
Referenced by Energine\share\gears\Field\getRights(), and Energine\share\gears\Field\setRights().
The documentation for this class was generated from the following file:
core/modules/share/gears/Field.php