Energine: Energine\share\gears\DocumentController Class Reference
Energine\share\gears\DocumentController Class Reference
DocumentController class is responsible for preparing the environment and running Document object.
Public Member Functions
getViewMode ()
Get the view mode.
run ()
Run processing.
getTransformer ()
Get transformer.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const TRANSFORM_HTML = 'html'
Constant string for transforming into the HTML.
const TRANSFORM_DEBUG_XML = 'debug'
const TRANSFORM_STRUCTURE_XML = 'struct'
const TRANSFORM_JSON = 'json'
const TRANSFORM_EMPTY = 'empty'
Empty transformation.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Member Functions
transform ($document)
Run transformation.
Static Private Attributes
static $transformer
XSLT transformer.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
DocumentController class is responsible for preparing the environment and running Document object.
class DocumentController;
Definition at line 27 of file DocumentController.php.
Member Function Documentation
Energine\share\gears\DocumentController::getTransformer ()
Get transformer.
The transformer type depends on one of reserved parameters in the GET request.
Returns
ITransformer
Definition at line 142 of file DocumentController.php.
Referenced by Energine\share\gears\DocumentController\transform().
{
         if (!isset(self::$transformer)) {
             $vm = $this->getViewMode();
             if ($vm == self::TRANSFORM_DEBUG_XML ||
                     $vm == self::TRANSFORM_STRUCTURE_XML
             ) {
                 self::$transformer = new XMLTransformer();
             }
             elseif ($vm == self::TRANSFORM_JSON) {
                 self::$transformer = new JSONTransformer();
             }
             else {
                 self::$transformer = new XSLTTransformer();
             }
         }
         return self::$transformer;
     }
Energine\share\gears\DocumentController::getViewMode ()
Get the view mode.
Returns
string
Definition at line 70 of file DocumentController.php.
Referenced by Energine\share\gears\DocumentController\getTransformer().
{
         $result = self::TRANSFORM_HTML;
         if (isset($_GET[self::TRANSFORM_DEBUG_XML]) &&
                 $this->getConfigValue('site.debug') ||
                 $this->getConfigValue('site.asXML')
         ) {
             $result = self::TRANSFORM_DEBUG_XML;
         }
         elseif (isset($_GET[self::TRANSFORM_HTML])) {
             $result = self::TRANSFORM_HTML;
         }
         elseif (isset($_GET[self::TRANSFORM_STRUCTURE_XML])) {
             $result = self::TRANSFORM_STRUCTURE_XML;
         }
         elseif (isset($_GET[self::TRANSFORM_JSON]) ||
                 (isset($_SERVER['HTTP_X_REQUEST']) &&
                         (strtolower($_SERVER['HTTP_X_REQUEST']) ==
                                 self::TRANSFORM_JSON))
         ) {
             $result = self::TRANSFORM_JSON;
         }
         return $result;
     }
Energine\share\gears\DocumentController::run ()
Run processing.
Prepare the environment
Create Document object and give him control
Transform XML-document
Definition at line 103 of file DocumentController.php.
{
         $language = E()->getLanguage();
         $language->setCurrent($language->getIDByAbbr(E()->getRequest()->getLang(), true));
         unset($language);
         try {
             $document = E()->getDocument();
             $document->loadComponents();
             $document->runComponents();
             if(($p = sizeof($path = E()->getRequest()->getPath())) != ($o = E()->getRequest()->getUsedSegments())){
 //                dump_log('URL: '.implode('/', $path). ' Path: '.$p.' Offset: '.$o, true);
                 throw new SystemException('ERR_404', SystemException::ERR_404, (string)E()->getRequest()->getURI());
             }
             $document->build();
         }
         catch (IRQ $int) {
             $document = E()->PageStructureDocument;
             if ($l = $int->getLayoutBlock()) {
                 $document->setLayout($l);
             }
             $document->setContent($int->getContentBlock());
             $document->build();
         }
         catch (SystemException $e) {
             $document = E()->ErrorDocument;
             $document->attachException($e);
             $document->build();
         }
         E()->getResponse()->write($this->transform($document));
     }
Energine\share\gears\DocumentController::transform ($document) private
Run transformation.
Transform XML-document in the output format and show the result to the client.
Parameters
Document $document XML-document.
Returns
mixed
Definition at line 168 of file DocumentController.php.
Referenced by Energine\share\gears\DocumentController\run().
{
         $this->getTransformer()->setDocument($document->getResult());
         $result = $this->getTransformer()->transform();
         return $result;
     }
Member Data Documentation
XSLTTransformer Energine\share\gears\DocumentController::$transformer static private
XSLT transformer.
Definition at line 64 of file DocumentController.php.
const Energine\share\gears\DocumentController::TRANSFORM_DEBUG_XML = 'debug'
Definition at line 38 of file DocumentController.php.
string Energine\share\gears\DocumentController::TRANSFORM_EMPTY = 'empty'
Empty transformation.
Note
The main idea of this constant was lost. Perhaps this is for the cases to return raw XML without XSLT transformation.
Definition at line 58 of file DocumentController.php.
string Energine\share\gears\DocumentController::TRANSFORM_HTML = 'html'
Constant string for transforming into the HTML.
Constant string for transforming into the JSON.
Constant string for transforming into the XML structure view format.
Constant string for transforming into the XML debugging view format.
Definition at line 32 of file DocumentController.php.
Referenced by Energine\share\gears\ErrorDocument\build(), and Energine\share\components\Grid\printData().
const Energine\share\gears\DocumentController::TRANSFORM_JSON = 'json'
Definition at line 50 of file DocumentController.php.
Referenced by Energine\share\gears\ErrorDocument\build().
const Energine\share\gears\DocumentController::TRANSFORM_STRUCTURE_XML = 'struct'
Definition at line 44 of file DocumentController.php.
Referenced by Energine\share\gears\Document\loadComponents().
The documentation for this class was generated from the following file:
core/modules/share/gears/DocumentController.php