Energine: Energine\share\gears\DataDescription Class Reference
Energine\share\gears\DataDescription Class Reference
Meta data.
Public Member Functions
__construct ()
load (array $columnsInfo)
Load the data descriptions received from the data base.
loadXML (\SimpleXMLElement $xmlDescr)
Load data descriptions from XML file.
addFieldDescription (FieldDescription $fieldDescription, $location= 'bottom', $targetFDName=null)
Add new field description.
removeFieldDescription (FieldDescription $fieldDescription)
Remove field description.
getFieldDescriptionByName ($name)
Get field description by field name.
getFieldDescriptionsByType ($types)
Get field descriptions by type.
getFieldDescriptionList ()
Get the list of field description names.
isEmpty ()
Check whether the field description array is empty.
intersect (DataDescription $otherDataDescr)
Intersect this data description with other object data description.
rewind ()
Rewind the Iterator to the first element.
current ()
Get current element.
key ()
Return the key of the current element.
next ()
Move forward to next element.
valid ()
Checks if current position is valid.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const FIELD_POSITION_AFTER = 'after'
Field position: 'after'.
const FIELD_POSITION_BEFORE = 'before'
Field position: 'before'.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Attributes
$fieldDescriptions
Meta data for fields.
$currentIndex = 0
Index of the current element (used for iteration).
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Meta data.
class DataDescription
Data description.
Definition at line 27 of file DataDescription.php.
Constructor & Destructor Documentation
Energine\share\gears\DataDescription::__construct ()
Definition at line 51 of file DataDescription.php.
{
         $this->fieldDescriptions = array();
     }
Member Function Documentation
Energine\share\gears\DataDescription::addFieldDescription (FieldDescription $fieldDescription, $location = 'bottom', $targetFDName = null)
Add new field description.
Parameters
FieldDescription $fieldDescription New field description.
string $location Description location.
string $targetFDName Target field description name.
Definition at line 93 of file DataDescription.php.
Referenced by Energine\comments\gears\CommentsHelper\createAndAddField(), Energine\share\gears\DataDescription\load(), and Energine\share\gears\DataDescription\loadXML().
{
         if($location == self::FIELD_POSITION_AFTER && $targetFDName && array_key_exists($targetFDName, $this->fieldDescriptions)){
             $this->fieldDescriptions = array_push_after($this->fieldDescriptions, array($fieldDescription->getName() => $fieldDescription), $targetFDName);
         }
        /* elseif($location == 'before' ){
         }*/
         else {
             $this->fieldDescriptions[$fieldDescription->getName()] = $fieldDescription;
         }
     }
Energine\share\gears\DataDescription::current ()
Get current element.
Returns
mixed
http://php.net/manual/en/iterator.current.php
Implements Iterator.
Definition at line 205 of file DataDescription.php.
{
         $fieldNames = $this->getFieldDescriptionList();
         return $this->fieldDescriptions[$fieldNames[$this->currentIndex]];
     }
Energine\share\gears\DataDescription::getFieldDescriptionByName ($name)
Get field description by field name.
Parameters
string $name Field name
Returns
FieldDescription|bool
Definition at line 122 of file DataDescription.php.
Referenced by Energine\share\gears\DataDescription\intersect().
{
         $fieldDescription = false;
         if (isset($this->fieldDescriptions[$name])) {
             $fieldDescription = $this->fieldDescriptions[$name];
         }
         return $fieldDescription;
     }
Energine\share\gears\DataDescription::getFieldDescriptionList ()
Get the list of field description names.
Returns
array
Todo:
Не очень красивый метод, нужно бы как то без него обойтись
Definition at line 154 of file DataDescription.php.
Referenced by Energine\share\gears\DataDescription\current(), Energine\share\gears\DataDescription\key(), and Energine\share\gears\DataDescription\valid().
{
         return array_keys($this->fieldDescriptions);
     }
Energine\share\gears\DataDescription::getFieldDescriptionsByType ($types)
Get field descriptions by type.
Parameters
$types string|array
Returns
FieldDescription[]
Definition at line 136 of file DataDescription.php.
{
         $result = array();
         if(!is_array($types)) $types = array($types);
         foreach($this->fieldDescriptions as $name => $fieldDescription){
             if(in_array($fieldDescription->getType(), $types)){
                 $result[$name] = $fieldDescription;
             }
         }
         return $result;
     }
Energine\share\gears\DataDescription::intersect (DataDescription $otherDataDescr)
Intersect this data description with other object data description.
Parameters
DataDescription $otherDataDescr Other data description.
Returns
DataDescription
Definition at line 173 of file DataDescription.php.
{
         $result = false;
         if ($this->isEmpty()) {
             $result = $otherDataDescr;
         }
         else {
             // проходимся по описаниям полей текущего объекта
             foreach ($this->fieldDescriptions as $fieldName => $fieldDescription) {
                 // если существует описание из БД - пересекаем с ним
                 if ($otherDataDescr->getFieldDescriptionByName($fieldName)) {
                     $this->fieldDescriptions[$fieldName] = FieldDescription::intersect(
                         $this->fieldDescriptions[$fieldName],
                         $otherDataDescr->getFieldDescriptionByName($fieldName)
                     );
                 }
                 /*
                  * Если описания из БД отсутствует, устанавливаем дополнительное свойство customField,
                  * которое указывает на то, что данные этого поля сохранять в БД не нужно.
                  */
                 else {
                     $this->getFieldDescriptionByName($fieldName)->setProperty('customField', 'customField');
                 }
             }
             $result = $this;
         }
         return $result;
     }
Energine\share\gears\DataDescription::isEmpty ()
Check whether the field description array is empty.
Returns
bool
Definition at line 163 of file DataDescription.php.
Referenced by Energine\share\gears\DataDescription\intersect().
{
         return !(bool)sizeof($this->fieldDescriptions);
     }
Energine\share\gears\DataDescription::key ()
Return the key of the current element.
Returns
mixed
http://php.net/manual/en/iterator.key.php
Implements Iterator.
Definition at line 210 of file DataDescription.php.
{
         $fieldNames = $this->getFieldDescriptionList();
         return $fieldNames[$this->currentIndex];
     }
Energine\share\gears\DataDescription::load (array $columnsInfo)
Load the data descriptions received from the data base.
Parameters
array $columnsInfo Data description.
See also
DBA::getColumnsInfo()
Definition at line 64 of file DataDescription.php.
Referenced by Energine\apps\gears\AdsManager\add(), and Energine\apps\gears\AdsManager\edit().
{
         foreach ($columnsInfo as $columnName => $columnInfo) {
             $fieldDescr = new FieldDescription($columnName);
             $fieldDescr->loadArray($columnInfo);
             $this->addFieldDescription($fieldDescr);
         }
     }
Energine\share\gears\DataDescription::loadXML (\SimpleXMLElement $xmlDescr)
Load data descriptions from XML file.
Parameters
\SimpleXMLElement $xmlDescr XML file with descriptions.
Definition at line 77 of file DataDescription.php.
{
         if (!empty($xmlDescr))
         foreach ($xmlDescr->field as $fieldXmlDescr) {
             $fieldDescr = new FieldDescription();
             $fieldDescr->loadXML($fieldXmlDescr);
             $this->addFieldDescription($fieldDescr);
         }
     }
Energine\share\gears\DataDescription::next ()
Move forward to next element.
http://php.net/manual/en/iterator.next.php
Implements Iterator.
Definition at line 215 of file DataDescription.php.
{
         $this->currentIndex++;
     }
Energine\share\gears\DataDescription::removeFieldDescription (FieldDescription $fieldDescription)
Remove field description.
Parameters
FieldDescription $fieldDescription Field description.
Definition at line 111 of file DataDescription.php.
{
             unset($this->fieldDescriptions[$fieldDescription->getName()]);
     }
Energine\share\gears\DataDescription::rewind ()
Rewind the Iterator to the first element.
Returns
bool
http://php.net/manual/en/iterator.rewind.php
Implements Iterator.
Definition at line 201 of file DataDescription.php.
{
         $this->currentIndex = 0;
     }
Energine\share\gears\DataDescription::valid ()
Checks if current position is valid.
Returns
bool
http://php.net/manual/en/iterator.valid.php
Implements Iterator.
Definition at line 219 of file DataDescription.php.
{
         $fieldNames = $this->getFieldDescriptionList();
         return isset($fieldNames[$this->currentIndex]);
     }
Member Data Documentation
int Energine\share\gears\DataDescription::$currentIndex = 0 private
Index of the current element (used for iteration).
Definition at line 49 of file DataDescription.php.
Referenced by Energine\share\gears\DataDescription\current(), and Energine\share\gears\DataDescription\key().
array Energine\share\gears\DataDescription::$fieldDescriptions private
Meta data for fields.
Definition at line 43 of file DataDescription.php.
string Energine\share\gears\DataDescription::FIELD_POSITION_AFTER = 'after'
Field position: 'after'.
Definition at line 32 of file DataDescription.php.
Referenced by Energine\share\components\DivisionEditor\edit().
string Energine\share\gears\DataDescription::FIELD_POSITION_BEFORE = 'before'
Field position: 'before'.
Definition at line 37 of file DataDescription.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/DataDescription.php