Energine: Energine\share\gears\TreeNode Class Reference
Energine\share\gears\TreeNode Class Reference
Tree's node manager.
Public Member Functions
__construct ($id)
getID ()
Get node ID.
getParent ()
Get parent node.
hasChildren ()
Check if this node has children.
getChildren ()
Get children.
getIterator ()
addChild (TreeNode $node)
Add child node.
removeChild ($node)
Remove child node.
getParents ()
Get all parents of this node.
getDescendants ()
Get all descendants of this node.
asList ($isRecursive=true)
Get this object as an array.
Public Member Functions inherited from IteratorAggregate
getIterator ()
Private Member Functions
iterateDescendants (TreeNodeList $nodeList)
Iterate over descendants and get them all.
Private Attributes
$id
Node ID.
$parent = null
Parent node.
$children
Array of children nodes.
Detailed Description
Tree's node manager.
final class TreeNode;
Attention
This is final.
Definition at line 214 of file TreeNodeList.php.
Constructor & Destructor Documentation
Energine\share\gears\TreeNode::__construct ($id)
Parameters
int $id Node ID.
Definition at line 234 of file TreeNodeList.php.
{
         $this->children = new TreeNodeList();
         $this->id = $id;
     }
Member Function Documentation
Energine\share\gears\TreeNode::addChild (TreeNode $node)
Add child node.
Parameters
TreeNode $node Child node.
Returns
TreeNode
Definition at line 286 of file TreeNodeList.php.
{
         $node = $this->children->add($node);
         $node->parent = $this;
         return $node;
     }
Energine\share\gears\TreeNode::asList ($isRecursive = true)
Get this object as an array.
Parameters
bool $isRecursive Is recursive?
Returns
array
Definition at line 351 of file TreeNodeList.php.
{
         $result[$this->getID()] = (!is_null($this->getParent()))?$this->getParent()->getID():null;
         if ($this->hasChildren() && $isRecursive) {
             $result += $this->getChildren()->asList();
         }
         return $result;
     }
Energine\share\gears\TreeNode::getChildren ()
Get children.
Returns
TreeNodeList
Definition at line 271 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNode\asList(), Energine\share\gears\TreeNode\getDescendants(), and Energine\share\gears\TreeNode\getIterator().
{
         return $this->children;
     }
Energine\share\gears\TreeNode::getDescendants ()
Get all descendants of this node.
Returns
TreeNodeList
Definition at line 325 of file TreeNodeList.php.
{
         $result = $this->iterateDescendants($this->getChildren());
         return $result;
     }
Energine\share\gears\TreeNode::getID ()
Get node ID.
Returns
int
Definition at line 244 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNodeList\add(), and Energine\share\gears\TreeNode\asList().
{
         return $this->id;
     }
Energine\share\gears\TreeNode::getIterator ()
Definition at line 275 of file TreeNodeList.php.
{
         return $this->getChildren();
     }
Energine\share\gears\TreeNode::getParent ()
Get parent node.
Returns
TreeNode
Definition at line 253 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNode\asList().
{
         return $this->parent;
     }
Energine\share\gears\TreeNode::getParents ()
Get all parents of this node.
Returns
TreeNodeList
Definition at line 309 of file TreeNodeList.php.
{
         $result = new TreeNodeList();
         $node = $this;
         while (!is_null($node)) {
             if (!is_null($node = $node->getParent())) {
                 $result->add($node);
             }
         }
         return $result;
     }
Energine\share\gears\TreeNode::hasChildren ()
Check if this node has children.
Returns
bool
Definition at line 262 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNode\asList().
{
         return (bool)$this->children->getLength();
     }
Energine\share\gears\TreeNode::iterateDescendants (TreeNodeList $nodeList) private
Iterate over descendants and get them all.
Parameters
TreeNodeList $nodeList Node list.
Returns
TreeNodeList
Definition at line 336 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNode\getDescendants().
{
         $result = new TreeNodeList();
         foreach ($nodeList as $node) {
             $result->add($node);
             $result->merge($node->iterateDescendants($node->getChildren()));
         }
         return $result;
     }
Energine\share\gears\TreeNode::removeChild ($node)
Remove child node.
Parameters
TreeNode $node Child node.
Returns
TreeNode
Definition at line 299 of file TreeNodeList.php.
{
         $this->children->remove($node)->parent = null;
         return $node;
     }
Member Data Documentation
TreeNodeList Energine\share\gears\TreeNode::$children private
Array of children nodes.
Definition at line 229 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNode\getChildren().
int Energine\share\gears\TreeNode::$id private
Node ID.
Definition at line 219 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNode\__construct(), and Energine\share\gears\TreeNode\getID().
TreeNode Energine\share\gears\TreeNode::$parent = null private
Parent node.
Definition at line 224 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNode\getParent().
The documentation for this class was generated from the following file:
core/modules/share/gears/TreeNodeList.php