Energine: Energine\share\gears\FileRepositoryLocal Class Reference
Energine\share\gears\FileRepositoryLocal Class Reference
Implementation of file loader interface IFileRepository for local FTP repositories.
Public Member Functions
__construct ($id, $base)
getName ()
Get internal name of implementation.
setId ($id)
Set repository ID (upl_id).
getId ()
Get repository ID (upl_id).
setBase ($base)
Set base path to the repository (upl_path).
getBase ()
Get base path to the repository (upl_path).
allowsCreateDir ()
Check if the creating of directories is allowed.
allowsUploadFile ()
Check if the file uploading is allowed.
allowsEditDir ()
Check if the editing of the directory is allowed.
allowsEditFile ()
Check if the editing of the file is allowed.
allowsDeleteDir ()
Check if the deleting of the directory is allowed.
allowsDeleteFile ()
Check if the deleting of the file is allowed.
uploadFile ($sourceFilename, $destFilename)
Upload a file to the repository.
putFile ($fileData, $filePath)
uploadAlt ($sourceFilename, $destFilename, $width, $height)
Upload a alt-file to the repository.
updateFile ($sourceFilename, $destFilename)
Update file.
updateAlt ($sourceFilename, $destFilename, $width, $height)
Update alt-file.
deleteFile ($filename)
Delete file from repository.
deleteAlt ($filename, $width, $height)
Delete alt-file from repository.
analyze ($filename)
Get the meta-information of the file (mime-type, size, etc.).
createDir ($dir)
Create new directory in the repository.
renameDir ($dir)
Rename directory in the repository.
deleteDir ($dir)
Delete directory from the repository.
prepare (&$data)
Prepare data with.
setPrepareFunction ($func)
Sets the function to prepare dataset.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const IMAGE_ALT_CACHE = 'uploads/alts/resizer/w[width]-h[height]/[upl_path]'
Path to the cache for alternative images.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Attributes
$id
Internal repository ID.
$base
Base path to the repository.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Implementation of file loader interface IFileRepository for local FTP repositories.
This is useful for the cases when the repository is local and the file is downloaded over FTP by using admin tools.
class FileRepositoryFTP;
Definition at line 27 of file FileRepositoryLocal.php.
Constructor & Destructor Documentation
Energine\share\gears\FileRepositoryLocal::__construct ($id, $base)
Parameters
int $id Repository ID.
string $base Base path to the repository.
Implements Energine\share\gears\IFileRepository.
Definition at line 46 of file FileRepositoryLocal.php.
{
         $this->setId($id);
         $this->setBase($base);
     }
Member Function Documentation
Energine\share\gears\FileRepositoryLocal::allowsCreateDir ()
Check if the creating of directories is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 73 of file FileRepositoryLocal.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryLocal::allowsDeleteDir ()
Check if the deleting of the directory is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 89 of file FileRepositoryLocal.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryLocal::allowsDeleteFile ()
Check if the deleting of the file is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 93 of file FileRepositoryLocal.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryLocal::allowsEditDir ()
Check if the editing of the directory is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 81 of file FileRepositoryLocal.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryLocal::allowsEditFile ()
Check if the editing of the file is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 85 of file FileRepositoryLocal.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryLocal::allowsUploadFile ()
Check if the file uploading is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 77 of file FileRepositoryLocal.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryLocal::analyze ($filename)
Get the meta-information of the file (mime-type, size, etc.).
Parameters
string $filename Filename.
Returns
object
Implements Energine\share\gears\IFileRepository.
Definition at line 169 of file FileRepositoryLocal.php.
Referenced by Energine\share\gears\FileRepositoryLocal\putFile(), Energine\share\gears\FileRepositoryRO\uploadAlt(), and Energine\share\gears\FileRepositoryLocal\uploadFile().
{
         $fi = E()->FileRepoInfo->analyze($filename, true);
         if (is_object($fi)) {
             $fi->ready = true;
         }
         return $fi;
     }
Energine\share\gears\FileRepositoryLocal::createDir ($dir)
Create new directory in the repository.
Parameters
string $dir Directory name.
Returns
boolean
Exceptions
SystemException 'ERR_DIR_CREATE'
Implements Energine\share\gears\IFileRepository.
Definition at line 183 of file FileRepositoryLocal.php.
{
         if (file_exists($dir)) return true;
         $dirs = array_filter(explode('/', $dir));
         array_pop($dirs);
         $parentDir = implode('/', $dirs);
         if (!file_exists($parentDir) || !is_writable($parentDir)) {
             throw new SystemException('ERR_DIR_CREATE', SystemException::ERR_CRITICAL, $parentDir);
         }
         return mkdir($dir);
     }
Energine\share\gears\FileRepositoryLocal::deleteAlt ($filename, $width, $height)
Delete alt-file from repository.
Parameters
string $filename Filename.
int $width Width
int $height Height
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 165 of file FileRepositoryLocal.php.
{
         return $this->deleteFile($filename);
     }
Energine\share\gears\FileRepositoryLocal::deleteDir ($dir)
Delete directory from the repository.
Parameters
string $dir Directory name.
Exceptions
SystemException 'ERR_UNIMPLEMENTED_YET'
Attention
This is not yet implemented!
Implements Energine\share\gears\IFileRepository.
Definition at line 212 of file FileRepositoryLocal.php.
{
         throw new SystemException('ERR_UNIMPLEMENTED_YET');
     }
Energine\share\gears\FileRepositoryLocal::deleteFile ($filename)
Delete file from repository.
Parameters
string $filename Filename.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 158 of file FileRepositoryLocal.php.
Referenced by Energine\share\gears\FileRepositoryLocal\deleteAlt().
{
         if (!@unlink($filename)) {
             return false;
         }
         return true;
     }
Energine\share\gears\FileRepositoryLocal::getBase ()
Get base path to the repository (upl_path).
Returns
string
Implements Energine\share\gears\IFileRepository.
Definition at line 69 of file FileRepositoryLocal.php.
{
         return $this->base;
     }
Energine\share\gears\FileRepositoryLocal::getId ()
Get repository ID (upl_id).
Returns
int
Implements Energine\share\gears\IFileRepository.
Definition at line 60 of file FileRepositoryLocal.php.
{
         return $this->id;
     }
Energine\share\gears\FileRepositoryLocal::getName ()
Get internal name of implementation.
Returns
string
Implements Energine\share\gears\IFileRepository.
Definition at line 51 of file FileRepositoryLocal.php.
{
         return 'local';
     }
Energine\share\gears\FileRepositoryLocal::prepare (& $data)
Prepare data with.
Parameters
&$data array repository data as array
Returns
array||boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 219 of file FileRepositoryLocal.php.
{
         return $data;
     }
Energine\share\gears\FileRepositoryLocal::putFile ($fileData, $filePath)
Definition at line 119 of file FileRepositoryLocal.php.
{
         $dir = dirname($filePath);
         if (!file_exists($dir)) {
             mkdir($dir, 0777, true);
         }
         if (!is_writable($dir)) {
             throw new SystemException('ERR_DIR_WRITE', SystemException::ERR_CRITICAL, $dir);
         }
         if (!file_put_contents($filePath, $fileData)) {
             throw new SystemException('ERR_PUT_FILE', SystemException::ERR_CRITICAL, $dir . DIRECTORY_SEPARATOR . $filePath);
         }
         return $this->analyze($filePath);
     }
Energine\share\gears\FileRepositoryLocal::renameDir ($dir)
Rename directory in the repository.
Parameters
string $dir Directory name.
Returns
boolean
Exceptions
SystemException 'ERR_UNIMPLEMENTED_YET'
Attention
This is not yet implemented!
Implements Energine\share\gears\IFileRepository.
Definition at line 201 of file FileRepositoryLocal.php.
{
         throw new SystemException('ERR_UNIMPLEMENTED_YET');
     }
Energine\share\gears\FileRepositoryLocal::setBase ($base)
Set base path to the repository (upl_path).
Parameters
string $base Base path.
Returns
IFileRepository
Implements Energine\share\gears\IFileRepository.
Definition at line 64 of file FileRepositoryLocal.php.
Referenced by Energine\share\gears\FileRepositoryLocal\__construct().
{
         $this->base = $base;
         return $this;
     }
Energine\share\gears\FileRepositoryLocal::setId ($id)
Set repository ID (upl_id).
Parameters
int $id Repository ID.
Returns
IFileRepository
Implements Energine\share\gears\IFileRepository.
Definition at line 55 of file FileRepositoryLocal.php.
Referenced by Energine\share\gears\FileRepositoryLocal\__construct().
{
         $this->id = $id;
         return $this;
     }
Energine\share\gears\FileRepositoryLocal::setPrepareFunction ($func)
Sets the function to prepare dataset.
Parameters
$func callable prepare function
Exceptions
SystemException 'ERR_NOT_USED'
Implements Energine\share\gears\IFileRepository.
Definition at line 227 of file FileRepositoryLocal.php.
{
         throw new SystemException('ERR_NOT_USED');
     }
Energine\share\gears\FileRepositoryLocal::updateAlt ($sourceFilename, $destFilename, $width, $height)
Update alt-file.
Update the alt-file in the repository.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
int $width Width.
int $height Height.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 149 of file FileRepositoryLocal.php.
{
         $destFilename = str_replace(
             array('[width]', '[height]', '[upl_path]'),
             array($width, $height, $destFilename),
             self::IMAGE_ALT_CACHE
         );
         return $this->updateFile($sourceFilename, $destFilename);
     }
Energine\share\gears\FileRepositoryLocal::updateFile ($sourceFilename, $destFilename)
Update file.
Update the file in the repository.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
Returns
boolean|object
Implements Energine\share\gears\IFileRepository.
Definition at line 142 of file FileRepositoryLocal.php.
Referenced by Energine\share\gears\FileRepositoryLocal\updateAlt().
{
         if (!copy($sourceFilename, $destFilename)) {
             return false;
         }
         return true;
     }
Energine\share\gears\FileRepositoryLocal::uploadAlt ($sourceFilename, $destFilename, $width, $height)
Upload a alt-file to the repository.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
int $width Width.
int $height Height.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 133 of file FileRepositoryLocal.php.
{
         $destFilename = str_replace(
             array('[width]', '[height]', '[upl_path]'),
             array($width, $height, $destFilename),
             self::IMAGE_ALT_CACHE
         );
         return $this->uploadFile($sourceFilename, $destFilename);
     }
Energine\share\gears\FileRepositoryLocal::uploadFile ($sourceFilename, $destFilename)
Upload a file to the repository.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
Returns
boolean
Exceptions
SystemException 'ERR_DIR_WRITE'
SystemException 'ERR_COPY_UPLOADED_FILE'
Implements Energine\share\gears\IFileRepository.
Definition at line 103 of file FileRepositoryLocal.php.
Referenced by Energine\share\gears\FileRepositoryLocal\uploadAlt().
{
         $dir = dirname($destFilename);
         if (!file_exists($dir)) {
             mkdir($dir, 0777, true);
         }
         if (!is_writable($dir)) {
             throw new SystemException('ERR_DIR_WRITE', SystemException::ERR_CRITICAL, $dir);
         }
         if (!copy($sourceFilename, $destFilename)) {
             throw new SystemException('ERR_COPY_UPLOADED_FILE', SystemException::ERR_CRITICAL, $destFilename);
         }
         return $this->analyze($destFilename);
     }
Member Data Documentation
string Energine\share\gears\FileRepositoryLocal::$base protected
Base path to the repository.
Definition at line 44 of file FileRepositoryLocal.php.
Referenced by Energine\share\gears\FileRepositoryLocal\__construct(), Energine\share\gears\FileRepositoryLocal\getBase(), and Energine\share\gears\FileRepositoryLocal\setBase().
int Energine\share\gears\FileRepositoryLocal::$id protected
Internal repository ID.
Definition at line 38 of file FileRepositoryLocal.php.
Referenced by Energine\share\gears\FileRepositoryLocal\__construct(), Energine\share\gears\FileRepositoryLocal\getId(), and Energine\share\gears\FileRepositoryLocal\setId().
string Energine\share\gears\FileRepositoryLocal::IMAGE_ALT_CACHE = 'uploads/alts/resizer/w[width]-h[height]/[upl_path]'
Path to the cache for alternative images.
Definition at line 32 of file FileRepositoryLocal.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/FileRepositoryLocal.php