Energine: Energine\share\gears\Document Class Reference
Energine\share\gears\Document Class Reference
Page document.
Public Member Functions
__construct ()
getID ()
Get document ID.
getLang ()
Get language ID.
setBreadCrumbs ($breadCrumbsClass)
Setting breadCrumbs class name It gives the possibilty to add custom BreadCrumbs class.
build ()
Building resulte XML Document.
loadComponents ()
Define and load page components into the ComponentManager.
runComponents ()
Run all components.
getResult ()
Get result.
getUser ()
Get current user.
getRights ()
Get user rights.
setProperty ($propName, $propValue)
Set document property.
getProperty ($propName)
Get document property.
removeProperty ($propName)
Remove property.
addTranslation ($const, Component $component=null)
Add translation constant.
isEditable ()
Check if the component editable.
getXMLDocument ()
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static getTemplatesData ($documentID)
Get the information about document XML-code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes
const SINGLE_SEGMENT = 'single'
Reserved URL segment for 'single'-mode.
const TEMPLATES_DIR = 'templates/'
Path to the directory with templates.
$componentManager
Component manager.
$user
Exemplar of the AuthUser class.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
createJavascriptDependencies ($dependencies, $jsmap, &$js_includes)
Create unique flat array of connected .js-files and their dependencies.
Protected Attributes
$language
Info about system language.
$sitemap
Site map.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Attributes
$breadCrumbsClass = 'BreadCrumbs'
$id = false
Document ID.
$lang
Document language ID.
$request
Request.
$doc
Result document.
$rights = false
User rights for document.
$properties = array()
Document properties.
$documentInfo = array()
Document information.
$translations = array()
Array of constants for translations.
Additional Inherited Members
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Page document.
final class Document;
Attention
This is final.
Definition at line 27 of file Document.php.
Constructor & Destructor Documentation
Energine\share\gears\Document::__construct ()
Definition at line 126 of file Document.php.
{
         parent::__construct();
         $this->user = E()->getAUser();
         $this->language = E()->getLanguage();
         $this->lang = $this->language->getCurrent();
         $this->sitemap = E()->getMap();
         $this->request = E()->getRequest();
         $segments = $this->request->getPath();
         $this->componentManager = new ComponentManager($this);
         // получаем идентификатор документа
         if (isset($segments[0]) && $segments[0] == self::SINGLE_SEGMENT)
             $segments = array();
         $this->id = $this->sitemap->getIDByURI($segments);
         if (empty($this->id)) {
             throw new SystemException('ERR_404', SystemException::ERR_404);
         }
         // получаем права пользователя на документ
         $this->rights =
             $this->sitemap->getDocumentRights($this->getID(), $this->user->getGroups());
         if ($this->getRights() == ACCESS_NONE) {
             throw new SystemException('ERR_403', SystemException::ERR_403);
         }
         // получаем информацию о документе
         $this->documentInfo = $this->sitemap->getDocumentInfo($this->getID());
         //Если его нет в перечне страниц значит он IsDisabled
         if (!$this->documentInfo) {
             throw new SystemException('ERR_404', SystemException::ERR_404);
         }
         //Если URL редиректа не пустой  - осуществляем редирект по нему
         if (!empty($this->documentInfo['RedirectUrl'])) {
             E()->getResponse()->setStatus('301');
             E()->getResponse()->setRedirect(Response::prepareRedirectURL($this->documentInfo['RedirectUrl']));
         }
         // загружаем компоненты страницы
         //$this->loadComponents($this->documentInfo['templateID']);
         // устанавливаем свойства документа
         $this->setProperty('keywords', $this->documentInfo['MetaKeywords']);
         $this->setProperty('description', $this->documentInfo['MetaDescription']);
         $this->setProperty('robots', $this->documentInfo['MetaRobots']);
         $this->setProperty('ID', $this->getID());
         $this->setProperty('default',
             $this->sitemap->getDefault() == $this->getID());
         //Если сайт - индексируемый
         $currentSite = E()->getSiteManager()->getCurrentSite();
         if ($currentSite->isIndexed) {
             //и сущестует код гугловерификации
             if (($verifyCode = $this->getConfigValue('google.verify')) &&
                 !empty($verifyCode)
             ) {
                 //то выводим его
                 $this->setProperty('google_verify', $verifyCode);
             }
             if (($analyticsCode = $currentSite->gaCode) || (($analyticsCode = $this->getConfigValue('google.analytics')) &&
                     !empty($analyticsCode))
             ) {
                 $this->setProperty('google_analytics', $analyticsCode);
             }
         }
     }
Member Function Documentation
Energine\share\gears\Document::addTranslation ($const, Component $component = null)
Add translation constant.
Parameters
string $const Translation constant
Component $component Component object.
Definition at line 584 of file Document.php.
{
         $this->translations[$const] =
             (!is_null($component)) ? $component->getName() : null;
     }
Energine\share\gears\Document::build ()
Building resulte XML Document.
Implements Energine\share\gears\IDocument.
Definition at line 225 of file Document.php.
{
         //Если у нас не режим json
         $this->doc = new \DOMDocument('1.0', 'UTF-8');
         $dom_root = $this->doc->createElement('document');
         $dom_root->setAttribute('debug', $this->getConfigValue('site.debug'));
         $dom_root->setAttribute('editable', $this->isEditable());
         $this->setProperty('url', (string)$this->request->getURI());
         $this->doc->appendChild($dom_root);
         if (!isset($this->properties['title'])) {
             $this->setProperty('title', strip_tags($this->documentInfo['Name']));
         }
         $dom_documentProperties = $this->doc->createElement('properties');
         foreach ($this->properties as $propName => $propValue) {
             $dom_property =
                 $this->doc->createElement('property', str_replace('&', '&amp;', $propValue));
             $dom_property->setAttribute('name', $propName);
             if ($propName == 'title') {
                 $dom_property->setAttribute('alt', $this->documentInfo['HtmlTitle']);
             }
             $dom_documentProperties->appendChild($dom_property);
         }
         $dom_root->appendChild($dom_documentProperties);
         //Дополнительные свойства, имеющие параметры
         $prop = $this->doc->createElement('property', (
         $baseURL = E()->getSiteManager()->getCurrentSite()->base));
         $prop->setAttribute('name', 'base');
         $prop->setAttribute('static', (($staticURL =
             $this->getConfigValue('site.static')) ? $staticURL : $baseURL));
         $prop->setAttribute('media', (($mediaURL =
             $this->getConfigValue('site.media')) ? $mediaURL : $baseURL));
         $prop->setAttribute('resizer', (($resizerURL =
             $this->getConfigValue('site.resizer')) ? $resizerURL : (E()->getSiteManager()->getDefaultSite()->base . 'resizer/')));
         $prop->setAttribute('folder', E()->getSiteManager()->getCurrentSite()->folder);
         $prop->setAttribute('default', E()->getSiteManager()->getDefaultSite()->base);
         $dom_documentProperties->appendChild($prop);
         $prop = $this->doc->createElement('property', $this->getLang());
         $prop->setAttribute('name', 'lang');
         $prop->setAttribute('abbr', $this->request->getLangSegment());
         $prop->setAttribute('default', E()->getLanguage()->getDefault());
         $prop->setAttribute('real_abbr', E()->getLanguage()->getAbbrByID($this->getLang()));
         $dom_documentProperties->appendChild($prop);
         if (($docVars = $this->getConfigValue('site.vars')) && is_array($docVars)) {
             $dom_documentVars = $this->doc->createElement('variables');
             foreach ($docVars as $varName => $varValue) {
                 $var = $this->doc->createElement('var', $varValue);
                 $var->setAttribute('name', strtoupper($varName));
                 $dom_documentVars->appendChild($var);
             }
             $dom_root->appendChild($dom_documentVars);
         }
         if ($og = E()->getOGObject()->build()) {
             $dom_root->appendChild($this->doc->importNode(
                 $og,
                 true
             ));
         }
         unset($prop, $staticURL, $baseURL, $og);
         foreach ($this->componentManager as $component) {
             $componentResult = false;
             $dom_errors = false;
             try {
                 if ($component->enabled()
                     &&
                     ($this->getRights() >= $component->getCurrentStateRights())
                 ) {
                     $componentResult = $component->build();
                 }
             } catch (DummyException $dummyException) {
             }
             if (!empty($componentResult)) {
                 try {
                     $componentResult = $this->doc->importNode(
                         $componentResult->documentElement,
                         true
                     );
                 } catch (\Exception $e) {
                     //stop($e->getTraceAsString());
                 }
                 if ($dom_errors) {
                     $componentResult->insertBefore($dom_errors, $componentResult->firstChild);
                 }
                 $dom_root->appendChild($componentResult);
             } elseif ($dom_errors) {
                 $dom_root->appendChild($dom_errors);
             }
         }
         if (!empty($this->translations)) {
             $dom_translations = $this->doc->createElement('translations');
             $dom_root->appendChild($dom_translations);
             foreach ($this->translations as $const => $componentName) {
                 $dom_translation =
                     $this->doc->createElement('translation', $this->translate($const));
                 $dom_translation->setAttribute('const', $const);
                 if (!is_null($componentName)) {
                     $dom_translation->setAttribute('component', $componentName);
                 }
                 $dom_translations->appendChild($dom_translation);
             }
         }
         // построение списка подключаемых js библиотек в порядке зависимостей
         $jsmap_file = HTDOCS_DIR . '/system.jsmap.php';
         if (file_exists($jsmap_file)) {
             $js_includes = array();
             $jsmap = include($jsmap_file);
             $xpath = new \DOMXPath($this->doc);
             $nl = $xpath->query('//javascript/behavior');
             if ($nl->length) {
                 foreach ($nl as $node) {
                     $cls_path = $node->getAttribute('path');
                     if ($cls_path && substr($cls_path, -1) != '/') {
                         $cls_path .= '/';
                     }
                     $cls = (($cls_path) ? $cls_path : '') . $node->getAttribute('name');
                     $this->createJavascriptDependencies(array($cls), $jsmap, $js_includes);
                 }
             }
             $dom_javascript = $this->doc->createElement('javascript');
             foreach ($js_includes as $js) {
                 $dom_js_library = $this->doc->createElement('library');
                 $dom_js_library->setAttribute('path', $js);
                 $dom_javascript->appendChild($dom_js_library);
             }
             $dom_root->appendChild($dom_javascript);
         }
     }
Energine\share\gears\Document::createJavascriptDependencies ($dependencies, $jsmap, & $js_includes) protected
Create unique flat array of connected .js-files and their dependencies.
Parameters
array $dependencies Dependencies.
array $jsmap JS map.
array $js_includes JS includes.
Definition at line 378 of file Document.php.
Referenced by Energine\share\gears\Document\build().
{
         if ($dependencies) {
             foreach ($dependencies as $dep) {
                 if (isset($jsmap[$dep]))
                     $this->createJavascriptDependencies($jsmap[$dep], $jsmap, $js_includes);
                 if (!in_array($dep, $js_includes)) {
                     $js_includes[] = $dep;
                 }
             }
         }
     }
Energine\share\gears\Document::getID ()
Get document ID.
Returns
int
Definition at line 195 of file Document.php.
Referenced by Energine\share\gears\Document\__construct(), and Energine\share\gears\Document\loadComponents().
{
         return $this->id;
     }
Energine\share\gears\Document::getLang ()
Get language ID.
Returns
int
Definition at line 204 of file Document.php.
Referenced by Energine\share\gears\Document\build().
{
         return $this->lang;
     }
Energine\share\gears\Document::getProperty ($propName)
Get document property.
Parameters
string $propName Property name.
Returns
string|false
Definition at line 560 of file Document.php.
{
         if (isset($this->properties[$propName])) {
             return $this->properties[$propName];
         }
         return false;
     }
Energine\share\gears\Document::getResult ()
Get result.
Returns
Implements Energine\share\gears\IDocument.
Definition at line 520 of file Document.php.
{
         return $this->doc;
     }
Energine\share\gears\Document::getRights ()
Get user rights.
See also
Document::$rights
Returns
int
Definition at line 540 of file Document.php.
Referenced by Energine\share\gears\Document\__construct(), Energine\share\gears\Document\build(), Energine\share\gears\Document\isEditable(), and Energine\share\gears\Document\runComponents().
{
         return $this->rights;
     }
static Energine\share\gears\Document::getTemplatesData ($documentID) static
Get the information about document XML-code.
If the value 'xml' is missed or incorrect then it will try to load XML from the file.
Parameters
int $documentID Document ID.
Returns
object
Exceptions
SystemException 'ERR_WRONG_[type]'
SystemException 'ERR_BAD_DOC_ID'
Definition at line 612 of file Document.php.
Referenced by Energine\share\gears\Document\loadComponents().
{
         $loadDataFromFile = function ($fileName, $type) {
             if (!($result = simplexml_load_string(file_get_contents_stripped(
                 Document::TEMPLATES_DIR .
                 constant(
                     'Energine\\share\\components\\DivisionEditor::TMPL_' .
                     strtoupper($type)) .
                 '/' . $fileName)))
             ) {
                 throw new SystemException('ERR_WRONG_' . strtoupper($type));
             }
             return $result;
         };
         if (!($templateData =
             E()->getDB()->select('share_sitemap', array('smap_content_xml as content', 'smap_layout_xml as layout', 'smap_content as content_file', 'smap_layout as layout_file'), array('smap_id' => $documentID)))
         ) {
             throw new SystemException('ERR_BAD_DOC_ID');
         }
         list($templateData) = $templateData;
         libxml_use_internal_errors(true);
         foreach (array(cmp\DivisionEditor::TMPL_LAYOUT, cmp\DivisionEditor::TMPL_CONTENT) as $type) {
             //Если нет данных поле
             if (!$templateData[$type]) {
                 //Берем из файла
                 $templateData[$type] = $loadDataFromFile($templateData[$type .
                 '_file'], $type);
             } else {
                 //Если есть данные в поле
                 //Пытаемся распарсить
                 if (!($templateData[$type] =
                     simplexml_load_string(stripslashes($templateData[$type])))
                 ) {
                     //Если не удалось - берем из файла
                     $templateData[$type] = $loadDataFromFile($templateData[$type .
                     '_file'], $type);
                     //и очищаем
                     E()->getDB()->modify(QAL::UPDATE, 'share_sitemap', array(
                         'smap_' .
                         $type .
                         '_xml' => ''), array('smap_id' => $documentID));
                 }
             }
             $templateData[$type . 'File'] = $templateData[$type . '_file'];
             unset($templateData[$type . '_file']);
         }
         return (object)$templateData;
     }
Energine\share\gears\Document::getUser ()
Get current user.
Returns
AuthUser
Definition at line 529 of file Document.php.
{
         return $this->user;
     }
Energine\share\gears\Document::getXMLDocument ()
Definition at line 663 of file Document.php.
{
         return $this->doc;
     }
Energine\share\gears\Document::isEditable ()
Check if the component editable.
Returns
bool
Definition at line 594 of file Document.php.
Referenced by Energine\share\gears\Document\build().
{
         if ($this->getRights() > 2) {
             return ($this->getConfigValue('site.debug')) ? isset($_REQUEST['editMode']) : isset($_POST['editMode']);
         } else {
             return false;
         }
     }
Energine\share\gears\Document::loadComponents ()
Define and load page components into the ComponentManager.
Todo:
Полный рефакторинг!
Definition at line 396 of file Document.php.
{
         // определяем и загружаем описания content- и layout- частей страницы
         $templateData = Document::getTemplatesData($this->getID());
         $contentXML = $templateData->content;
         $layoutXML = $templateData->layout;
         $contentFile = $templateData->contentFile;
         $layoutFile = $templateData->layoutFile;
         unset($templateData);
         // вызывается ли компонент в single режиме?
         $actionParams = $this->request->getPath(Request::PATH_ACTION);
         if (sizeof($actionParams) > 1 &&
             $actionParams[0] == self::SINGLE_SEGMENT
         ) {
             /*
             * Устанавливаем смещение пути на количество существующих
             * сегментов + 1 зарезирвированный сегмент + 1 сегмент
             * имени компонента.
             */
             $this->request->setPathOffset($this->request->getPathOffset() + 2);
             $this->setProperty('single', 'single');
             if ($actionParams[1] == 'pageToolBar') {
                 $this->componentManager->add(
                     $this->componentManager->createComponent(
                         'pageToolBar',
                         'share',
                         'DivisionEditor',
                         array('state' => 'showPageToolbar')
                     )
                 );
             } // существует ли запрошенный компонент среди компонентов страницы?
             else {
                 if (
                     !(
                     $blockDescription = ComponentManager::findBlockByName(
                         $layoutXML,
                         $actionParams[1]
                     )
                     )
                     &&
                     !(
                     $blockDescription = ComponentManager::findBlockByName(
                         $contentXML,
                         $actionParams[1]
                     )
                     )
                 ) {
                     throw new SystemException('ERR_NO_SINGLE_COMPONENT', SystemException::ERR_CRITICAL, $actionParams[1]);
                 }
                 if (E()->getController()->getViewMode() ==
                     DocumentController::TRANSFORM_STRUCTURE_XML
                 ) {
                     $int = new IRQ();
                     $int->addBlock($blockDescription);
                     throw $int;
                 }
                 $this->componentManager->add(
                     ComponentManager::createBlockFromDescription($blockDescription)
                 );
             }
         } else {
             if (E()->getController()->getViewMode() ==
                 DocumentController::TRANSFORM_STRUCTURE_XML
             ) {
                 $int = new IRQ();
                 $int->addBlock($layoutXML);
                 $int->addBlock($contentXML);
                 throw $int;
             }
             foreach (array(
                          $layoutXML,
                          $contentXML
                      ) as $XML) {
                 $this->componentManager->add(
                     ComponentManager::createBlockFromDescription($XML, array('file' => ($XML == $contentXML)
                             ? $contentFile : $layoutFile))
                 );
             }
             /*
             * Добавляем к набору компонентов страницы
             * обязательные стандартные компоненты:
             *     - BreadCrumbs
             */
             $this->componentManager->add($this->componentManager->createComponent('breadCrumbs', 'share', $this->breadCrumbsClass));
             //Если пользователь не авторизован и авторизационный домен не включает текущеий домен - то добавляем компонент для кроссдоменной авторизации
             if (
                 !$this->user->isAuthenticated()
                 &&
                 (strpos(E()->getSiteManager()->getCurrentSite()->host, $this->getConfigValue('site.domain')) === false)
             )
                 $this->componentManager->add(
                     $this->componentManager->createComponent('cdAuth', 'share', 'CrossDomainAuth')
                 );
         }
     }
Energine\share\gears\Document::removeProperty ($propName)
Remove property.
Parameters
string $propName Property name.
Definition at line 572 of file Document.php.
{
         if (isset($this->properties[$propName])) {
             unset($this->properties[$propName]);
         }
     }
Energine\share\gears\Document::runComponents ()
Run all components.
Definition at line 499 of file Document.php.
{
         foreach ($this->componentManager as $block) {
             //$block->run();
             if (
                 $block->enabled()
                 &&
                 ($this->getRights() >= $block->getCurrentStateRights())
             ) {
                 $block->run();
             }
             /*
             * Запускаем определение текущего действия компонента
             * и загрузку конфигурационной информации.
             */
             //$component->getState();
             // если у пользователя достаточно прав - запускаем работу компонента
         }
     }
Energine\share\gears\Document::setBreadCrumbs ($breadCrumbsClass)
Setting breadCrumbs class name It gives the possibilty to add custom BreadCrumbs class.
Parameters
string $breadCrumbsClass
Exceptions
SystemException
Definition at line 215 of file Document.php.
{
         if(!class_parents($breadCrumbsClass)){
             throw new SystemException('ERR_BAD_BREADCRUMBS_CLASS', SystemException::ERR_DEVELOPER, $breadCrumbsClass);
         }
         $this->breadCrumbsClass = $breadCrumbsClass;
     }
Energine\share\gears\Document::setProperty ($propName, $propValue)
Set document property.
Parameters
string $propName Property name.
string $propValue Property value.
Definition at line 550 of file Document.php.
Referenced by Energine\share\gears\Document\__construct(), Energine\share\gears\Document\build(), and Energine\share\gears\Document\loadComponents().
{
         $this->properties[$propName] = $propValue;
     }
Member Data Documentation
Energine\share\gears\Document::$breadCrumbsClass = 'BreadCrumbs' private
Definition at line 44 of file Document.php.
Referenced by Energine\share\gears\Document\setBreadCrumbs().
ComponentManager Energine\share\gears\Document::$componentManager
Component manager.
Definition at line 80 of file Document.php.
DOMDocument Energine\share\gears\Document::$doc private
Result document.
Definition at line 86 of file Document.php.
Referenced by Energine\share\gears\Document\getResult(), and Energine\share\gears\Document\getXMLDocument().
array Energine\share\gears\Document::$documentInfo = array() private
Document information.
See also
Sitemap::getDocumentInfo()
Definition at line 117 of file Document.php.
int Energine\share\gears\Document::$id = false private
Document ID.
Definition at line 50 of file Document.php.
Referenced by Energine\share\gears\Document\getID().
int Energine\share\gears\Document::$lang private
Document language ID.
Definition at line 56 of file Document.php.
Referenced by Energine\share\gears\Document\getLang().
Language Energine\share\gears\Document::$language protected
Info about system language.
Definition at line 62 of file Document.php.
array Energine\share\gears\Document::$properties = array() private
Document properties.
Definition at line 104 of file Document.php.
Request Energine\share\gears\Document::$request private
Request.
Definition at line 74 of file Document.php.
int Energine\share\gears\Document::$rights = false private
User rights for document.
Rights:
ACCESS_NONE = 0
ACCESS_READ = 1
ACCESS_EDIT = 2
ACCESS_FULL = 3
Definition at line 98 of file Document.php.
Referenced by Energine\share\gears\Document\getRights().
Sitemap Energine\share\gears\Document::$sitemap protected
Site map.
Definition at line 68 of file Document.php.
array Energine\share\gears\Document::$translations = array() private
Array of constants for translations.
Definition at line 124 of file Document.php.
AuthUser Energine\share\gears\Document::$user
Exemplar of the AuthUser class.
Definition at line 110 of file Document.php.
Referenced by Energine\share\gears\Document\getUser().
string Energine\share\gears\Document::SINGLE_SEGMENT = 'single'
Reserved URL segment for 'single'-mode.
Definition at line 32 of file Document.php.
string Energine\share\gears\Document::TEMPLATES_DIR = 'templates/'
Path to the directory with templates.
Definition at line 38 of file Document.php.
Referenced by Energine\share\gears\Document\getTemplatesData(), and Energine\share\components\DivisionEditor\loadTemplateData().
The documentation for this class was generated from the following file:
core/modules/share/gears/Document.php