Energine: Energine\share\gears\Data Class Reference
Energine\share\gears\Data Class Reference
Holds data.
Public Member Functions
load ($data)
Load the dataset, received from the data base.
addRow (array $rowData)
Add data row to all data fields.
removeRow ($rowIndex)
Remove data row from all data fields.
changeRow ($rowIndex, array $rowData)
Change the data row for all data fields.
addField (Field $field)
Add data field.
removeField (Field $field)
Remove data field.
getFieldByName ($name)
Get field by his name.
getFields ()
Get all data fields.
getLength ()
Get the total amount of data fields.
isEmpty ()
Check if data fields array is empty.
getRowCount ()
Get the total amount of data rows.
asArray ($groupedByFields=false)
Get all data fields as an array.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Private Attributes
$fields = array()
Data fields.
$length = 0
Amount of data fields.
$rows = 0
Amount of data rows.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
Holds data.
class Data
Definition at line 27 of file Data.php.
Member Function Documentation
Energine\share\gears\Data::addField (Field $field)
Add data field.
Parameters
Field $field New data field.
Definition at line 117 of file Data.php.
Referenced by Energine\comments\gears\CommentsHelper\createAndAddField(), Energine\apps\gears\AdsManager\edit(), Energine\share\gears\Data\load(), and Energine\apps\gears\NewsEditorSaver\setData().
{
         $this->fields[$field->getName()] = $field;
         $this->length++;
     }
Energine\share\gears\Data::addRow (array $rowData)
Add data row to all data fields.
Parameters
array $rowData Data row.
Definition at line 73 of file Data.php.
{
         foreach ($rowData as $fieldName => $fieldValue) {
             $field = $this->getFieldByName($fieldName);
             if ($field) {
                 $field->addRowData($fieldValue);
             }
         }
     }
Energine\share\gears\Data::asArray ($groupedByFields = false)
Get all data fields as an array.
Parameters
bool $groupedByFields Group by fields?
Returns
array
Definition at line 195 of file Data.php.
{
         $result = array();
         $res = array();
         foreach ($this->fields as $fieldName => $field) {
             $result[$fieldName] = $field->getData();
         }
         if ($groupedByFields) {
             return $result;
         }
         $fieldNames = array_keys($this->fields);
         $rows = $this->getRowCount();
         for ($i = 0; $i < $rows; $i++) {
             foreach ($fieldNames as $fieldName) {
                 $res[$i][$fieldName] = $result[$fieldName][$i];
             }
         }
         return $res;
     }
Energine\share\gears\Data::changeRow ($rowIndex, array $rowData)
Change the data row for all data fields.
Parameters
int $rowIndex Row ID.
array $rowData Row data.
Returns
boolean
Definition at line 101 of file Data.php.
{
         $result = false;
         foreach ($rowData as $fieldName => $fieldValue) {
             $field = $this->getFieldByName($fieldName);
             if ($field) {
                 $result = $field->setRowData($rowIndex, $fieldValue);
             }
         }
         return $result;
     }
Energine\share\gears\Data::getFieldByName ($name)
Get field by his name.
Parameters
string $name Field name.
Returns
Field
Definition at line 140 of file Data.php.
Referenced by Energine\share\gears\Data\addRow(), Energine\share\gears\Data\changeRow(), Energine\apps\gears\AdsManager\edit(), Energine\share\gears\Data\getRowCount(), Energine\share\gears\Data\load(), and Energine\apps\gears\NewsEditorSaver\setData().
{
         $field = false;
         if (isset($this->fields[$name])) {
             $field = $this->fields[$name];
         }
         return $field;
     }
Energine\share\gears\Data::getFields ()
Get all data fields.
Returns
array
Definition at line 153 of file Data.php.
{
         return $this->fields;
     }
Energine\share\gears\Data::getLength ()
Get the total amount of data fields.
Returns
int
Definition at line 162 of file Data.php.
{
         return $this->length;
     }
Energine\share\gears\Data::getRowCount ()
Get the total amount of data rows.
Returns
int
Definition at line 180 of file Data.php.
Referenced by Energine\share\gears\Data\asArray().
{
         if ($this->length > 0) {
             $fieldNames = array_keys($this->fields);
             $firstFieldName = $fieldNames[0];
             $this->rows = $this->getFieldByName($firstFieldName)->getRowCount();
         }
         return $this->rows;
     }
Energine\share\gears\Data::isEmpty ()
Check if data fields array is empty.
Returns
bool
Definition at line 171 of file Data.php.
{
         return empty($this->fields);
     }
Energine\share\gears\Data::load ($data)
Load the dataset, received from the data base.
Parameters
array $data Dataset.
See also
DBA::selectRequest()
Definition at line 53 of file Data.php.
{
         if (is_array($data) && ! empty($data)) {
             $data = inverseDBResult($data);
             foreach ($data as $fieldName => $fieldValues) {
                 //     ,
                 if (!($fieldObject = $this->getFieldByName($fieldName))) {
                     $fieldObject = new Field($fieldName);
                     $this->addField($fieldObject);
                 }
                 //
                 $fieldObject->setData($fieldValues);
             }
         }
     }
Energine\share\gears\Data::removeField (Field $field)
Remove data field.
Parameters
Field $field Data field.
Definition at line 127 of file Data.php.
{
         if (isset($this->fields[$field->getName()])) {
             unset($this->fields[$field->getName()]);
             $this->length--;
         }
     }
Energine\share\gears\Data::removeRow ($rowIndex)
Remove data row from all data fields.
Parameters
int $rowIndex Row ID.
Definition at line 87 of file Data.php.
{
         foreach ($this->fields as $field) {
             $field->removeRowData($rowIndex);
         }
     }
Member Data Documentation
array Energine\share\gears\Data::$fields = array() private
Data fields.
Definition at line 32 of file Data.php.
Referenced by Energine\share\gears\Data\getFields().
int Energine\share\gears\Data::$length = 0 private
Amount of data fields.
Definition at line 38 of file Data.php.
Referenced by Energine\share\gears\Data\getLength().
int Energine\share\gears\Data::$rows = 0 private
Amount of data rows.
Definition at line 44 of file Data.php.
Referenced by Energine\share\gears\Data\asArray(), and Energine\share\gears\Data\getRowCount().
The documentation for this class was generated from the following file:
core/modules/share/gears/Data.php