Energine: Energine\share\gears\Saver Class Reference
Energine\share\gears\Saver Class Reference
Data saver into data base.
Public Member Functions
__construct ()
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
Get data description.
getData ()
Get data.
setData (Data $data)
Set data.
setMode ($mode)
Set save mode.
getMode ()
Get save mode.
getFilter ()
Get condition for save SQL-request.
setFilter ($filter)
Set condition for save SQL-request.
validate ()
Validate date before saving.
getErrors ()
Get fields with errors.
addError ($fieldName)
Add field name where an error occurred.
save ()
Save data.
getResult ()
Get result of saving.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Attributes
$dataDescription = false
Data description.
$data = false
Data.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Attributes
$errors = array()
Field names where errors occurred.
$filter = null
Condition for save SQL-request.
$mode = QAL::INSERT
Save mode.
$result = false
Result of saving.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Data saver into data base.
class Saver;
Definition at line 26 of file Saver.php.
Constructor & Destructor Documentation
Energine\share\gears\Saver::__construct ()
Definition at line 68 of file Saver.php.
{
         parent::__construct();
     }
Member Function Documentation
Energine\share\gears\Saver::addError ($fieldName)
Add field name where an error occurred.
Parameters
string $fieldName Field name.
Definition at line 206 of file Saver.php.
Referenced by Energine\share\gears\Saver\validate().
{
         array_push($this->errors, $this->translate('FIELD_' . $fieldName));
     }
Energine\share\gears\Saver::getData ()
Get data.
Returns
Data
Definition at line 95 of file Saver.php.
Referenced by Energine\share\gears\SiteSaver\createMainPage(), Energine\share\gears\SiteSaver\save(), Energine\share\gears\SitePropertiesSaver\save(), Energine\share\gears\DivisionSaver\save(), Energine\share\gears\ExtendedSaver\save(), Energine\share\gears\Saver\save(), Energine\share\gears\SitePropertiesSaver\setData(), Energine\apps\gears\NewsEditorSaver\setData(), Energine\share\gears\DivisionSaver\validate(), and Energine\share\gears\Saver\validate().
{
         return $this->data;
     }
Energine\share\gears\Saver::getDataDescription ()
Get data description.
Returns
DataDescription
Definition at line 86 of file Saver.php.
Referenced by Energine\share\gears\Saver\save(), Energine\share\gears\DivisionSaver\validate(), and Energine\share\gears\Saver\validate().
{
         return $this->dataDescription;
     }
Energine\share\gears\Saver::getErrors ()
Get fields with errors.
Returns
array
Definition at line 197 of file Saver.php.
{
         return $this->errors;
     }
Energine\share\gears\Saver::getFilter ()
Get condition for save SQL-request.
Returns
mixed
Definition at line 131 of file Saver.php.
Referenced by Energine\share\gears\Saver\save().
{
         return $this->filter;
     }
Energine\share\gears\Saver::getMode ()
Get save mode.
Returns
string
Definition at line 122 of file Saver.php.
Referenced by Energine\share\gears\SiteSaver\save(), Energine\share\gears\SitePropertiesSaver\save(), Energine\share\gears\DivisionSaver\save(), Energine\share\gears\ExtendedSaver\save(), and Energine\share\gears\Saver\save().
{
         return $this->mode;
     }
Energine\share\gears\Saver::getResult ()
Get result of saving.
Returns
mixed
Definition at line 346 of file Saver.php.
{
         return $this->result;
     }
Energine\share\gears\Saver::save ()
Save data.
Todo:
,
Definition at line 213 of file Saver.php.
{
         //
         $data = array();
         //
         //  false,          .
         $m2mData = false;
         $m2mFDs = $this->getDataDescription()->getFieldDescriptionsByType(FieldDescription::FIELD_TYPE_MULTI);
         if (!empty($m2mFDs)) {
             foreach ($m2mFDs as $fieldInfo) {
                 if (is_null($fieldInfo->getPropertyValue('customField'))) {
                     //  m2m
                     list($m2mTableName, $m2mPKName) = array_values($fieldInfo->getPropertyValue('key'));
                     //
                     $m2mInfo = $this->dbh->getColumnsInfo($m2mTableName);
                     unset($m2mInfo[$m2mPKName]);
                     $m2mData[$m2mTableName]['pk'] = $m2mPKName;
                 }
             }
         }
         for ($i = 0; $i < $this->getData()->getRowCount(); $i++) {
             foreach ($this->getDataDescription() as $fieldName => $fieldInfo) {
                 //  ,
                 if (is_null($fieldInfo->getPropertyValue('customField')) && $this->getData()->getFieldByName($fieldName)) {
                     $fieldValue = $this->getData()->getFieldByName($fieldName)->getRowData($i);
                     if ($fieldInfo->getType() == FieldDescription::FIELD_TYPE_HTML_BLOCK) {
                         $fieldValue = DataSet::cleanupHTML($fieldValue);
                     }
                     //
                     if ($fieldInfo->isMultilanguage() == false && $fieldInfo->getPropertyValue('key') !== true && $fieldInfo->getPropertyValue('languageID') == false) {
                         switch ($fieldInfo->getType()) {
                             case FieldDescription::FIELD_TYPE_FLOAT:
                                 $fieldValue = str_replace(',', '.', $fieldValue);
                                 break;
                             case FieldDescription::FIELD_TYPE_MULTI:
                                 $m2mValues = $fieldValue;
                                 //
                                 //   NULL
                                 $fieldValue = '';
                                 /**
                                  * @todo   ,
                                  *
                                  */
                                 //  m2m
                                 list($m2mTableName, $m2mPKName) = array_values($fieldInfo->getPropertyValue('key'));
                                 //
                                 $m2mInfo = $this->dbh->getColumnsInfo($m2mTableName);
                                 unset($m2mInfo[$m2mPKName]);
                                 foreach ($m2mValues as $val) {
                                     $m2mData[$m2mTableName]['pk'] = $m2mPKName;
                                     $m2mData[$m2mTableName][key($m2mInfo)][] = $val;
                                 }
                                 unset($m2mValues, $m2mPKName, $m2mInfo, $m2mTableName);
                                 break;
                         }
                         $data[$fieldInfo->getPropertyValue('tableName')][$fieldName] = $fieldValue;
                     }
                     elseif ($fieldInfo->isMultilanguage() || $fieldInfo->getPropertyValue('languageID')) {
                         $data[$fieldInfo->getPropertyValue('tableName')][$this->data->getFieldByName('lang_id')->getRowData($i)][$fieldName] = $fieldValue;
                     }
                     elseif ($fieldInfo->getPropertyValue('key') === true) {
                         $pkName = $fieldName; //
                         $mainTableName = $fieldInfo->getPropertyValue('tableName'); //
                     }
                 }
             }
         }
         if ($this->getMode() == QAL::INSERT) {
             $data[$mainTableName] = (!isset($data[$mainTableName])) ? array() : $data[$mainTableName];
             $id = $this->dbh->modify(QAL::INSERT, $mainTableName, $data[$mainTableName]);
             unset($data[$mainTableName]);
             foreach ($data as $tableName => $langRow) {
                 foreach ($langRow as $row) {
                     $row[$pkName] = $id;
                     /*$result = */
                     $this->dbh->modify(QAL::INSERT, $tableName, $row);
                 }
             }
             $result = $id;
         }
         else {
             if (isset($data[$mainTableName])) {
                 /*$result = */
                 $this->dbh->modify(QAL::UPDATE, $mainTableName, $data[$mainTableName], $this->getFilter());
                 unset($data[$mainTableName]);
             }
             foreach ($data as $tableName => $langRow) {
                 foreach ($langRow as $langID => $row) {
                     try {
                         /*$result = */
                         $this->dbh->modify(QAL::INSERT, $tableName, array_merge($row, $this->getFilter()));
                     }
                     catch (\Exception $e) {
                         /*$result = */
                         $this->dbh->modify(QAL::UPDATE, $tableName, $row, array_merge($this->getFilter(), array('lang_id' => $langID)));
                     }
                 }
             }
             if ($pkName)
                 $result = $this->getData()->getFieldByName($pkName)->getRowData(0);
             else $result = true;
         }
         if (is_array($m2mData) && is_numeric($result)) {
             foreach ($m2mData as $tableName => $m2mInfo) {
                 $this->dbh->modify(QAL::DELETE, $tableName, null, array($m2mInfo['pk'] => $result));
             }
             foreach ($m2mData as $tableName => $m2mInfo) {
                 $pk = $m2mInfo['pk'];
                 unset($m2mInfo['pk']);
                 if ($m2mInfo)
                     foreach (current($m2mInfo) as $fieldValue) {
                         $this->dbh->modify(QAL::INSERT_IGNORE, $tableName, array(key($m2mInfo) => $fieldValue, $pk => $result));
                     }
             }
         }
         return ($this->result = $result);
     }
Energine\share\gears\Saver::setData (Data $data)
Set data.
Parameters
Data $data Data.
Definition at line 104 of file Saver.php.
{
         $this->data = $data;
     }
Energine\share\gears\Saver::setDataDescription (DataDescription $dataDescription)
Set data description.
Parameters
DataDescription $dataDescription Data description.
Definition at line 77 of file Saver.php.
{
         $this->dataDescription = $dataDescription;
     }
Energine\share\gears\Saver::setFilter ($filter)
Set condition for save SQL-request.
Parameters
mixed $filter Condition for save SQL-request.
Definition at line 140 of file Saver.php.
{
         $this->filter = $filter;
     }
Energine\share\gears\Saver::setMode ($mode)
Set save mode.
Parameters
string $mode Mode.
Definition at line 113 of file Saver.php.
{
         $this->mode = $mode;
     }
Energine\share\gears\Saver::validate ()
Validate date before saving.
Returns
boolean
Exceptions
SystemException 'ERR_DEV_BAD_DATA'
Todo:
callback
Definition at line 153 of file Saver.php.
{
         $result = false;
         if (!$this->getData() || !$this->getDataDescription()) {
             throw new SystemException('ERR_DEV_BAD_DATA', SystemException::ERR_DEVELOPER);
         }
         foreach ($this->getDataDescription() as $fieldName => $fieldDescription) {
             $fieldData = $this->getData()->getFieldByName($fieldName);
             if ($fieldDescription->getType() == FieldDescription::FIELD_TYPE_BOOL ||
                 //$fieldDescription->getType() == FieldDescription::FIELD_TYPE_PFILE ||
                 $fieldDescription->getType() == FieldDescription::FIELD_TYPE_FILE ||
                 $fieldDescription->getType() == FieldDescription::FIELD_TYPE_CAPTCHA ||
                 $fieldName == 'lang_id' ||
                 !is_null($fieldDescription->getPropertyValue('customField'))
                 || $fieldDescription->getPropertyValue('nullable')
             ) {
                 continue;
             }
                 //     POST-  -
             elseif ($fieldData == false && $fieldName != 'lang_id') {
                 $this->addError($fieldName);
                 $result = false;
                 break;
             }
             else {
                 for ($i = 0; $i < $fieldData->getRowCount(); $i++) {
                     if (!$fieldDescription->validate($fieldData->getRowData($i))) {
                         $this->addError($fieldName);
                         $result = false;
                         break 2;
                     }
                 }
                 $result = true;
             }
         }
         return $result;
     }
Member Data Documentation
Data Energine\share\gears\Saver::$data = false protected
Data.
Definition at line 60 of file Saver.php.
Referenced by Energine\share\gears\Saver\getData(), Energine\share\gears\DivisionSaver\save(), Energine\share\gears\Saver\save(), and Energine\share\gears\Saver\setData().
DataDescription Energine\share\gears\Saver::$dataDescription = false protected
Data description.
Definition at line 54 of file Saver.php.
Referenced by Energine\share\gears\Saver\getDataDescription(), and Energine\share\gears\Saver\setDataDescription().
array Energine\share\gears\Saver::$errors = array() private
Field names where errors occurred.
Definition at line 31 of file Saver.php.
Referenced by Energine\share\gears\Saver\getErrors().
mixed Energine\share\gears\Saver::$filter = null private
Condition for save SQL-request.
See also
QAL::select()
Definition at line 39 of file Saver.php.
Referenced by Energine\share\gears\Saver\getFilter(), Energine\apps\gears\NewsEditorSaver\setData(), and Energine\share\gears\Saver\setFilter().
string Energine\share\gears\Saver::$mode = QAL::INSERT private
Save mode.
See also
QAL::INSERT
QAL::UPDATE
Definition at line 48 of file Saver.php.
Referenced by Energine\share\gears\Saver\getMode(), and Energine\share\gears\Saver\setMode().
mixed Energine\share\gears\Saver::$result = false private
Result of saving.
Definition at line 66 of file Saver.php.
Referenced by Energine\share\gears\SiteSaver\copyRows(), Energine\share\gears\Saver\getResult(), Energine\share\gears\SiteSaver\save(), Energine\share\gears\DivisionSaver\save(), Energine\share\gears\ExtendedSaver\save(), Energine\share\gears\Saver\save(), and Energine\share\gears\Saver\validate().
The documentation for this class was generated from the following file:
core/modules/share/gears/Saver.php