Energine: Energine\share\gears\Response Class Reference
Energine\share\gears\Response Class Reference
HTTP-response.
Public Member Functions
__construct ()
setStatus ($statusCode, $reasonPhrase=null)
Set response status.
setHeader ($name, $value, $replace=true)
Set response header.
addCookie ($name=UserSession::DEFAULT_SESSION_NAME, $value= '', $expire=0, $domain=false, $path= '/')
Set cookies.
sendCookies ()
Send cookies to the list.
sendHeaders ()
Send headers.
deleteCookie ($name)
Remove cookie by name.
setRedirect ($location, $status=302)
Set redirection URL and redirect.
redirectToCurrentSection ($action= '')
Redirect to current section.
write ($data)
Add data to the response body.
goBack ()
Go back.
disableCache ()
Disable cache.
commit ()
Send response to the client.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static prepareRedirectURL ($redirectURL)
Prepare redirection URL.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Private Attributes
$reasonPhrases
Reason phrases.
$statusLine
Line of the response status.
$headers
Response header.
$cookies
Response cookies.
$body
Response body.
Additional Inherited Members
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
HTTP-response.
final class Response;
Attention
This is final.
Definition at line 26 of file Response.php.
Constructor & Destructor Documentation
Energine\share\gears\Response::__construct ()
Definition at line 57 of file Response.php.
{
         $this->reasonPhrases = include_once('reasonPhrases.inc.php');
         $this->setStatus(200);
         $this->headers = array();
         $this->cookies = array();
         $this->body = '';
     }
Member Function Documentation
Energine\share\gears\Response::addCookie ($name = UserSession::DEFAULT_SESSION_NAME, $value = '', $expire = 0, $domain = false, $path = '/')
Set cookies.
Parameters
string $name Session name.
string $value Value.
int $expire Expire time.
bool $domain Domain.
string $path Path.
Definition at line 126 of file Response.php.
Referenced by Energine\share\gears\Response\deleteCookie().
{
         if (!$domain) {
             if ($domain = $this->getConfigValue('site.domain')) {
                 $domain = '.' . $domain;
                 $path = '/';
             } else {
                 $path = E()->getSiteManager()->getCurrentSite()->root;
                 $domain = E()->getSiteManager()->getCurrentSite()->domain;
             }
         }
         //todo VZ: remove this?
         /*if ($this->getConfigValue('site.domain')) {
             $path = '/';
             $domain = '.' . $this->getConfigValue('site.domain');
         }
         else {
             $path = E()->getSiteManager()->getCurrentSite()->root;
             $domain = '';
         }*/
         $secure = false;
         $_COOKIE[$name] = $value;
         $this->cookies[$name] =
             compact('value', 'expire', 'path', 'domain', 'secure');
     }
Energine\share\gears\Response::commit ()
Send response to the client.
Note
This the last step.
Definition at line 256 of file Response.php.
Referenced by Energine\share\gears\Response\goBack(), and Energine\share\gears\Response\setRedirect().
{
         if (!headers_sent()) {
             $this->sendHeaders();
             $this->sendCookies();
         } else {
             //throw new SystemException('ERR_HEADERS_SENT', SystemException::ERR_CRITICAL);
         }
         $contents = $this->body;
         if ((bool)Object::_getConfigValue('site.compress')
             && isset($_SERVER['HTTP_ACCEPT_ENCODING'])
             && (strpos($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip') !== false)
             && !(bool)Object::_getConfigValue('site.debug')
         ) {
             header("Vary: Accept-Encoding");
             header("Content-Encoding: gzip");
             $contents = gzencode($contents, 6);
         }
         echo $contents;
         session_write_close();
         exit;
     }
Energine\share\gears\Response::deleteCookie ($name)
Remove cookie by name.
Parameters
string $name
Definition at line 177 of file Response.php.
{
         $this->addCookie($name, '', (time() - 1));
     }
Energine\share\gears\Response::disableCache ()
Disable cache.
Definition at line 246 of file Response.php.
{
         $this->setHeader('Cache-Control', 'no-store, no-cache, must-revalidate');
         $this->setHeader('Pragma', 'no-cache');
         $this->setHeader('X-Accel-Expires', 0);
     }
Energine\share\gears\Response::goBack ()
Go back.
See also
auth.php
Definition at line 229 of file Response.php.
{
         if (isset($_GET['return'])) {
             $url = $_GET['return'];
         }
         else if (isset($_SERVER['HTTP_REFERER'])) {
             $url = $_SERVER['HTTP_REFERER'];
         }
         else {
             $url = E()->getSiteManager()->getCurrentSite()->root;
         }
         $this->setHeader('Location', $url);
         $this->commit();
     }
static Energine\share\gears\Response::prepareRedirectURL ($redirectURL) static
Prepare redirection URL.
It replaces lang and site to the correspond values.
Parameters
string $redirectURL Redirection URL.
Returns
string
Definition at line 72 of file Response.php.
Referenced by Energine\share\gears\Document\__construct(), Energine\share\components\NavigationMenu\loadData(), and Energine\share\components\PageList\loadData().
{
         if (empty($redirectURL)) return $redirectURL;
         $lang = E()->getLanguage();
         return str_replace(
             array(
                 '%lang%',
                 '%site%'
             ),
             array(
                 $lang->getAbbrByID($lang->getCurrent()),
                 E()->getSiteManager()->getCurrentSite()->base
             ),
             $redirectURL);
     }
Energine\share\gears\Response::redirectToCurrentSection ($action = '')
Redirect to current section.
Parameters
string $action Action name.
Definition at line 202 of file Response.php.
{
         if ($action && substr($action, -1) !== '/') {
             $action .= '/';
         }
         $request = E()->getRequest();
         $this->setRedirect(
             E()->getSiteManager()->getCurrentSite()->base .
                 $request->getLangSegment()
                 . $request->getPath(Request::PATH_TEMPLATE, true)
                 . $action
         );
     }
Energine\share\gears\Response::sendCookies ()
Send cookies to the list.
This is used only in commit. It is made public for possibility to call this from capcha (but this is exception).
Definition at line 156 of file Response.php.
Referenced by Energine\share\gears\Response\commit().
{
         foreach ($this->cookies as $name => $params) {
             setcookie($name, $params['value'], $params['expire'], $params['path'], $params['domain'], $params['secure']);
         }
     }
Energine\share\gears\Response::sendHeaders ()
Send headers.
Definition at line 165 of file Response.php.
Referenced by Energine\share\gears\Response\commit().
{
         header($this->statusLine);
         foreach ($this->headers as $name => $value) {
             header("$name: $value");
         }
     }
Energine\share\gears\Response::setHeader ($name, $value, $replace = true)
Set response header.
Parameters
string $name Header name.
string $value Header value.
boolean $replace Defines whether the header value should be replaced.
Definition at line 110 of file Response.php.
Referenced by Energine\share\gears\Response\disableCache(), Energine\share\gears\Response\goBack(), and Energine\share\gears\Response\setRedirect().
{
         if ((!$replace) && isset($this->headers[$name])) {
             return;
         }
         $this->headers[$name] = $value;
     }
Energine\share\gears\Response::setRedirect ($location, $status = 302)
Set redirection URL and redirect.
Parameters
string $location Redirection URL.
int $status
Exceptions
InvalidArgumentException
Definition at line 188 of file Response.php.
Referenced by Energine\share\gears\Response\redirectToCurrentSection().
{
         if(!in_array($status, array(301, 302))) throw new InvalidArgumentException();
         $this->setStatus($status);
         $this->setHeader('Location', $location);
         $this->setHeader('Content-Length', 0);
         $this->commit();
     }
Energine\share\gears\Response::setStatus ($statusCode, $reasonPhrase = null)
Set response status.
Parameters
int $statusCode Status code.
string $reasonPhrase Reason phrase.
Definition at line 94 of file Response.php.
Referenced by Energine\share\gears\Response\__construct(), and Energine\share\gears\Response\setRedirect().
{
         if (is_null($reasonPhrase)) {
             $reasonPhrase =
                 (isset($this->reasonPhrases[$statusCode]) ? $this->reasonPhrases[$statusCode] : '');
         }
         $this->statusLine =
             ((isset($_SERVER['SERVER_PROTOCOL'])) ? $_SERVER['SERVER_PROTOCOL'] : 'UNKNOWN') . " $statusCode $reasonPhrase";
     }
Energine\share\gears\Response::write ($data)
Add data to the response body.
Parameters
string $data New data.
Definition at line 220 of file Response.php.
{
         $this->body .= $data;
     }
Member Data Documentation
string Energine\share\gears\Response::$body private
Response body.
Definition at line 55 of file Response.php.
Referenced by Energine\share\gears\Response\commit().
array Energine\share\gears\Response::$cookies private
Response cookies.
Definition at line 49 of file Response.php.
array Energine\share\gears\Response::$headers private
Response header.
Definition at line 43 of file Response.php.
mixed Energine\share\gears\Response::$reasonPhrases private
Reason phrases.
Definition at line 31 of file Response.php.
string Energine\share\gears\Response::$statusLine private
Line of the response status.
Definition at line 37 of file Response.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/Response.php