Energine: Energine\share\gears\Translit Class Reference
Energine\share\gears\Translit Class Reference
Service class for line transliteration.
Static Public Member Functions
static transliterate ($string, $wordSeparator= '', $clean=false)
Transliterate.
static asURLSegment ($string)
Cast for URL.
Private Member Functions
__construct ()
Static Private Attributes
static $cyr
Ukrainian/Russian symbols.
static $lat
Corresponded latin symbols.
Detailed Description
Service class for line transliteration.
final class Translit;
Attention
This is final.
Definition at line 28 of file Translit.php.
Constructor & Destructor Documentation
Energine\share\gears\Translit::__construct () private
Definition at line 45 of file Translit.php.
 {}
Member Function Documentation
static Energine\share\gears\Translit::asURLSegment ($string) static
Cast for URL.
Parameters
string $string String line.
Returns
string
Definition at line 92 of file Translit.php.
Referenced by Energine\share\components\FileRepository\saveDir(), Energine\share\components\WidgetsRepository\saveNewTemplate(), and Energine\apps\gears\NewsEditorSaver\setData().
{
         return strtolower(self::transliterate($string, '-', true));
     }
static Energine\share\gears\Translit::transliterate ($string, $wordSeparator = '', $clean = false) static
Transliterate.
Parameters
string $string String line.
string $wordSeparator Word separator.
bool $clean Clean transliterated line?
Returns
mixed|string
Definition at line 55 of file Translit.php.
Referenced by Energine\share\gears\SitePropertiesSaver\setData(), and Energine\share\components\FileRepository\uploadZip().
{
         //$str = iconv($encIn, "utf-8", $str);
         for($i=0; $i<count(self::$cyr); $i++){
             $string = str_replace(self::$cyr[$i], self::$lat[$i], $string);
         }
         $string = preg_replace("/([qwrtpsdfghklzxcvbnmQWRTPSDFGHKLZXCVBNM]+)[jJ]e/", "\${1}e", $string);
         $string = preg_replace("/([qwrtpsdfghklzxcvbnmQWRTPSDFGHKLZXCVBNM]+)[jJ]/", "\${1}y", $string);
         $string = preg_replace("/([eyuioaEYUIOA]+)[Kk]h/", "\${1}h", $string);
         $string = preg_replace("/^kh/", "h", $string);
         $string = preg_replace("/^Kh/", "H", $string);
         $string = trim($string);
         if ($wordSeparator) {
             $string = str_replace(' ', $wordSeparator, $string);
             $string = preg_replace('/['.$wordSeparator.']{2,}/','', $string);
         }
         if ($clean) {
             $string = strtolower($string);
             $string = preg_replace('/[^-_a-z0-9]+/','', $string);
             $string = str_replace('--', '', $string);
         }
         //return iconv("utf-8", $encOut, $str);
         return $string;
     }
Member Data Documentation
array Energine\share\gears\Translit::$cyr static private
Initial value:
= array(
    'Щ',  'Ш', 'Ч', 'Ц','Ю', 'Я', 'Ж', 'А','Б','В','Г','Д','Е','Ё','З','И','Й','К','Л','М','Н','О','П','Р','С','Т','У','Ф','Х', 'Ь','Ы','Ъ','Э','Є','Ї','І',
    'щ',  'ш', 'ч', 'ц','ю', 'я', 'ж', 'а','б','в','г','д','е','ё','з','и','й','к','л','м','н','о','п','р','с','т','у','ф','х', 'ь','ы','ъ','э','є','ї', 'і')
Ukrainian/Russian symbols.
Definition at line 33 of file Translit.php.
array Energine\share\gears\Translit::$lat static private
Initial value:
= array(
    'Shh','Sh','Ch','C','Ju','Ja','Zh','A','B','V','G','D','Je','Jo','Z','I','J','K','L','M','N','O','P','R','S','T','U','F','Kh','Y','Y','','E','Je','Ji','I',
    'shh','sh','ch','c','ju','ja','zh','a','b','v','g','d','je','jo','z','i','j','k','l','m','n','o','p','r','s','t','u','f','kh','y','y','','e','je','ji', 'i')
Corresponded latin symbols.
Definition at line 41 of file Translit.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/Translit.php