Energine: Energine\share\gears\FileRepoInfo Class Reference
Energine\share\gears\FileRepoInfo Class Reference
Alternative to FileInfo.
Public Member Functions
__construct ()
analyze ($filename, $forceReadFromFile=false)
Analyze file.
getRepositoryInstanceById ($upl_id)
Get repository instance by ID.
getRepositoryInstanceByPath ($upl_path)
Get repository instance by path.
getRepositoryRoot ($upl_path)
Get repository root path.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const META_TYPE_IMAGE = 'image'
Image meta type.
const META_TYPE_VIDEO = 'video'
Video meta type.
const META_TYPE_AUDIO = 'audio'
Audio meta type.
const META_TYPE_ZIP = 'zip'
Zip meta type.
const META_TYPE_TEXT = 'text'
Text meta type.
const META_TYPE_FOLDER = 'folder'
Folder meta type.
const META_TYPE_UNKNOWN = 'unknown'
Unknown meta type.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
getRepositoryInstanceByRepoPath ($upl_root)
Get repository instance by repository path.
Private Member Functions
getFileInfoData ($filename)
Get file information data.
Private Attributes
$finfo
File info object.
$getFInfoSQL
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Alternative to FileInfo.
class FileRepoInfo;
Definition at line 24 of file FileRepoInfo.php.
Constructor & Destructor Documentation
Energine\share\gears\FileRepoInfo::__construct ()
Definition at line 71 of file FileRepoInfo.php.
{
         parent::__construct();
         $this->finfo = new \finfo(FILEINFO_MIME_TYPE);
         $this->getFInfoSQL = $this->dbh->getPDO()->prepare('SELECT upl_internal_type as type, upl_mime_type as mime, upl_width as width, upl_height as height, upl_is_mp4 as is_mp4, upl_is_webm as is_webm, upl_is_flv as is_flv FROM share_uploads WHERE upl_path = ?');
     }
Member Function Documentation
Energine\share\gears\FileRepoInfo::analyze ($filename, $forceReadFromFile = false)
Analyze file.
Parameters
string $filename File name.
bool $forceReadFromFile
Returns
mixed|object
Exceptions
Exception
Definition at line 86 of file FileRepoInfo.php.
Referenced by Energine\share\gears\AbstractBuilder\createField().
{
         try {
             if ($forceReadFromFile
                 || !$this->getFInfoSQL->execute(array($filename))
                 || !($result = $this->getFInfoSQL->fetch(\PDO::FETCH_ASSOC))
             ) {
                 if(!($result = $this->getFileInfoData($filename))){
                     throw new \Exception();
                 }
             }
         } catch (\Exception $e) {
             $result['type'] = self::META_TYPE_UNKNOWN;
             $result['mime'] = 'unknown/mime-type';
             $result['width'] = null;
             $result['height'] = null;
             $result['is_flv'] = false;
             $result['is_webm'] = false;
             $result['is_mp4'] = false;
         }
         return (object)$result;
     }
Energine\share\gears\FileRepoInfo::getFileInfoData ($filename) private
Get file information data.
Parameters
string $filename Filename.
Returns
mixed
Definition at line 117 of file FileRepoInfo.php.
Referenced by Energine\share\gears\FileRepoInfo\analyze().
{
         $result['width'] = '';
         $result['height'] = '';
         $result['is_mp4'] = false;
         $result['is_webm'] = false;
         $result['is_flv'] = false;
         // hotfix для php на продакшне без поддержки https://
         // todo: пофиксить, до выяснения
         if (strpos($filename, 'https://') !== false) {
             $result['mime'] = 'unknown/mime-type';
             $result['type'] = self::META_TYPE_UNKNOWN;
             return $result;
         } elseif (is_dir($filename)) {
             $result['type'] = self::META_TYPE_FOLDER;
             $result['mime'] = 'unknown/mime-type';
         } elseif (!file_exists($filename)) {
             $result['mime'] = 'unknown/mime-type';
             $result['type'] = self::META_TYPE_UNKNOWN;
         } else {
             switch (
                 $result['mime'] = $this->finfo->file($filename)) {
                 case 'image/jpeg':
                 case 'image/png':
                 case 'image/gif':
                     $tmp = getimagesize($filename);
                     $result['type'] = self::META_TYPE_IMAGE;
                     $result['width'] = $tmp[0];
                     $result['height'] = $tmp[1];
                     break;
                 case 'video/x-flv':
                 case 'video/mp4':
                     $result['type'] = self::META_TYPE_VIDEO;
                     break;
                 case 'text/csv':
                 case 'text/plain':
                     $result['type'] = self::META_TYPE_TEXT;
                     break;
                 case 'application/zip':
                     $result['type'] = self::META_TYPE_ZIP;
                     break;
                 default:
                     $result['type'] =
                         self::META_TYPE_UNKNOWN;
                     break;
             }
         }
         return $result;
     }
Energine\share\gears\FileRepoInfo::getRepositoryInstanceById ($upl_id)
Get repository instance by ID.
It returns IFileRepository for processing video files into the repository.
Parameters
int $upl_id Uploads ID.
Returns
IFileRepository|FileRepositoryLocal|FileRepositoryRO
Exceptions
SystemException
Definition at line 178 of file FileRepoInfo.php.
{
         $upl_path = $this->dbh->getScalar('share_uploads', 'upl_path', array('upl_id' => $upl_id));
         $upl_root = $this->getRepositoryRoot($upl_path);
         return $this->getRepositoryInstanceByRepoPath($upl_root);
     }
Energine\share\gears\FileRepoInfo::getRepositoryInstanceByPath ($upl_path)
Get repository instance by path.
It returns IFileRepository for processing video files into the repository.
Parameters
string $upl_path Uploads path.
Returns
IFileRepository|FileRepositoryLocal|FileRepositoryRO
Exceptions
SystemException
Definition at line 194 of file FileRepoInfo.php.
{
         $upl_root = $this->getRepositoryRoot($upl_path);
         return $this->getRepositoryInstanceByRepoPath($upl_root);
     }
Energine\share\gears\FileRepoInfo::getRepositoryInstanceByRepoPath ($upl_root) protected
Get repository instance by repository path.
It returns the instance of IFileRepository by $repo_id.
Parameters
string $upl_root Uploads root path.
Returns
FileRepositoryLocal|IFileRepository
Definition at line 230 of file FileRepoInfo.php.
Referenced by Energine\share\gears\FileRepoInfo\getRepositoryInstanceById(), and Energine\share\gears\FileRepoInfo\getRepositoryInstanceByPath().
{
         $repo_id = $this->dbh->getScalar('share_uploads', 'upl_id', array('upl_path' => $upl_root));
         $cfg = E()->getConfigValue('repositories.mapping');
         if ($cfg) {
             $repo_mime = $this->dbh->getScalar('share_uploads', 'upl_mime_type', array('upl_id' => $repo_id));
             if (!empty($cfg[$repo_mime])) {
                 $repo_class_name = $cfg[$repo_mime];
                 $repo_class_name = 'Energine\\share\\gears\\'.$repo_class_name;
                 $result = new $repo_class_name($repo_id, $upl_root);
                 if ($result instanceof IFileRepository) {
                     return $result;
                 }
             }
         }
         // fallback
         $result = new FileRepositoryLocal($repo_id, 'uploads/public');
         return $result;
     }
Energine\share\gears\FileRepoInfo::getRepositoryRoot ($upl_path)
Get repository root path.
It returns repository root from the whole file path. For example uploads/public
Parameters
string $upl_path Uploads path.
Returns
string
Exceptions
SystemException
Definition at line 209 of file FileRepoInfo.php.
Referenced by Energine\share\gears\FileRepoInfo\getRepositoryInstanceById(), and Energine\share\gears\FileRepoInfo\getRepositoryInstanceByPath().
{
         $upl_junks = explode('/', $upl_path, 3);
         if (empty($upl_junks[1])) {
             //todo VZ: remove this?
             //throw new SystemException('ERR_INVALID_UPL_PATH');
             $upl_root = '';
         }
         else {
             $upl_root = $upl_junks[0] . '/' . $upl_junks[1];
         }
         return $upl_root;
     }
Member Data Documentation
finfo Energine\share\gears\FileRepoInfo::$finfo private
File info object.
Definition at line 65 of file FileRepoInfo.php.
PDOStatement Energine\share\gears\FileRepoInfo::$getFInfoSQL private
Definition at line 69 of file FileRepoInfo.php.
string Energine\share\gears\FileRepoInfo::META_TYPE_AUDIO = 'audio'
Audio meta type.
Definition at line 39 of file FileRepoInfo.php.
string Energine\share\gears\FileRepoInfo::META_TYPE_FOLDER = 'folder'
Folder meta type.
Definition at line 54 of file FileRepoInfo.php.
Referenced by Energine\share\components\FileRepository\edit(), and Energine\share\components\FileRepository\saveDir().
string Energine\share\gears\FileRepoInfo::META_TYPE_IMAGE = 'image'
Image meta type.
Definition at line 29 of file FileRepoInfo.php.
string Energine\share\gears\FileRepoInfo::META_TYPE_TEXT = 'text'
Text meta type.
Definition at line 49 of file FileRepoInfo.php.
string Energine\share\gears\FileRepoInfo::META_TYPE_UNKNOWN = 'unknown'
Unknown meta type.
Definition at line 59 of file FileRepoInfo.php.
string Energine\share\gears\FileRepoInfo::META_TYPE_VIDEO = 'video'
Video meta type.
Definition at line 34 of file FileRepoInfo.php.
Referenced by Energine\share\components\DataSet\embedPlayer().
string Energine\share\gears\FileRepoInfo::META_TYPE_ZIP = 'zip'
Zip meta type.
Definition at line 44 of file FileRepoInfo.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/FileRepoInfo.php