Energine: Energine\share\gears\ComponentManager Class Reference
Energine\share\gears\ComponentManager Class Reference
Manager of the set of the document's components.
Public Member Functions
__construct (Document $document)
register (IBlock $block)
Add new IBlock to the ComponentManager::$registeredBlocks.
add (IBlock $block)
Add new IBlock to the ComponentManager::$blocks.
addComponent (Component $component)
Add component.
getBlockByName ($name)
Get the block by his name.
createComponent ($name, $module, $class, $params=null)
Create component.
rewind ()
Rewind the Iterator to the first element.
valid ()
Checks if current position is valid.
key ()
Return the key of the current element.
next ()
Move forward to next element.
current ()
Get current element.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static createComponentFromDescription (\SimpleXMLElement $componentDescription)
Create component from XML description.
static findBlockByName (\SimpleXMLElement $containerXMLDescription, $blockName)
Find block in the component XML description by his name.
static getDescriptionFromFile ($blockDescriptionFileName)
Load the component description from the file.
static createBlockFromDescription (\SimpleXMLElement $blockDescription, $additionalProps=array())
Create block from description.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Static Private Member Functions
static _createComponent ($name, $module, $class, $params=null)
Create component by requested parameters.
Private Attributes
$registeredBlocks = array()
Set of components.
$blocks = array()
Array of blocks (IBlock).
$blockNames = array()
Array of block names.
$iteratorIndex = 0
Iterator index.
Static Private Attributes
static $document
Document.
Additional Inherited Members
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
Manager of the set of the document's components.
final class ComponentManager;
Attention
This is final.
Definition at line 28 of file ComponentManager.php.
Constructor & Destructor Documentation
Energine\share\gears\ComponentManager::__construct (Document $document)
Parameters
Document $document Document.
Definition at line 69 of file ComponentManager.php.
{
         self::$document = $document;
     }
Member Function Documentation
static Energine\share\gears\ComponentManager::_createComponent ($name, $module, $class, $params = null) static private
Create component by requested parameters.
Parameters
string $name Component name.
string $module Component module name.
$class Component class.
$params Parameters.
Returns
Component
Exceptions
SystemException
Definition at line 304 of file ComponentManager.php.
{
         try {
             $module = explode('/', $module);
             $vendorNS = 'Energine';
             if(sizeof($module) > 1){
                 $vendorNS = 'EnergineSite';
             }
             $module = array_pop($module);
             $fqClassName = $vendorNS.'\\'.$module.'\\'.'components'.'\\'.$class;
             $result = new $fqClassName($name, $module, $params);
         }
         catch (SystemException $e) {
             throw new SystemException($e->getMessage(), SystemException::ERR_DEVELOPER, array(
                 'class' => (($module !==
                         'site') ? str_replace('*', $module, CORE_COMPONENTS_DIR) :
                         SITE_COMPONENTS_DIR . $module) . '/' . $class .
                     '.php',
                 'trace' => $e->getTraceAsString()
             ));
         }
         return $result;
     }
Energine\share\gears\ComponentManager::add (IBlock $block)
Add new IBlock to the ComponentManager::$blocks.
Parameters
IBlock $block New block.
Definition at line 87 of file ComponentManager.php.
Referenced by Energine\share\gears\ComponentManager\addComponent().
{
         $this->blocks[$block->getName()] = $block;
         /*
                 $iterateContainer = function(Block $block) use(&$iterateContainer) {
                     $result = array();
                     if ($block instanceof ComponentContainer) {
                         foreach ($block as $blockChildName => $blockChild) {
                             $result[$blockChildName] = $blockChild;
                             $result = array_merge($result, $iterateContainer($blockChild));
                         }
                     }
                     else {
                          $result[$block->getName()] = $block;
                     }
                     return $result;
                 };
                 $this->blockCache = array_merge($this->blockCache, $iterateContainer($block));
          *
          */
     }
Energine\share\gears\ComponentManager::addComponent (Component $component)
Add component.
Parameters
Component $component
Deprecated:
С поялением концепции блоков нужно использовать ComponentManager::add
Definition at line 117 of file ComponentManager.php.
{
         $this->add($component);
     }
static Energine\share\gears\ComponentManager::createBlockFromDescription (\SimpleXMLElement $blockDescription, $additionalProps = array()) static
Create block from description.
Parameters
\SimpleXMLElement $blockDescription Block description.
array $additionalProps Additional properties.
Returns
IBlock
Exceptions
SystemException ERR_UNKNOWN_BLOCKTYPE
Definition at line 268 of file ComponentManager.php.
Referenced by Energine\share\components\WidgetsRepository\buildWidget(), Energine\share\gears\ComponentContainer\createFromDescription(), Energine\share\gears\Document\loadComponents(), and Energine\apps\components\NewsRepository\showSmapSelector().
{
         $result = false;
         switch ($blockDescription->getName()) {
             case 'content':
                 $props = array_merge(array('tag' => 'content'), $additionalProps);
                 $result = ComponentContainer::createFromDescription($blockDescription, $props);
                 break;
             case 'page':
                 $props = array_merge(array('tag' => 'layout'), $additionalProps);
                 $result = ComponentContainer::createFromDescription($blockDescription, $props);
                 break;
             case 'container':
                 $result = ComponentContainer::createFromDescription($blockDescription);
                 break;
             case 'component':
                 $result = self::createComponentFromDescription($blockDescription);
                 break;
             default:
                 throw new SystemException('ERR_UNKNOWN_BLOCKTYPE', SystemException::ERR_CRITICAL);
                 break;
         }
         return $result;
     }
Energine\share\gears\ComponentManager::createComponent ($name, $module, $class, $params = null)
Create component.
Parameters
string $name Component name.
string $module Component module name.
string $class Component class.
array $params Component properties.
Returns
Component
Definition at line 213 of file ComponentManager.php.
{
         return call_user_func_array(array('Energine\\share\\gears\\ComponentManager', '_createComponent'), func_get_args());
     }
static Energine\share\gears\ComponentManager::createComponentFromDescription (\SimpleXMLElement $componentDescription) static
Create component from XML description.
Parameters
\SimpleXMLElement $componentDescription Component description.
Returns
Component
Exceptions
SystemException ERR_DEV_NO_REQUIRED_ATTRIB [attribute_name]
Definition at line 143 of file ComponentManager.php.
{
         // перечень необходимых атрибутов компонента
         $requiredAttributes = array('name', 'module', 'class');
         $name = $class = $module = null;
         //после отработки итератора должны получить $name, $module, $class
         foreach ($requiredAttributes as $attrName) {
             if (!isset($componentDescription[$attrName])) {
                 throw new SystemException("ERR_DEV_NO_REQUIRED_ATTRIB $attrName", SystemException::ERR_DEVELOPER);
             }
             $$attrName = (string) $componentDescription[$attrName];
         }
         // извлекаем параметры компонента
         $params = null;
         if (isset($componentDescription->params)) {
             $params = array();
             foreach ($componentDescription->params->param as $tagName => $paramDescr) {
                 if ($tagName == 'param') {
                     if (isset($paramDescr['name'])) {
                         $paramName = (string) $paramDescr['name'];
                         //Если count больше ноля значит это вложенный SimpleXML елемент
                         if(!$paramDescr->count()){
                             $paramValue = (string)$paramDescr;
                         }
                         else {
                             list($paramValue) = $paramDescr->children();
                         }
                         //$paramValue = (string) $paramDescr;
                         //Если в массиве параметров уже существует параметр с таким именем, превращаем этот параметр в массив
                         if (isset($params[$paramName])) {
                             if (!is_array($params[$paramName])) {
                                 $params[$paramName] =
                                     array($params[$paramName]);
                             }
                             array_push($params[$paramName], $paramValue);
                         }
                         else {
                             $params[$paramName] = $paramValue;
                         }
                     }
                 }
             }
         }
         /*        $result = false;
                 if(
                     !isset($params['rights'])
                     ||
                     (isset($params['rights']) && self::$document->getRights() >= $params['rights'])
                 ) {
                     $result = self::_createComponent($name, $module, $class, $params);
                 }*/
         $result = self::_createComponent($name, $module, $class, $params);
         return $result;
     }
Energine\share\gears\ComponentManager::current ()
Get current element.
Returns
mixed
http://php.net/manual/en/iterator.current.php
Implements Iterator.
Definition at line 344 of file ComponentManager.php.
{
         return $this->blocks[$this->blockNames[$this->iteratorIndex]];
     }
static Energine\share\gears\ComponentManager::findBlockByName (\SimpleXMLElement $containerXMLDescription, $blockName) static
Find block in the component XML description by his name.
Parameters
\SimpleXMLElement $containerXMLDescription Component descriptions.
string $blockName Block name.
Returns
IBlock|bool
Definition at line 224 of file ComponentManager.php.
Referenced by Energine\share\components\WidgetsRepository\buildParamsForm(), and Energine\share\gears\Document\loadComponents().
{
         $blocks = $containerXMLDescription->xpath(
             'descendant-or-self::*[name()="container" or name() = "component"]' .
             '[@name="' . $blockName . '"]'
         );
         if (!empty($blocks)) {
             list($blocks) = $blocks;
         }
         else {
             $blocks = false;
         }
         return $blocks;
     }
Energine\share\gears\ComponentManager::getBlockByName ($name)
Get the block by his name.
Parameters
string $name Block name.
Returns
Component
Definition at line 127 of file ComponentManager.php.
{
         $result = false;
         if (isset($this->registeredBlocks[$name])) {
             $result = $this->registeredBlocks[$name];
         }
         return $result;
     }
static Energine\share\gears\ComponentManager::getDescriptionFromFile ($blockDescriptionFileName) static
Load the component description from the file.
Parameters
string $blockDescriptionFileName File name.
Returns
Exceptions
SystemException ERR_DEV_NO_CONTAINER_FILE
SystemException ERR_DEV_BAD_CONTAINER_FILE
Definition at line 248 of file ComponentManager.php.
Referenced by Energine\apps\components\NewsRepository\showSmapSelector().
{
         if (!file_exists($blockDescriptionFileName)) {
             throw new SystemException('ERR_DEV_NO_CONTAINER_FILE', SystemException::ERR_CRITICAL, $blockDescriptionFileName);
         }
         if (!($blockDescription = simplexml_load_file($blockDescriptionFileName))) {
             throw new SystemException('ERR_DEV_BAD_CONTAINER_FILE', SystemException::ERR_CRITICAL, $blockDescriptionFileName);
         }
         return $blockDescription;
     }
Energine\share\gears\ComponentManager::key ()
Return the key of the current element.
Returns
mixed
http://php.net/manual/en/iterator.key.php
Implements Iterator.
Definition at line 336 of file ComponentManager.php.
{
         return $this->blockNames[$this->iteratorIndex];
     }
Energine\share\gears\ComponentManager::next ()
Move forward to next element.
http://php.net/manual/en/iterator.next.php
Implements Iterator.
Definition at line 340 of file ComponentManager.php.
{
         $this->iteratorIndex++;
     }
Energine\share\gears\ComponentManager::register (IBlock $block)
Add new IBlock to the ComponentManager::$registeredBlocks.
Parameters
IBlock $block New block.
Definition at line 78 of file ComponentManager.php.
{
         $this->registeredBlocks[$block->getName()]  = $block;
     }
Energine\share\gears\ComponentManager::rewind ()
Rewind the Iterator to the first element.
Returns
bool
http://php.net/manual/en/iterator.rewind.php
Implements Iterator.
Definition at line 327 of file ComponentManager.php.
{
         $this->blockNames = array_keys($this->blocks);
         $this->iteratorIndex = 0;
     }
Energine\share\gears\ComponentManager::valid ()
Checks if current position is valid.
Returns
bool
http://php.net/manual/en/iterator.valid.php
Implements Iterator.
Definition at line 332 of file ComponentManager.php.
{
         return isset($this->blockNames[$this->iteratorIndex]);
     }
Member Data Documentation
array Energine\share\gears\ComponentManager::$blockNames = array() private
Array of block names.
This used for increasing the iterations. It is filled by ComponentManager::rewind method.
Definition at line 59 of file ComponentManager.php.
array Energine\share\gears\ComponentManager::$blocks = array() private
Array of blocks (IBlock).
It can contain components and containers.
Definition at line 51 of file ComponentManager.php.
Referenced by Energine\share\gears\ComponentManager\findBlockByName().
Document Energine\share\gears\ComponentManager::$document static private
Document.
Definition at line 43 of file ComponentManager.php.
Referenced by Energine\share\gears\ComponentManager\__construct().
int Energine\share\gears\ComponentManager::$iteratorIndex = 0 private
Iterator index.
Definition at line 64 of file ComponentManager.php.
Referenced by Energine\share\gears\ComponentManager\current(), and Energine\share\gears\ComponentManager\key().
array Energine\share\gears\ComponentManager::$registeredBlocks = array() private
Set of components.
This set is used to quick find the component by ComponentManager::getComponentByName. It is filled by adding an component in the stream.
Definition at line 37 of file ComponentManager.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/ComponentManager.php