Energine: Energine\comments\components\CommentsList Class Reference
Energine\comments\components\CommentsList Class Reference
List of comments.
Public Member Functions
__construct ($name, $module, array $params=null)
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Member Functions
createDataDescription ()
Create data description.
createBuilder ()
Create builder.
createPager ()
Create pager.
loadData ()
Load data.
defineParams ()
main ()
Default action.
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
Возвращает описание данных
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Protected Attributes
$isTree = false
Are the comments tree-like?
$targetIds = array()
Comment ID(s).
$comments = null
Comments.
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Member Functions
addUsersInfo ($data)
Add information about users.
getUsersByComments ($data)
Get users who left comments.
Private Attributes
$loadedData = null
Loaded data.
$commentsFieldName = ''
Comment field name.
$bindComponent = null
Component to which this list is bound.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
List of comments.
class CommentsList;
Usage example:
$commentsParams = array(
    'table_name' => $this->getTableName(),
    'is_tree' => false,
    'target_ids' => $this->getData()->getFieldByName('news_id')->getData()
);
$commentsList = $this->document->componentManager->createComponent('commentsList', 'comments', 'CommentsList', $commentsParams);
$commentsList->run();
$this->document->componentManager->addComponent($commentsList);
Definition at line 37 of file CommentsList.php.
Constructor & Destructor Documentation
Energine\comments\components\CommentsList::__construct ($name, $module, array $params = null)
Definition at line 85 of file CommentsList.php.
{
         parent::__construct($name, $module, $params);
         $this->setProperty('exttype', 'comments');
         $this->setType(self::COMPONENT_TYPE_LIST);
         $commentTable = $this->dbh->tableExists(
             $this->getParam('table_name') . '_comment');
         $this->isTree = $this->getParam('is_tree');
         $this->setProperty('is_tree', $this->isTree);
         $right = $this->document->getRights();
         $this->setProperty('is_editable', (int) (
                 $right > 1)); // добавлять и править/удалять своё
         $this->setProperty('is_admin', (int) ($right > 2)); // godmode
         if (E()->getAUser()->isAuthenticated()) {
             $this->document->setProperty('CURRENT_UID', E()->getAUser()->getID());
         }
         $this->targetIds = $this->getParam('target_ids');
         $this->comments = new Comments($commentTable, $this->isTree);
     }
Member Function Documentation
Energine\comments\components\CommentsList::addUsersInfo ($data) private
Add information about users.
Parameters
array $data Data.
Returns
array
Definition at line 258 of file CommentsList.php.
Referenced by Energine\comments\components\CommentsList\loadData().
{
         if ($data && is_array($data)) {
             $usersInfo = $this->getUsersByComments($data);
             $usersInfo = convertDBResult($usersInfo, 'u_id');
             foreach ($data as &$item) {
                 if ($item['u_id']) {
                     $user = $usersInfo[$item['u_id']];
                     $item['u_nick'] =
                             trim($user['u_nick']) ? trim($user['u_nick']) : $user['u_fullname'];
                 } else {
                     $item['u_nick'] = $item['comment_nick'];
                 }
             }
         }
         return $data;
     }
Energine\comments\components\CommentsList::createBuilder () protected
Create builder.
Returns
AbstractBuilder
Definition at line 161 of file CommentsList.php.
{
         if ($this->isTree and is_array($data = $this->loadData())) {
             $builder = new TreeBuilder();
             $tree =
                     TreeConverter::convert($data, 'comment_id', 'comment_parent_id');
             $builder->setTree($tree);
         }
         else {
             $builder = parent::createBuilder();
         }
         $this->builder = $builder;
         return $this->builder;
     }
Energine\comments\components\CommentsList::createDataDescription () protected
Create data description.
Returns
DataDescription
Exceptions
SystemException 'ERR_DEV_LOAD_DATA_DESCR_IS_FUNCTION'
Definition at line 113 of file CommentsList.php.
{
         $dataDescription = new DataDescription();
         $fd = new FieldDescription('comment_id');
         $fd->setType(FieldDescription::FIELD_TYPE_INT);
         $fd->setProperty('key', true); // для построения дерева
         $dataDescription->addFieldDescription($fd);
         // если у нас древовидная структура - добавляем предка
         if ($this->isTree) {
             $fd = new FieldDescription('comment_parent_id');
             $fd->setType(FieldDescription::FIELD_TYPE_INT);
             $dataDescription->addFieldDescription($fd);
         }
         // комментиркемая сущность
         $fd = new FieldDescription('target_id');
         $fd->setType(FieldDescription::FIELD_TYPE_INT);
         $dataDescription->addFieldDescription($fd);
         $fd = new FieldDescription('u_id');
         $fd->setType(FieldDescription::FIELD_TYPE_INT);
         $dataDescription->addFieldDescription($fd);
         $fd = new FieldDescription('comment_created');
         $fd->setType(FieldDescription::FIELD_TYPE_DATETIME)->setProperty('outputFormat', '%E');
         $dataDescription->addFieldDescription($fd);
         $fd = new FieldDescription('comment_name');
         $fd->setType(FieldDescription::FIELD_TYPE_STRING);
         $dataDescription->addFieldDescription($fd);
         $fd = new FieldDescription('comment_approved');
         $fd->setType(FieldDescription::FIELD_TYPE_BOOL);
         $dataDescription->addFieldDescription($fd);
         // Инфа о юзере
         $fd = new FieldDescription('u_nick');
         $fd->setType(FieldDescription::FIELD_TYPE_STRING);
         $dataDescription->addFieldDescription($fd);
         return $dataDescription;
     }
Energine\comments\components\CommentsList::createPager () protected
Create pager.
Definition at line 179 of file CommentsList.php.
Referenced by Energine\comments\components\CommentsList\loadData().
{
         if (!$this->pager) {
             $recordsPerPage = intval($this->getParam('recordsPerPage'));
             if ($recordsPerPage > 0) {
                 $this->pager = new Pager($recordsPerPage);
                 if ($this->isActive() &&
                         $this->getType() == self::COMPONENT_TYPE_LIST) {
                     $actionParams = $this->getStateParams(true);
                     if (
                             !isset($actionParams['pageNumber'])
                             ||
                             (
                                 !($page = intval($actionParams['pageNumber']))
                                 &&
                                 ($actionParams['pageNumber'] !== 'last')
                             )
                     ) {
                         $page = 1;
                     }
                     elseif($actionParams['pageNumber'] === 'last'){
                         $page = $this->comments->getPageCount($this->targetIds, $recordsPerPage);
                     }
                     $this->pager->setCurrentPage($page);
                 }
                 $this->pager->setProperty('title', $this->translate('TXT_PAGES'));
             }
         }
     }
Energine\comments\components\CommentsList::defineParams () protected
Definition at line 239 of file CommentsList.php.
{
         return array_merge(
             parent::defineParams(),
             array(
                 'table_name' => '',
                 'is_tree' => 0,
                 'target_ids' => array(),
                 'bind' => '',
                 'commentsFieldName' => 'comments',
             )
         );
     }
Energine\comments\components\CommentsList::getUsersByComments ($data) private
Get users who left comments.
Информация о юзерах оставивших комментарии
Parameters
array $data
Returns
array
Definition at line 284 of file CommentsList.php.
Referenced by Energine\comments\components\CommentsList\addUsersInfo().
{
         $result = array();
         if ($data && is_array($data)) {
             $userIds = array();
             foreach ($data as $item) {
                 if ($item['u_id']) {
                     $userIds[] = $item['u_id'];
                 }
             }
             $userIds = array_unique($userIds);
             if ($userIds) {
                 $userIds = implode(',', $userIds);
                 $result = $this->dbh->selectRequest(
                     'SELECT u.* ' .
                             " FROM user_users u
                      WHERE u.u_id in($userIds)"
                 );
             }
         }
         return $result;
     }
Energine\comments\components\CommentsList::loadData () protected
Load data.
Returns
mixed
Definition at line 213 of file CommentsList.php.
Referenced by Energine\comments\components\CommentsList\createBuilder().
{
         if (is_null($this->loadedData)) {
             $this->createPager();
             $limitArr = null;
             if (!$this->isTree and $this->pager) {
                 // pager существует -- загружаем только часть данных, текущую страницу
                 $limitArr = $this->pager->getLimit();
             }
             $this->loadedData =
                     $this->comments->getListByIds($this->targetIds, $limitArr);
             if ($this->pager and $limitArr) {
                 $this->setType(self::COMPONENT_TYPE_LIST);
                 $this->pager->setRecordsCount($this->comments->getCountByLastList());
             }
             $this->loadedData = $this->addUsersInfo($this->loadedData);
             $this->setProperty('comment_count', is_array($this->loadedData) ? count($this->loadedData) : 0);
         }
         return $this->loadedData;
     }
Energine\comments\components\CommentsList::main () protected
Default action.
Returns
boolean
Definition at line 312 of file CommentsList.php.
{
         parent::main();
         if ($this->getParam('bind')) {
             $this->bindComponent =
                     $this->document->componentManager->getBlockByName($this->getParam('bind'));
             if (!$this->isTree and $this->pager) {
                 $ap = $this->bindComponent->getStateParams(true);
                 $subUrl = '';
                 if (isset($ap['themeID'])) {
                     $subUrl = $ap['themeID'] . '/';
                 }
                 $this->pager->setProperty('additional_url', $subUrl);
             }
         }
     }
Member Data Documentation
Component Energine\comments\components\CommentsList::$bindComponent = null private
Component to which this list is bound.
Definition at line 74 of file CommentsList.php.
Comments Energine\comments\components\CommentsList::$comments = null protected
Comments.
Definition at line 60 of file CommentsList.php.
string Energine\comments\components\CommentsList::$commentsFieldName = '' private
Comment field name.
Definition at line 67 of file CommentsList.php.
bool Energine\comments\components\CommentsList::$isTree = false protected
Are the comments tree-like?
Definition at line 42 of file CommentsList.php.
array Energine\comments\components\CommentsList::$loadedData = null private
Loaded data.
Definition at line 54 of file CommentsList.php.
Referenced by Energine\comments\components\CommentsList\loadData().
int array Energine\comments\components\CommentsList::$targetIds = array() protected
Comment ID(s).
Definition at line 48 of file CommentsList.php.
The documentation for this class was generated from the following file:
core/modules/comments/components/CommentsList.php