Energine: Energine\share\gears\URI Class Reference
Energine\share\gears\URI Class Reference
URI (Unified Resource Identifier).
Public Member Functions
__construct ($uri)
setScheme ($scheme)
Set scheme (protocol)
getScheme ()
Get scheme (protocol).
setHost ($host)
Set host name.
getHost ()
Get host name.
setPort ($port)
Set port number.
getPort ()
Get port.
setPath ($path)
Set path.
getPath ($asString=true)
Get path.
getPathSegment ($pos)
Get path segment with $pos index.
setQuery ($query)
Set query.
getQuery ()
Get query.
setFragment ($fragment)
Set document fragment.
getFragment ()
Get document fragment.
__toString ()
Get URI as string.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static validate ($uri)
Validate URI.
static create ($uriString= '')
Create URI.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Private Attributes
$scheme
Request scheme (protocol).
$host
Host name.
$path
Path.
$query
Query of parameters.
$fragment
Document fragment ID.
$port
Port number.
Static Private Attributes
static $trick
Trick for imitation of private constructor.
Additional Inherited Members
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
URI (Unified Resource Identifier).
Attention
This is final.
Definition at line 23 of file URI.php.
Constructor & Destructor Documentation
Energine\share\gears\URI::__construct ($uri)
Parameters
string $uri URI.
Exceptions
SystemException 'ERR_PRIVATE_CONSTRUCTOR'
Definition at line 71 of file URI.php.
{
         if(is_null(self::$trick)){
             throw new SystemException('ERR_PRIVATE_CONSTRUCTOR', SystemException::ERR_DEVELOPER);
         }
         $matches = array();
         if($uri && ($matches = self::validate($uri))){
             $this->setScheme($matches[0]);
             $this->setHost($matches[1]);
             $this->setPort($matches[2]);
             $this->setPath($matches[3]);
             $this->setQuery(isset($matches[4]) ? $matches[4] : '');
         }
         else {
             $this->scheme = $this->host = $this->path = $this->query = $this->fragment = '';
         }
     }
Member Function Documentation
Energine\share\gears\URI::__toString ()
Get URI as string.
Returns
string
Definition at line 271 of file URI.php.
{
         if (!empty($this->scheme) && !empty($this->host)) {
             return $this->scheme.'://'.$this->host.
             (empty($this->path) ? '/' : $this->getPath(true)).
             (empty($this->query) ? '' : '?'.$this->query).
             (empty($this->fragment) ? '' : '#'.$this->fragment);
         }
         else {
             return '';
         }
     }
static Energine\share\gears\URI::create ($uriString = '') static
Create URI.
Parameters
string $uriString URI string.
Returns
URI
Definition at line 112 of file URI.php.
Referenced by Energine\share\gears\SiteManager\__construct(), and Energine\share\gears\Request\__construct().
{
         self::$trick = true;
         if(!$uriString){
             $host = explode(':', ((isset($_SERVER['HTTP_HOST']))?$_SERVER['HTTP_HOST']:$_SERVER['SERVER_NAME']));
             $protocol = (isset($_SERVER['HTTPS']) ? 'https' : 'http');
             if(sizeof($host) == 1){
                 $port = ($protocol == 'http')?80:443;
                 list($host) = $host;
             }
             else{
                 list($host, $port) = $host;
             }
             $uriString = $protocol.'://'.$host.':'.$port.$_SERVER['REQUEST_URI'];
         }
         return new URI($uriString);
     }
Energine\share\gears\URI::getFragment ()
Get document fragment.
Returns
string
Definition at line 262 of file URI.php.
{
         return $this->fragment;
     }
Energine\share\gears\URI::getHost ()
Get host name.
Returns
string
Definition at line 162 of file URI.php.
{
         return $this->host;
     }
Energine\share\gears\URI::getPath ($asString = true)
Get path.
Parameters
boolean $asString Return as string?
Returns
array|string
Definition at line 204 of file URI.php.
Referenced by Energine\share\gears\URI\__toString().
{
         $path = $this->path;
         if ($asString) {
             if (!empty($path)) {
                 $path = '/'.implode('/', $path).'/';
             }
             else {
                 $path = '/';
             }
         }
         return $path;
     }
Energine\share\gears\URI::getPathSegment ($pos)
Get path segment with $pos index.
Parameters
int $pos Position
Returns
string
Definition at line 223 of file URI.php.
{
         if (isset($this->path[$pos])) {
             return $this->path[$pos];
         }
         return '';
     }
Energine\share\gears\URI::getPort ()
Get port.
Returns
int
Definition at line 182 of file URI.php.
{
         return $this->port;
     }
Energine\share\gears\URI::getQuery ()
Get query.
Returns
string
Definition at line 244 of file URI.php.
{
         return $this->query;
     }
Energine\share\gears\URI::getScheme ()
Get scheme (protocol).
Returns
string
Definition at line 145 of file URI.php.
{
         return $this->scheme;
     }
Energine\share\gears\URI::setFragment ($fragment)
Set document fragment.
Parameters
string $fragment Document fragment.
Definition at line 253 of file URI.php.
{
         $this->fragment = strval($fragment);
     }
Energine\share\gears\URI::setHost ($host)
Set host name.
Parameters
string $host Host name.
Definition at line 154 of file URI.php.
Referenced by Energine\share\gears\URI\__construct().
{
         $this->host = strtolower($host);
     }
Energine\share\gears\URI::setPath ($path)
Set path.
Parameters
string $path Path.
Definition at line 191 of file URI.php.
Referenced by Energine\share\gears\URI\__construct().
{
         if (!is_array($path)) {
             $path = array_values(array_diff(explode('/', $path), array('')));
         }
         $this->path = $path;
     }
Energine\share\gears\URI::setPort ($port)
Set port number.
If $port is not defined, then the port 80 will be used.
Parameters
int $port Port number.
Definition at line 172 of file URI.php.
Referenced by Energine\share\gears\URI\__construct().
{
         if(!$port) $port = 80;
         $this->port = $port;
     }
Energine\share\gears\URI::setQuery ($query)
Set query.
Parameters
string $query Query.
Definition at line 235 of file URI.php.
Referenced by Energine\share\gears\URI\__construct().
{
         $this->query = strval($query);
     }
Energine\share\gears\URI::setScheme ($scheme)
Set scheme (protocol)
Parameters
string $scheme Scheme.
Definition at line 136 of file URI.php.
Referenced by Energine\share\gears\URI\__construct().
{
         $this->scheme = strtolower($scheme);
     }
static Energine\share\gears\URI::validate ($uri) static
Validate URI.
It returns an array of matched strings.
Parameters
string $uri URI
Returns
array|bool
Definition at line 97 of file URI.php.
{
         $result = false;
         if(preg_match('/^(\w+):\/\/([a-z0-9\.\-]+)\:?([0-9]{2,5})?(\/[^?]*)[\?]?(.*)?$/i', $uri, $matches) && count($matches) >= 5){
             array_shift($matches);
             $result = $matches;
         }
         return $result;
     }
Member Data Documentation
string Energine\share\gears\URI::$fragment private
Document fragment ID.
Definition at line 52 of file URI.php.
Referenced by Energine\share\gears\URI\getFragment(), and Energine\share\gears\URI\setFragment().
string Energine\share\gears\URI::$host private
Host name.
Definition at line 34 of file URI.php.
Referenced by Energine\share\gears\URI\create(), Energine\share\gears\URI\getHost(), and Energine\share\gears\URI\setHost().
array Energine\share\gears\URI::$path private
Path.
Definition at line 40 of file URI.php.
Referenced by Energine\share\gears\URI\getPath(), and Energine\share\gears\URI\setPath().
int Energine\share\gears\URI::$port private
Port number.
Definition at line 64 of file URI.php.
Referenced by Energine\share\gears\URI\create(), Energine\share\gears\URI\getPort(), and Energine\share\gears\URI\setPort().
string Energine\share\gears\URI::$query private
Query of parameters.
Definition at line 46 of file URI.php.
Referenced by Energine\share\gears\URI\getQuery(), and Energine\share\gears\URI\setQuery().
string Energine\share\gears\URI::$scheme private
Request scheme (protocol).
Definition at line 28 of file URI.php.
Referenced by Energine\share\gears\URI\getScheme(), and Energine\share\gears\URI\setScheme().
bool Energine\share\gears\URI::$trick static private
Trick for imitation of private constructor.
Definition at line 58 of file URI.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/URI.php