Energine: Energine\share\gears\FileUploader Class Reference
Energine\share\gears\FileUploader Class Reference
File uploader for the server.
Public Member Functions
__construct (Array $restrictions=array())
setRestrictions (array $restrictions)
Set uploaded file restrictions.
setFile (array $file)
Set file description.
validate ()
Validate uploaded file.
upload ($dir)
Upload file into the directory.
getFileObjectName ()
Get the uploaded filename on the server side.
getFileRealName ()
Get the filename on the client side.
getExtension ()
Get the file extension.
cleanUp ()
Clean the object properties for further reuse.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Member Functions
generateFilename ($dir, $ext)
Generate filename.
Protected Attributes
$file = array()
Description of uploaded file.
$FileObjectName
Filename on the server side.
$FileRealName
Filename on the client side.
Private Attributes
$restrictions = array()
Restriction for uploaded file.
$ext
File extension.
$uploadsPath = ''
Root path of uploaded files.
$validated = false
Validation flag.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
File uploader for the server.
class FileUploader;
Definition at line 25 of file FileUploader.php.
Constructor & Destructor Documentation
Energine\share\gears\FileUploader::__construct (Array $restrictions = array())
Parameters
array $restrictions File restrictions.
Definition at line 77 of file FileUploader.php.
{
         $this->restrictions = $restrictions;
     }
Member Function Documentation
Energine\share\gears\FileUploader::cleanUp ()
Clean the object properties for further reuse.
Definition at line 253 of file FileUploader.php.
{
         $this->restrictions = array();
         $this->ext = null;
         $this->FileObjectName = null;
         $this->validated = false;
     }
Energine\share\gears\FileUploader::generateFilename ($dir, $ext) protected
Generate filename.
Parameters
string $dir Directory.
string $ext File extension.
Returns
string
Definition at line 211 of file FileUploader.php.
Referenced by Energine\share\gears\VideoUploader\upload(), and Energine\share\gears\FileUploader\upload().
{
         if ($dir[0] == '/') {
             $dir = substr($dir, 1);
         }
         if ($dir[strlen($dir)-1] != '/') {
             $dir .= '/';
         }
         return $this->uploadsPath.$dir.FileRepository::generateFilename($this->uploadsPath.$dir, $ext);
     }
Energine\share\gears\FileUploader::getExtension ()
Get the file extension.
Returns
string
Definition at line 246 of file FileUploader.php.
Referenced by Energine\share\gears\VideoUploader\upload().
{
         return $this->ext;
     }
Energine\share\gears\FileUploader::getFileObjectName ()
Get the uploaded filename on the server side.
Returns
string
Definition at line 227 of file FileUploader.php.
{
         return $this->FileObjectName;
     }
Energine\share\gears\FileUploader::getFileRealName ()
Get the filename on the client side.
Returns
string
Definition at line 237 of file FileUploader.php.
{
         return $this->FileRealName;
     }
Energine\share\gears\FileUploader::setFile (array $file)
Set file description.
Parameters
array $file File.
Exceptions
SystemException 'ERR_DEV_BAD_DATA'
SystemException 'ERR_NO_FILE'
SystemException 'ERR_UPLOAD_FAILED'
Definition at line 106 of file FileUploader.php.
{
         if (!isset($file['name'], $file['size'], $file['tmp_name'], $file['error'])) {
             throw new SystemException('ERR_DEV_BAD_DATA', SystemException::ERR_DEVELOPER, $file);
         }
         if ($file['error'] == UPLOAD_ERR_NO_FILE){
             throw new SystemException('ERR_NO_FILE', SystemException::ERR_NOTICE, $file);
         }
         if($file['error'] != UPLOAD_ERR_OK || !is_uploaded_file($file['tmp_name'])) {
             throw new SystemException('ERR_UPLOAD_FAILED', SystemException::ERR_WARNING, $file['error']);
         }
         $this->file = $file;
         $this->validate();
     }
Energine\share\gears\FileUploader::setRestrictions (array $restrictions)
Set uploaded file restrictions.
array(
    'ext' => array('jpg', 'gif')
)
Parameters
array $restrictions Restriction
Definition at line 93 of file FileUploader.php.
{
         $this->restrictions = $restrictions;
     }
Energine\share\gears\FileUploader::upload ($dir)
Upload file into the directory.
Parameters
string $dir Directory within the root directory of the downloaded files. ()
Returns
boolean
Exceptions
SystemException 'ERR_DEV_UPLOAD_FAILED'
Definition at line 159 of file FileUploader.php.
{
         if (!$this->validated) {
             $this->validate();
         }
         $filePath = $this->generateFilename($dir, $this->ext);
         if (
             !@move_uploaded_file(
                 $this->file['tmp_name'],
                 $filePath
             )
         ) {
             throw new SystemException('ERR_DEV_UPLOAD_FAILED', SystemException::ERR_WARNING, $this->file['name']);
         }
         //@todo
         //
         /*
         if(in_array($this->getExtension(), array('gif', 'png', 'jpg', 'jpeg'))){
 //            $img = new Image();
 //            $img->loadFromFile($filePath);
 //
 //            if(($img->getWidth()> 800) && ($img->getHeight() > 600)){
 //              $img->resize(800, 600);
 //              $img->saveToFile($filePath);
 //            }
 //            unset($image);
             // ------------------------
 //            elseif($img->getWidth()> 800){
 //              $img->resize(800, null);
 //                $img->saveToFile($filePath);
 //            }
 //            elseif($img->getHeight()> 600){
 //                $img->resize(null, 600);
 //                $img->saveToFile($filePath);
 //            }
         }
         */
         $this->FileRealName = $this->file['name'];
         $this->FileObjectName = $filePath;
         chmod($this->FileObjectName, 0666);
         return true;
     }
Energine\share\gears\FileUploader::validate ()
Validate uploaded file.
Returns
boolean
Exceptions
SystemException 'ERR_DEV_BAD_DATA'
SystemException 'ERR_BAD_FILE_TYPE'
Definition at line 131 of file FileUploader.php.
Referenced by Energine\share\gears\FileUploader\setFile(), and Energine\share\gears\FileUploader\upload().
{
         //     MIME type,     .
         if (empty($this->file)) {
             throw new SystemException('ERR_DEV_BAD_DATA', SystemException::ERR_DEVELOPER, $this->file['name']);
         }
         $dummy = explode('.', $this->file['name']);
         $this->ext = array_pop($dummy);
         if(isset($this->restrictions['ext'])){
             if(!in_array($this->ext, $this->restrictions['ext'])){
                 throw new SystemException('ERR_BAD_FILE_TYPE', SystemException::ERR_DEVELOPER, $this->file['name']);
             }
         }
         return ($this->validated = true);
     }
Member Data Documentation
string Energine\share\gears\FileUploader::$ext private
File extension.
Definition at line 46 of file FileUploader.php.
Referenced by Energine\share\gears\FileUploader\generateFilename(), and Energine\share\gears\FileUploader\getExtension().
array Energine\share\gears\FileUploader::$file = array() protected
Description of uploaded file.
$_FILES
See also
PHP manual, POST method uploads
Definition at line 34 of file FileUploader.php.
Referenced by Energine\share\gears\FileUploader\setFile().
string Energine\share\gears\FileUploader::$FileObjectName protected
Filename on the server side.
Definition at line 52 of file FileUploader.php.
Referenced by Energine\share\gears\FileUploader\getFileObjectName().
string Energine\share\gears\FileUploader::$FileRealName protected
Filename on the client side.
Definition at line 59 of file FileUploader.php.
Referenced by Energine\share\gears\FileUploader\getFileRealName().
array Energine\share\gears\FileUploader::$restrictions = array() private
Restriction for uploaded file.
Definition at line 40 of file FileUploader.php.
Referenced by Energine\share\gears\VideoUploader\__construct(), Energine\share\gears\FileUploader\__construct(), and Energine\share\gears\FileUploader\setRestrictions().
string Energine\share\gears\FileUploader::$uploadsPath = '' private
Root path of uploaded files.
Definition at line 65 of file FileUploader.php.
boolean Energine\share\gears\FileUploader::$validated = false private
Validation flag.
It indicates whether the validation was done (this can be checked with upload);
Definition at line 72 of file FileUploader.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/FileUploader.php