Energine: Energine\apps\components\Vote Class Reference
Energine\apps\components\Vote Class Reference
Voting by discussions.
Public Member Functions
__construct ($name, $module, array $params=null)
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const VOTED_COOKIE_PREFIX = 'nrgn_voted_'
Vote prefix for cookie.
const COOKIE_LIFETIME = 86400
Cookie lifespan.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
main ()
Default action.
createBuilder ()
Create builder.
getVote ()
Get vote.
vote ()
Vote.
prepare ()
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
Возвращает описание данных
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Private Member Functions
isUserCanVote ($voteID)
Check if the user can vote.
getVoteResults ($voteID)
Get vote result.
Private Attributes
$voteID
Vote ID.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Voting by discussions.
class Vote;
Definition at line 25 of file Vote.php.
Constructor & Destructor Documentation
Energine\apps\components\Vote::__construct ($name, $module, array $params = null)
Definition at line 47 of file Vote.php.
{
         $params['active'] = true;
         parent::__construct($name, $module, $params);
         $this->setProperty('recordsPerPage', false);
     }
Member Function Documentation
Energine\apps\components\Vote::createBuilder () protected
Create builder.
Returns
AbstractBuilder
Definition at line 71 of file Vote.php.
Referenced by Energine\apps\components\Vote\prepare().
{
         return new SimpleBuilder();
     }
Energine\apps\components\Vote::getVote () protected
Get vote.
Definition at line 78 of file Vote.php.
{
         $sp = $this->getStateParams(true);
         $voteID = (int)$sp['vid'];
         $this->prepare();
         if ($this->isUserCanVote($voteID)) {
             $this->getData()->load($this->dbh->select('SELECT vote_question_id, vote_question_title  FROM `apps_vote_question` LEFT JOIN apps_vote_question_translation USING(vote_question_id)
         WHERE lang_id=%s AND vote_id= %s ORDER BY vote_question_order_num', $this->document->getLang(), $voteID));
             $this->setProperty('question', $this->dbh->getScalar('apps_vote_translation', 'vote_name', array('vote_id' => $voteID, 'lang_id' => $this->document->getLang())));
             $this->setProperty('date', AbstractBuilder::enFormatDate($this->dbh->getScalar('apps_vote', 'vote_date', array('vote_id' => $voteID)), '%E'));
             $this->setProperty('count', $this->dbh->getScalar   ('apps_vote_question', 'SUM(vote_question_counter', array('vote_id' => $voteID)));
             $this->setProperty('canVote', 1);
         } else {
             $this->setProperty('canVote', 0);
             $this->getVoteResults($voteID);
         }
     }
Energine\apps\components\Vote::getVoteResults ($voteID) private
Get vote result.
Parameters
int | string $voteID Vote ID.
Definition at line 136 of file Vote.php.
Referenced by Energine\apps\components\Vote\getVote(), and Energine\apps\components\Vote\vote().
{
         $this->setProperty('count', $counter = $this->dbh->getScalar('apps_vote_question', 'SUM(vote_question_counter)', array('vote_id' => $voteID)));
         $this->prepare();
         $data = $this->dbh->select('SELECT vote_question_id, vote_question_title, ROUND(100*vote_question_counter/%s) as percent FROM `apps_vote_question` LEFT JOIN apps_vote_question_translation USING(vote_question_id) WHERE lang_id=%s AND vote_id= %s ORDER BY vote_question_order_num', $counter, $this->document->getLang(), $voteID);
         if ($data && is_array($data))
             $this->getData()->load($data);
         $this->setProperty('question', $this->dbh->getScalar('apps_vote_translation', 'vote_name', array('vote_id' => $voteID, 'lang_id' => $this->document->getLang())));
         $this->setProperty('date', AbstractBuilder::enFormatDate($this->dbh->getScalar('apps_vote', 'vote_date', array('vote_id' => $voteID)), '%E'));
         $fd = new FieldDescription('percent');
         $fd->setType(FieldDescription::FIELD_TYPE_INT);
         $this->getDataDescription()->addFieldDescription($fd);
     }
Energine\apps\components\Vote::isUserCanVote ($voteID) private
Check if the user can vote.
Parameters
int | string $voteID Vote ID.
Returns
bool
Definition at line 104 of file Vote.php.
Referenced by Energine\apps\components\Vote\getVote(), and Energine\apps\components\Vote\vote().
{
         $code = true;
 //        if ($uid = $this->document->getUser()->getID()) {
             if (isset($_COOKIE[self::VOTED_COOKIE_PREFIX . $voteID])) {
                 $code = false;
             }
         /*} else {
             $code = false;
         }*/
         return $code;
     }
Energine\apps\components\Vote::main () protected
Default action.
Returns
boolean
Definition at line 56 of file Vote.php.
{
         if ($voteId
             = $this->dbh->getScalar('SELECT vote_id FROM apps_vote WHERE vote_is_active ORDER BY vote_date DESC LIMIT 0,1')
         ) {
             $this->setProperty('vote_id', $voteId);
             $this->setBuilder(new EmptyBuilder());
             $this->js = $this->buildJS();
         } else {
             $this->disable();
         }
     }
Energine\apps\components\Vote::prepare () protected
Definition at line 153 of file Vote.php.
Referenced by Energine\apps\components\Vote\getVote(), and Energine\apps\components\Vote\getVoteResults().
{
         $data = new Data();
         $dataDescription = new DataDescription();
         $dataDescription->load(
             array(
                 'vote_question_id' => array(
                     'key' => true,
                     'nullable' => false,
                     'type' => FieldDescription::FIELD_TYPE_INT,
                     'length' => 10,
                     'index' => 'PRI'
                 ),
                 'vote_question_title' => array(
                     'key' => false,
                     'nullable' => false,
                     'type' => FieldDescription::FIELD_TYPE_STRING,
                     'length' => 255,
                     'index' => false
                 )
             )
         );
         $this->setData($data);
         $this->setDataDescription($dataDescription);
         E()->getController()->getTransformer()->setFileName('../../../../core/modules/apps/transformers/single_vote.xslt');
         $this->setBuilder($this->createBuilder());
     }
Energine\apps\components\Vote::vote () protected
Vote.
Definition at line 119 of file Vote.php.
{
         $sp = $this->getStateParams(true);
         $QID = (int)$sp['qid'];
         $voteID = $this->dbh->getScalar('apps_vote_question', 'vote_id', array('vote_question_id' => $QID));
         if ($this->isUserCanVote($voteID)) {
             $this->dbh->modify('UPDATE apps_vote_question SET vote_question_counter = vote_question_counter+1 WHERE vote_question_id=%s', $QID);
             $this->response->addCookie(self::VOTED_COOKIE_PREFIX . $voteID, 'voted', time() + self::COOKIE_LIFETIME, E()->getSiteManager()->getCurrentSite()->host);
         }
         $this->setProperty('canVote', 0);
         $this->getVoteResults($voteID);
     }
Member Data Documentation
int Energine\apps\components\Vote::$voteID private
Vote ID.
Definition at line 31 of file Vote.php.
Referenced by Energine\apps\components\Vote\getVote(), Energine\apps\components\Vote\getVoteResults(), Energine\apps\components\Vote\isUserCanVote(), and Energine\apps\components\Vote\vote().
const Energine\apps\components\Vote::COOKIE_LIFETIME = 86400
Cookie lifespan.
24 hours.
Definition at line 42 of file Vote.php.
const Energine\apps\components\Vote::VOTED_COOKIE_PREFIX = 'nrgn_voted_'
Vote prefix for cookie.
Definition at line 36 of file Vote.php.
The documentation for this class was generated from the following file:
core/modules/apps/components/Vote.php