Energine: Energine\share\gears\FileRepositoryFTP Class Reference
Energine\share\gears\FileRepositoryFTP Class Reference
Implementation of file loader interface IFileRepository for remote FTP repositories.
Public Member Functions
__construct ($id, $base)
getName ()
Get internal name of implementation.
setId ($id)
Set repository ID (upl_id).
getId ()
Get repository ID (upl_id).
setBase ($base)
Set base path to the repository (upl_path).
getBase ()
Get base path to the repository (upl_path).
allowsCreateDir ()
Check if the creating of directories is allowed.
allowsUploadFile ()
Check if the file uploading is allowed.
allowsEditDir ()
Check if the editing of the directory is allowed.
allowsEditFile ()
Check if the editing of the file is allowed.
allowsDeleteDir ()
Check if the deleting of the directory is allowed.
allowsDeleteFile ()
Check if the deleting of the file is allowed.
uploadFile ($sourceFilename, $destFilename)
Upload a file to the repository.
putFile ($fileData, $filePath)
uploadAlt ($sourceFilename, $destFilename, $width, $height)
Upload a alt-file to the repository.
updateFile ($sourceFilename, $destFilename)
Update file.
updateAlt ($sourceFilename, $destFilename, $width, $height)
Update alt-file.
deleteFile ($filename)
Delete file from repository.
deleteAlt ($filename, $width, $height)
Delete alt-file from repository.
analyze ($filename)
Get the meta-information of the file (mime-type, size, etc.).
createDir ($dir)
Create new directory in the repository.
renameDir ($dir)
Rename directory in the repository.
deleteDir ($dir)
Delete directory from the repository.
setPrepareFunction ($func)
Sets the function to prepare dataset.
prepare (&$data)
Prepare data with.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const IMAGE_ALT_CACHE = 'resizer/w[width]-h[height]/[upl_path]'
Path to the cache for alternative images.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Attributes
$id
Internal repository ID.
$base
Base path to the repository.
$ftp_media
FTP object for file downloading.
$ftp_alts
FTP object for loading alts.
Private Attributes
$prepareFunction = null
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Implementation of file loader interface IFileRepository for remote FTP repositories.
class FileRepositoryFTP;
This is useful for the cases when the repository is remote and the file is downloaded over FTP by using admin tools.
Rights table
Action Allowed?
CreateDir true
UploadFile true
EditDir true
EditFile true
DeleteDir true
DeleteFile true
Definition at line 60 of file FileRepositoryFTP.php.
Constructor & Destructor Documentation
Energine\share\gears\FileRepositoryFTP::__construct ($id, $base)
Parameters
int $id Repository ID.
string $base Base path to the repository.
Exceptions
SystemException 'ERR_MISSING_MEDIA_FTP_CONFIG'
SystemException 'ERR_MISSING_ALTS_FTP_CONFIG'
Implements Energine\share\gears\IFileRepository.
Definition at line 103 of file FileRepositoryFTP.php.
{
         $this->setId($id);
         $this->setBase($base);
         $cfg_ftp_media = E()->getConfigValue('repositories.ftp.' . $base . '.media');
         $cfg_ftp_alts = E()->getConfigValue('repositories.ftp.' . $base . '.alts');
         if (empty($cfg_ftp_media)) {
             throw new SystemException('ERR_MISSING_MEDIA_FTP_CONFIG');
         }
         if (empty($cfg_ftp_alts)) {
             throw new SystemException('ERR_MISSING_ALTS_FTP_CONFIG');
         }
         $this->ftp_media = new FTP(
             $cfg_ftp_media['server'],
             $cfg_ftp_media['port'],
             $cfg_ftp_media['username'],
             $cfg_ftp_media['password']
         );
         $this->ftp_alts = new FTP(
             $cfg_ftp_alts['server'],
             $cfg_ftp_alts['port'],
             $cfg_ftp_alts['username'],
             $cfg_ftp_alts['password']
         );
     }
Member Function Documentation
Energine\share\gears\FileRepositoryFTP::allowsCreateDir ()
Check if the creating of directories is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 155 of file FileRepositoryFTP.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryFTP::allowsDeleteDir ()
Check if the deleting of the directory is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 171 of file FileRepositoryFTP.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryFTP::allowsDeleteFile ()
Check if the deleting of the file is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 175 of file FileRepositoryFTP.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryFTP::allowsEditDir ()
Check if the editing of the directory is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 163 of file FileRepositoryFTP.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryFTP::allowsEditFile ()
Check if the editing of the file is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 167 of file FileRepositoryFTP.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryFTP::allowsUploadFile ()
Check if the file uploading is allowed.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 159 of file FileRepositoryFTP.php.
{
         return true;
     }
Energine\share\gears\FileRepositoryFTP::analyze ($filename)
Get the meta-information of the file (mime-type, size, etc.).
Parameters
string $filename Filename.
Returns
object
Implements Energine\share\gears\IFileRepository.
Definition at line 302 of file FileRepositoryFTP.php.
Referenced by Energine\share\gears\FileRepositoryFTP\putFile(), Energine\share\gears\FileRepositoryFTP\updateAlt(), Energine\share\gears\FileRepositoryFTP\updateFile(), Energine\share\gears\FileRepositoryFTP\uploadAlt(), and Energine\share\gears\FileRepositoryFTP\uploadFile().
{
         $fi = E()->FileRepoInfo->analyze($filename, true);
         if (is_object($fi)) {
             $fi->ready = true;
         }
         return $fi;
     }
Energine\share\gears\FileRepositoryFTP::createDir ($dir)
Create new directory in the repository.
Parameters
string $dir Directory name.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 310 of file FileRepositoryFTP.php.
{
         $initially_connected = $this->ftp_media->connected();
         try {
             $base = $this->getBase() . '/';
             if (strpos($dir, $base) === 0) {
                 $dir = substr($dir, strlen($base));
             }
             if (!$initially_connected) {
                 $this->ftp_media->connect();
             }
             $this->ftp_media->createDir($dir);
             if (!$initially_connected) {
                 $this->ftp_media->disconnect();
             }
         } catch (\Exception $e) {
             return false;
         }
         return true;
     }
Energine\share\gears\FileRepositoryFTP::deleteAlt ($filename, $width, $height)
Delete alt-file from repository.
Parameters
string $filename Filename.
int $width Width
int $height Height
Returns
boolean
Exceptions
SystemException 'ERR_UNIMPLEMENTED_YET'
Attention
This is not yet implemented!
Implements Energine\share\gears\IFileRepository.
Definition at line 298 of file FileRepositoryFTP.php.
{
         throw new SystemException('ERR_UNIMPLEMENTED_YET');
     }
Energine\share\gears\FileRepositoryFTP::deleteDir ($dir)
Delete directory from the repository.
Parameters
string $dir Directory name.
Exceptions
SystemException 'ERR_UNIMPLEMENTED_YET'
Attention
This is not yet implemented!
Implements Energine\share\gears\IFileRepository.
Definition at line 354 of file FileRepositoryFTP.php.
{
         throw new SystemException('ERR_UNIMPLEMENTED_YET');
     }
Energine\share\gears\FileRepositoryFTP::deleteFile ($filename)
Delete file from repository.
Parameters
string $filename Filename.
Returns
boolean
Exceptions
SystemException 'ERR_UNIMPLEMENTED_YET'
Attention
This is not yet implemented!
Implements Energine\share\gears\IFileRepository.
Definition at line 287 of file FileRepositoryFTP.php.
{
         throw new SystemException('ERR_UNIMPLEMENTED_YET');
     }
Energine\share\gears\FileRepositoryFTP::getBase ()
Get base path to the repository (upl_path).
Returns
string
Implements Energine\share\gears\IFileRepository.
Definition at line 151 of file FileRepositoryFTP.php.
Referenced by Energine\share\gears\FileRepositoryFTP\createDir(), Energine\share\gears\FileRepositoryFTP\putFile(), Energine\share\gears\FileRepositoryFTP\updateFile(), and Energine\share\gears\FileRepositoryFTP\uploadFile().
{
         return $this->base;
     }
Energine\share\gears\FileRepositoryFTP::getId ()
Get repository ID (upl_id).
Returns
int
Implements Energine\share\gears\IFileRepository.
Definition at line 142 of file FileRepositoryFTP.php.
{
         return $this->id;
     }
Energine\share\gears\FileRepositoryFTP::getName ()
Get internal name of implementation.
Returns
string
Implements Energine\share\gears\IFileRepository.
Definition at line 133 of file FileRepositoryFTP.php.
{
         return 'ftp';
     }
Energine\share\gears\FileRepositoryFTP::prepare (& $data)
Prepare data with.
Parameters
&$data array repository data as array
Returns
array||boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 373 of file FileRepositoryFTP.php.
{
         if ($data && $this->prepareFunction) {
             array_walk($data, $this->prepareFunction);
         }
     }
Energine\share\gears\FileRepositoryFTP::putFile ($fileData, $filePath)
Definition at line 197 of file FileRepositoryFTP.php.
{
         try {
             $base = $this->getBase() . '/';
             if (strpos($filePath, $base) === 0) {
                 $destFilename = substr($filePath, strlen($base));
             }
             $this->ftp_media->connect();
             if (!file_put_contents($filePath2 = FileRepository::TEMPORARY_DIR.basename($destFilename), $fileData)) {
                 throw new SystemException('ERR_PUT_FILE', SystemException::ERR_CRITICAL, $filePath2);
             }
             $result = $this->ftp_media->uploadFile($filePath2, $filePath);
             $fi = false;
             if ($result) {
                 $fi = $this->analyze($filePath);
             }
             $this->ftp_media->disconnect();
             return $fi;
         } catch (\Exception $e) {
             return false;
         }
     }
Energine\share\gears\FileRepositoryFTP::renameDir ($dir)
Rename directory in the repository.
Parameters
string $dir Directory name.
Returns
boolean
Exceptions
SystemException 'ERR_UNIMPLEMENTED_YET'
Attention
This is not yet implemented!
Implements Energine\share\gears\IFileRepository.
Definition at line 343 of file FileRepositoryFTP.php.
{
         throw new SystemException('ERR_UNIMPLEMENTED_YET');
     }
Energine\share\gears\FileRepositoryFTP::setBase ($base)
Set base path to the repository (upl_path).
Parameters
string $base Base path.
Returns
IFileRepository
Implements Energine\share\gears\IFileRepository.
Definition at line 146 of file FileRepositoryFTP.php.
Referenced by Energine\share\gears\FileRepositoryFTP\__construct().
{
         $this->base = $base;
         return $this;
     }
Energine\share\gears\FileRepositoryFTP::setId ($id)
Set repository ID (upl_id).
Parameters
int $id Repository ID.
Returns
IFileRepository
Implements Energine\share\gears\IFileRepository.
Definition at line 137 of file FileRepositoryFTP.php.
Referenced by Energine\share\gears\FileRepositoryFTP\__construct().
{
         $this->id = $id;
         return $this;
     }
Energine\share\gears\FileRepositoryFTP::setPrepareFunction ($func)
Sets the function to prepare dataset.
Parameters
$func callable prepare function
Exceptions
SystemException 'ERR_BAD_PREPARE_FUNCTION'
Implements Energine\share\gears\IFileRepository.
Definition at line 362 of file FileRepositoryFTP.php.
{
         if (!is_callable($func)) {
             throw new SystemException('ERR_BAD_PREPARE_FUNCTION');
         }
         $this->prepareFunction = $func;
     }
Energine\share\gears\FileRepositoryFTP::updateAlt ($sourceFilename, $destFilename, $width, $height)
Update alt-file.
Update the alt-file in the repository.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
int $width Width.
int $height Height.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 259 of file FileRepositoryFTP.php.
{
         $destFilename = str_replace(
             array('[width]', '[height]', '[upl_path]'),
             array($width, $height, $destFilename),
             self::IMAGE_ALT_CACHE
         );
         try {
             $this->ftp_alts->connect();
             $result = $this->ftp_alts->uploadFile($sourceFilename, $destFilename);
             $fi = false;
             if ($result) {
                 $fi = $this->analyze($sourceFilename);
             }
             $this->ftp_alts->disconnect();
             return $fi;
         } catch (\Exception $e) {
             return false;
         }
     }
Energine\share\gears\FileRepositoryFTP::updateFile ($sourceFilename, $destFilename)
Update file.
Update the file in the repository.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
Returns
boolean|object
Implements Energine\share\gears\IFileRepository.
Definition at line 240 of file FileRepositoryFTP.php.
{
         try {
             $base = $this->getBase() . '/';
             if (strpos($destFilename, $base) === 0) {
                 $destFilename = substr($destFilename, strlen($base));
             }
             $this->ftp_media->connect();
             $result = $this->ftp_media->uploadFile($sourceFilename, $destFilename);
             $fi = false;
             if ($result) {
                 $fi = $this->analyze($sourceFilename);
             }
             $this->ftp_media->disconnect();
             return $fi;
         } catch (\Exception $e) {
             return false;
         }
     }
Energine\share\gears\FileRepositoryFTP::uploadAlt ($sourceFilename, $destFilename, $width, $height)
Upload a alt-file to the repository.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
int $width Width.
int $height Height.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 219 of file FileRepositoryFTP.php.
{
         $destFilename = str_replace(
             array('[width]', '[height]', '[upl_path]'),
             array($width, $height, $destFilename),
             self::IMAGE_ALT_CACHE
         );
         try {
             $this->ftp_alts->connect();
             $result = $this->ftp_alts->uploadFile($sourceFilename, $destFilename);
             $fi = false;
             if ($result) {
                 $fi = $this->analyze($sourceFilename);
             }
             $this->ftp_alts->disconnect();
             return $fi;
         } catch (\Exception $e) {
             return false;
         }
     }
Energine\share\gears\FileRepositoryFTP::uploadFile ($sourceFilename, $destFilename)
Upload a file to the repository.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
Returns
boolean
Implements Energine\share\gears\IFileRepository.
Definition at line 179 of file FileRepositoryFTP.php.
{
         try {
             $base = $this->getBase() . '/';
             if (strpos($destFilename, $base) === 0) {
                 $destFilename = substr($destFilename, strlen($base));
             }
             $this->ftp_media->connect();
             $result = $this->ftp_media->uploadFile($sourceFilename, $destFilename);
             $fi = false;
             if ($result) {
                 $fi = $this->analyze($sourceFilename);
             }
             $this->ftp_media->disconnect();
             return $fi;
         } catch (\Exception $e) {
             return false;
         }
     }
Member Data Documentation
string Energine\share\gears\FileRepositoryFTP::$base protected
Base path to the repository.
Definition at line 78 of file FileRepositoryFTP.php.
Referenced by Energine\share\gears\FileRepositoryFTP\__construct(), Energine\share\gears\FileRepositoryFTP\createDir(), Energine\share\gears\FileRepositoryFTP\getBase(), Energine\share\gears\FileRepositoryFTP\putFile(), Energine\share\gears\FileRepositoryFTP\setBase(), Energine\share\gears\FileRepositoryFTP\updateFile(), and Energine\share\gears\FileRepositoryFTP\uploadFile().
FTP Energine\share\gears\FileRepositoryFTP::$ftp_alts protected
FTP object for loading alts.
Definition at line 90 of file FileRepositoryFTP.php.
FTP Energine\share\gears\FileRepositoryFTP::$ftp_media protected
FTP object for file downloading.
Definition at line 84 of file FileRepositoryFTP.php.
int Energine\share\gears\FileRepositoryFTP::$id protected
Internal repository ID.
Definition at line 72 of file FileRepositoryFTP.php.
Referenced by Energine\share\gears\FileRepositoryFTP\__construct(), Energine\share\gears\FileRepositoryFTP\getId(), and Energine\share\gears\FileRepositoryFTP\setId().
Energine\share\gears\FileRepositoryFTP::$prepareFunction = null private
Definition at line 95 of file FileRepositoryFTP.php.
string Energine\share\gears\FileRepositoryFTP::IMAGE_ALT_CACHE = 'resizer/w[width]-h[height]/[upl_path]'
Path to the cache for alternative images.
Definition at line 66 of file FileRepositoryFTP.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/FileRepositoryFTP.php