Energine: Energine\share\gears\Object Class Reference
Energine\share\gears\Object Class Reference
Public Member Functions
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Attributes
$executionTime
Execution time counter.
Static Private Attributes
static $systemConfig
System configuration.
Detailed Description
Definition at line 32 of file Object.php.
Member Function Documentation
static Energine\share\gears\Object::_getConfigValue ($paramPath, $initial = null) static
Get the configuration value by parameter path.
Object::_getConfigValue('database.dsn');
Parameters
string $paramPath Parameter path.
mixed $initial Default value. It will be used if the looked value is not found.
Returns
string
Note
Use dot character as separator between configuration's tree levels.
Definition at line 100 of file Object.php.
Referenced by Energine\user\components\LoginForm\__construct(), Energine\share\gears\Cache\__construct(), Energine\share\components\DataSet\cleanupHTML(), Energine\share\gears\Response\commit(), and Energine\forms\gears\FormConstructor\getDatabase().
{
         if(is_null(self::$systemConfig)) self::setConfigArray(include(self::CONFIG_FILE));
         $result = self::$systemConfig;
         $paramPath = explode('.', $paramPath);
         foreach($paramPath as $segment) {
             if(isset($result[$segment]))
                 $result = $result[$segment];
             else {
                 return $initial;
             }
         }
         return $result;
     }
static Energine\share\gears\Object::getConfigArray () static
Get the configurations.
Returns
array
Definition at line 140 of file Object.php.
{
         return self::$systemConfig;
     }
Energine\share\gears\Object::getConfigValue ($paramPath, $initial = null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Parameters
string $paramPath Parameter path.
mixed $initial Default value. It will be used if the looked value is not found.
Returns
string
See also
Object::_getConfigValue()
Definition at line 124 of file Object.php.
Referenced by Energine\share\components\CrossDomainAuth\__construct(), Energine\share\components\AttachmentEditor\__construct(), Energine\share\gears\XSLTTransformer\__construct(), Energine\seo\components\GoogleSitemap\__construct(), Energine\share\gears\SiteManager\__construct(), Energine\share\gears\Mail\__construct(), Energine\share\gears\UserSession\__construct(), Energine\share\gears\Document\__construct(), Energine\share\gears\Response\addCookie(), Energine\share\gears\ErrorDocument\build(), Energine\share\gears\OGObject\build(), Energine\share\gears\Document\build(), Energine\share\components\TextBlock\buildJS(), Energine\share\components\DBDataSet\buildJS(), Energine\share\gears\QAL\buildWhereCondition(), Energine\user\components\Register\checkCaptcha(), Energine\apps\components\FeedbackForm\checkCaptcha(), Energine\forms\components\Form\checkCaptcha(), Energine\comments\components\CommentsForm\checkCaptcha(), Energine\share\gears\AbstractBuilder\createField(), Energine\forms\gears\FormConstructor\createMultiField(), Energine\forms\gears\FormConstructor\createSelectField(), Energine\seo\components\Robots\createSitemapSegment(), Energine\share\components\FileRepository\createThumbFields(), Energine\share\components\Grid\defineParams(), Energine\share\gears\DBA\fulfill(), Energine\share\gears\DBA\funcExists(), Energine\share\gears\Registry\getDB(), Energine\seo\components\Robots\getSitemapSegmentIds(), Energine\share\gears\DocumentController\getViewMode(), Energine\share\gears\Document\isEditable(), Energine\share\gears\Document\loadComponents(), Energine\seo\components\Robots\loadData(), Energine\forms\components\FormResults\loadDataDescription(), Energine\share\gears\DBA\procExists(), Energine\user\components\Register\saveData(), Energine\share\components\FileRepository\saveThumbs(), Energine\user\components\RestorePassword\send(), Energine\apps\components\FeedbackForm\send(), Energine\forms\components\Form\send(), Energine\user\components\SocialLoginForm\showLoginForm(), Energine\user\components\LoginForm\showLoginForm(), Energine\share\gears\XSLTTransformer\transform(), and Energine\share\gears\VideoUploader\upload().
{
         return self::_getConfigValue($paramPath, $initial);
     }
Energine\share\gears\Object::getTimer ()
Get the current value of the execution time counter.
Returns
float
Definition at line 83 of file Object.php.
{
         return $this->executionTime;
     }
Energine\share\gears\Object::resetTimer ()
Reset the execution time counter.
Returns
float
Definition at line 72 of file Object.php.
{
         $result = $this->stopTimer();
         $this->startTimer();
         return $result;
     }
static Energine\share\gears\Object::setConfigArray ($config) static
Set the Object::$systemConfig.
Parameters
array $config
Definition at line 132 of file Object.php.
{
         self::$systemConfig = $config;
     }
Energine\share\gears\Object::startTimer ()
Start the execution time counter.
Definition at line 54 of file Object.php.
Referenced by Energine\share\gears\Object\resetTimer().
{
         $this->executionTime = \microtime(true);
     }
Energine\share\gears\Object::stopTimer ()
Stop the execution time counter.
Returns
float
Definition at line 63 of file Object.php.
Referenced by Energine\share\gears\Object\resetTimer().
{
         return ($this->executionTime = \microtime(true) - $this->executionTime);
     }
Member Data Documentation
float Energine\share\gears\Object::$executionTime private
Execution time counter.
Definition at line 49 of file Object.php.
Referenced by Energine\share\gears\Object\getTimer().
SimpleXMLElement Energine\share\gears\Object::$systemConfig static private
System configuration.
It has tree structure.
Definition at line 43 of file Object.php.
const Energine\share\gears\Object::CONFIG_FILE = 'system.config.php'
Configuration file name.
Definition at line 36 of file Object.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/Object.php