Energine: Energine\user\components\Register Class Reference
Energine\user\components\Register Class Reference
Registration form.
Public Member Functions
__construct ($name, $module, array $params=null)
Public Member Functions inherited from Energine\share\components\DBDataSet
__construct ($name, $module, array $params=null)
getTableName ()
Get table name.
getFilter ()
Get filter.
addFilterCondition ($filter)
Add filter condition.
getPK ()
Get filed name of primary key.
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Member Functions
defineParams ()
checkLogin ()
Check login.
save ()
Save.
checkCaptcha ()
Check captcha.
failure ($errorMessage, $data)
Failure.
saveData ()
Save data.
prepare ()
success ()
Show registration result.
Protected Member Functions inherited from Energine\share\components\DBDataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
loadDataDescription ()
Load data description.
loadData ()
Load data.
getDataLanguage ()
Get data language.
setTableName ($tableName)
Set table name.
setParam ($name, $value)
Set component parameter if such exist.
setFilter ($filter)
Set filter.
clearFilter ()
Reset filter.
getOrder ()
Get sort order.
setOrder (array $order)
Set sort order.
getLimit ()
Get limit.
setLimit (array $limit)
Set limit.
setPK ($primaryColumnName)
Set primary key.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
getFKData ($fkTableName, $fkKeyName)
Get data from linked table.
getTranslationTableName ()
Get table name with translations.
view ()
Show view form.
recordExists ($id, $fieldName=false)
Detect if the specific record exist.
buildJS ()
Create description of JS objects.
getPreviousState ()
Get previous state.
saveText ()
Save text.
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Protected Attributes
$user
Exemplar of User class.
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Registration form.
class Register;
Definition at line 25 of file Register.php.
Constructor & Destructor Documentation
Energine\user\components\Register::__construct ($name, $module, array $params = null)
Definition at line 35 of file Register.php.
{
         parent::__construct($name, $module, $params);
         $this->setAction('save-new-user');
         $this->setType(self::COMPONENT_TYPE_FORM_ADD);
         $this->user = new User();
         $this->setTableName(User::USER_TABLE_NAME);
         $this->addTranslation('TXT_ENTER_CAPTCHA');
         if (!$this->getTitle())
             $this->setTitle($this->translate(
                 'TXT_' . strtoupper($this->getName())));
     }
Member Function Documentation
Energine\user\components\Register::checkCaptcha () protected
Check captcha.
Exceptions
SystemException
Definition at line 108 of file Register.php.
Referenced by Energine\user\components\Register\save().
{
         require_once('core/modules/share/gears/recaptchalib.php');
         $privatekey = $this->getConfigValue('recaptcha.private');
         $resp = recaptcha_check_answer($privatekey,
             $_SERVER["REMOTE_ADDR"],
             $_POST["recaptcha_challenge_field"],
             $_POST["recaptcha_response_field"]);
         if (!$resp->is_valid) {
             throw new SystemException($this->translate('TXT_BAD_CAPTCHA'), SystemException::ERR_CRITICAL);
         }
     }
Energine\user\components\Register::checkLogin () protected
Check login.
It is called by AJAX by filling registration form.
Definition at line 63 of file Register.php.
{
         $login = trim($_POST['login']);
         $result = !(bool)simplifyDBResult(
             $this->dbh->select(
                 $this->getTableName(),
                 array('COUNT(u_id) as number'),
                 array('u_name' => $login)
             ),
             'number',
             true
         );
         $field = 'login';
         $message = ($result) ? $this->translate('TXT_LOGIN_AVAILABLE') : $this->translate('TXT_LOGIN_ENGAGED');
         $result = array(
             'result' => $result,
             'message' => $message,
             'field' => $field,
         );
         $builder = new JSONCustomBuilder();
         $this->setBuilder($builder);
         $builder->setProperties($result);
     }
Energine\user\components\Register::defineParams () protected
Definition at line 51 of file Register.php.
{
         $result = array_merge(parent::defineParams(),
             array(
                 'active' => true,
             ));
         return $result;
     }
Energine\user\components\Register::failure ($errorMessage, $data) protected
Failure.
Parameters
string $errorMessage Error message.
mixed $data Data.
Definition at line 127 of file Register.php.
Referenced by Energine\user\components\Register\save().
{
         $this->getConfig()->setCurrentState('main');
         $this->prepare();
         $eFD = new FieldDescription('error_message');
         $eFD->setMode(FieldDescription::FIELD_MODE_READ);
         $eFD->setType(FieldDescription::FIELD_TYPE_STRING);
         $this->getDataDescription()->addFieldDescription($eFD);
         $this->getData()->load(array(array_merge(array('error_message' => $errorMessage), $data)));
         $this->getDataDescription()->getFieldDescriptionByName('error_message')->removeProperty('title');
     }
Energine\user\components\Register::prepare () protected
Definition at line 172 of file Register.php.
Referenced by Energine\user\components\Register\failure().
{
         parent::prepare();
         //u_id  u_is_active
         if ($this->getDataDescription()->getFieldDescriptionByName('u_id')) {
             $this->getDataDescription()->removeFieldDescription($this->getDataDescription()->getFieldDescriptionByName('u_id'));
         }
         if ($this->getDataDescription()->getFieldDescriptionByName('u_is_active')) {
             $this->getDataDescription()->removeFieldDescription($this->getDataDescription()->getFieldDescriptionByName('u_is_active'));
         }
         //      confirmationNeeded
         if ($this->getDataDescription()->getFieldDescriptionByName('u_password')) {
             $this->getDataDescription()->removeFieldDescription($this->getDataDescription()->getFieldDescriptionByName('u_password'));
         }
         $this->getDataDescription()->getFieldDescriptionByName('u_name')->setType(FieldDescription::FIELD_TYPE_EMAIL);
     }
Energine\user\components\Register::save () protected
Save.
It process all possible errors and redirect to the result page.
Definition at line 91 of file Register.php.
{
         //inspect($_SESSION);
         try {
             $this->checkCaptcha();
             $this->saveData();
             $_SESSION['saved'] = true;
             $this->response->redirectToCurrentSection('success/');
         } catch (SystemException $e) {
             $this->failure($e->getMessage(), $_POST[$this->getTableName()]);
         }
     }
Energine\user\components\Register::saveData () protected
Save data.
Exceptions
SystemException
Definition at line 144 of file Register.php.
Referenced by Energine\user\components\Register\save().
{
         $password = $_POST[$this->getTableName()]['u_password'] = User::generatePassword();
         try {
             $result = $this->user->create($_POST[$this->getTableName()]);
             $mailer = new Mail();
             $mailer->setFrom($this->getConfigValue('mail.from'));
             $mailer->setSubject($this->translate('TXT_SUBJ_REGISTER'));
             $mailer->setText(
                 $this->translate('TXT_BODY_REGISTER'),
                 array(
                     'login' => $this->user->getValue('u_name'),
                     'name' => $this->user->getValue('u_fullname'),
                     'password' => $password
                 )
             );
             $mailer->addTo($this->user->getValue('u_name'));
             $mailer->send();
         } catch (\Exception $error) {
             throw new SystemException($error->getMessage(), SystemException::ERR_WARNING);
         }
     }
Energine\user\components\Register::success () protected
Show registration result.
Definition at line 192 of file Register.php.
{
         //     saved      .  !
         /*if (!isset($_SESSION['saved'])) {
             throw new SystemException('ERR_404', SystemException::ERR_404);
         }*/
         //unset($_SESSION['saved']);
         if ($textBlock = $this->document->componentManager->getBlockByName('RegTextBlock')) {
             $textBlock->disable();
         }
         $this->setBuilder($this->createBuilder());
         $dataDescription = new DataDescription();
         $ddi = new FieldDescription('success_message');
         $ddi->setType(FieldDescription::FIELD_TYPE_TEXT);
         $ddi->setMode(FieldDescription::FIELD_MODE_READ);
         $ddi->removeProperty('title');
         $dataDescription->addFieldDescription($ddi);
         $data = new Data();
         $di = new Field('success_message');
         $di->setData($this->translate('TXT_USER_REGISTRED'));
         $data->addField($di);
         $this->setDataDescription($dataDescription);
         $this->setData($data);
     }
Member Data Documentation
User Energine\user\components\Register::$user protected
Exemplar of User class.
Definition at line 30 of file Register.php.
The documentation for this class was generated from the following file:
core/modules/user/components/Register.php