Energine: Energine\user\gears\FBOAuth Class Reference
Energine\user\gears\FBOAuth Class Reference
Extends the BaseFacebook class with the intent of using PHP sessions to store user ids and access tokens.
Public Member Functions
__construct ($config)
Identical to the parent constructor, except that we start a PHP session to store the user ID and access token if during the course of execution we discover them.
__get ($varName)
__set ($varName, $varValue)
__unset ($varName)
__isset ($varName)
Public Attributes
const COOKIE_LIFETIME = 3600
Protected Member Functions
setPersistentData ($key, $value)
Provides the implementations of the inherited abstract methods.
getPersistentData ($key, $default=false)
clearPersistentData ($key)
clearAllPersistentData ()
constructSessionVariableName ($key)
Static Protected Attributes
static $kSupportedKeys
Private Attributes
$localStorage = array()
Detailed Description
Extends the BaseFacebook class with the intent of using PHP sessions to store user ids and access tokens.
Definition at line 25 of file FBOAuth.php.
Constructor & Destructor Documentation
Energine\user\gears\FBOAuth::__construct ($config)
Identical to the parent constructor, except that we start a PHP session to store the user ID and access token if during the course of execution we discover them.
Parameters
Array $config the application configuration.
See also
BaseFacebook::__construct in facebook.php
Definition at line 38 of file FBOAuth.php.
{
         parent::__construct($config);
     }
Member Function Documentation
Energine\user\gears\FBOAuth::__get ($varName)
Definition at line 93 of file FBOAuth.php.
{
         if (isset($this->localStorage[$varName])) return $this->localStorage[$varName];
         return (isset($_COOKIE[$varName]))? $_COOKIE[$varName]: null;
     }
Energine\user\gears\FBOAuth::__isset ($varName)
Definition at line 108 of file FBOAuth.php.
{
         if(isset($this->localStorage[$varName]) && !is_null($this->localStorage[$varName])) return true;
         return isset($_COOKIE[$varName]);
     }
Energine\user\gears\FBOAuth::__set ($varName, $varValue)
Definition at line 98 of file FBOAuth.php.
{
         $this->localStorage[$varName] = $varValue;
         setcookie($varName, $varValue, time() + self::COOKIE_LIFETIME, '/');
     }
Energine\user\gears\FBOAuth::__unset ($varName)
Definition at line 103 of file FBOAuth.php.
{
         unset($this->localStorage[$varName]);
         setcookie($varName, '', time() - self::COOKIE_LIFETIME, '/');
     }
Energine\user\gears\FBOAuth::clearAllPersistentData () protected
Definition at line 81 of file FBOAuth.php.
{
         foreach (self::$kSupportedKeys as $key) {
             $this->clearPersistentData($key);
         }
     }
Energine\user\gears\FBOAuth::clearPersistentData ($key) protected
Definition at line 71 of file FBOAuth.php.
Referenced by Energine\user\gears\FBOAuth\clearAllPersistentData().
{
         if (!in_array($key, self::$kSupportedKeys)) {
             self::errorLog('Unsupported key passed to clearPersistentData.');
             return;
         }
         $session_var_name = $this->constructSessionVariableName($key);
         unset($this->$session_var_name);
     }
Energine\user\gears\FBOAuth::constructSessionVariableName ($key) protected
Definition at line 87 of file FBOAuth.php.
Referenced by Energine\user\gears\FBOAuth\clearPersistentData(), Energine\user\gears\FBOAuth\getPersistentData(), and Energine\user\gears\FBOAuth\setPersistentData().
{
         return implode('_', array('fb',
             $this->getAppId(),
             $key));
     }
Energine\user\gears\FBOAuth::getPersistentData ($key, $default = false) protected
Definition at line 61 of file FBOAuth.php.
{
         if (!in_array($key, self::$kSupportedKeys)) {
             self::errorLog('Unsupported key passed to getPersistentData.');
             return $default;
         }
         $session_var_name = $this->constructSessionVariableName($key);
         return isset($this->$session_var_name) ?
                 $this->$session_var_name : $default;
     }
Energine\user\gears\FBOAuth::setPersistentData ($key, $value) protected
Provides the implementations of the inherited abstract methods.
The implementation uses PHP sessions to maintain a store for authorization codes, user ids, CSRF states, and access tokens.
Definition at line 51 of file FBOAuth.php.
{
         if (!in_array($key, self::$kSupportedKeys)) {
             self::errorLog('Unsupported key passed to setPersistentData.');
             return;
         }
         $session_var_name = $this->constructSessionVariableName($key);
         $this->$session_var_name = $value;
     }
Member Data Documentation
Energine\user\gears\FBOAuth::$kSupportedKeys static protected
Initial value:
=
            array('state', 'code', 'access_token', 'user_id')
Definition at line 42 of file FBOAuth.php.
Energine\user\gears\FBOAuth::$localStorage = array() private
Definition at line 27 of file FBOAuth.php.
const Energine\user\gears\FBOAuth::COOKIE_LIFETIME = 3600
Definition at line 26 of file FBOAuth.php.
The documentation for this class was generated from the following file:
core/modules/user/gears/FBOAuth.php