Energine: Energine\share\gears\TagManager Class Reference
Energine\share\gears\TagManager Class Reference
Tag manager.
Public Member Functions
__construct ($dataDescription, $data, $tableName)
createFieldDescription ()
Create field description.
createField ($initialValue=null)
Create field.
save ($id)
bind ($tags, $mapValue, $mapTableName)
Bind set of tags with specific field.
pull ($mapValue, $mapTableName, $asString=false)
Pull tag names by passed information from linked table.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static getID ($tag)
Get tag IDs by passed values.
static getTagStartedWith ($str, $limit=false)
Get tags that begins from passed characters.
static getTags ($tagID, $asSting=false)
Get tags by IDs.
static getFilter ($tags, $mapTableName)
Get filter.
static insert ($tag)
Insert tag.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes
const TAG_TABLENAME = 'share_tags'
Table name with tags.
const TAGS_TABLE_SUFFIX = '_tags'
Table suffix.
const TAG_TABLENAME_TRANSLATION = 'share_tags_translation'
Translation table for tags.
const TAG_SEPARATOR = ','
Tag separator.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Attributes
$dataDescription
Data descriptions.
$data
Data.
$tableName
Table name.
$isActive
Activity flag.
$pk
Key field description.
Additional Inherited Members
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Tag manager.
class TagManager;
Definition at line 24 of file TagManager.php.
Constructor & Destructor Documentation
Energine\share\gears\TagManager::__construct ($dataDescription, $data, $tableName)
Parameters
DataDescription $dataDescription Data description.
Data $data Data.
string $tableName Table name.
Definition at line 81 of file TagManager.php.
{
         parent::__construct();
         if ($this->isActive = $this->dbh->tableExists($this->tableName = $tableName . '_tags')) {
             $this->dataDescription = $dataDescription;
             $this->data = $data;
             foreach ($this->dataDescription as $fd) {
                 if ($fd->getPropertyValue('key')) {
                     $this->pk = $fd;
                     break;
                 }
             }
         }
     }
Member Function Documentation
Energine\share\gears\TagManager::bind ($tags, $mapValue, $mapTableName)
Bind set of tags with specific field.
Parameters
string $tags single string line of tags.
string $mapValue Name of ligaments filed in linked table.
string $mapTableName Name of a linked table.
Returns
array
Exceptions
SystemException 'ERR_WRONG_TABLE_NAME'
Definition at line 156 of file TagManager.php.
Referenced by Energine\share\gears\TagManager\save().
{
         if (!$this->dbh->tableExists($mapTableName)) {
             throw new SystemException('ERR_WRONG_TABLE_NAME', SystemException::ERR_DEVELOPER, $mapTableName);
         }
         $tags =
                 array_filter(array_map(create_function('$tag', 'return mb_convert_case(trim($tag), MB_CASE_LOWER, "UTF-8");'), explode(self::TAG_SEPARATOR, $tags)));
         //Анализируем структуру таблицы
         $columns = array_keys($this->dbh->getColumnsInfo($mapTableName));
         unset($columns['tag_id']);
         list($mapFieldName) = $columns;
         $this->dbh->modify(QAL::DELETE, $mapTableName, null, array($mapFieldName => $mapValue));
         if (!empty($tags)) {
             foreach ($tags as $tag) {
                 try {
                     $tag_id = $this->dbh->getScalar(self::TAG_TABLENAME_TRANSLATION, 'tag_id', array('tag_name' => $tag, 'lang_id' => E()->getLanguage()->getCurrent()));
                     if (!$tag_id) {
                         $tag_id = self::insert($tag);
                     }
                 }
                 catch (\Exception $e) {
                 }
             }
             $tagIDs = array_keys(self::getID($tags));
             foreach ($tagIDs as $tagID) {
                 $this->dbh->modify(QAL::INSERT, $mapTableName, array($mapFieldName => $mapValue, 'tag_id' => $tagID));
             }
         }
     }
Energine\share\gears\TagManager::createField ($initialValue = null)
Create field.
Parameters
mixed $initialValue Initial value.
Definition at line 114 of file TagManager.php.
{
         if ($this->isActive) {
             $field = new Field('tags');
             if (
                 is_null($initialValue)
             ) {
                 if (
                     !$this->data->isEmpty()
                     && ($currentData = $this->data->getFieldByName($this->pk->getName()))
                 ) {
                     $field->setData($this->pull($currentData->getData(), $this->tableName));
                     $this->data->addField($field);
                 }
             }
             else {
                 for($i=0; $i<count(E()->getLanguage()->getLanguages()); $i++){
                     $field->setRowData($i, (is_array($initialValue))?$initialValue:array($initialValue));
                 }
                 $this->data->addField($field);
             }
         }
     }
Energine\share\gears\TagManager::createFieldDescription ()
Create field description.
Definition at line 99 of file TagManager.php.
{
         if ($this->isActive) {
             if (!($fd = $this->dataDescription->getFieldDescriptionByName('tags'))) {
                 $fd = new FieldDescription('tags');
                 $this->dataDescription->addFieldDescription($fd);
             }
             $fd->setType(FieldDescription::FIELD_TYPE_TEXTBOX_LIST)->setProperty('url', 'tag-autocomplete')->setProperty('separator', TagManager::TAG_SEPARATOR);
         }
     }
static Energine\share\gears\TagManager::getFilter ($tags, $mapTableName) static
Get filter.
Parameters
mixed $tags
string $mapTableName Map table name.
Returns
array|mixed
Exceptions
SystemException 'ERR_WRONG_TABLE_NAME'
Definition at line 335 of file TagManager.php.
Referenced by Energine\apps\components\NewsFeed\createCalendar(), Energine\share\components\SiteList\loadData(), Energine\share\components\NavigationMenu\loadData(), and Energine\share\components\PageList\loadData().
{
         if (!E()->getDB()->tableExists($mapTableName)) {
             throw new SystemException('ERR_WRONG_TABLE_NAME', SystemException::ERR_DEVELOPER, $mapTableName);
         }
         $result = array();
         $tagInfo = self::getID($tags);
         if (!empty($tagInfo)) {
             $columns = array_keys(E()->getDB()->getColumnsInfo($mapTableName));
             unset($columns['tag_id']);
             list($mapFieldName) = $columns;
             $result =
                     simplifyDBResult(E()->getDB()->select($mapTableName, array($mapFieldName), array('tag_id' => array_keys($tagInfo))), $mapFieldName);
         }
         return $result;
     }
static Energine\share\gears\TagManager::getID ($tag) static
Get tag IDs by passed values.
Parameters
mixed $tag Tags.
Returns
array
Definition at line 238 of file TagManager.php.
Referenced by Energine\share\components\TagEditor\getTagIds().
{
         $result = null;
         if (!is_array($tag)) {
             $tag = explode(self::TAG_SEPARATOR, $tag);
         }
         $in = array();
         foreach($tag as $t) {
             $in[] = E()->getDB()->quote($t);
         }
         if (!empty($in)) {
             $res = E()->getDB()->select(
                 'SELECT t.tag_id, tr.tag_name FROM ' . self::TAG_TABLENAME . ' as t '.
                 'JOIN ' . self::TAG_TABLENAME_TRANSLATION . ' as tr ON t.tag_id = tr.tag_id AND tr.lang_id = %s ' .
                 'WHERE tr.tag_name IN (' . implode(',', $in) . ')',
                 E()->getLanguage()->getCurrent()
             );
         } else {
             $res = false;
         }
         if (is_array($res)) {
             foreach ($res as $row) {
                 $result[$row['tag_id']] = $row['tag_name'];
             }
         }
         return $result;
     }
static Energine\share\gears\TagManager::getTags ($tagID, $asSting = false) static
Get tags by IDs.
Parameters
array | int $tagID Tag ID(s).
bool $asSting Return as string?
Returns
array|string|mixed
Definition at line 298 of file TagManager.php.
Referenced by Energine\share\components\TagEditor\getTags().
{
         $result = array();
         if (empty($tagID)) {
             $tagID = array('-1');
         }
         if (!is_array($tagID)) {
             $tagID = array($tagID);
         }
         $res = E()->getDB()->select(
             'SELECT t.tag_id, tr.tag_name FROM ' . self::TAG_TABLENAME . ' as t '.
             'JOIN ' . self::TAG_TABLENAME_TRANSLATION . ' as tr ON t.tag_id = tr.tag_id AND tr.lang_id = %s ' .
             'WHERE tr.tag_id IN (' . implode(',', $tagID) . ')',
             E()->getLanguage()->getCurrent()
         );
         if(is_array($res)){
             foreach ($res as $resVal){
                 $result[$resVal['tag_id']] = $resVal['tag_name'];
             }
         }
         return ($asSting &&
                 is_array($result)) ? implode(self::TAG_SEPARATOR, $result) : $result;
     }
static Energine\share\gears\TagManager::getTagStartedWith ($str, $limit = false) static
Get tags that begins from passed characters.
Parameters
string $str First tag characters.
bool | int $limit Limit the amount of matched tags.
Returns
array
Definition at line 275 of file TagManager.php.
Referenced by Energine\apps\components\ExtendedFeedEditor\autoCompleteTags(), and Energine\share\components\Grid\autoCompleteTags().
{
         $res = E()->getDB()->select(
             'SELECT tr.tag_name FROM ' . self::TAG_TABLENAME . ' as t '.
             'JOIN ' . self::TAG_TABLENAME_TRANSLATION . ' as tr ON t.tag_id = tr.tag_id AND tr.lang_id = %s ' .
             'WHERE tr.tag_name LIKE ' . E()->getDB()->quote(trim($str) . '%%') . ' ' .
             'ORDER BY tr.tag_name DESC ' .
             (($limit) ? 'LIMIT ' . (int) $limit : ''),
             E()->getLanguage()->getCurrent()
         );
         $result = simplifyDBResult($res, 'tag_name');
         return $result;
     }
static Energine\share\gears\TagManager::insert ($tag) static
Insert tag.
Parameters
mixed $tag Tag.
Returns
bool|int
Definition at line 357 of file TagManager.php.
Referenced by Energine\share\components\TagEditor\getTagIds().
{
         $tag_id = E()->getDB()->modify(QAL::INSERT, self::TAG_TABLENAME, array('tag_code' => $tag));
         $langs = E()->getLanguage()->getLanguages();
         if ($langs && $tag_id) {
             foreach($langs as $lang_id => $lang_info) {
                 E()->getDB()->modify(QAL::INSERT_IGNORE, self::TAG_TABLENAME_TRANSLATION,
                     array('tag_id' => $tag_id, 'lang_id' => $lang_id, 'tag_name' => $tag));
             }
         }
         return $tag_id;
     }
Energine\share\gears\TagManager::pull ($mapValue, $mapTableName, $asString = false)
Pull tag names by passed information from linked table.
Parameters
string $mapValue Map value.
string $mapTableName Map table name.
bool $asString Return as string?
Returns
array|mixed
Exceptions
SystemException 'ERR_WRONG_TABLE_NAME'
Definition at line 197 of file TagManager.php.
Referenced by Energine\share\gears\TagManager\createField().
{
         if (!$this->dbh->tableExists($mapTableName)) {
             throw new SystemException('ERR_WRONG_TABLE_NAME', SystemException::ERR_DEVELOPER, $mapTableName);
         }
         $columns = array_keys($this->dbh->getColumnsInfo($mapTableName));
         $mapFieldName = '';
         unset($columns['tag_id']);
         list($mapFieldName) = $columns;
         $res =
                 $this->dbh->select($mapTableName, array('tag_id', $mapFieldName), array($mapFieldName => $mapValue));
         if (is_array($res)) {
             $result = array();
             foreach ($res as $row) {
                 if (!isset($result[$row[$mapFieldName]])) {
                     $result[$row[$mapFieldName]] = array();
                 }
                 $result[$row[$mapFieldName]][] = $row['tag_id'];
             }
         }
         foreach ((array)$mapValue as $targetID) {
             if (isset($result[$targetID])) {
                 $data[] = self::getTags($result[$targetID], $asString);
             }
             else {
                 $data[] = array();
             }
         }
         //return current($data);
         return $data;
     }
Energine\share\gears\TagManager::save ($id)
Definition at line 140 of file TagManager.php.
{
         if ($this->isActive && isset($_POST['tags'])) {
             $this->bind($_POST['tags'], $id, $this->tableName);
         }
     }
Member Data Documentation
Data Energine\share\gears\TagManager::$data private
Data.
Definition at line 58 of file TagManager.php.
Referenced by Energine\share\gears\TagManager\__construct(), and Energine\share\gears\TagManager\pull().
DataDescription Energine\share\gears\TagManager::$dataDescription private
Data descriptions.
Definition at line 53 of file TagManager.php.
Referenced by Energine\share\gears\TagManager\__construct().
bool Energine\share\gears\TagManager::$isActive private
Activity flag.
Definition at line 68 of file TagManager.php.
FieldDescription Energine\share\gears\TagManager::$pk private
Key field description.
Definition at line 74 of file TagManager.php.
string Energine\share\gears\TagManager::$tableName private
Table name.
Definition at line 63 of file TagManager.php.
Referenced by Energine\share\gears\TagManager\__construct(), and Energine\share\gears\TagManager\createField().
string Energine\share\gears\TagManager::TAG_SEPARATOR = ','
Tag separator.
Definition at line 47 of file TagManager.php.
Referenced by Energine\share\gears\TagManager\createFieldDescription(), Energine\share\components\TagEditor\getRawData(), Energine\share\components\TagEditor\getTagIds(), Energine\share\components\TagEditor\getTags(), and Energine\share\components\TagEditor\main().
string Energine\share\gears\TagManager::TAG_TABLENAME = 'share_tags'
Table name with tags.
Definition at line 29 of file TagManager.php.
Referenced by Energine\share\components\TagEditor\__construct(), Energine\share\components\TagEditor\getRawData(), and Energine\share\components\TagEditor\main().
string Energine\share\gears\TagManager::TAG_TABLENAME_TRANSLATION = 'share_tags_translation'
Translation table for tags.
Definition at line 41 of file TagManager.php.
string Energine\share\gears\TagManager::TAGS_TABLE_SUFFIX = '_tags'
Table suffix.
Definition at line 35 of file TagManager.php.
Referenced by Energine\share\components\Grid\linkExtraManagers().
The documentation for this class was generated from the following file:
core/modules/share/gears/TagManager.php