Energine: Energine\share\gears\SiteSaver Class Reference
Energine\share\gears\SiteSaver Class Reference
Saver for sites editor.
Public Member Functions
save ()
Save data.
Public Member Functions inherited from Energine\share\gears\Saver
__construct ()
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
Get data description.
getData ()
Get data.
setData (Data $data)
Set data.
setMode ($mode)
Set save mode.
getMode ()
Get save mode.
getFilter ()
Get condition for save SQL-request.
setFilter ($filter)
Set condition for save SQL-request.
validate ()
Validate date before saving.
getErrors ()
Get fields with errors.
addError ($fieldName)
Add field name where an error occurred.
save ()
Save data.
getResult ()
Get result of saving.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const MODULES = 'modules'
Modules.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Member Functions
createMainPage ($id)
Create main page of the site and set rights for it.
copyStructure ($sourceSiteID, $destinationSiteID)
Copy site structure into another site.
copyRows ($source, $PID, $newPID, $siteID)
Copy rows.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Protected Attributes inherited from Energine\share\gears\Saver
$dataDescription = false
Data description.
$data = false
Data.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Saver for sites editor.
class SiteSaver;
Definition at line 22 of file SiteSaver.php.
Member Function Documentation
Energine\share\gears\SiteSaver::copyRows ($source, $PID, $newPID, $siteID) private
Copy rows.
Parameters
array $source Source that copies.
int $PID Parent ID.
string | int $newPID New parent ID.
int $siteID Destination site ID.
Returns
array
Definition at line 198 of file SiteSaver.php.
Referenced by Energine\share\gears\SiteSaver\copyStructure().
{
         $result = array();
         //inspect(func_get_args());
         foreach ($source as $key => $row) {
             if ($row['smap_pid'] == $PID) {
                 $newRow = $row;
                 $newRow['site_id'] = $siteID;
                 $newRow['smap_pid'] = $newPID;
                 if ($row['smap_segment'] === '') $newRow['smap_segment'] = QAL::EMPTY_STRING;
                 $oldPID = $row['smap_id'];
                 unset($newRow['smap_id']);
                 //unset($source[$key]);
                 $result += $this->copyRows($source, $oldPID, $result[$row['smap_id']] = $this->dbh->modify(QAL::INSERT, 'share_sitemap', $newRow), $siteID);
             }
         }
         return $result;
     }
Energine\share\gears\SiteSaver::copyStructure ($sourceSiteID, $destinationSiteID) private
Copy site structure into another site.
Parameters
int $sourceSiteID Source site ID.
int $destinationSiteID Destination site ID.
Definition at line 137 of file SiteSaver.php.
Referenced by Energine\share\gears\SiteSaver\save().
{
         $source = $this->dbh->select(
             'share_sitemap',
             array('smap_id', 'smap_layout', 'smap_content', 'smap_pid', 'smap_segment', 'smap_order_num', 'smap_redirect_url'),
             array('site_id' => $sourceSiteID)
         );
         if (is_array($source)) {
             $oldtoNewMAP = $this->copyRows($source, null, '', $destinationSiteID);
             foreach ($oldtoNewMAP as $oldID => $newID) {
                 $this->dbh->modifyRequest('
                 INSERT INTO share_sitemap_translation(
                     smap_id,
                     lang_id,
                     smap_name,
                     smap_description_rtf,
                     smap_html_title,
                     smap_meta_keywords,
                     smap_meta_description,
                     smap_is_disabled)
                 SELECT
                     %s,
                     lang_id,
                     smap_name,
                     smap_description_rtf,
                     smap_html_title,
                     smap_meta_keywords,
                     smap_meta_description,
                     smap_is_disabled
                  FROM share_sitemap_translation
                  WHERE smap_id = %s
                  ', $newID, $oldID
                 );
                 $this->dbh->modifyRequest(
                     'INSERT INTO share_sitemap_tags(smap_id, tag_id)
                      SELECT %s, tag_id
                         FROM share_sitemap_tags
                         WHERE smap_id = %s
                     ', $newID, $oldID
                 );
                 $this->dbh->modifyRequest(
                     'INSERT INTO share_access_level ' .
                     '(smap_id, right_id, group_id) ' .
                     'SELECT %s, al.right_id, al.group_id ' .
                     'FROM `share_access_level` al ' .
                     'WHERE al.smap_id = %s', $newID, $oldID
                 );
             }
         }
         //throw new SystemException('sdsdsd');
     }
Energine\share\gears\SiteSaver::createMainPage ($id) private
Create main page of the site and set rights for it.
Parameters
int $id Site ID.
Definition at line 74 of file SiteSaver.php.
Referenced by Energine\share\gears\SiteSaver\save().
{
         //        ,    default
         //   -  default.[type].xml
         //     -   default.[type].xml   ..  ?
         $module = $this->getData()->getFieldByName('site_folder')->getRowData(0);
         $content = $layout = false;
         foreach(array('content', 'layout') as $type){
             foreach(glob(implode(DIRECTORY_SEPARATOR, array(SITE_DIR, self::MODULES, $module, 'templates', $type, '*'))) as $path){
                 if($xml = simplexml_load_file($path)){
                     $attrs = $xml->attributes();
                     if(isset($attrs['default'])){
                         $$type = $module.'/'.basename($path);
                         break;
                     }
                 }
             }
             if(!$$type && file_exists(implode(DIRECTORY_SEPARATOR, array(SITE_DIR, self::MODULES, $module, 'templates', $type, 'default.'.$type.'.xml')))){
                 $$type = $module.'/'.'default.'.$type.'.xml';
             }
             if(!$$type){
                 $$type = 'default.'.$type.'.xml';
             }
             //
             //     ...
         }
         $translationTableName = 'share_sites_translation';
         //      -
         $smapId = $this->dbh->modify(QAL::INSERT, 'share_sitemap', array('smap_content' => $content, 'smap_layout' => $layout, 'site_id' => $id, 'smap_segment' => QAL::EMPTY_STRING));
         foreach ($_POST[$translationTableName] as $langID => $siteInfo) {
             $this->dbh->modify(
                 QAL::INSERT,
                 'share_sitemap_translation',
                 array(
                     'lang_id' => $langID,
                     'smap_id' => $smapId,
                     'smap_name' => $siteInfo['site_name']
                 )
             );
         }
         //
         $this->dbh->modifyRequest(
             'INSERT IGNORE INTO share_access_level ' .
             '(smap_id, right_id, group_id) ' .
             'SELECT %s, al.right_id, al.group_id ' .
             'FROM `share_access_level` al ' .
             'LEFT JOIN share_sitemap s ON s.smap_id = al.smap_id ' .
             'WHERE s.smap_pid is NULL AND site_id= %s',
             $smapId,
             E()->getSiteManager()->getDefaultSite()->id
         );
     }
Energine\share\gears\SiteSaver::save ()
Save data.
Note
After saving site data it creates new section, translations and rights.
Definition at line 34 of file SiteSaver.php.
{
         $mainTableName = 'share_sites';
         if (isset($_POST[$mainTableName]['site_is_default']) && $_POST[$mainTableName]['site_is_default'] !== '0') {
             $this->dbh->modify(QAL::UPDATE, $mainTableName, array('site_is_default' => 0));
         }
         $result = parent::save();
         $id = ($this->getMode() == QAL::INSERT) ? $result : $this->getData()->getFieldByName('site_id')->getRowData(0);
         //
         $domainIDs = simplifyDBResult($this->dbh->select('SELECT domain_id FROM share_domains WHERE domain_id NOT IN (SELECT domain_id FROM share_domain2site)'), 'domain_id');
         if (!empty($domainIDs)) {
             foreach ($domainIDs as $domainID) {
                 $this->dbh->modify(QAL::INSERT, 'share_domain2site', array('site_id' => $id, 'domain_id' => $domainID));
             }
         }
         //
         $tm = new TagManager($this->dataDescription, $this->dataDescription, 'share_sites');
         $tm->save($id);
         if ($this->getMode() == QAL::INSERT) {
             //
             //
             if (isset($_POST['copy_site_structure'])) {
                 $this->copyStructure((int)$_POST['copy_site_structure'], $id);
             } else {
                 $this->createMainPage($id);
             }
         }
         return $result;
     }
Member Data Documentation
string Energine\share\gears\SiteSaver::MODULES = 'modules'
Modules.
Definition at line 27 of file SiteSaver.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/SiteSaver.php