Energine: Energine\user\gears\VKOAuth Class Reference
Energine\user\gears\VKOAuth Class Reference
Class for user authorization over Вконтакте (VK).
Public Member Functions
__construct ($config, $return=false)
__destruct ()
getApiUrl ($method, $responseFormat= 'json')
Get API URL.
connect ()
Connect.
getLoginUrl ($params)
Get login URL.
getVKId ()
Get VK ID.
api ($method, $parameters=array(), $format= 'array')
API.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const AUTHORIZE_URL = 'https://oauth.vk.com/authorize'
Authorization URL.
const ACCESS_TOKEN_URL = 'https://oauth.vk.com/access_token'
Access token URL.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Member Functions
getCode ()
Get code.
createUrl ($url, $parameters)
Create URL.
request ($url, $method= 'GET', $postFields=array())
Send request.
Private Attributes
$appId
VK application ID.
$apiSecret
VK application secret key.
$accessToken = null
VK access token.
$ch
Instance curl.
$VKId = false
User ID.
$callbackUrl
Callback URL.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Class for user authorization over Вконтакте (VK).
class VKOAuth;
Definition at line 25 of file VKOAuth.php.
Constructor & Destructor Documentation
Energine\user\gears\VKOAuth::__construct ($config, $return = false)
Parameters
array $config Configurations
string | bool $return
Definition at line 80 of file VKOAuth.php.
{
         $this->callbackUrl = ($base = E()->getSiteManager()->getCurrentSite()->base)
             . 'auth.php?vkAuth&return=' . ((!$return) ? $base : $return);
         $this->appId = $config['appId'];
         $this->apiSecret = $config['secret'];
     }
Energine\user\gears\VKOAuth::__destruct ()
Definition at line 87 of file VKOAuth.php.
{
         if(is_resource($this->ch))
             curl_close($this->ch);
     }
Member Function Documentation
Energine\user\gears\VKOAuth::api ($method, $parameters = array(), $format = 'array')
API.
Parameters
string $method Method name.
array $parameters Parameters.
string $format Format.
Returns
mixed
Definition at line 178 of file VKOAuth.php.
{
         $parameters['timestamp'] = time();
         $parameters['api_id'] = $this->appId;
         $parameters['random'] = rand(0, 10000);
         if (!is_null($this->accessToken)) {
             $parameters['access_token'] = $this->accessToken;
         }
         ksort($parameters);
         $sig = '';
         foreach ($parameters as $key => $value) {
             $sig .= $key . '=' . $value;
         }
         $sig .= $this->apiSecret;
         $parameters['sig'] = md5($sig);
         $rs = $this->request($this->createUrl(
             $this->getApiUrl($method, $format == 'array' ? 'json' : $format), $parameters));
         return $format == 'array' ? json_decode($rs, true) : $rs;
     }
Energine\user\gears\VKOAuth::connect ()
Connect.
Returns
mixed
Exceptions
SystemException
Definition at line 110 of file VKOAuth.php.
{
         $this->ch = curl_init();
         $parameters = array(
             'client_id' => $this->appId,
             'client_secret' => $this->apiSecret,
             'code' => $this->getCode(),
             'redirect_uri' => $this->callbackUrl
         );
         $rs = json_decode($this->request(
             $this->createUrl(self::ACCESS_TOKEN_URL, $parameters)), true);
         if (isset($rs['error'])) {
             throw new SystemException($rs['error'] .
             (!isset($rs['error_description']) ? : ': ' . $rs['error_description']));
         } else {
             $this->accessToken = $rs['access_token'];
             $this->VKId = $rs['user_id'];
             return $rs;
         }
     }
Energine\user\gears\VKOAuth::createUrl ($url, $parameters) private
Create URL.
Parameters
string $url URL.
array $parameters Parameters.
Returns
string
Definition at line 207 of file VKOAuth.php.
Referenced by Energine\user\gears\VKOAuth\api(), Energine\user\gears\VKOAuth\connect(), and Energine\user\gears\VKOAuth\getLoginUrl().
{
         $piece = array();
         foreach ($parameters as $key => $value) {
             $piece[] = $key . '=' . rawurlencode($value);
         }
         $url .= '?' . implode('&', $piece);
         return $url;
     }
Energine\user\gears\VKOAuth::getApiUrl ($method, $responseFormat = 'json')
Get API URL.
Parameters
string $method Method name.
string $responseFormat Response format.
Returns
string
Definition at line 99 of file VKOAuth.php.
Referenced by Energine\user\gears\VKOAuth\api().
{
         return 'https://api.vk.com/method/' . $method . '.' . $responseFormat;
     }
Energine\user\gears\VKOAuth::getCode () private
Get code.
Returns
string | bool
Definition at line 153 of file VKOAuth.php.
Referenced by Energine\user\gears\VKOAuth\connect().
{
         $code = false;
         if (isset($_GET['code']) && ctype_alnum($_GET['code'])) {
             $code = $_GET['code'];
         }
         return $code;
     }
Energine\user\gears\VKOAuth::getLoginUrl ($params)
Get login URL.
Parameters
array $params Parameters.
Returns
string
Definition at line 137 of file VKOAuth.php.
{
         $parameters = array(
             'client_id' => $this->appId,
             'scope' => $params['scope'],
             'redirect_uri' => $params['redirect_uri'],
             'response_type' => 'code'
         );
         return $this->createUrl(self::AUTHORIZE_URL, $parameters);
     }
Energine\user\gears\VKOAuth::getVKId ()
Get VK ID.
Returns
int
Definition at line 166 of file VKOAuth.php.
{
         return $this->VKId;
     }
Energine\user\gears\VKOAuth::request ($url, $method = 'GET', $postFields = array()) private
Send request.
Parameters
string $url URL.
string $method Method name.
array $postFields Post fields.
Returns
mixed
Definition at line 224 of file VKOAuth.php.
Referenced by Energine\user\gears\VKOAuth\api(), and Energine\user\gears\VKOAuth\connect().
{
         curl_setopt_array($this->ch, array(
             CURLOPT_USERAGENT => 'VK/1.0',
             CURLOPT_RETURNTRANSFER => true,
             CURLOPT_SSL_VERIFYPEER => false,
             CURLOPT_POST => ($method == 'POST'),
             CURLOPT_POSTFIELDS => $postFields,
             CURLOPT_URL => $url
         ));
         return curl_exec($this->ch);
     }
Member Data Documentation
string Energine\user\gears\VKOAuth::$accessToken = null private
VK access token.
Definition at line 42 of file VKOAuth.php.
Referenced by Energine\user\gears\VKOAuth\api().
string Energine\user\gears\VKOAuth::$apiSecret private
VK application secret key.
Definition at line 36 of file VKOAuth.php.
Referenced by Energine\user\gears\VKOAuth\api().
string Energine\user\gears\VKOAuth::$appId private
VK application ID.
Definition at line 30 of file VKOAuth.php.
Referenced by Energine\user\gears\VKOAuth\api().
string Energine\user\gears\VKOAuth::$callbackUrl private
Callback URL.
URL for getting access token.
Definition at line 61 of file VKOAuth.php.
resource Energine\user\gears\VKOAuth::$ch private
Instance curl.
Definition at line 48 of file VKOAuth.php.
integer Energine\user\gears\VKOAuth::$VKId = false private
User ID.
Definition at line 54 of file VKOAuth.php.
Referenced by Energine\user\gears\VKOAuth\getVKId().
string Energine\user\gears\VKOAuth::ACCESS_TOKEN_URL = 'https://oauth.vk.com/access_token'
Access token URL.
Definition at line 73 of file VKOAuth.php.
string Energine\user\gears\VKOAuth::AUTHORIZE_URL = 'https://oauth.vk.com/authorize'
Authorization URL.
Definition at line 67 of file VKOAuth.php.
The documentation for this class was generated from the following file:
core/modules/user/gears/VKOAuth.php