Energine: Energine\apps\gears\AdsManager Class Reference
Energine\apps\gears\AdsManager Class Reference
Ads manager.
Public Member Functions
add (DataDescription $dd)
Add ad.
edit (Data $d, DataDescription $dd)
Edit ad.
save (array $data)
Save ad information.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static isActive ()
Is an ad active?
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes
const TABLE_NAME = 'apps_ads'
Table name.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Additional Inherited Members
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Ads manager.
class AdsManager;
Definition at line 25 of file AdsManager.php.
Member Function Documentation
Energine\apps\gears\AdsManager::add (DataDescription $dd)
Add ad.
Modify input DataDescription argument by adding to it an information about ad fields.
Parameters
DataDescription $dd Data description.
Definition at line 38 of file AdsManager.php.
{
         $fds = $this->dbh->getColumnsInfo(self::TABLE_NAME);
         unset($fds['smap_id']);
         unset($fds['ad_id']);
         foreach ($fds as $key => $value)
             $fds[$key]['tabName'] = 'TXT_ADS';
         $dd->load($fds);
     }
Energine\apps\gears\AdsManager::edit (Data $d, DataDescription $dd)
Edit ad.
Modify input DataDescription argument by adding to it an information about ad.
Parameters
Data $d Data.
DataDescription $dd Data description.
Definition at line 53 of file AdsManager.php.
{
         $fds = $this->dbh->getColumnsInfo(self::TABLE_NAME);
         unset($fds['smap_id']);
         $fds['ad_id']['key'] = false;
         foreach ($fds as $key => $value)
             $fds[$key]['tabName'] = 'TXT_ADS';
         $dd->load($fds);
         $data = $this->dbh->select(self::TABLE_NAME, array_keys($fds), array('smap_id' => $d->getFieldByName('smap_id')->getRowData(0)));
         if(is_array($data)){
             //Тут как всегда проблема с загрузкой значений в мультиязычный билдер
             foreach($data[0] as $fieldName => $fieldData){
                 $f = new Field($fieldName);
                 for($i=0, $l=sizeof(E()->getLanguage()->getLanguages()); $i<$l; $i++) {
                     $f->setRowData($i, $fieldData);
                 }
                 $d->addField($f);
             }
         }
     }
static Energine\apps\gears\AdsManager::isActive () static
Is an ad active?
Returns
bool
Definition at line 106 of file AdsManager.php.
Referenced by Energine\apps\components\Ads\__construct(), Energine\share\components\DivisionEditor\add(), Energine\share\components\DivisionEditor\edit(), and Energine\share\gears\DivisionSaver\save().
{
         return (bool)E()->getDB()->tableExists(self::TABLE_NAME);
     }
Energine\apps\gears\AdsManager::save (array $data)
Save ad information.
Parameters
array $data Energine.
Returns
array|bool
Definition at line 81 of file AdsManager.php.
{
         $checkIfDataExists = function($data) {
             //Что либо предпринимаем только в том случае когда хотя бы одно из значимых полей заполнено
             unset($data['ad_id'], $data['smap_id']);
             return (bool)array_filter($data);
         };
         $result = true;
         if(isset($data['ad_id']) && intval($adID = $data['ad_id'])){
             unset($data['ad_id']);
             if($checkIfDataExists($data))
                 $result = $this->dbh->modify(QAL::UPDATE, self::TABLE_NAME, $data, array('ad_id' => $adID));
             else
                 $result = $this->dbh->modify(QAL::DELETE, self::TABLE_NAME, null, array('ad_id' => $adID));
         } else {
             if($checkIfDataExists($data))
                 $result = $this->dbh->modify(QAL::INSERT, self::TABLE_NAME, $data);
         }
         return $result;
     }
Member Data Documentation
string Energine\apps\gears\AdsManager::TABLE_NAME = 'apps_ads'
Table name.
Definition at line 30 of file AdsManager.php.
Referenced by Energine\apps\components\Ads\main(), and Energine\share\gears\DivisionSaver\save().
The documentation for this class was generated from the following file:
core/modules/apps/gears/AdsManager.php