Energine: Energine\share\gears\Sitemap Class Reference
Energine\share\gears\Sitemap Class Reference
Site map.
Public Member Functions
__construct ($siteID)
getDefault ()
Get default page ID.
getURLByID ($smapID)
Get URL section by page ID.
getIDByURI (array $segments)
Get page ID by his URL.
getDocumentRights ($docID, $groups=false)
Get document rights.
getChilds ($smapID, $returnAsTreeNodeList=false)
Get all child sections.
getDescendants ($smapID)
Get all descendants.
getParent ($smapID)
Get parent.
getParents ($smapID)
Get parents.
getDocumentInfo ($id)
Get document information.
getTree ()
Get Tree object.
getInfo ()
Get the whole information about sections in unstructured view.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static getSiteID ($pageID)
Get site ID by page ID.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Private Member Functions
getSitemapData ($id)
Get information about sections.
preparePageInfo ($current)
Prepare page information.
buildPagesMap ($ids)
Build page map.
Private Attributes
$tree
Class exemplar that works with tree structures.
$info = array()
Information about sections where the user can access.
$defaultID = false
Default page ID.
$defaultMetaKeywords
Default Meta-Keywords.
$defaultMetaDescription
Default Meta-Description.
$defaultMetaRobots
Default Meta-Robots.
$langID
Current language ID.
$cacheAccessLevels = array()
Cache of access levels.
$siteID
Current site ID.
Additional Inherited Members
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Site map.
It contain the methods for work with site structure.
final class Sitemap;
Attention
This is singleton class.
This is final.
Definition at line 28 of file Sitemap.php.
Constructor & Destructor Documentation
Energine\share\gears\Sitemap::__construct ($siteID)
Parameters
int $siteID Site ID.
Exceptions
SystemException 'ERR_NO_TRANSLATION'
SystemException 'ERR_404'
Definition at line 94 of file Sitemap.php.
{
         parent::__construct();
         $this->siteID = $siteID;
         $this->langID = E()->getLanguage()->getCurrent();
         $userGroups = array_keys(E()->UserGroup->asArray());
         //Загружаем идентификаторы для последующего формирования древовидной стркутуры
         $res = $this->dbh->select(
             'SELECT s.smap_id, s.smap_pid FROM share_sitemap s ' .
             'LEFT JOIN share_sitemap_translation st ON st.smap_id = s.smap_id ' .
             'WHERE st.smap_is_disabled = 0 AND s.site_id = %s AND st.lang_id = %s ' .
             'AND s.smap_id IN( ' .
             ' SELECT smap_id ' .
             ' FROM share_access_level ' .
             ' WHERE group_id IN (' . implode(',', E()->getAUser()->getGroups()) . ')) ' .
             'ORDER BY smap_order_num',
             $this->siteID,
             $this->langID
         );
         //@todo Нужно бы накладывать ограничение в подзапросе на сайт, не факт правда что это увеличит быстродействие
         /*
         SELECT s.smap_id, s.smap_pid FROM share_sitemap s LEFT JOIN share_sitemap_translation st ON st.smap_id = s.smap_id WHERE st.smap_is_disabled = 0 AND s.site_id = '6' AND st.lang_id = '1' AND s.smap_id IN(
         SELECT a.smap_id
         FROM share_access_level  a
         LEFT JOIN share_sitemap s USING(smap_id)
         WHERE group_id IN (1) AND s.site_id=6
         ) ORDER BY smap_order_num
         */
         if ($res === true) {
             return;
             throw new SystemException('ERR_NO_TRANSLATION', SystemException::ERR_CRITICAL, $this->dbh->getLastRequest());
         }
         //Кешируем уровни доступа к страницам сайта
         //Формируем матрицу вида
         //[идентификатор раздела][идентификатор роли] = идентификатор уровня доступа
         $rightsMatrix = $this->dbh->select('share_access_level', true, array('smap_id' => array_map(create_function('$a', 'return $a["smap_id"];'), $res)));
         if (!is_array($rightsMatrix)) {
             throw new SystemException('ERR_404', SystemException::ERR_404);
         }
         foreach ($rightsMatrix as $data) {
             foreach ($userGroups as $groupID) {
                 //todo проверить вариант с пересечением array_diff
                 if (!isset($this->cacheAccessLevels[$data['smap_id']][$groupID]))
                     $this->cacheAccessLevels[$data['smap_id']][$groupID] = ACCESS_NONE;
             }
             $this->cacheAccessLevels[$data['smap_id']][$data['group_id']] = (int)$data['right_id'];
         }
         //Загружаем перечень идентификаторов в объект дерева
         $this->tree = TreeConverter::convert($res, 'smap_id', 'smap_pid');
         $res = $this->dbh->select('
           SELECT s.smap_id,ss.site_meta_keywords, ss.site_meta_description, sss.site_meta_robots
             FROM share_sitemap s
             LEFT JOIN share_sites_translation ss ON ss.site_id=s.site_id
             LEFT JOIN share_sites sss ON sss.site_id=s.site_id
             WHERE ss.site_id = %s AND s.smap_pid IS NULL and ss.lang_id = %s
         ', $this->siteID, $this->langID);
         list($res) = $res;
         $this->defaultID = $res['smap_id'];
         $this->defaultMetaKeywords = $res['site_meta_keywords'];
         $this->defaultMetaDescription = $res['site_meta_description'];
         $this->defaultMetaRobots = $res['site_meta_robots'];
         $this->getSitemapData(array_keys($this->tree->asList()));
     }
Member Function Documentation
Energine\share\gears\Sitemap::buildPagesMap ($ids) private
Build page map.
The returned array looks as follows:
array('$section_id'=>array())
Parameters
array $ids Section IDs.
Returns
array
Definition at line 426 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\getChilds(), Energine\share\gears\Sitemap\getDescendants(), and Energine\share\gears\Sitemap\getParents().
{
         $result = array();
         if (is_array($ids)) {
             foreach ($ids as $id) {
                 $info = $this->getDocumentInfo($id);
                 $info['Segment'] = $this->getURLByID($id);
                 $result[$id] = $info;
             }
         }
         return $result;
     }
Energine\share\gears\Sitemap::getChilds ($smapID, $returnAsTreeNodeList = false)
Get all child sections.
Parameters
int $smapID Section ID.
bool $returnAsTreeNodeList Return all as TreeNodeList?
Returns
array
Definition at line 361 of file Sitemap.php.
{
         $result = array();
         if ($node = $this->tree->getNodeById($smapID)) {
             if (!$returnAsTreeNodeList) {
                 $result = $this->buildPagesMap(array_keys($node->getChildren()->asList(false)));
             } else {
                 $result = $node->getChildren();
             }
         }
         return $result;
     }
Energine\share\gears\Sitemap::getDefault ()
Get default page ID.
Returns
int
Definition at line 261 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\getIDByURI().
{
         return $this->defaultID;
     }
Energine\share\gears\Sitemap::getDescendants ($smapID)
Get all descendants.
Parameters
int $smapID Section ID.
Returns
array
Definition at line 379 of file Sitemap.php.
{
         $result = array();
         if ($node = $this->tree->getNodeById($smapID)) {
             $result = $this->buildPagesMap(array_keys($node->getChildren()->asList()));
         }
         return $result;
     }
Energine\share\gears\Sitemap::getDocumentInfo ($id)
Get document information.
Parameters
int $id Section ID
Returns
array
Definition at line 445 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\buildPagesMap(), and Energine\share\gears\Sitemap\getURLByID().
{
         // Ищем документ с нужным идентификатором в $this->info
         if (isset($this->info[$id]))
             $result = $this->info[$id];
         else {
             $result = $this->getSitemapData($id);
             $result = $result[$id];
         }
         return $result;
     }
Energine\share\gears\Sitemap::getDocumentRights ($docID, $groups = false)
Get document rights.
It also defines the set of rights for a page.
Parameters
int $docID Document ID.
mixed $groups Group/set of groups. If this is not defined the group of current user will be used.
Returns
int
Definition at line 337 of file Sitemap.php.
{
         if (!$groups) {
             $groups = E()->getAUser()->getGroups();
         } elseif (!is_array($groups)) {
             $groups = array($groups);
         }
         $groups = array_combine($groups, $groups);
         $result = 0;
         if (isset($this->cacheAccessLevels[$docID])) {
             $result = max(array_intersect_key($this->cacheAccessLevels[$docID], $groups));
         }
         return $result;
     }
Energine\share\gears\Sitemap::getIDByURI (array $segments)
Get page ID by his URL.
Parameters
array $segments URL.
Returns
int
Definition at line 304 of file Sitemap.php.
{
         $request = E()->getRequest();
         $id = $this->getDefault();
         if (empty($segments)) {
             return $id;
         }
         foreach ($segments as $key => $segment) {
             $found = false;
             foreach ($this->info as $pageID => $pageInfo) {
                 if (($segment == $pageInfo['Segment']) && ($id == $pageInfo['Pid'])) {
                     $id = $pageID;
                     $request->setPathOffset($key + 1);
                     $found = true;
                     break;
                 }
             }
             if (!$found) {
                 break;
             }
         }
         //return ($id != $this->getDefault())?$id:false;
         return $id;
     }
Energine\share\gears\Sitemap::getInfo ()
Get the whole information about sections in unstructured view.
Returns
array
Definition at line 471 of file Sitemap.php.
{
         return $this->info;
     }
Energine\share\gears\Sitemap::getParent ($smapID)
Get parent.
Parameters
int $smapID Section ID.
Returns
int
Definition at line 393 of file Sitemap.php.
{
         $node = $this->tree->getNodeById($smapID);
         $result = false;
         if (!is_null($node)) {
             $result = key($node->getParents()->asList(false));
         }
         return $result;
     }
Energine\share\gears\Sitemap::getParents ($smapID)
Get parents.
Parameters
int $smapID Section ID.
Returns
array
Definition at line 409 of file Sitemap.php.
{
         $node = $this->tree->getNodeById($smapID);
         $result = array();
         if (!is_null($node)) {
             $result = $this->buildPagesMap(array_reverse(array_keys($node->getParents()->asList(false))));
         }
         return $result;
     }
static Energine\share\gears\Sitemap::getSiteID ($pageID) static
Get site ID by page ID.
Parameters
int $pageID Page ID.
Returns
mixed
Definition at line 172 of file Sitemap.php.
{
         return simplifyDBResult(
             E()->getDB()->select('share_sitemap', 'site_id', array('smap_id' => (int)$pageID)),
             'site_id',
             true
         );
     }
Energine\share\gears\Sitemap::getSitemapData ($id) private
Get information about sections.
Parameters
int | array $id Section ID or array of IDs.
Returns
array
Definition at line 186 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\__construct(), and Energine\share\gears\Sitemap\getDocumentInfo().
{
         if (!is_array($id)) {
             $id = array($id);
         }
         if ($diff = array_diff($id, array_keys($this->info))) {
             $ids = implode(',', $diff);
             $result = convertDBResult(
                 $this->dbh->select(
                     'SELECT s.smap_id,
                         s.smap_pid,
                         s.site_id as site,
                         s.smap_segment as Segment,
                         s.smap_meta_robots,
                         st.smap_name,
                         st.smap_title,
                         smap_redirect_url,
                         smap_description_rtf,
                         smap_html_title,
                         smap_meta_keywords,
                         smap_meta_description
                         FROM share_sitemap s
                         LEFT JOIN share_sitemap_translation st ON s.smap_id = st.smap_id
                         WHERE st.lang_id = %s AND s.site_id = %s AND s.smap_id IN (' .
                     $ids . ')',
                     $this->langID,
                     $this->siteID
                 ),
                 'smap_id', true);
             if (is_array($result)) {
                 $result = array_map(array($this, 'preparePageInfo'), $result);
                 $this->info += $result;
             }
         } else {
             $result = array();
             foreach ($this->info as $key => $value) {
                 if (in_array($key, $diff))
                     $result[$key] = $value;
             }
         }
         return $result;
     }
Energine\share\gears\Sitemap::getTree ()
Get Tree object.
Returns
TreeNodeList
Definition at line 462 of file Sitemap.php.
{
         return $this->tree;
     }
Energine\share\gears\Sitemap::getURLByID ($smapID)
Get URL section by page ID.
Parameters
int $smapID Page ID.
Returns
string
Definition at line 271 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\buildPagesMap().
{
         $result = array();
         $node = $this->tree->getNodeById($smapID);
         if (!is_null($node)) {
             $parents = array_reverse(array_keys($node->getParents()->asList(false)));
             foreach ($parents as $id) {
                 if (isset($this->info[$id]) && $this->info[$id]['Segment']) {
                     $result[] = $this->info[$id]['Segment'];
                 } else {
                     $res = $this->getDocumentInfo($id, false);
                     $result[] = $res['Segment'];
                 }
             }
         }
         $currentSegment = $this->getDocumentInfo($smapID);
         $currentSegment = $currentSegment['Segment'];
         $result[] = $currentSegment;
         $result = array_filter($result);
         if (!empty($result))
             $result = implode('/', $result) . '/';
         else {
             $result = '';
         }
         return $result;
     }
Energine\share\gears\Sitemap::preparePageInfo ($current) private
Prepare page information.
This is internal method for transforming information about document. It set all keys to camelNotation and change template ID for link.
Parameters
array $current Current page.
Returns
array
Definition at line 242 of file Sitemap.php.
{
         //inspect($current);
         //здесь что то лишнее
         //@todo А нужно ли вообще обрабатывать все разделы?
         $result = convertFieldNames($current, 'smap');
         if (is_null($result['MetaKeywords'])) $result['MetaKeywords'] = $this->defaultMetaKeywords;
         if (is_null($result['MetaDescription'])) $result['MetaDescription'] = $this->defaultMetaDescription;
         if (is_null($result['MetaRobots']) || empty($result['MetaRobots'])) $result['MetaRobots'] = $this->defaultMetaRobots;
         //if($result['RedirectUrl']) $result['RedirectUrl'] = (URI::validate($result['RedirectUrl']))?$result['RedirectUrl']:E()->getSiteManager()->getCurrentSite()->base.$result['RedirectUrl'];
         return $result;
     }
Member Data Documentation
array Energine\share\gears\Sitemap::$cacheAccessLevels = array() private
Cache of access levels.
Definition at line 80 of file Sitemap.php.
int Energine\share\gears\Sitemap::$defaultID = false private
Default page ID.
This variable was created to minimize the using of requests.
Definition at line 46 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\getDefault().
string Energine\share\gears\Sitemap::$defaultMetaDescription private
Default Meta-Description.
See also
Sitemap::defaultMetaKeywords
Definition at line 63 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\preparePageInfo().
string Energine\share\gears\Sitemap::$defaultMetaKeywords private
Default Meta-Keywords.
This is used for all pages that haven't custom Meta-keyword. This variable was created to minimize the using of requests.
Definition at line 55 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\preparePageInfo().
string Energine\share\gears\Sitemap::$defaultMetaRobots private
Default Meta-Robots.
Definition at line 68 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\preparePageInfo().
array Energine\share\gears\Sitemap::$info = array() private
Information about sections where the user can access.
Definition at line 39 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\buildPagesMap(), and Energine\share\gears\Sitemap\getInfo().
int Energine\share\gears\Sitemap::$langID private
Current language ID.
Definition at line 74 of file Sitemap.php.
int Energine\share\gears\Sitemap::$siteID private
Current site ID.
Definition at line 86 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\__construct().
TreeNodeList Energine\share\gears\Sitemap::$tree private
Class exemplar that works with tree structures.
Definition at line 33 of file Sitemap.php.
Referenced by Energine\share\gears\Sitemap\getTree().
The documentation for this class was generated from the following file:
core/modules/share/gears/Sitemap.php