Energine: Energine\comments\components\CommentsForm Class Reference
Energine\comments\components\CommentsForm Class Reference
Show comments and form for commenting.
Public Member Functions
__construct ($name, $module, array $params=null)
build ()
Public Member Functions inherited from Energine\share\components\DataSet
__construct ($name, $module, array $params=null)
getData ()
Get data.
build ()
Build block.
Public Member Functions inherited from Energine\share\gears\Component
__construct ($name, $module, array $params=null)
getState ()
Get current state of the component.
getCurrentStateRights ()
Get current rights level of the user.
getName ()
Get name.
run ()
Run current state method.
disable ()
Disable component.
enable ()
Enable component.
enabled ()
Is enabled?
build ()
Build block.
getStateParams ($returnAsAssocArray=false)
Get state parameters.
setStateParam ($paramName, $paramValue)
Set state parameter.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Member Functions
isExistsNeedTables ()
Check if required tables exist: commented table and table of comments.
saveComment ()
Save comment and give back JSON.
clearPost ($s)
Clear user's post.
isTargetEditable ()
Check if the current section for the user is editable.
deleteComment ()
Delete comment.
defineParams ()
prepare ()
showComments ()
Show comments.
ban ()
Ban.
banip ()
Ban IP.
checkCaptcha ()
Check captcha.
Protected Member Functions inherited from Energine\share\components\DataSet
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setData (Data $data)
Set Data object.
getToolbar ($toolbarName=false)
Get toolbar(s).
addToolbar ($toolbar)
Add toolbar.
setDataDescription (DataDescription $dataDescription)
Set data description.
getDataDescription ()
Возвращает описание данных
prepare ()
Prepare data.
createBuilder ()
Create builder.
createDataDescription ()
Create data description.
createToolbar ()
Create toolbar.
createPager ()
Create pager.
loadData ()
Load data.
loadDataDescription ()
Load data description.
getConfig ()
createData ()
Create data.
buildJS ()
Create description of JS objects.
setAction ($action, $isFullURI=false)
Set action for form processor.
getDataSetAction ()
Get an address of form processor.
setType ($type)
Set component type.
getType ()
Get component type.
setTitle ($title)
Set component title.
getTitle ()
Get component title.
addTranslation ()
Add translation.
downloadFile ($data, $MIMEType, $fileName)
Download file.
cleanup ()
Clean up.
addWYSIWYGTranslations ()
Add translations for WYSIWYG toolbar.
fileLibrary ()
Get file library.
source ()
Run source.
imageManager ()
Show image manager.
embedPlayer ()
Player for embedding in text areas.
Protected Member Functions inherited from Energine\share\gears\Component
isActive ()
Get the 'active' parameter of the component.
getConfig ()
Get component configurations.
setBuilder (IBuilder $builder)
Set component builder.
getBuilder ()
Get component builder.
defineParams ()
Defines allowable component parameters and their default values as an array like array(paramName => defaultValue)
setParam ($name, $value)
Set component parameter if such exist.
getParam ($name)
Get component parameter.
main ()
Default action.
prepare ()
Prepare data.
setProperty ($propName, $propValue)
Set/update property value.
getProperty ($propName)
Get property value.
removeProperty ($propName)
Remove property.
Private Member Functions
updateComment ($targetId, $commentName, $commentNick, $commentId)
Update comment.
removeComment ($id)
Remove comment.
addComment ($targetId, $commentName, $commentNick, $parentId=null)
Add comment.
getUserInfo ($uId)
Get user information.
buildResult ($comment)
Build result as JSON.
Private Attributes
$userEditor
User editor.
$banIPEditor
Editor of baned IPs.
$bindComponent
Bounded component.
$commentTable = ''
Table with comments.
$targetTable = ''
Commented table.
$isTree = false
Are the comments tree-like?
$isExistsTables = null
Are tables exist?
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\components\DataSet
static cleanupHTML ($data)
Remove malicious and redundant HTML code.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\components\DataSet
const COMPONENT_TYPE_LIST = 'list'
Component type: list.
const COMPONENT_TYPE_FORM = 'form'
Component type: form.
const COMPONENT_TYPE_FORM_ADD = QAL::INSERT
Form type: insert form.
const COMPONENT_TYPE_FORM_ALTER = QAL::UPDATE
Form type: edit form.
const TB_PREFIX = 'toolbar_'
Prefix for toolbar name.
const RECORD_PER_PAGE = 50
Default amount of records per page.
Public Attributes inherited from Energine\share\gears\Component
const DEFAULT_STATE_NAME = 'main'
Default state name:
$document
Page document.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Attributes inherited from Energine\share\components\DataSet
$fileLibrary
File library.
$imageManager
Image manager.
$js
JavaScript.
$pager
List of pages (pager).
Protected Attributes inherited from Energine\share\gears\Component
$doc
Document DOM of the component.
$request
Instance of the Request object.
$params
Component parameters.
$module
Module name that owns the component.
$response
Response object exemplar.
$builder = false
Builder of the component result.
$config
Component configurations.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
Show comments and form for commenting.
class CommentsForm;
Usage example in "*.content.xml":
<component name="commentsForm" module="comments" class="CommentsForm">
<params>
<param name="bind">newsArchive</param>
<param name="comment_tables">stb_news_comment</param>
<param name="show_comments">1</param>
<param name="show_form">1</param>
</params>
</component>
Definition at line 36 of file CommentsForm.php.
Constructor & Destructor Documentation
Energine\comments\components\CommentsForm::__construct ($name, $module, array $params = null)
Definition at line 83 of file CommentsForm.php.
{
         // если комментарии скрыты то бессмысленно показывать форму
         if (!isset($params['show_comments']) or !$params['show_comments']) {
             $params['show_form'] = 0;
         }
         parent::__construct($name, $module, $params);
         $this->commentTable = $this->getParam('comment_tables');
         $this->targetTable =
                 substr($this->commentTable, 0, strrpos($this->commentTable, '_'));
         $this->bindComponent =
                 $this->document->componentManager->getBlockByName($this->getParam('bind'));
         $this->isTree = $this->getParam('is_tree');
         $this->setProperty('limit', $this->getParam('textLimit'));
         $this->setProperty('is_anonymous', (string) !$this->document->user->isAuthenticated());
         $this->addTranslation('TXT_ENTER_CAPTCHA');
     }
Member Function Documentation
Energine\comments\components\CommentsForm::addComment ($targetId, $commentName, $commentNick, $parentId = null) private
Add comment.
It returns a comment as an array with user information in the field u_nick.
Parameters
int $targetId Comment ID.
string $commentName Comment.
string $commentNick Comment nick.
int $parentId Parent comment.
Returns
array
Definition at line 440 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\saveComment().
{
         if ($this->document->user && $this->document->user->getID()) {
             $uId = $this->document->user->getID();
             $userInfo = $this->getUserInfo($uId);
             $userName = array_shift($userInfo);
         } else {
             $uId = null;
             $userName = $commentNick;
         }
         $created = time(); // для JSONBuilder
         $createdStr = date('Y-m-d H:i:s', $created); // для запроса
         $parentIdSql = intval($parentId) ? intval($parentId) : 'NULL';
         $uIdSql = intval($uId) ? intval($uId) : 'NULL';
         $commentId = $this->dbh->modifyRequest("INSERT {$this->commentTable}
             SET target_id = %s,
                 comment_parent_id = $parentIdSql,
                 comment_name = %s,
                 comment_nick = %s,
                 u_id = $uIdSql,
                 comment_created = %s,
                 comment_approved = 0",
             $targetId, $commentName, $commentNick, $createdStr
         );
         return array(
             'is_tree' => (int) $this->isTree, // для отрисовки или не отрисовки ссылки "коментировать" в js
             'comment_id' => $commentId,
             'comment_parent_id' => $parentId,
             'target_id' => $targetId,
             'u_id' => $uId,
             'comment_created' => $createdStr,
             'comment_name' => $commentName,
             'comment_approved' => 0,
             'u_nick' => $userName
         );
     }
Energine\comments\components\CommentsForm::ban () protected
Ban.
Definition at line 609 of file CommentsForm.php.
{
         $this->request->setPathOffset($this->request->getPathOffset() + 1);
         $this->userEditor = $this->document->componentManager->createComponent('ue','user','UserEditor');
         $this->userEditor->run();
     }
Energine\comments\components\CommentsForm::banip () protected
Ban IP.
Definition at line 638 of file CommentsForm.php.
{
         $this->request->setPathOffset($this->request->getPathOffset() + 1);
         $this->banIPEditor = $this->document->componentManager->createComponent('bie','user','BanIPEditor');
         $this->banIPEditor->run();
     }
Energine\comments\components\CommentsForm::build ()
Exceptions
SystemException
Implements Energine\share\gears\IBlock.
Definition at line 618 of file CommentsForm.php.
{
         $result = '';
         switch($this->getState()){
             case 'ban':
                 $result = $this->userEditor->build();
                 break;
             case 'banip':
                 $result = $this->banIPEditor->build();
                 break;
             default:
                 $result = parent::build();
                 break;
         }
         return $result;
     }
Energine\comments\components\CommentsForm::buildResult ($comment) private
Build result as JSON.
Parameters
array $comment Comment.
Returns
IBuilder
Definition at line 511 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\saveComment().
{
         $builder = new CommentsJSONBuilder();
         $dataDescription = new DataDescription();
         $this->setDataDescription($dataDescription);
         $localData = new Data();
         $this->setData($localData);
         $localData->load($comment);
         $fd = new FieldDescription('comment_id');
         $fd->setType(FieldDescription::FIELD_TYPE_INT);
         $dataDescription->addFieldDescription($fd);
         if ($this->isTree) {
             $fd = new FieldDescription('is_tree');
             $fd->setType(FieldDescription::FIELD_TYPE_BOOL);
             $dataDescription->addFieldDescription($fd);
             if (isset($comment[0]['comment_parent_id'])) {
                 $fd = new FieldDescription('comment_parent_id');
                 $fd->setType(FieldDescription::FIELD_TYPE_INT);
                 $dataDescription->addFieldDescription($fd);
             }
         }
         $fd = new FieldDescription('target_id');
         $fd->setType(FieldDescription::FIELD_TYPE_INT);
         $dataDescription->addFieldDescription($fd);
         $fd = new FieldDescription('comment_name');
         $fd->setType(FieldDescription::FIELD_TYPE_STRING);
         $dataDescription->addFieldDescription($fd);
         $fd = new FieldDescription('u_id');
         $fd->setType(FieldDescription::FIELD_TYPE_INT);
         $dataDescription->addFieldDescription($fd);
         $fd = new FieldDescription('comment_created');
         $fd->setType(FieldDescription::FIELD_TYPE_DATETIME);
         $fd->setProperty('outputFormat', '%E');
         $dataDescription->addFieldDescription($fd);
         $fd = new FieldDescription('comment_approved');
         $fd->setType(FieldDescription::FIELD_TYPE_BOOL);
         $dataDescription->addFieldDescription($fd);
         $builder->setData($localData);
         $builder->setDataDescription($dataDescription);
         //добавляем поля о прокоментировавшем
         $fd = new FieldDescription('u_nick');
         $fd->setType(FieldDescription::FIELD_TYPE_STRING);
         $dataDescription->addFieldDescription($fd);
         return $builder;
     }
Energine\comments\components\CommentsForm::checkCaptcha () protected
Check captcha.
Exceptions
SystemException 'TXT_BAD_CAPTCHA'
Definition at line 649 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\saveComment().
{
         require_once('core/modules/share/gears/recaptchalib.php');
         $privatekey = $this->getConfigValue('recaptcha.private');
         $resp = recaptcha_check_answer($privatekey,
             $_SERVER["REMOTE_ADDR"],
             $_POST["recaptcha_challenge_field"],
             $_POST["recaptcha_response_field"]);
         if (!$resp->is_valid) {
             throw new SystemException($this->translate('TXT_BAD_CAPTCHA'), SystemException::ERR_CRITICAL);
         }
     }
Energine\comments\components\CommentsForm::clearPost ($s) protected
Clear user's post.
Parameters
string $s
Returns
string
Definition at line 214 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\saveComment().
{
         return strip_tags($s);
     }
Energine\comments\components\CommentsForm::defineParams () protected
Definition at line 338 of file CommentsForm.php.
{
         $result = array_merge(parent::defineParams(), array(
             'comment_tables' => '',
             'active' => true,
             'is_tree' => 0,
             'bind' => false,
             'bind_state' => 'view',
             'bind_pk_param_idx' => 0,
             'show_comments' => false,
             'show_form' => false,
             'textLimit' => 250,
             'allows_anonymous' => true,
         ));
         return $result;
     }
Energine\comments\components\CommentsForm::deleteComment () protected
Delete comment.
Exceptions
Exception 'Adding comments has been disabled'
Exception 'Add comment can auth user only'
Exception 'Mistake arg'
Definition at line 273 of file CommentsForm.php.
{
         $builder = new JSONCustomBuilder();
         $this->setBuilder($builder);
         try {
             if (!$this->getParam('show_form')) {
                 throw new \Exception('Adding comments has been disabled');
             }
             if (!$this->document->user->isAuthenticated()) {
                 throw new \Exception('Add comment can auth user only');
             }
             if (!isset($_POST['comment_id']) or
                     !($commentId = (int) $_POST['comment_id']))
                 throw new \Exception('Mistake arg');
             $builder->setProperties(
                 array(
                     'mode' => 'delete',
                     'result' => $this->removeComment($commentId)
                 )
             );
         }
         catch (SystemException $e) {
             $message['errors'][] = array('message' =>
             $e->getMessage() . current($e->getCustomMessage()));
             $builder->setProperties(
                 array_merge(
                     array('result' => false, 'header' => $this->translate('TXT_SHIT_HAPPENS')),
                     $message)
             );
         }
     }
Energine\comments\components\CommentsForm::getUserInfo ($uId) private
Get user information.
User name and avatar.
Parameters
int $uId User ID.
Returns
string[]
Definition at line 488 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\addComment().
{
         $result = array('u_nick' => '');
         $userInfo = $this->dbh->select('user_users',
             array('u_nick', 'u_fullname'),
             array('u_id' => $uId),
             null, array(1)
         );
         if ($userInfo) {
             $result = $userInfo[0];
             if (!$result['u_nick']) {
                 $result['u_nick'] = $result['u_fullname'];
             }
             unset($result['u_fullname']);
         }
         return $result;
     }
Energine\comments\components\CommentsForm::isExistsNeedTables () protected
Check if required tables exist: commented table and table of comments.
Returns
bool
Definition at line 109 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\prepare().
{
         if (is_null($this->isExistsTables)) {
             $this->isExistsTables =
                     (bool) $this->dbh->tableExists($this->commentTable) &&
                             (bool) $this->dbh->tableExists($this->targetTable);
         }
         return $this->isExistsTables;
     }
Energine\comments\components\CommentsForm::isTargetEditable () protected
Check if the current section for the user is editable.
Returns
bool
Definition at line 223 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\prepare(), Energine\comments\components\CommentsForm\removeComment(), Energine\comments\components\CommentsForm\saveComment(), and Energine\comments\components\CommentsForm\updateComment().
{
         if (!$this->getParam('allows_anonymous') && !E()->getAUser()->isAuthenticated())
             return false;
         $right =
                 E()->getMap()->getDocumentRights($this->document->getID());
         return $right >= ACCESS_READ;
     }
Energine\comments\components\CommentsForm::prepare () protected
Definition at line 358 of file CommentsForm.php.
{
         if ($this->getState() == 'deleteComment') {
             ;
             ;
         }
         else {
             if (($this->bindComponent &&
                     $this->bindComponent->getState() == $this->getParam('bind_state')) &&
                     ($this->getState() == 'main')
                     && $this->getParam('show_form') &&
                     $this->getParam('show_comments')
                     && $this->isExistsNeedTables()) {
                 parent::prepare();
                 if (
                     $this->document->getUser()->isAuthenticated()
                     &&
                     ($captcha =
                         $this->getDataDescription()->getFieldDescriptionByName('captcha'))
                 ) {
                     $this->getDataDescription()->removeFieldDescription($captcha);
                 }
                 //ID комментируемого элемента
                 $ap = $this->bindComponent->getStateParams(true);
                 //Тут костыль
                 if (is_array($ap)) {
                     $apk = array_keys($ap);
                     $param_idx = $this->getParam('bind_pk_param_idx');
                     $apName = (isset($apk[$param_idx])) ? $apk[$param_idx] : $apk[sizeof($apk) - 1];
                     $targetId = $ap[$apName];
                 } else {
                     $targetId = $this->document->getID();
                 }
                 if ($this->isTargetEditable()) {
                     $this->getDataDescription()->getFieldDescriptionByName('target_id')->setType(FieldDescription::FIELD_TYPE_HIDDEN);
                     $f = new Field('target_id');
                     $f->setData($targetId);
                     $this->getData()->addField($f);
                     // добавляем переводы для формы
                     $this->addTranslation('COMMENT_DO'); // коментировать
                     $this->addTranslation('COMMENT_DO_NEWS'); // коментировать новость
                     $this->addTranslation('COMMENT_REMAIN'); // осталось
                     $this->addTranslation('COMMENT_SYMBOL1'); // символ
                     $this->addTranslation('COMMENT_SYMBOL2'); // символа
                     $this->addTranslation('COMMENT_SYMBOL3'); // символов
                     $this->addTranslation('COMMENT_REALY_REMOVE'); // Действительно удалить комментарий?
                 }
                 else {
                     // форма нужна только для вывода списка комментариев
                     $this->setProperty('hide_form', 1);
                 }
                 $this->addTranslation('COMMENTS'); // коментирии
             }
             else {
                 $this->disable();
             }
             if ($this->getParam('show_comments') &&
                     $this->isExistsNeedTables() &&
                     is_object($this->bindComponent) &&
                     $this->bindComponent->getState() == $this->getParam('bind_state')
                     && $this->bindComponent->getData() &&
                     !$this->bindComponent->getData()->isEmpty()) {
                 $this->showComments();
             }
         }
     }
Energine\comments\components\CommentsForm::removeComment ($id) private
Remove comment.
Parameters
int $id Comment ID.
Returns
bool
Definition at line 313 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\deleteComment().
{
         if (!in_array('1', E()->getAUser()->getGroups())) {
             if (!$this->isTargetEditable()) { // юзеру доступно только чтение
                 return false;
             }
             // если не админ -  проверяем авторство
             $comments =
                     $this->dbh->select($this->commentTable, true, array('comment_id' => $id));
             if (!$comments) { // уже удалён
                 return true;
             }
             $comment = $comments[0];
             if (!E()->getAUser() || E()->getAUser()->getID() != $comment['u_id']) {
                 // не автор - запретить!
                 return false;
             }
         }
         return $this->dbh->modify(QAL::DELETE, $this->commentTable, null, array('comment_id' => $id));
     }
Energine\comments\components\CommentsForm::saveComment () protected
Save comment and give back JSON.
Only for authorized users.
Exceptions
Exception 'Adding comments has been disabled'
Exception 'Add comment can auth user only'
Exception 'Mistake targetId'
Exception 'Save error'
Definition at line 128 of file CommentsForm.php.
{
         $builder = new JSONCustomBuilder();
         $this->setBuilder($builder);
         try {
             if (!$this->getParam('show_form')) {
                 throw new \Exception('Adding comments has been disabled');
             }
             if (!$this->getParam('allows_anonymous') && !$this->document->user->isAuthenticated()) {
                 throw new \Exception('Add comment can auth user only');
             }
             if (!isset($_POST['target_id']) or
                     !($targetId = (int) $_POST['target_id']))
                 throw new Exception('Mistake targetId');
             if (!$this->isTargetEditable()) {
                 throw new SystemException('read only');
             }
             if (!$this->document->getUser()->isAuthenticated() && empty($_POST['comment_nick'])) {
                 throw new SystemException('TXT_COMMENT_NICK_IS_REQUIRED');
             }
             if (!$this->document->getUser()->isAuthenticated()) {
                 $this->checkCaptcha();
             }
             if (isset($_POST['comment_name']) and
                     $commentName = trim($_POST['comment_name'])) {
                 if ($this->isTree and isset($_POST['parent_id'])) {
                     $parentId = intval($_POST['parent_id']);
                 }
                 else $parentId = 0;
                 $commentName = $this->clearPost($commentName);
                 $commentNick = $this->clearPost((isset($_POST['comment_nick'])) ? $_POST['comment_nick'] : '');
                 if (isset($_POST['comment_id']) and
                         $commentId = intval($_POST['comment_id'])) {
                     // отредактированный коммент
                     if (!$isUpdated =
                             $this->updateComment($targetId, $commentName, $commentNick, $commentId))
                         throw new \Exception('Save error');
                 }
                 else {
                     // новый коммент
                     $comment =
                             $this->addComment($targetId, $commentName, $commentNick, $parentId);
                 }
             }
             else {
                 throw new SystemException('Comment is empty');
             }
             if (!empty($isUpdated)) {
                 $builder->setProperties(array(
                     'result' => true,
                     'mode' => 'update',
                     'data' => array(
                         'comment_name' => $commentName,
                         'comment_nick' => $commentNick,
                         'comment_id' => $commentId
                     )
                 ));
             }
             else {
                 $this->setBuilder($this->buildResult(array($comment)));
             }
         }
         catch (SystemException $e) {
             $message['errors'][] = array('message' =>
             $e->getMessage() . current($e->getCustomMessage()));
             $builder->setProperties(
                 array_merge(array('result' => false, 'header' => $this->translate('TXT_SHIT_HAPPENS')), $message));
         }
     }
Energine\comments\components\CommentsForm::showComments () protected
Show comments.
Definition at line 571 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\prepare().
{
         if ($this->getParam('bind_state') == 'main') {
             $targetIds = $this->document->getID();
         } else {
             $priFieldName = $this->bindComponent->getPK();
             $targetIds = $this->bindComponent->getData()->getFieldByName($priFieldName)->getData();
         }
         $commentsParams = array(
             'active' => true,
             'table_name' => $this->targetTable,
             'is_tree' => $this->getParam('is_tree'),
             'bind' => $this->getParam('bind'),
             'recordsPerPage' => $this->getParam('recordsPerPage'),
             'target_ids' => $targetIds
         );
         $this->setProperty('bind', $this->getParam('bind'));
         $commentsList =
                 $this->document->componentManager->createComponent('commentsList', 'comments', 'CommentsList', $commentsParams);
         $this->document->componentManager->addComponent($commentsList);
         if ($this->getParam('bind') && $forumTheme =
                 $this->document->componentManager->getBlockByName($this->getParam('bind'))) {
             $ap = $forumTheme->getStateParams(true);
             if (isset($ap['pageNumber'])) {
                 $commentsList->addActionParam('pageNumber', $ap['pageNumber']);
             }
         }
         $commentsList->run();
     }
Energine\comments\components\CommentsForm::updateComment ($targetId, $commentName, $commentNick, $commentId) private
Update comment.
Parameters
int $targetId Target ID.
string $commentName Comment name.
string $commentNick Nick.
string | int $commentId Comment ID.
Returns
bool|int
Definition at line 240 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\saveComment().
{
         if (!in_array('1', E()->getAUser()->getGroups())) {
             if (!$this->isTargetEditable()) { // юзеру доступно только чтение
                 return false;
             }
             // если не админ -  проверяем авторство
             $comments =
                     $this->dbh->select($this->commentTable, true, array('comment_id' => $commentId));
             if (!$comments) { // удалён
                 return false;
             }
             $comment = $comments[0];
             if (E()->getAUser()->getID() != $comment['u_id']) {
                 // не автор - запретить!
                 return false;
             }
         }
         return $this->dbh->modify(QAL::UPDATE, $this->commentTable,
             array(
                 'comment_name' => $commentName,
                 'comment_nick' => $commentNick,
             ),
             array('comment_id' => $commentId)
         );
     }
Member Data Documentation
mixed Energine\comments\components\CommentsForm::$banIPEditor private
Editor of baned IPs.
Definition at line 47 of file CommentsForm.php.
DBDataSet boolean Energine\comments\components\CommentsForm::$bindComponent private
Bounded component.
Definition at line 52 of file CommentsForm.php.
string Energine\comments\components\CommentsForm::$commentTable = '' private
Table with comments.
Note
It should be a component parameter.
Definition at line 60 of file CommentsForm.php.
bool Energine\comments\components\CommentsForm::$isExistsTables = null private
Are tables exist?
Definition at line 78 of file CommentsForm.php.
Referenced by Energine\comments\components\CommentsForm\isExistsNeedTables().
bool Energine\comments\components\CommentsForm::$isTree = false private
Are the comments tree-like?
Definition at line 72 of file CommentsForm.php.
string Energine\comments\components\CommentsForm::$targetTable = '' private
Commented table.
Definition at line 66 of file CommentsForm.php.
Component Energine\comments\components\CommentsForm::$userEditor private
User editor.
Definition at line 41 of file CommentsForm.php.
The documentation for this class was generated from the following file:
core/modules/comments/components/CommentsForm.php