Energine: Energine\share\gears\FTP Class Reference
Energine\share\gears\FTP Class Reference
Upload files over FTP.
Public Member Functions
__construct ($server, $port, $username, $password)
connect ()
Connect to FTP.
disconnect ()
Disconnect FTP-Server.
connected ()
Check if the server is connected.
uploadFile ($sourceFilename, $destFilename)
Upload file.
createDir ($dir)
Create directory.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Protected Attributes
$conn_id
Connection resource over FTP.
$server
FTP-Server address.
$port
FTP port.
$username
FTP username.
$password
FTP password.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
Upload files over FTP.
This is class-wrapper with build-in PHP functions for uploading files over FTP.
class FTP;
Definition at line 27 of file FTP.php.
Constructor & Destructor Documentation
Energine\share\gears\FTP::__construct ($server, $port, $username, $password)
Parameters
string $server FTP address.
string $port Port.
string $username Username.
string $password Password.
Definition at line 64 of file FTP.php.
{
         $this->server = $server;
         $this->port = $port;
         $this->username = $username;
         $this->password = $password;
     }
Member Function Documentation
Energine\share\gears\FTP::connect ()
Connect to FTP.
It connects and authorize the user on the FTP-server.
Returns
bool
Exceptions
SystemException 'ERR_CONNECT_FTP'
SystemException 'ERR_FRP_LOGIN_PASSWORD'
Definition at line 81 of file FTP.php.
{
         $this->conn_id = ftp_connect($this->server, $this->port);
         if (!$this->conn_id) throw new SystemException('ERR_CONNECT_FTP', SystemException::ERR_CRITICAL, $this->server);
         $login_result = ftp_login($this->conn_id, $this->username, $this->password);
         if (!$login_result) throw new SystemException('ERR_FRP_LOGIN_PASSWORD', SystemException::ERR_CRITICAL, $this->username);
         ftp_pasv($this->conn_id, true);
         return true;
     }
Energine\share\gears\FTP::connected ()
Check if the server is connected.
Returns
bool
Definition at line 114 of file FTP.php.
Referenced by Energine\share\gears\FTP\createDir(), Energine\share\gears\FTP\disconnect(), and Energine\share\gears\FTP\uploadFile().
{
         return is_resource($this->conn_id);
     }
Energine\share\gears\FTP::createDir ($dir)
Create directory.
Parameters
string $dir Directory name.
Returns
boolean
Exceptions
SystemException 'ERR_FTP_NOT_CONNECTED'
Definition at line 156 of file FTP.php.
Referenced by Energine\share\gears\FTP\uploadFile().
{
         if (!$this->connected()) throw new SystemException('ERR_FTP_NOT_CONNECTED', SystemException::ERR_CRITICAL);
         // рекурсивно переходит (и создает отсутствующие директории) в заданную директорию на ftp
         if ($dir and $dir != '.') {
             $dirs = explode('/', $dir);
             if ($dirs) {
                 foreach($dirs as $d) {
                     if (!empty($d)) {
                         $list = ftp_nlist($this->conn_id, '.');
                         if (is_array($list) and in_array($d, $list)) {
                             ftp_chdir($this->conn_id, $d);
                         } else {
                             ftp_mkdir($this->conn_id, $d);
                             ftp_chdir($this->conn_id, $d);
                         }
                     }
                 }
             }
         }
         return true;
     }
Energine\share\gears\FTP::disconnect ()
Disconnect FTP-Server.
It returns false if the server was not connected.
Returns
bool
Definition at line 100 of file FTP.php.
{
         if ($this->connected()) {
             ftp_close($this->conn_id);
             $this->conn_id = false;
             return true;
         }
         return false;
     }
Energine\share\gears\FTP::uploadFile ($sourceFilename, $destFilename)
Upload file.
Parameters
string $sourceFilename Source filename.
string $destFilename Destination filename.
Returns
boolean
Exceptions
SystemException 'ERR_FTP_NOT_CONNECTED'
Definition at line 127 of file FTP.php.
{
         if (!$this->connected()) throw new SystemException('ERR_FTP_NOT_CONNECTED', SystemException::ERR_CRITICAL);
         $dirname = dirname($destFilename);
         $basename = basename($destFilename);
         if ($dirname) {
             $this->createDir($dirname);
         }
         // delete existing file before ftp_put, if any
         $list = ftp_nlist($this->conn_id, '.');
         if (is_array($list) and in_array($basename, $list)) {
             ftp_delete($this->conn_id, $basename);
         }
         return ftp_put($this->conn_id, $basename, $sourceFilename, FTP_BINARY);
     }
Member Data Documentation
resource Energine\share\gears\FTP::$conn_id protected
Connection resource over FTP.
Definition at line 32 of file FTP.php.
string Energine\share\gears\FTP::$password protected
FTP password.
Definition at line 56 of file FTP.php.
Referenced by Energine\share\gears\FTP\__construct().
int Energine\share\gears\FTP::$port protected
FTP port.
Definition at line 44 of file FTP.php.
Referenced by Energine\share\gears\FTP\__construct().
string Energine\share\gears\FTP::$server protected
FTP-Server address.
Definition at line 38 of file FTP.php.
Referenced by Energine\share\gears\FTP\__construct().
string Energine\share\gears\FTP::$username protected
FTP username.
Definition at line 50 of file FTP.php.
Referenced by Energine\share\gears\FTP\__construct().
The documentation for this class was generated from the following file:
core/modules/share/gears/FTP.php