Energine: Energine\share\gears\OKOAuth Class Reference
Energine\share\gears\OKOAuth Class Reference
Class for user authorisation over Однокласники.
Public Member Functions
__construct ($config, $return=false)
connect ()
Connect.
getUser ()
Get user information.
getLoginUrl ($params)
Get login URL.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const API_URL = 'http://api.odnoklassniki.ru/fb.do'
API URL.
const AUTHORIZE_URL = 'http://www.odnoklassniki.ru/oauth/authorize'
Authorize URL.
const ACCESS_TOKEN_URL = 'http://api.odnoklassniki.ru/oauth/token.do'
Access token URL.
const SIGN_TOKEN_NAME = 'access_token'
Sign token name.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Member Functions
request ($url, $params=array(), $method= 'GET')
Send request.
parseRequestResult ($result)
Parse request result.
api ($url, $method="GET", $parameters=array())
API.
createUrl ($url, $parameters)
Create URL.
getCode ()
Get code.
Private Attributes
$appSecret
Application secret key.
$appId
Application ID.
$appPublic
Application public key.
$callbackUrl
Callback URL.
$accessToken
Access token.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Class for user authorisation over Однокласники.
class OKOAuth;
Definition at line 24 of file OKOAuth.php.
Constructor & Destructor Documentation
Energine\share\gears\OKOAuth::__construct ($config, $return = false)
Parameters
array $config Configurations.
bool $return
Definition at line 76 of file OKOAuth.php.
{
         $this->appId = $config['appId'];
         $this->appPublic = $config['public'];
         $this->appSecret = $config['secret'];
         $this->callbackUrl = ($base = E()->getSiteManager()->getCurrentSite()->base)
             . 'auth.php?okAuth&return=' . ((!$return) ? $base : $return);
     }
Member Function Documentation
Energine\share\gears\OKOAuth::api ($url, $method = "GET", $parameters = array()) private
API.
Parameters
string $url URL.
string $method Method name.
array $parameters Parameters.
Returns
mixed|null
Definition at line 176 of file OKOAuth.php.
Referenced by Energine\share\gears\OKOAuth\getUser().
{
         if ( strrpos($url, 'http://') !== 0 && strrpos($url, 'https://') !== 0 ) {
             $url = self::API_URL . $url;
         }
         $parameters['access_token'] = $this->accessToken;
         $response = null;
         switch( $method ) {
             case 'GET'  : $response = $this->request( $url, $parameters, "GET"  ); break;
             case 'POST' : $response = $this->request( $url, $parameters, "POST" ); break;
         }
         if($response){
             $response = json_decode( $response );
         }
         return $response;
     }
Energine\share\gears\OKOAuth::connect ()
Connect.
Returns
mixed
Exceptions
Exception
Definition at line 132 of file OKOAuth.php.
{
         $parameters = array(
             "client_id"     => $this->appId,
             "client_secret" => $this->appSecret,
             "grant_type"    => "authorization_code",
             "redirect_uri"  => $this->callbackUrl,
             "code"          => $this->getCode()
         );
         $response = $this->request($this->createUrl(self::ACCESS_TOKEN_URL, $parameters), $parameters);
         $response = $this->parseRequestResult($response);
         if(!$response || !isset($response->access_token)){
             throw new \Exception( "Error: " . $response->error);
         }
         $this->accessToken = $response->access_token;
         return $response;
     }
Energine\share\gears\OKOAuth::createUrl ($url, $parameters) private
Create URL.
Parameters
string $url URL.
array $parameters Parameters.
Returns
string
Definition at line 216 of file OKOAuth.php.
Referenced by Energine\share\gears\OKOAuth\connect(), and Energine\share\gears\OKOAuth\getLoginUrl().
{
         $piece = array();
         foreach ($parameters as $key => $value) {
             $piece[] = $key . '=' . rawurlencode($value);
         }
         $url .= '?' . implode('&', $piece);
         return $url;
     }
Energine\share\gears\OKOAuth::getCode () private
Get code.
Returns
string
Definition at line 230 of file OKOAuth.php.
Referenced by Energine\share\gears\OKOAuth\connect().
{
         $code = false;
         if (isset($_GET['code'])) {
             $code = $_GET['code'];
         }
         return $code;
     }
Energine\share\gears\OKOAuth::getLoginUrl ($params)
Get login URL.
Parameters
array $params Parameters.
Returns
string
Definition at line 198 of file OKOAuth.php.
{
         $parameters = array(
             'client_id' => $this->appId,
             'scope' => $params['scope'],
             'redirect_uri' => $params['redirect_uri'],
             'response_type' => 'code'
         );
         return $this->createUrl(self::AUTHORIZE_URL, $parameters);
     }
Energine\share\gears\OKOAuth::getUser ()
Get user information.
Returns
array
Definition at line 155 of file OKOAuth.php.
{
         $user = array();
         $sig = md5('application_key=' . $this->appPublic . 'method=users.getCurrentUser' . md5($this->accessToken . $this->appSecret));
         $response = $this->api( '?application_key=' . $this->appPublic . '&method=users.getCurrentUser&sig=' .$sig);
         $user['id']    = (property_exists($response,'uid'))?$response->uid:"";
         $user['firstName']     = (property_exists($response,'first_name'))?$response->first_name:"";
         $user['lastName']      = (property_exists($response,'last_name'))?$response->last_name:"";
         $user['photoURL']      = (property_exists($response,'pic_1'))?$response->pic_1:"";
         return $user;
     }
Energine\share\gears\OKOAuth::parseRequestResult ($result) private
Parse request result.
Parameters
mixed $result Request result.
Returns
mixed|StdClass
Definition at line 113 of file OKOAuth.php.
Referenced by Energine\share\gears\OKOAuth\connect().
{
         if(json_decode($result)) {
             return json_decode($result);
         }
         parse_str($result, $output);
         $result = new StdClass();
         foreach($output as $k => $v) {
             $result->$k = $v;
         }
         return $result;
     }
Energine\share\gears\OKOAuth::request ($url, $params = array(), $method = 'GET') private
Send request.
Parameters
string $url URL.
array $params Parameters.
string $method Method name.
Returns
mixed
Definition at line 92 of file OKOAuth.php.
Referenced by Energine\share\gears\OKOAuth\api(), and Energine\share\gears\OKOAuth\connect().
{
         $ch = curl_init();
         curl_setopt_array($ch, array(
             CURLOPT_USERAGENT => 'OK/1.0',
             CURLOPT_RETURNTRANSFER => true,
             CURLOPT_SSL_VERIFYPEER => false,
             CURLOPT_POST => ($method == 'POST'),
             CURLOPT_POSTFIELDS => $params,
             CURLOPT_URL => $url
         ));
         $response = curl_exec($ch);
         curl_close ($ch);
         return $response;
     }
Member Data Documentation
Energine\share\gears\OKOAuth::$accessToken private
Access token.
Definition at line 70 of file OKOAuth.php.
Referenced by Energine\share\gears\OKOAuth\api().
int Energine\share\gears\OKOAuth::$appId private
Application ID.
Definition at line 55 of file OKOAuth.php.
string Energine\share\gears\OKOAuth::$appPublic private
Application public key.
Definition at line 60 of file OKOAuth.php.
int string Energine\share\gears\OKOAuth::$appSecret private
Application secret key.
Definition at line 50 of file OKOAuth.php.
string Energine\share\gears\OKOAuth::$callbackUrl private
Callback URL.
Definition at line 65 of file OKOAuth.php.
string Energine\share\gears\OKOAuth::ACCESS_TOKEN_URL = 'http://api.odnoklassniki.ru/oauth/token.do'
Access token URL.
Definition at line 39 of file OKOAuth.php.
string Energine\share\gears\OKOAuth::API_URL = 'http://api.odnoklassniki.ru/fb.do'
API URL.
Definition at line 29 of file OKOAuth.php.
string Energine\share\gears\OKOAuth::AUTHORIZE_URL = 'http://www.odnoklassniki.ru/oauth/authorize'
Authorize URL.
Definition at line 34 of file OKOAuth.php.
string Energine\share\gears\OKOAuth::SIGN_TOKEN_NAME = 'access_token'
Sign token name.
Definition at line 44 of file OKOAuth.php.
The documentation for this class was generated from the following file:
core/modules/user/gears/OKOAuth.php