Energine: Energine\share\gears\TreeNodeList Class Reference
Energine\share\gears\TreeNodeList Class Reference
List of nodes.
Public Member Functions
__construct ()
add (TreeNode $node)
Add node.
getRoot ()
Get root node.
insertBefore (TreeNode $node, TreeNode $beforeNode)
Insert node before target node.
remove (TreeNode $node)
Remove node.
getLength ()
Get the length of node list.
getNodeById ($id)
Get node by his ID.
asList ($isRecursive=true)
Get the tree as an array.
current ()
Get current element.
key ()
Return the key of the current element.
next ()
Move forward to next element.
rewind ()
Rewind the Iterator to the first element.
valid ()
Checks if current position is valid.
merge (TreeNodeList $newNodeList)
Merge node lists.
Private Member Functions
findNode ($id, TreeNodeList $nodeList)
Find the node in node list.
Private Attributes
$currentKey
Internal pointer.
$nodeList = array()
Node list.
Detailed Description
List of nodes.
class TreeNodeList;
Definition at line 25 of file TreeNodeList.php.
Constructor & Destructor Documentation
Energine\share\gears\TreeNodeList::__construct ()
Definition at line 39 of file TreeNodeList.php.
{
     }
Member Function Documentation
Energine\share\gears\TreeNodeList::add (TreeNode $node)
Add node.
Parameters
TreeNode $node New node.
Returns
TreeNode
Definition at line 49 of file TreeNodeList.php.
{
         $this->nodeList[$node->getID()] = $node;
         return $node;
     }
Energine\share\gears\TreeNodeList::asList ($isRecursive = true)
Get the tree as an array.
Parameters
bool $isRecursive Is recursive?
Returns
array
Definition at line 135 of file TreeNodeList.php.
{
         $result = array();
         foreach ($this as $node) {
             $result += $node->asList($isRecursive);
         }
         return $result;
     }
Energine\share\gears\TreeNodeList::current ()
Get current element.
Returns
mixed
http://php.net/manual/en/iterator.current.php
Implements Iterator.
Definition at line 144 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNodeList\getRoot().
{
         return $this->nodeList[$this->currentKey];
     }
Energine\share\gears\TreeNodeList::findNode ($id, TreeNodeList $nodeList) private
Find the node in node list.
Parameters
int $id Node ID.
TreeNodeList $nodeList Node list.
Returns
TreeNode|null
Definition at line 114 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNodeList\getNodeById().
{
         foreach ($nodeList as $node) {
             if ($node->getID() == $id) {
                 return $node;
             }
             elseif($node->hasChildren()) {
                 $result = $this->findNode($id, $node->getChildren());
                 if (!is_null($result)) {
                     return $result;
                 }
             }
         }
         return null;
     }
Energine\share\gears\TreeNodeList::getLength ()
Get the length of node list.
Returns
int
Definition at line 93 of file TreeNodeList.php.
{
         return sizeof($this->nodeList);
     }
Energine\share\gears\TreeNodeList::getNodeById ($id)
Get node by his ID.
Parameters
int $id Node ID.
Returns
TreeNode
Definition at line 103 of file TreeNodeList.php.
{
         return $this->findNode($id, $this);
     }
Energine\share\gears\TreeNodeList::getRoot ()
Get root node.
Returns
TreeNode
Definition at line 58 of file TreeNodeList.php.
{
         $k = array_keys($this->nodeList);
         $k = current($k);
         return $this->nodeList[$k];
     }
Energine\share\gears\TreeNodeList::insertBefore (TreeNode $node, TreeNode $beforeNode)
Insert node before target node.
Parameters
TreeNode $node Node that will be inserted.
TreeNode $beforeNode Target node.
Returns
TreeNode
Definition at line 71 of file TreeNodeList.php.
{
     }
Energine\share\gears\TreeNodeList::key ()
Return the key of the current element.
Returns
mixed
http://php.net/manual/en/iterator.key.php
Implements Iterator.
Definition at line 148 of file TreeNodeList.php.
{
         return $this->currentKey;
     }
Energine\share\gears\TreeNodeList::merge (TreeNodeList $newNodeList)
Merge node lists.
Parameters
TreeNodeList $newNodeList New node list.
Returns
TreeNodeList
Definition at line 199 of file TreeNodeList.php.
{
         $this->nodeList = array_merge($this->nodeList, $newNodeList->nodeList);
         return $this;
     }
Energine\share\gears\TreeNodeList::next ()
Move forward to next element.
http://php.net/manual/en/iterator.next.php
Implements Iterator.
Definition at line 152 of file TreeNodeList.php.
{
         //получаем все ключи
         $keys = array_keys($this->nodeList);
         //меняем местами ключ со значением, получая индексы
         $indexes = array_flip($keys);
         //получаем индекс текущего ключа
         $currentIndex = $indexes[$this->currentKey];
         $currentIndex++;
         if(isset($keys[$currentIndex])) {
             $this->currentKey = $keys[$currentIndex];
         }
         else {
             $this->currentKey = null;
         }
     }
Energine\share\gears\TreeNodeList::remove (TreeNode $node)
Remove node.
Parameters
TreeNode $node Node.
Returns
TreeNode
Definition at line 81 of file TreeNodeList.php.
{
         $result = $node;
         unset($this->nodeList[$node->getID()]);
         return $result;
     }
Energine\share\gears\TreeNodeList::rewind ()
Rewind the Iterator to the first element.
Returns
bool
http://php.net/manual/en/iterator.rewind.php
Implements Iterator.
Definition at line 168 of file TreeNodeList.php.
{
         if(empty($this->nodeList)) return;
         //получаем все ключи
         $keys = array_keys($this->nodeList);
         //меняем местами ключ со значением, получая индексы
         $this->currentKey = $keys[0];
     }
Energine\share\gears\TreeNodeList::valid ()
Checks if current position is valid.
Returns
bool
http://php.net/manual/en/iterator.valid.php
Implements Iterator.
Definition at line 176 of file TreeNodeList.php.
{
         if(!is_null($this->currentKey)){
             $keys = array_keys($this->nodeList);
             $indexes = array_flip($keys);
             if(!isset($indexes[$this->currentKey])) {
                 $result = false;
             }
             else {
                 $result = $indexes[$this->currentKey] < sizeof($indexes);
             }
         }
         else {
             $result = false;
         }
         return $result;
     }
Member Data Documentation
mixed Energine\share\gears\TreeNodeList::$currentKey private
Internal pointer.
Definition at line 30 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNodeList\current(), Energine\share\gears\TreeNodeList\key(), Energine\share\gears\TreeNodeList\next(), and Energine\share\gears\TreeNodeList\valid().
array Energine\share\gears\TreeNodeList::$nodeList = array() private
Node list.
Array of TreeNode.
Definition at line 37 of file TreeNodeList.php.
Referenced by Energine\share\gears\TreeNodeList\getLength().
The documentation for this class was generated from the following file:
core/modules/share/gears/TreeNodeList.php