Energine: Energine\share\gears\ComponentContainer Class Reference
Energine\share\gears\ComponentContainer Class Reference
Container of components.
Public Member Functions
__construct ($name, array $properties=array())
add (IBlock $block)
Add block.
isEmpty ()
Check if the container is empty.
getName ()
Get name.
setProperty ($propertyName, $propertyValue)
Set property to the ComponentContainer::$properties.
getProperty ($propertyName)
Get property value from ComponentContainer::$properties by property name.
removeProperty ($propertyName)
Remove property from ComponentContainer::$properties.
build ()
Build DOM document.
run ()
Call run() method for all blocks.
rewind ()
Rewind the Iterator to the first element.
valid ()
Checks if current position is valid.
key ()
Return the key of the current element.
next ()
Move forward to next element.
current ()
Get current element.
disable ()
Disable ComponentContainer.
enabled ()
Is enabled?
getCurrentStateRights ()
Get current rights level of the user.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static createFromDescription (\SimpleXMLElement $containerDescription, array $additionalAttributes=array())
Create component container from description.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Private Attributes
$enabled = true
Defines whether the component container is enabled.
$properties = array()
Properties.
$name
Container name.
$blocks = array()
Array of IBlock.
$iteratorIndex = 0
Iterator index.
$childNames = array()
Array of child names.
$document
Additional Inherited Members
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Detailed Description
Container of components.
class ComponentContainer
Definition at line 24 of file ComponentContainer.php.
Constructor & Destructor Documentation
Energine\share\gears\ComponentContainer::__construct ($name, array $properties = array())
Parameters
string $name Component name.
array $properties Component properties.
Definition at line 63 of file ComponentContainer.php.
{
         $this->name = $name;
         $this->document = E()->getDocument();
         $this->properties = $properties;
         if (!isset($this->properties['tag'])) {
             $this->properties['tag'] = 'container';
         }
         $this->document->componentManager->register($this);
     }
Member Function Documentation
Energine\share\gears\ComponentContainer::add (IBlock $block)
Add block.
Parameters
IBlock $block New block.
Definition at line 78 of file ComponentContainer.php.
{
         $this->blocks[$block->getName()] = $block;
     }
Energine\share\gears\ComponentContainer::build ()
Build DOM document.
Returns
DOMElement|array
Implements Energine\share\gears\IBlock.
Definition at line 164 of file ComponentContainer.php.
{
         $doc = new \DOMDocument('1.0', 'UTF-8');
         $containerDOM = $doc->createElement($this->properties['tag']);
         $containerDOM->setAttribute('name', $this->getName());
         $doc->appendChild($containerDOM);
         foreach ($this->properties as $propertyName => $propertyValue) {
             if ($propertyName != 'tag') {
                 $containerDOM->setAttribute($propertyName, $propertyValue);
             }
         }
         foreach ($this->blocks as $block) {
             if (
                 $block->enabled()
                 &&
                 ($this->document->getRights() >= $block->getCurrentStateRights())
             ) {
                 $blockDOM = $block->build();
                 if ($blockDOM instanceof \DOMDocument) {
                     $blockDOM =
                         $doc->importNode($blockDOM->documentElement, true);
                     $containerDOM->appendChild($blockDOM);
                 }
             }
         }
         return $doc;
     }
static Energine\share\gears\ComponentContainer::createFromDescription (\SimpleXMLElement $containerDescription, array $additionalAttributes = array()) static
Create component container from description.
Parameters
\SimpleXMLElement $containerDescription Container description.
array $additionalAttributes Additional attributes.
Returns
ComponentContainer
Exceptions
SystemException ERR_NO_CONTAINER_NAME
Definition at line 90 of file ComponentContainer.php.
Referenced by Energine\share\gears\ComponentManager\createBlockFromDescription().
{
         $attributes = $containerDescription->attributes();
         if (in_array($containerDescription->getName(), array('page', 'content'))) {
             $properties['name'] = $containerDescription->getName();
         }
         elseif (!isset($attributes['name'])) {
             throw new SystemException('ERR_NO_CONTAINER_NAME', SystemException::ERR_DEVELOPER);
         }
         foreach ($attributes as $propertyName => $propertyValue) {
             $properties[(string) $propertyName] = (string) $propertyValue;
         }
         $name = $properties['name'];
         unset($properties['name']);
         $properties = array_merge($properties, $additionalAttributes);
         $result = new ComponentContainer($name, $properties);
         foreach ($containerDescription->children() as $blockDescription) {
             $result->add(ComponentManager::createBlockFromDescription($blockDescription));
         }
         return $result;
     }
Energine\share\gears\ComponentContainer::current ()
Get current element.
Returns
mixed
http://php.net/manual/en/iterator.current.php
Implements Iterator.
Definition at line 221 of file ComponentContainer.php.
{
         return $this->blocks[$this->childNames[$this->iteratorIndex]];
     }
Energine\share\gears\ComponentContainer::disable ()
Disable ComponentContainer.
Definition at line 228 of file ComponentContainer.php.
{
         $this->enabled = false;
         foreach ($this->blocks as $block) {
             $block->disable();
         }
     }
Energine\share\gears\ComponentContainer::enabled ()
Is enabled?
Returns
bool
Implements Energine\share\gears\IBlock.
Definition at line 236 of file ComponentContainer.php.
Referenced by Energine\share\gears\ComponentContainer\disable().
{
         return $this->enabled;
     }
Energine\share\gears\ComponentContainer::getCurrentStateRights ()
Get current rights level of the user.
This is needed for running current action.
Returns
mixed
Implements Energine\share\gears\IBlock.
Definition at line 240 of file ComponentContainer.php.
{
         return 0;
     }
Energine\share\gears\ComponentContainer::getName ()
Get name.
Returns
string
Implements Energine\share\gears\IBlock.
Definition at line 122 of file ComponentContainer.php.
Referenced by Energine\share\gears\ComponentContainer\build().
{
         return $this->name;
     }
Energine\share\gears\ComponentContainer::getProperty ($propertyName)
Get property value from ComponentContainer::$properties by property name.
Parameters
string $propertyName Property name.
Returns
string or null
Definition at line 142 of file ComponentContainer.php.
{
         $result = null;
         if (isset($this->properties[$propertyName])) {
             $result = $this->properties[$propertyName];
         }
         return $result;
     }
Energine\share\gears\ComponentContainer::isEmpty ()
Check if the container is empty.
Returns
bool
Definition at line 118 of file ComponentContainer.php.
{
         return (boolean) sizeof($this->childs);
     }
Energine\share\gears\ComponentContainer::key ()
Return the key of the current element.
Returns
mixed
http://php.net/manual/en/iterator.key.php
Implements Iterator.
Definition at line 213 of file ComponentContainer.php.
{
         return $this->childNames[$this->iteratorIndex];
     }
Energine\share\gears\ComponentContainer::next ()
Move forward to next element.
http://php.net/manual/en/iterator.next.php
Implements Iterator.
Definition at line 217 of file ComponentContainer.php.
{
         $this->iteratorIndex++;
     }
Energine\share\gears\ComponentContainer::removeProperty ($propertyName)
Remove property from ComponentContainer::$properties.
Parameters
string $propertyName Property name.
Definition at line 155 of file ComponentContainer.php.
{
         unset($this->properties[$propertyName]);
     }
Energine\share\gears\ComponentContainer::rewind ()
Rewind the Iterator to the first element.
Returns
bool
http://php.net/manual/en/iterator.rewind.php
Implements Iterator.
Definition at line 204 of file ComponentContainer.php.
{
         $this->childNames = array_keys($this->blocks);
         $this->iteratorIndex = 0;
     }
Energine\share\gears\ComponentContainer::run ()
Call run() method for all blocks.
Implements Energine\share\gears\IBlock.
Definition at line 194 of file ComponentContainer.php.
{
         foreach ($this->blocks as $block) {
             if ($block->enabled()
                 && ($this->document->getRights() >= $block->getCurrentStateRights())
             ) {
                 $block->run();
             }
         }
     }
Energine\share\gears\ComponentContainer::setProperty ($propertyName, $propertyValue)
Set property to the ComponentContainer::$properties.
Parameters
string $propertyName Property name.
string $propertyValue Property value.
Definition at line 132 of file ComponentContainer.php.
{
         $this->properties[(string) $propertyName] = (string) $propertyValue;
     }
Energine\share\gears\ComponentContainer::valid ()
Checks if current position is valid.
Returns
bool
http://php.net/manual/en/iterator.valid.php
Implements Iterator.
Definition at line 209 of file ComponentContainer.php.
{
         return isset($this->childNames[$this->iteratorIndex]);
     }
Member Data Documentation
array Energine\share\gears\ComponentContainer::$blocks = array() private
Array of IBlock.
Definition at line 44 of file ComponentContainer.php.
array Energine\share\gears\ComponentContainer::$childNames = array() private
Array of child names.
Definition at line 54 of file ComponentContainer.php.
Document Energine\share\gears\ComponentContainer::$document private
Definition at line 58 of file ComponentContainer.php.
bool Energine\share\gears\ComponentContainer::$enabled = true private
Defines whether the component container is enabled.
Definition at line 29 of file ComponentContainer.php.
Referenced by Energine\share\gears\ComponentContainer\enabled().
int Energine\share\gears\ComponentContainer::$iteratorIndex = 0 private
Iterator index.
Definition at line 49 of file ComponentContainer.php.
Referenced by Energine\share\gears\ComponentContainer\current(), and Energine\share\gears\ComponentContainer\key().
string Energine\share\gears\ComponentContainer::$name private
Container name.
Definition at line 39 of file ComponentContainer.php.
Referenced by Energine\share\gears\ComponentContainer\__construct(), Energine\share\gears\ComponentContainer\createFromDescription(), and Energine\share\gears\ComponentContainer\getName().
array Energine\share\gears\ComponentContainer::$properties = array() private
Properties.
Definition at line 34 of file ComponentContainer.php.
Referenced by Energine\share\gears\ComponentContainer\__construct(), and Energine\share\gears\ComponentContainer\createFromDescription().
The documentation for this class was generated from the following file:
core/modules/share/gears/ComponentContainer.php