Energine: Energine\share\gears\User Class Reference
Energine\share\gears\User Class Reference
User manager.
Public Member Functions
__construct ($id=false)
getGroups ()
Get the list of groups to which belongs the user.
getID ()
Get user ID.
getValue ($fieldName)
Get the field value.
getFields ()
Get the list of fields.
create ($data)
Create new user.
update ($data)
Update user data.
isInGroup ($groupID)
setGroups ($groups)
Set user groups.
Public Member Functions inherited from Energine\share\gears\DBWorker
__construct ()
translate ($const, $langID=null)
Non-static wrapper method over DBWorker::_translate.
dateToString ($date, $format= '%d-%d-%d')
Non-static wrapper method over DBWorker::_dateToString.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Static Public Member Functions
static getFBUser ($fbID)
Get user by his ID in Facebook.
static linkFBUserByEmail ($email, $fbID)
Link Facebook user by his E-Mail.
static getVKUser ($vkID)
Get user by his ID in VKontakte.
static getOKUser ($okID)
Get user by his ID in Одноклассники.
static generatePassword ($length=8)
Generate random password with specific length from numbers and latin characters.
Static Public Member Functions inherited from Energine\share\gears\DBWorker
static _translate ($const, $langId=null)
Get the translation of the text constant.
static _dateToString ($year, $month, $day)
Transform date to the string.
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Public Attributes
const USER_TABLE_NAME = 'user_users'
Table name of users.
const GROUP_TABLE_NAME = 'user_user_groups'
Table name of groups.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Protected Member Functions
loadInfo ($UID)
Load information about the user from data base.
Protected Attributes
$userGroup
Object for work with users.
Protected Attributes inherited from Energine\share\gears\DBWorker
$dbh
Reference to the DBWorker::$dbhInstance for derived classes.
Private Attributes
$id = false
User ID.
$info = array()
Information about the user.
Additional Inherited Members
Static Protected Attributes inherited from Energine\share\gears\DBWorker
static $dbhInstance
QAL object.
Detailed Description
User manager.
class User;
It holds an information about user, saves data, etc.
Definition at line 26 of file User.php.
Constructor & Destructor Documentation
Energine\share\gears\User::__construct ($id = false)
Parameters
bool | int $id User ID.
Definition at line 62 of file User.php.
{
         parent::__construct();
         $this->id = $id;
         $this->userGroup = E()->UserGroup;
         //Если пользователь существует  - загружаем его информацию
         if ($this->id) {
             $this->loadInfo($this->id);
         }
     }
Member Function Documentation
Energine\share\gears\User::create ($data)
Create new user.
Parameters
array $data Data.
Exceptions
SystemException 'ERR_INSUFFICIENT_DATA'
SystemException 'ERR_NOT_UNIQUE_DATA'
Definition at line 138 of file User.php.
{
         //проверяем имеются ли все необходимые значения
         $tableInfo = $this->dbh->getColumnsInfo(self::USER_TABLE_NAME);
         $necessaryFields = $uniqueFields = array();
         foreach ($tableInfo as $columnName => $columnInfo) {
             //отбираем все поля !nullable, не PRI, и без дефолтного значения
             if (!$columnInfo['nullable'] && $columnInfo['index'] != DBA::PRIMARY_INDEX && !$columnInfo['default']) {
                 array_push($necessaryFields, $columnName);
             }
             //Отбираем все уникальные поля
             if ($columnInfo['index'] == DBA::UNIQUE_INDEX) {
                 array_push($uniqueFields, $columnName);
             }
         }
         //если пересечение списка необходимых полей и списка полей данных не пустое  - значит недостаточно данных для сохранения
         if ($undefinedFields = array_diff($necessaryFields, array_keys($data))) {
             throw new SystemException('ERR_INSUFFICIENT_DATA', SystemException::ERR_WARNING, $undefinedFields);
         }
         //проверяем являются ли введенные поля уникальными
         if (!empty($uniqueFields)) {
             $condition = array();
             foreach ($uniqueFields as $fieldname) {
                 $condition[] = $fieldname . ' = "' . $data[$fieldname] . '"';
             }
             $condition = implode(' OR ', $condition);
             if (simplifyDBResult($this->dbh->select(self::USER_TABLE_NAME, 'COUNT(u_id) as num', $condition), 'num', true) > 0) {
                 throw new SystemException('ERR_NOT_UNIQUE_DATA', SystemException::ERR_WARNING);
             }
         }
         $this->info = $data;
         //$this->info['u_password'] = $data['u_password'];
         $data['u_password'] = sha1($data['u_password']);
         $this->id = $this->dbh->modify(QAL::INSERT, self::USER_TABLE_NAME, $data);
         $this->setGroups(array($this->userGroup->getDefaultUserGroup()));
     }
static Energine\share\gears\User::generatePassword ($length = 8) static
Generate random password with specific length from numbers and latin characters.
Parameters
int $length Password length.
Returns
string
Definition at line 291 of file User.php.
Referenced by Energine\user\components\Register\saveData(), and Energine\user\components\RestorePassword\send().
{
         $chars = '0123456789abcdefghjiklmnopqrstuvwxyzABCDEFGHJIKLMNOPQRSTUVWXYZ';
         $password = '';
         $max = strlen($chars) - 1; // $max = count($chars) - 1;
         for ($i = 0; $i < $length; $i++) {
             $password .= $chars[mt_rand(0, $max)];
         }
         return $password;
     }
static Energine\share\gears\User::getFBUser ($fbID) static
Get user by his ID in Facebook.
Parameters
string $fbID Facebook user ID.
Returns
bool|User
Definition at line 233 of file User.php.
{
         $result = false;
         if ($UID = simplifyDBResult(E()->getDB()->select(self::USER_TABLE_NAME, 'u_id', array('u_fbid' => $fbID, 'u_is_active' => 1)), 'u_id', true)) {
             return new User($UID);
         }
         return $result;
     }
Energine\share\gears\User::getFields ()
Get the list of fields.
Returns
array
Definition at line 125 of file User.php.
{
         $result = $this->dbh->getColumnsInfo(self::USER_TABLE_NAME);
         return $result;
     }
Energine\share\gears\User::getGroups ()
Get the list of groups to which belongs the user.
Returns
array
Definition at line 91 of file User.php.
Referenced by Energine\share\gears\User\isInGroup().
{
         $result = array();
         $result = $this->userGroup->getUserGroups($this->id);
         return $result;
     }
Energine\share\gears\User::getID ()
Get user ID.
Returns
int
Definition at line 102 of file User.php.
Referenced by Energine\share\gears\AuthUser\isAuthenticated(), Energine\share\gears\User\setGroups(), and Energine\share\gears\User\update().
{
         return $this->id;
     }
static Energine\share\gears\User::getOKUser ($okID) static
Get user by his ID in Одноклассники.
Parameters
string $okID User ID in Одноклассники.
Returns
bool|User
Definition at line 277 of file User.php.
{
         $result = false;
         if ($UID = simplifyDBResult(E()->getDB()->select(self::USER_TABLE_NAME, 'u_id', array('u_okid' => $okID, 'u_is_active' => 1)), 'u_id', true)) {
             return new User($UID);
         }
         return $result;
     }
Energine\share\gears\User::getValue ($fieldName)
Get the field value.
Parameters
string $fieldName Field name.
Returns
mixed
Definition at line 112 of file User.php.
{
         $result = false;
         if (isset($this->info[$fieldName])) {
             $result = $this->info[$fieldName];
         }
         return $result;
     }
static Energine\share\gears\User::getVKUser ($vkID) static
Get user by his ID in VKontakte.
Parameters
string $vkID VKontakte user ID.
Returns
bool|User
Definition at line 263 of file User.php.
{
         $result = false;
         if ($UID = simplifyDBResult(E()->getDB()->select(self::USER_TABLE_NAME, 'u_id', array('u_vkid' => $vkID, 'u_is_active' => 1)), 'u_id', true)) {
             return new User($UID);
         }
         return $result;
     }
Energine\share\gears\User::isInGroup ($groupID)
Parameters
$groupID int Group id
Returns
bool
Definition at line 194 of file User.php.
{
         return in_array($groupID, $this->getGroups());
     }
static Energine\share\gears\User::linkFBUserByEmail ($email, $fbID) static
Link Facebook user by his E-Mail.
Parameters
string $email User E-Mail.
string $fbID Facebook user ID.
Returns
bool|User
Definition at line 248 of file User.php.
{
         $result = false;
         if ($UID = simplifyDBResult(E()->getDB()->select(self::USER_TABLE_NAME, 'u_id', array('u_name' => $email, 'u_is_active' => 1)), 'u_id', true)) {
             $result = new User($UID);
             $result->update(array('u_fbid' => $fbID));
         }
         return $result;
     }
Energine\share\gears\User::loadInfo ($UID) protected
Load information about the user from data base.
Parameters
int $UID User ID.
Definition at line 77 of file User.php.
Referenced by Energine\share\gears\User\__construct().
{
         $result = $this->dbh->select(self::USER_TABLE_NAME, true, array('u_id' => $UID));
         if (is_array($result) && !empty($result)) {
             $this->id = $UID;
             $result[0]['u_password'] = true;
             $this->info = $result[0];
         }
     }
Energine\share\gears\User::setGroups ($groups)
Set user groups.
Exceptions
SystemException
Parameters
array | integer $groups Groups.
Definition at line 205 of file User.php.
Referenced by Energine\share\gears\User\create().
{
         //Устанавливать группы можно только тогда, когда пользователь создан
         if ($this->getID()) {
             if(!is_array($groups)){
                 $groups = array($groups);
             }
             //$this->dbh->beginTransaction();
             try {
                 $this->dbh->modify(QAL::DELETE, self::GROUP_TABLE_NAME, null, array('u_id' => $this->getID()));
                 foreach ($groups as $groupID) {
                     $this->dbh->modify(QAL::INSERT, self::GROUP_TABLE_NAME, array('u_id' => $this->getID(), 'group_id' => $groupID));
                 }
                 //$this->dbh->commit();
             }
             catch (SystemException $e) {
                 //$this->dbh->rollback();
                 //передаем исключение дальше
                 throw new SystemException($e->getMessage(), $e->getCode(), $e->getCustomMessage());
             }
         }
     }
Energine\share\gears\User::update ($data)
Update user data.
Parameters
array $data New user data.
Returns
boolean
Definition at line 182 of file User.php.
{
         $result = false;
         if ($this->getID()) {
             $result = $this->dbh->modify(QAL::UPDATE, self::USER_TABLE_NAME, $data, array('u_id' => $this->getID()));
         }
         return $result;
     }
Member Data Documentation
int Energine\share\gears\User::$id = false private
User ID.
Definition at line 44 of file User.php.
Referenced by Energine\share\gears\AuthUser\__construct(), Energine\share\gears\User\__construct(), Energine\share\gears\AuthUser\authenticate(), and Energine\share\gears\User\getID().
array Energine\share\gears\User::$info = array() private
Information about the user.
Definition at line 56 of file User.php.
UserGroup Energine\share\gears\User::$userGroup protected
Object for work with users.
Definition at line 50 of file User.php.
string Energine\share\gears\User::GROUP_TABLE_NAME = 'user_user_groups'
Table name of groups.
Definition at line 37 of file User.php.
string Energine\share\gears\User::USER_TABLE_NAME = 'user_users'
Table name of users.
Definition at line 31 of file User.php.
Referenced by Energine\user\components\Register\__construct().
The documentation for this class was generated from the following file:
core/modules/share/gears/User.php