Energine: Energine\share\gears\Filter Class Reference
Energine\share\gears\Filter Class Reference
Filters.
Public Member Functions
__construct ()
apply (Grid $grid)
Apply filter to the grid.
attachField (FilterField $field)
Attach new filed.
detachField (FilterField $field)
Detach field.
load (\SimpleXMLElement $filterDescription, array $meta=null)
Build filter from XML description.
getFields ()
Get filter fields.
setProperty ($name, $value)
Set filter property.
getProperty ($name)
Get property.
build ()
Build filter.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const TAG_NAME = 'filter'
Filter tag name.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Member Functions
translate ()
Translate attributes for filter fields.
Private Attributes
$doc
Document.
$fields = array()
Set of FilterField's.
$properties = array()
Additional properties.
$map = array()
$data = null
$condition = false
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Filters.
class Filter;
Definition at line 25 of file Filter.php.
Constructor & Destructor Documentation
Energine\share\gears\Filter::__construct ()
Definition at line 69 of file Filter.php.
{
         $stringTypes = array(
             FieldDescription::FIELD_TYPE_STRING,
             FieldDescription::FIELD_TYPE_SELECT,
             FieldDescription::FIELD_TYPE_TEXT,
             FieldDescription::FIELD_TYPE_HTML_BLOCK,
             FieldDescription::FIELD_TYPE_VALUE,
             FieldDescription::FIELD_TYPE_PHONE,
             FieldDescription::FIELD_TYPE_EMAIL,
             FieldDescription::FIELD_TYPE_CODE,
         );
         $numericTypes = array(
             FieldDescription::FIELD_TYPE_INT,
             FieldDescription::FIELD_TYPE_FLOAT
         );
         $dateTypes = array(
             FieldDescription::FIELD_TYPE_DATETIME,
             FieldDescription::FIELD_TYPE_DATE
         );
         $this->map = array(
             'like' => array(
                 'title' => DBWorker::_translate('TXT_FILTER_SIGN_CONTAINS'),
                 'type' => $stringTypes,
                 'condition' => 'LIKE \'%%%s%%\'',
             ),
             'notlike' => array(
                 'title' => DBWorker::_translate('TXT_FILTER_SIGN_NOT_CONTAINS'),
                 'type' => $stringTypes,
                 'condition' => 'NOT LIKE \'%%%s%%\'',
             ),
             '=' => array(
                 'title' => '=',
                 'type' => array_merge($stringTypes, $numericTypes, $dateTypes),
                 'condition' => '= \'%s\'',
             ),
             '!=' => array(
                 'title' => '!=',
                 'type' => array_merge($stringTypes, $numericTypes, $dateTypes),
                 'condition' => '!= \'%s\'',
             ),
             '<' => array(
                 'title' => '<',
                 'type' => array_merge($dateTypes, $numericTypes),
                 'condition' => '<\'%s\'',
             ),
             '>' => array(
                 'title' => '>',
                 'type' => array_merge($dateTypes, $numericTypes),
                 'condition' => '>\'%s\'',
             ),
             'between' => array(
                 'title' => DBWorker::_translate('TXT_FILTER_SIGN_BETWEEN'),
                 'type' => array_merge($dateTypes, $numericTypes),
                 'condition' => 'BETWEEN \'%s\' AND \'%s\'',
             ),
             'checked' => array(
                 'title' => DBWorker::_translate('TXT_FILTER_SIGN_CHECKED'),
                 'type' => array(FieldDescription::FIELD_TYPE_BOOL),
                 'condition' => '= 1',
             ),
             'unchecked' => array(
                 'title' => DBWorker::_translate('TXT_FILTER_SIGN_UNCHEKED'),
                 'type' => array(FieldDescription::FIELD_TYPE_BOOL),
                 'condition' => '!=1'
             ),
         );
         if (isset($_POST[self::TAG_NAME]) && !empty($_POST[self::TAG_NAME])) {
             $this->data = $_POST[self::TAG_NAME];
             if (!isset($this->data['condition']) || !in_array($this->data['condition'], array_keys($this->map))) {
                 throw new SystemException('ERR_BAD_FILTER_DATA', SystemException::ERR_CRITICAL, $this->data);
             }
             $this->condition = $this->data['condition'];
             unset($this->data['condition']);
         }
     }
Member Function Documentation
Energine\share\gears\Filter::apply (Grid $grid)
Apply filter to the grid.
Parameters
Grid $grid
Exceptions
SystemException
Definition at line 152 of file Filter.php.
{
         if ($this->data) {
             $dbh = E()->getDB();
             $tableName = key($this->data);
             $fieldName = key($this->data[$tableName]);
             $values = $this->data[$tableName][$fieldName];
             if (
                 !$dbh->tableExists($tableName)
                 ||
                 !($tableInfo = $dbh->getColumnsInfo($tableName))
                 ||
                 !isset($tableInfo[$fieldName])
             ) {
                 throw new SystemException('ERR_BAD_FILTER_DATA', SystemException::ERR_CRITICAL, $tableName);
             }
             if (
             is_array($tableInfo[$fieldName]['key'])
             ) {
                 $fkTranslationTableName =
                     $dbh->getTranslationTablename($tableInfo[$fieldName]['key']['tableName']);
                 $fkTableName =
                     ($fkTranslationTableName) ? $fkTranslationTableName
                         : $tableInfo[$fieldName]['key']['tableName'];
                 $fkValueField = substr($fkKeyName =
                         $tableInfo[$fieldName]['key']['fieldName'], 0, strrpos($fkKeyName, '_')) .
                     '_name';
                 $fkTableInfo = $dbh->getColumnsInfo($fkTableName);
                 if (!isset($fkTableInfo[$fkValueField])) $fkValueField = $fkKeyName;
                 if ($res =
                     $dbh->getColumn($fkTableName, $fkKeyName,
                         $fkTableName . '.' . $fkValueField . ' ' .
                         call_user_func_array('sprintf', array_merge(array($this->map[$this->condition]['condition']), $values)) .
                         ' ')
                 ) {
                     $grid->addFilterCondition(array($tableName . '.' . $fieldName => $res));
                 } else {
                     $grid->addFilterCondition(' FALSE');
                 }
             } else {
                 $fieldType = FieldDescription::convertType($tableInfo[$fieldName]['type'], $fieldName, $tableInfo[$fieldName]['length'], $tableInfo[$fieldName]);
                 if (in_array($this->condition, array('like', 'notlike')) && in_array($fieldType, array(FieldDescription::FIELD_TYPE_DATE, FieldDescription::FIELD_TYPE_DATETIME))) {
                     if ($this->condition == 'like') {
                         $this->condition = '=';
                     } else {
                         $this->condition = '!=';
                     }
                 }
                 $fieldName = (($tableName) ? $tableName . '.' : '') . $fieldName;
                 if ($fieldType == FieldDescription::FIELD_TYPE_DATETIME) {
                     $fieldName = 'DATE(' . $fieldName . ')';
                 }
                 if (in_array($fieldType, array(FieldDescription::FIELD_TYPE_DATETIME, FieldDescription::FIELD_TYPE_DATE))) {
                     array_walk($this->map, function(&$row){
                         $row['condition'] = str_replace('\'%s\'', 'DATE(\'%s\')', $row['condition']);
                     });
                 }
                 $conditionPatterns = $this->map[$this->condition]['condition'];
                 $grid->addFilterCondition(
                     $fieldName . ' ' .
                     call_user_func_array('sprintf', array_merge(array($conditionPatterns), $values)) .
                     ' '
                 );
             }
         }
     }
Energine\share\gears\Filter::attachField (FilterField $field)
Attach new filed.
Parameters
FilterField $field New filter field.
Definition at line 232 of file Filter.php.
Referenced by Energine\share\gears\Filter\load().
{
         $field->setIndex(arrayPush($this->fields, $field));
         $field->attach($this);
     }
Energine\share\gears\Filter::build ()
Build filter.
Returns
Definition at line 310 of file Filter.php.
{
         $result = false;
         if (sizeof($this->fields)) {
             $this->translate();
             $this->doc = new \DOMDocument('1.0', 'UTF-8');
             $filterElem = $this->doc->createElement(self::TAG_NAME);
             $filterElem->setAttribute('title', DBWorker::_translate('TXT_FILTER'));
             $filterElem->setAttribute('apply', DBWorker::_translate('BTN_APPLY_FILTER'));
             $filterElem->setAttribute('reset', DBWorker::_translate('TXT_RESET_FILTER'));
             if (!empty($this->properties)) {
                 $props = $this->doc->createElement('properties');
                 foreach ($this->properties as $propName => $propValue) {
                     $prop = $this->doc->createElement('property');
                     $prop->setAttribute('name', $propName);
                     $prop->appendChild($this->doc->createTextNode($propValue));
                     $props->appendChild($prop);
                 }
                 $filterElem->appendChild($props);
             }
             //
             $operatorsNode = $this->doc->createElement('operators');
             /*
              * <option value="like"><xsl:value-of select="$TRANSLATION[@const='TXT_FILTER_SIGN_CONTAINS']"/></option>
                  <option value="notlike"><xsl:value-of select="$TRANSLATION[@const='TXT_FILTER_SIGN_NOT_CONTAINS']"/></option>
                  <option value="=">=</option>
                  <option value="!=">!=</option>
                  <option value="&lt;"><xsl:text>&lt;</xsl:text></option>
                  <option value="&gt;"><xsl:text>&gt;</xsl:text></option>
                  <option value="checked">checked</option>
                  <option value="unchecked">unchecked</option>
                  <option value="between"><xsl:value-of select="$TRANSLATION[@const='TXT_FILTER_SIGN_BETWEEN']"/></option>
              */
             foreach ($this->map as $operatorName => $operator) {
                 $operatorNode = $this->doc->createElement('operator');
                 $operatorNode->setAttribute('title', $operator['title']);
                 $operatorNode->setAttribute('name', $operatorName);
                 $operatorsNode->appendChild($operatorNode);
                 $typesNode = $this->doc->createElement('types');
                 foreach ($operator['type'] as $typeName) {
                     $typesNode->appendChild($this->doc->createElement('type', $typeName));
                 }
                 $operatorNode->appendChild($typesNode);
             }
             $filterElem->appendChild($operatorsNode);
             foreach ($this->fields as $field) {
                 $filterElem->appendChild($this->doc->importNode($field->build(), true));
             }
             $this->doc->appendChild($filterElem);
             $result = $this->doc->documentElement;
         }
         return $result;
     }
Energine\share\gears\Filter::detachField (FilterField $field)
Detach field.
Exceptions
SystemException 'ERR_DEV_NO_CONTROL_TO_DETACH'
Parameters
FilterField $field filter field.
Definition at line 244 of file Filter.php.
{
         if (!isset($this->fields[$field->getIndex()])) {
             throw new SystemException('ERR_DEV_NO_CONTROL_TO_DETACH', SystemException::ERR_DEVELOPER);
         }
         unset($this->fields[$field->getIndex()]);
     }
Energine\share\gears\Filter::getFields ()
Get filter fields.
Returns
array
Definition at line 278 of file Filter.php.
{
         return $this->fields;
     }
Energine\share\gears\Filter::getProperty ($name)
Get property.
Parameters
string $name Property name.
Returns
array|null
Definition at line 298 of file Filter.php.
{
         if (isset($this->properties[$name])) {
             return $this->properties[$name];
         }
         return null;
     }
Energine\share\gears\Filter::load (\SimpleXMLElement $filterDescription, array $meta = null)
Build filter from XML description.
Exceptions
SystemException 'ERR_DEV_NO_CONTROL_TYPE'
Parameters
\SimpleXMLElement $filterDescription Filter description.
array $meta Info about table columns
Returns
mixed
Definition at line 260 of file Filter.php.
{
         if (!empty($filterDescription))
             foreach ($filterDescription->field as $fieldDescription) {
                 if (!isset($fieldDescription['name'])) {
                     throw new SystemException('ERR_BAD_FILTER_XML', SystemException::ERR_DEVELOPER);
                 }
                 $name = (string)$fieldDescription['name'];
                 $field = new FilterField($name);
                 $this->attachField($field);
                 $field->load($fieldDescription, (isset($meta[$name]) ? $meta[$name] : null));
             }
     }
Energine\share\gears\Filter::setProperty ($name, $value)
Set filter property.
Parameters
string $name Property name.
mixed $value Property value.
Definition at line 288 of file Filter.php.
{
         $this->properties[$name] = $value;
     }
Energine\share\gears\Filter::translate () private
Translate attributes for filter fields.
Definition at line 370 of file Filter.php.
Referenced by Energine\share\gears\Filter\build().
{
         foreach ($this->fields as $field) {
             $field->translate();
         }
     }
Member Data Documentation
Energine\share\gears\Filter::$condition = false private
Definition at line 67 of file Filter.php.
Referenced by Energine\share\gears\Filter\apply().
Energine\share\gears\Filter::$data = null private
Definition at line 61 of file Filter.php.
DOMDocument Energine\share\gears\Filter::$doc private
Document.
Definition at line 36 of file Filter.php.
array Energine\share\gears\Filter::$fields = array() private
Set of FilterField's.
Definition at line 42 of file Filter.php.
Referenced by Energine\share\gears\Filter\getFields().
Energine\share\gears\Filter::$map = array() private
Definition at line 55 of file Filter.php.
array Energine\share\gears\Filter::$properties = array() private
Additional properties.
Definition at line 48 of file Filter.php.
string Energine\share\gears\Filter::TAG_NAME = 'filter'
Filter tag name.
Definition at line 30 of file Filter.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/Filter.php