Energine: Energine\share\gears\Image Class Reference
Energine\share\gears\Image Class Reference
Class for work with images.
Public Member Functions
create ($width, $height)
Create an image by defined width and height.
getWidth ()
Get image width.
getHeight ()
Get image height.
loadFromFile ($filename, $type=self::TYPE_UNKNOWN)
Load image from file.
saveToFile ($filename, $type=self::TYPE_UNKNOWN)
Save image to the file.
resize ($newWidth, $newHeight, $crop=false)
Resize the image.
__destruct ()
show ()
Show image.
Public Member Functions inherited from Energine\share\gears\Object
startTimer ()
Start the execution time counter.
stopTimer ()
Stop the execution time counter.
resetTimer ()
Reset the execution time counter.
getTimer ()
Get the current value of the execution time counter.
getConfigValue ($paramPath, $initial=null)
Non-static method-wrapper over Object::_getConfigValue for simpler using inside the derivative classes.
Public Attributes
const DEFAULT_MEMORY_LIMIT = 16777216
Default memory limit.
const TYPE_UNKNOWN = 0
Unknown image type.
const TYPE_PNG = 1
PNG (Portable Network Graphics) image.
const TYPE_GIF = 2
GIF (Graphics Interchange Format) image.
const TYPE_JPEG = 3
JPEG (Joint Photographic Experts Group) image.
Public Attributes inherited from Energine\share\gears\Object
const CONFIG_FILE = 'system.config.php'
Configuration file name.
Private Member Functions
checkAvailableMemory ($width, $height)
Check available memory.
convertSizeToBytes ($size)
Convert image size into bytes.
crop ($newWidth, $newHeight)
Crop the image.
resizeWithMargins ($newWidth, $newHeight)
Resize the image with margins.
getExtension ($filename)
Get file extension.
Private Attributes
$extensions
Map of file extensions with image types.
$image
Image.
$width
Width.
$height
Height.
$type
Image type.
Additional Inherited Members
Static Public Member Functions inherited from Energine\share\gears\Object
static _getConfigValue ($paramPath, $initial=null)
Get the configuration value by parameter path.
static setConfigArray ($config)
Set the Object::$systemConfig.
static getConfigArray ()
Get the configurations.
Detailed Description
Class for work with images.
class Image;
Definition at line 24 of file Image.php.
Constructor & Destructor Documentation
Energine\share\gears\Image::__destruct ()
Definition at line 449 of file Image.php.
{
         if ($this->image) {
             imagedestroy($this->image);
         }
     }
Member Function Documentation
Energine\share\gears\Image::checkAvailableMemory ($width, $height) private
Check available memory.
Parameters
int $width Image width.
int $height Image height.
Returns
bool
Definition at line 124 of file Image.php.
Referenced by Energine\share\gears\Image\create(), Energine\share\gears\Image\loadFromFile(), and Energine\share\gears\Image\resize().
{
         $isMemoryAvailable = true;
         $memoryLimit = ini_get('memory_limit');
         if ($memoryLimit != -1) {
             $memoryLimit = $this->convertSizeToBytes($memoryLimit);
             $memoryNeeded = $width * $height * 4/*B = 32BPP*/ * 1.5; // 1.5 - Хрен Его Знает Что За Фактор :)
             if (function_exists('memory_get_usage')) {
                 /*
                 * если мы можем узнать занимаемую скриптом память,
                 * проверяем количество свободной памяти простым вичитанием
                 * занимаемой памяти из установленного лимита.
                 */
                 $memoryUsage = memory_get_usage();
                 $isMemoryAvailable = $memoryNeeded < ($memoryLimit - $memoryUsage);
             }
         }
         return $isMemoryAvailable;
     }
Energine\share\gears\Image::convertSizeToBytes ($size) private
Convert image size into bytes.
Parameters
int $size Image size.
Returns
int
Definition at line 150 of file Image.php.
Referenced by Energine\share\gears\Image\checkAvailableMemory().
{
         if (!empty($size)) {
             $size = trim($size);
             $measurement = strtolower($size[strlen($size)-1]);
             switch($measurement) {
                 case 'g': $size *= 1024;
                 case 'm': $size *= 1024;
                 case 'k': $size *= 1024;
             }
         }
         else {
             $size = self::DEFAULT_MEMORY_LIMIT;
         }
         return $size;
     }
Energine\share\gears\Image::create ($width, $height)
Create an image by defined width and height.
Parameters
int $width Width.
int $height Height.
Exceptions
SystemException 'ERR_MEMORY_NOT_AVAILABLE'
Definition at line 104 of file Image.php.
{
         if (!$this->checkAvailableMemory($width, $height)) {
             throw new SystemException('ERR_MEMORY_NOT_AVAILABLE', SystemException::ERR_NOTICE);
         }
         $this->image  = imagecreatetruecolor($width, $height);
         $this->width  = $width;
         $this->height = $height;
         $this->type   = self::TYPE_UNKNOWN;
     }
Energine\share\gears\Image::crop ($newWidth, $newHeight) private
Crop the image.
Parameters
int $newWidth New width.
int $newHeight New height.
Returns
resource
Definition at line 325 of file Image.php.
Referenced by Energine\share\gears\Image\resize().
{
         list($width,$height)= array($this->width, $this->height);
         $OldImage = $this->image;
         // check if ratios match
         $_ratio=array($width/$height,$newWidth/$newHeight);
         if ($_ratio[0] != $_ratio[1]) { // crop image
             // find the right scale to use
             $_scale=min((float)($width/$newWidth),(float)($height/$newHeight));
             // coords to crop
             $cropX=(float)($width-($_scale*$newWidth));
             $cropY=(float)($height-($_scale*$newHeight));
             // cropped image size
             $cropW=(float)($width-$cropX);
             $cropH=(float)($height-$cropY);
             $crop=ImageCreateTrueColor($cropW,$cropH);
             // crop the middle part of the image to fit proportions
             ImageCopy(
                 $crop,
                 $OldImage,
                 0,
                 0,
                 (int)($cropX/2),
                 (int)($cropY/2),
                 $cropW,
                 $cropH
             );
         }
         // do the thumbnail
         $NewThumb=ImageCreateTrueColor($newWidth,$newHeight);
         if (isset($crop)) { // been cropped
             ImageCopyResampled(
                 $NewThumb,
                 $crop,
                 0,
                 0,
                 0,
                 0,
                 $newWidth,
                 $newHeight,
                 $cropW,
                 $cropH
             );
             ImageDestroy($crop);
         } else { // ratio match, regular resize
             //todo VZ: $w and $h (i.e. destination width and height) are not defined.
             ImageCopyResampled(
                 $NewThumb,
                 $OldImage,
                 0,
                 0,
                 0,
                 0,
                 $w,
                 $h,
                 $width,
                 $height
             );
         }
         $result = $NewThumb;
         return $result;
     }
Energine\share\gears\Image::getExtension ($filename) private
Get file extension.
Parameters
string $filename Filename.
Returns
string
Definition at line 445 of file Image.php.
Referenced by Energine\share\gears\Image\loadFromFile(), and Energine\share\gears\Image\saveToFile().
{
         return substr(strrchr($filename, '.'), 1);
     }
Energine\share\gears\Image::getHeight ()
Get image height.
Returns
int
Definition at line 183 of file Image.php.
{
         return $this->height;
     }
Energine\share\gears\Image::getWidth ()
Get image width.
Returns
int
Definition at line 174 of file Image.php.
{
         return $this->width;
     }
Energine\share\gears\Image::loadFromFile ($filename, $type = self::TYPE_UNKNOWN)
Load image from file.
If the image type is not explicit defined this method tries to detect it from file extension.
Parameters
int $filename Filename.
int $type Image type.
Exceptions
SystemException 'ERR_DEV_FILE_DOESNT_EXISTS'
SystemException 'ERR_CANNOT_DETERMINE_IMAGE_TYPE'
SystemException 'ERR_BAD_FILE_FORMAT'
SystemException 'ERR_MEMORY_NOT_AVAILABLE'
Definition at line 199 of file Image.php.
{
         if (!file_exists($filename)) {
             throw new SystemException('ERR_DEV_FILE_DOESNT_EXISTS', SystemException::ERR_DEVELOPER, $filename);
         }
         if ($type == self::TYPE_UNKNOWN) {
             // пробуем определить тип по расширению
             $ext = $this->getExtension($filename);
             if (!array_key_exists($ext, $this->extensions)) {
                 throw new SystemException('ERR_CANNOT_DETERMINE_IMAGE_TYPE', SystemException::ERR_WARNING, $filename);
             }
             $type = $this->extensions[$ext];
         }
         if (!$imageSize = @getimagesize($filename)) {
             throw new SystemException('ERR_BAD_FILE_FORMAT', SystemException::ERR_WARNING, $filename);
         }
         if (!$this->checkAvailableMemory($imageSize[0], $imageSize[1])) {
             throw new SystemException('ERR_MEMORY_NOT_AVAILABLE', SystemException::ERR_NOTICE);
         }
         $image = null;
         switch ($type) {
             case self::TYPE_PNG:  $image = @imagecreatefrompng($filename);  break;
             case self::TYPE_GIF:  $image = @imagecreatefromgif($filename);  break;
             case self::TYPE_JPEG: $image = @imagecreatefromjpeg($filename); break;
             default: // unreachable
         }
         if (!$image) {
             throw new SystemException('ERR_BAD_FILE_FORMAT', SystemException::ERR_WARNING, $filename);
         }
         $this->image  = $image;
         $this->width  = imagesx($this->image);
         $this->height = imagesy($this->image);
         $this->type   = $type;
     }
Energine\share\gears\Image::resize ($newWidth, $newHeight, $crop = false)
Resize the image.
Parameters
int $newWidth New width.
int $newHeight New height.
bool $crop Crop the image?
Todo:
Если ширина ИЛИ высота равны null – они вычисляются пропорционально.
Exceptions
SystemException 'ERR_MEMORY_NOT_AVAILABLE'
Definition at line 297 of file Image.php.
{
         if (!$this->checkAvailableMemory($newWidth, $newHeight)) {
             throw new SystemException('ERR_MEMORY_NOT_AVAILABLE', SystemException::ERR_NOTICE);
         }
         if($crop){
             $resizedImage = $this->crop($newWidth, $newHeight);
         }
         else{
             $resizedImage = $this->resizeWithMargins($newWidth, $newHeight);
         }
         imagedestroy($this->image);
         $this->image  = $resizedImage;
         $this->width  = $newWidth;
         $this->height = $newHeight;
     }
Energine\share\gears\Image::resizeWithMargins ($newWidth, $newHeight) private
Resize the image with margins.
Parameters
int $newWidth New width.
int $newHeight New height.
Returns
resource
Definition at line 402 of file Image.php.
Referenced by Energine\share\gears\Image\resize().
{
         $posX = $posY = 0;
         $lowend = 0.8;
         $highend = 1.25;
         $scaleX = (float)$newWidth / $this->width;
         $scaleY = (float)$newHeight / $this->height;
         $scale = min($scaleX, $scaleY);
         $newCanvasWidth = $newWidth;
         $newCanvasHeight = $newHeight;
         $scaleR = $scaleX / $scaleY;
         if($scaleR < $lowend || $scaleR > $highend)
         {
             $newCanvasWidth = (int)($scale * $this->width + 0.5);
             $newCanvasHeight = (int)($scale * $this->height + 0.5);
             $posX = (int)(0.5 * ($newWidth - $newCanvasWidth));
             $posY = (int)(0.5 * ($newHeight - $newCanvasHeight));
         }
         $resizedImage = imagecreatetruecolor($newWidth, $newHeight);
         $bgColor = imagecolorallocate($resizedImage, 255, 255, 255);
         imagefill($resizedImage, 0, 0, $bgColor);
         imagecopyresampled(
         $resizedImage, $this->image,
         $posX, $posY, 0, 0,
         $newCanvasWidth, $newCanvasHeight,
         $this->width, $this->height
         );
         return $resizedImage;
     }
Energine\share\gears\Image::saveToFile ($filename, $type = self::TYPE_UNKNOWN)
Save image to the file.
If the image type is not explicit defined this method tries to detect it from file extension.
Parameters
string $filename Filename.
int $type Image type.
Returns
bool
Exceptions
SystemException 'ERR_DEV_NO_IMAGE_TO_SAVE'
SystemException 'ERR_CANNOT_DETERMINE_IMAGE_TYPE'
SystemException 'ERR_CANT_SAVE_FILE'
Definition at line 250 of file Image.php.
{
         if (!$this->image) {
             throw new SystemException('ERR_DEV_NO_IMAGE_TO_SAVE', SystemException::ERR_DEVELOPER, $filename);
         }
         if ($type == self::TYPE_UNKNOWN) {
             $ext = $this->getExtension($filename);
             if (array_key_exists($ext, $this->extensions)) {
                 $type = $this->extensions[$ext];
             }
             elseif ($this->type != self::TYPE_UNKNOWN) {
                 $type = $this->type;
             }
             else {
                 throw new SystemException('ERR_CANNOT_DETERMINE_IMAGE_TYPE', SystemException::ERR_WARNING, $filename);
             }
         }
         $success = false;
         switch ($type) {
             case self::TYPE_PNG:  $success = @imagepng ($this->image, $filename); break;
             case self::TYPE_GIF:  $success = @imagegif ($this->image, $filename); break;
             case self::TYPE_JPEG: $success = @imagejpeg($this->image, $filename); break;
             default: // unreachable
         }
         if (!$success) {
             throw new SystemException('ERR_CANT_SAVE_FILE', SystemException::ERR_WARNING, $filename);
         }
         try {
             @chmod($filename, 0666);
         }
         catch (\Exception $e){}
         return $success;
     }
Energine\share\gears\Image::show ()
Show image.
Definition at line 458 of file Image.php.
{
         switch ($this->type){
             case self::TYPE_PNG:
                 $contentType = 'image/png';
                 $funcName = 'imagepng';
                 break;
             case self::TYPE_JPEG :
                 $contentType = 'image/jpg';
                 $funcName = 'imagejpeg';
                 break;
             case self::TYPE_GIF:
                 $contentType = 'image/gif';
                 $funcName = 'imagegif';
                 break;
             default:
                 return;
         }
         $response = E()->getResponse();
         $response->setHeader('Content-type', $contentType);
         ob_start();
         call_user_func($funcName, $this->image);
         $data = ob_get_clean();
         $response->write($data);
         $response->commit();
     }
Member Data Documentation
array Energine\share\gears\Image::$extensions private
Initial value:
= array(
    'png'  => self::TYPE_PNG,
    'gif'  => self::TYPE_GIF,
    'jpg'  => self::TYPE_JPEG,
    'jpe'  => self::TYPE_JPEG,
    'jpeg' => self::TYPE_JPEG
    )
Map of file extensions with image types.
Definition at line 58 of file Image.php.
int Energine\share\gears\Image::$height private
Height.
Definition at line 84 of file Image.php.
Referenced by Energine\share\gears\Image\checkAvailableMemory(), Energine\share\gears\Image\create(), Energine\share\gears\Image\crop(), and Energine\share\gears\Image\getHeight().
resource Energine\share\gears\Image::$image private
Image.
Definition at line 72 of file Image.php.
Referenced by Energine\share\gears\Image\crop(), and Energine\share\gears\Image\loadFromFile().
int Energine\share\gears\Image::$type private
Image type.
See also
Image::TYPE_UNKNOWN, Image::TYPE_PNG, Image::TYPE_GIF, Image::TYPE_JPEG
Definition at line 91 of file Image.php.
Referenced by Energine\share\gears\Image\loadFromFile(), and Energine\share\gears\Image\saveToFile().
int Energine\share\gears\Image::$width private
Width.
Definition at line 78 of file Image.php.
Referenced by Energine\share\gears\Image\checkAvailableMemory(), Energine\share\gears\Image\create(), Energine\share\gears\Image\crop(), and Energine\share\gears\Image\getWidth().
int Energine\share\gears\Image::DEFAULT_MEMORY_LIMIT = 16777216
Default memory limit.
16 Mb.
Note
If compiled without memory-limit.
Definition at line 32 of file Image.php.
const Energine\share\gears\Image::TYPE_GIF = 2
GIF (Graphics Interchange Format) image.
Definition at line 46 of file Image.php.
const Energine\share\gears\Image::TYPE_JPEG = 3
JPEG (Joint Photographic Experts Group) image.
Definition at line 50 of file Image.php.
const Energine\share\gears\Image::TYPE_PNG = 1
PNG (Portable Network Graphics) image.
Definition at line 42 of file Image.php.
const Energine\share\gears\Image::TYPE_UNKNOWN = 0
Unknown image type.
Definition at line 38 of file Image.php.
The documentation for this class was generated from the following file:
core/modules/share/gears/Image.php