Energine: core/modules/share/gears/Registry.php File Reference
Registry.php File Reference
E(), Registry.
Classes
class Energine\share\gears\Registry
Application registry.
Namespaces
Energine\share\gears
The main abstract class for all objects in the system.
Functions
E ()
E[nergine].
Detailed Description
E(), Registry.
It contains the definition to:
function E();
   final class Registry;
Author
dr.Pavka
Copyright
Energine 2013
Version
1.0.0
Definition in file Registry.php.
Function Documentation
E ()
E[nergine].
Shortcut for Registry::getInstance.
Returns
Energine
Definition at line 25 of file Registry.php.
Referenced by Energine\seo\components\Robots\__construct(), Energine\share\components\LinkingEditor\__construct(), Energine\user\components\LoginForm\__construct(), Energine\share\components\CrossDomainAuth\__construct(), Energine\apps\components\Feed\__construct(), Energine\share\components\BreadCrumbs\__construct(), Energine\share\components\PageList\__construct(), Energine\apps\components\SimilarNews\__construct(), Energine\seo\components\GoogleSitemap\__construct(), Energine\share\gears\DBWorker\__construct(), Energine\share\components\FileRepository\__construct(), Energine\share\gears\DBStructureInfo\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\share\gears\User\__construct(), Energine\share\gears\ComponentContainer\__construct(), Energine\share\gears\OKOAuth\__construct(), Energine\user\gears\VKOAuth\__construct(), Energine\comments\components\CommentsList\__construct(), Energine\share\gears\Request\__construct(), Energine\share\gears\Sitemap\__construct(), Energine\share\gears\FileRepositoryFTP\__construct(), Energine\share\gears\UserSession\__construct(), Energine\share\gears\SystemException\__construct(), Energine\share\gears\Document\__construct(), Energine\share\gears\Component\__construct(), Energine\share\gears\Site\__get(), Energine\share\gears\DBWorker\_translate(), Energine\share\components\DivisionEditor\add(), Energine\share\gears\Response\addCookie(), Energine\share\gears\FileRepositoryLocal\analyze(), Energine\share\gears\FileRepositoryFTP\analyze(), Energine\share\gears\Filter\apply(), Energine\share\gears\AuthUser\authenticate(), Energine\share\gears\TagManager\bind(), Energine\share\components\SiteProperties\build(), Energine\share\gears\ErrorDocument\build(), Energine\share\gears\OGObject\build(), Energine\share\gears\Document\build(), Energine\user\components\RoleEditor\buildDivRightsData(), Energine\share\gears\AbstractBuilder\buildFieldValue(), Energine\forms\components\Form\buildForm(), Energine\share\components\TextBlock\buildJS(), Energine\share\components\DBDataSet\buildJS(), Energine\share\components\DivisionEditor\buildRightsTab(), Energine\share\components\LinkingEditor\changeOrder(), Energine\share\components\DataSet\cleanupHTML(), Energine\share\components\SitemapTree\createBuilder(), Energine\share\components\NavigationMenu\createBuilder(), Energine\seo\components\GoogleSitemap\createBuilder(), Energine\apps\components\FeedEditor\createData(), Energine\apps\components\ExtendedFeed\createData(), Energine\forms\components\FormEditor\createData(), Energine\comments\gears\CommentsHelper\createField(), Energine\share\gears\TagManager\createField(), Energine\share\gears\AbstractBuilder\createField(), Energine\share\gears\AttachmentManager\createField(), Energine\comments\gears\CommentsHelper\createInstanceFor(), Energine\comments\gears\Comments\createInstanceFor(), Energine\share\gears\SiteSaver\createMainPage(), Energine\seo\components\Robots\createSitemapSegment(), ddump_log(), Energine\share\components\Grid\defineParams(), Energine\share\components\LanguageEditor\deleteData(), Energine\apps\gears\AdsManager\edit(), Energine\apps\components\NewsRepository\edit(), Energine\forms\components\FormEditor\edit(), Energine\share\components\DivisionEditor\edit(), Energine\forms\components\FormsEditor\editForm(), Energine\forms\components\FormEditor\editSelector(), Energine\share\components\DataSet\embedPlayer(), Energine\apps\components\Branding\findNearestParentBrandID(), Energine\share\gears\DBA\funcExists(), Energine\share\gears\ComponentConfig\getActionByURI(), Energine\share\gears\ComponentConfig\getConfigPath(), Energine\share\components\DBDataSet\getDataLanguage(), Energine\share\components\Grid\getDataLanguage(), Energine\share\gears\Sitemap\getDocumentRights(), Energine\share\gears\User\getFBUser(), Energine\share\gears\TagManager\getFilter(), Energine\share\components\DBDataSet\getFKData(), Energine\share\gears\TagManager\getID(), Energine\share\gears\Sitemap\getIDByURI(), Energine\share\gears\Registry\getMap(), Energine\share\gears\User\getOKUser(), Energine\share\gears\FileRepoInfo\getRepositoryInstanceByRepoPath(), Energine\user\components\SocialLoginForm\getReturnUrl(), Energine\share\gears\Sitemap\getSiteID(), Energine\seo\components\Robots\getSitemapSegmentIds(), Energine\share\gears\TagManager\getTags(), Energine\share\gears\TagManager\getTagStartedWith(), Energine\share\gears\Document\getTemplatesData(), Energine\share\gears\User\getVKUser(), Energine\share\components\SiteEditor\go(), Energine\share\gears\Response\goBack(), Energine\share\gears\TagManager\insert(), Energine\apps\gears\AdsManager\isActive(), Energine\seo\components\Robots\isSeoConfigured(), Energine\comments\components\CommentsForm\isTargetEditable(), Energine\share\gears\UserSession\isValid(), Energine\share\gears\User\linkFBUserByEmail(), Energine\share\gears\Site\load(), Energine\share\gears\Document\loadComponents(), Energine\share\components\SitemapTree\loadData(), Energine\share\components\LangSwitcher\loadData(), Energine\share\components\SiteList\loadData(), Energine\share\components\NavigationMenu\loadData(), Energine\share\components\BreadCrumbs\loadData(), Energine\share\components\PageList\loadData(), Energine\seo\components\Robots\loadData(), Energine\seo\components\GoogleSitemap\loadData(), Energine\share\components\DivisionEditor\loadData(), Energine\seo\components\Robots\main(), Energine\apps\components\Ads\main(), Energine\share\components\LinkingEditor\main(), Energine\seo\components\GoogleSitemap\main(), Energine\apps\components\SimilarNews\main(), Energine\apps\components\NewsFeed\main(), Energine\apps\components\Feed\main(), Energine\share\components\DivisionEditor\main(), Energine\share\gears\UserSession\manuallyCreateSessionInfo(), Energine\share\gears\UserSession\manuallyDeleteSessionInfo(), Energine\seo\components\GoogleSitemap\map(), Energine\share\components\DBDataSet\modify(), Energine\share\components\DBDataSet\multiLoadData(), Energine\apps\components\Vote\prepare(), Energine\share\components\DivisionEditor\prepare(), Energine\share\gears\Response\prepareRedirectURL(), Energine\share\components\Grid\printData(), Energine\user\components\UserEditor\printUserGroups(), Energine\share\gears\DBA\procExists(), Energine\share\gears\Response\redirectToCurrentSection(), Energine\comments\components\CommentsForm\removeComment(), Energine\apps\components\NewsFeed\rss(), Energine\share\gears\MultiLanguageBuilder\run(), Energine\share\gears\DocumentController\run(), Energine\forms\components\FormEditor\save(), Energine\share\components\DivisionEditor\save(), Energine\share\components\WidgetsRepository\saveContent(), Energine\share\components\TranslationEditor\saveData(), Energine\share\components\LanguageEditor\saveData(), Energine\share\components\WidgetsRepository\saveNewTemplate(), Energine\share\components\AttachmentEditor\savequickupload(), Energine\share\components\WidgetsRepository\saveTemplate(), Energine\share\components\DBDataSet\saveText(), Energine\share\components\DivisionEditor\selector(), Energine\apps\components\FeedbackForm\send(), Energine\forms\components\Form\send(), Energine\apps\gears\NewsEditorSaver\setData(), Energine\share\gears\Field\setData(), Energine\share\gears\XSLTTransformer\setFileName(), Energine\share\gears\Mail\setText(), Energine\share\gears\Image\show(), Energine\user\components\SocialLoginForm\showLoginForm(), Energine\user\components\LoginForm\showLoginForm(), Energine\forms\components\FormsEditor\showResult(), Energine\forms\components\Form\success(), Energine\apps\components\NewsFeed\tag(), Energine\share\gears\XMLTransformer\transform(), Energine\share\gears\JSONTransformer\transform(), Energine\share\gears\XSLTTransformer\transform(), Energine\comments\components\CommentsForm\updateComment(), Energine\seo\components\GoogleSitemap\videomap(), and Energine\apps\components\Vote\vote().
     {
         return Energine\share\gears\Registry::getInstance();
     }