Energine: core/modules/share/gears/utils.func.php File Reference
utils.func.php File Reference
Utilities: inspect(), splitDate(), stop(), simple_log(), dump_log(), ddump_log(), simplifyDBResult(), inverseDBResult(), convertDBResult(), convertFieldNames(), arrayPush(), array_push_before(), array_push_after(), file_get_contents_stripped().
Functions
inspect ()
Inspect variables.
splitDate ($date)
Split date.
stop ()
Terminate program.
simple_log ($var)
Simple log function.
dump_log ($var, $append=false)
Write the variable information into log file.
ddump_log ()
Write the variable information into log file and terminate program.
simplifyDBResult ($dbResult, $fieldName, $singleRow=false)
Simplify data base result.
inverseDBResult (array $dbResult)
Transpose 2D array.
convertDBResult ($dbResult, $pkName, $deletePK=false)
Convert data base result.
convertFieldNames (array $fields, $prefix= '')
Convert field names to Camel Notation.
arrayPush (array &$array, $var, $key=null)
Push the new array element at the end of the array.
array_push_before (array $array, $var, $pos)
Push the new array element before specific position.
array_push_after ($src, $in, $pos)
Push the new array element after specific position.
file_get_contents_stripped ($fileName)
Get stripped contents.
str_replace_opt ($from, $to, $src)
Optimized for large strings str_replace.
simplifyClassName ($fullyQualifiedClassName)
Detailed Description
Utilities: inspect(), splitDate(), stop(), simple_log(), dump_log(), ddump_log(), simplifyDBResult(), inverseDBResult(), convertDBResult(), convertFieldNames(), arrayPush(), array_push_before(), array_push_after(), file_get_contents_stripped().
It contain the set of service utilities of the system.
Author
1m.dm
Copyright
Energine 2006
Version
1.0.0
Definition in file utils.func.php.
Function Documentation
array_push_after ($src, $in, $pos)
Push the new array element after specific position.
Parameters
array $src Array.
mixed $in New array element.
int | string $pos Position.
Returns
array
Definition at line 344 of file utils.func.php.
Referenced by Energine\share\gears\DataDescription\addFieldDescription().
{
     if(is_int($pos)) $R=array_merge(array_slice($src,0,$pos+1), $in, array_slice($src,$pos+1));
     else{
         foreach($src as $k=>$v){
             $R[$k]=$v;
             if($k==$pos)$R=array_merge($R,$in);
         }
     }return $R;
 }
array_push_before (array $array, $var, $pos)
Push the new array element before specific position.
Parameters
array $array Array.
mixed $var New array element.
int | string $pos Position.
Returns
array
Definition at line 313 of file utils.func.php.
Referenced by Energine\share\components\BreadCrumbs\loadData().
{
     $result = array();
     if (!is_array($var)) {
         $var = array($var);
     }
     if (is_int($pos)) {
         $result = array_merge(
             array_slice($array, 0, $pos),
             $var,
             array_slice($array, $pos)
         );
     }
     else {
         foreach ($array as $key => $value){
             if ($key == $pos) {
                 $result = array_merge($result, $var);
             }
             $result[$key] = $value;
         }
     }
     return $result;
 }
arrayPush (array & $array, $var, $key = null)
Push the new array element at the end of the array.
The index of newly inserted element will be returned.
Parameters
array $array Array.
mixed $var New array element
int $key Desired key value of the new element.
Returns
int
See also
array_push()
Definition at line 288 of file utils.func.php.
Referenced by Energine\share\gears\Container\attachControl(), Energine\share\gears\Toolbar\attachControl(), Energine\share\gears\Filter\attachField(), Energine\share\components\Grid\loadData(), and Energine\share\components\DBDataSet\multiLoadData().
{
     $newkey = 0;
     $keys = array_keys($array);
     if (!empty($keys)) {
         if (is_null($key)) {
             rsort($keys);
             $newkey = $keys[0] + 1;
         }
         else {
             $newkey = $key;
         }
     }
     $array[$newkey] = $var;
     return $newkey;
 }
convertDBResult ($dbResult, $pkName, $deletePK = false)
Convert data base result.
Parameters
mixed $dbResult Data base result.
mixed $pkName Primary key.
boolean $deletePK Delete fields with primary key from the result?
Returns
array
Todo:
написать подробное описание!
See also
QAL::select()
Exceptions
SystemException 'ERR_DEV_BAD_DATA'
Definition at line 224 of file utils.func.php.
Referenced by Energine\share\gears\UserGroup\__construct(), Energine\comments\gears\CommentsHelper\addUsersInfo(), Energine\comments\components\CommentsList\addUsersInfo(), Energine\user\components\RoleEditor\buildDivRightsData(), Energine\share\components\DivisionEditor\buildRightsTab(), Energine\apps\components\FeedEditor\changeOrder(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\user\components\UserEditor\createData(), Energine\apps\components\Branding\findNearestParentBrandID(), Energine\share\gears\Sitemap\getSitemapData(), Energine\apps\components\Ads\main(), Energine\share\components\DBDataSet\modify(), and Energine\apps\components\NewsFeed\tag().
{
     $result = false;
     if (is_array($dbResult) && !empty($dbResult)) {
         if (is_string($pkName)) {
             foreach ($dbResult as $key => $row) {
                 if (isset($row[$pkName])) {
                     $result[$row[$pkName]] = $row;
                     if ($deletePK) {
                         unset($result[$row[$pkName]][$pkName]);
                     }
                 }
                 else {
                     throw new SystemException('ERR_DEV_BAD_DATA', SystemException::ERR_DEVELOPER);
                 }
             }
         }
         elseif (is_array($pkName) && sizeof($pkName) == 2) {
             foreach ($dbResult as $key => $row) {
                 $result[$row[$pkName[0]]][$row[$pkName[1]]] = $row;
                 if ($deletePK) {
                     unset($result[$row[$pkName[0]]][$row[$pkName[1]]][$pkName[0]]);
                     unset($result[$row[$pkName[0]]][$row[$pkName[1]]][$pkName[1]]);
                 }
             }
         }
     }
     return $result;
 }
convertFieldNames (array $fields, $prefix = '')
Convert field names to Camel Notation.
Parameters
array $fields
string $prefix Prefix, that should be removed from the name.
Returns
array
Definition at line 261 of file utils.func.php.
Referenced by Energine\share\gears\Site\__construct(), Energine\share\gears\SiteManager\__construct(), and Energine\share\gears\Sitemap\preparePageInfo().
{
     $result = array();
     foreach ($fields as $fieldName => $fieldValue) {
         if (($plen = strlen($prefix)) > 0 && strpos($fieldName, $prefix) === 0) {
             $fieldName = substr($fieldName, $plen);
         }
         //$fieldName = preg_replace('/_(\w)/e', 'strtoupper(\'$1\')', $fieldName);
         $fieldName = preg_replace_callback('/_(\w)/', function($m){ return strtoupper($m[1]);}, $fieldName);
         $result[$fieldName] = $fieldValue;
     }
     return $result;
 }
ddump_log ()
Write the variable information into log file and terminate program.
Log-file will be overwritten.
Definition at line 129 of file utils.func.php.
                      {
     $result = array();
     $args = func_get_args();
     foreach ($args as $arg) {
         $result[] = var_export($arg, true);
     }
     file_put_contents(
         'logs/debug.log',
         "\ndate: ".date("l dS of F Y h:i:s")."\n\n".implode("\n", $result)."\n"
     );
     chmod('logs/debug.log', 0666);
     E()->getResponse()->commit();
 }
dump_log ($var, $append = false)
Write the variable information into log file.
Parameters
mixed $var Variable
boolean $append Append the log into the file? If false the file will be overwritten.
Definition at line 106 of file utils.func.php.
{
     $t = microtime(true);
     $micro = sprintf("%06d",($t - floor($t)) * 1000000);
     $d = new \DateTime( date('Y-m-d H:i:s.'.$micro,$t) );
     $flags = ($append ? FILE_APPEND : null);
     ob_start();
     var_dump($var);
     $data = ob_get_contents();
     ob_end_clean();
     file_put_contents(
         'logs/debug.log',
         "\ndate: ".$d->format('l dS of F Y h:i:s:u')."\n\n".$data."\n",
         $flags
     );
     chmod('logs/debug.log', 0666);
 }
file_get_contents_stripped ($fileName)
Get stripped contents.
Parameters
string $fileName Filename.
Returns
string
Definition at line 363 of file utils.func.php.
Referenced by Energine\share\gears\Document\getTemplatesData().
{
     return stripslashes(trim(file_get_contents($fileName)));
 }
inspect ()
Inspect variables.
It directly prints the information about input arguments to the output stream formatted with HTML.
Definition at line 19 of file utils.func.php.
Referenced by Energine\share\components\FileRepository\uploadZip().
                    {
     $args = func_get_args();
     if(php_sapi_name() != 'cli'){
         echo '<pre>';
         call_user_func_array('var_dump', $args);
         echo '</pre>';
     }
     else {
         print(PHP_EOL);
         call_user_func_array('var_dump', $args);
         print(PHP_EOL);
     }
 }
inverseDBResult (array $dbResult)
Transpose 2D array.
Input:
 array(
     $n => array(
         $fieldName => $fieldValue
     )
 )
Output: array($fieldName => array($n => $fieldValue))
 array(
     $fieldName => array(
         $n => $fieldValue
     )
 )
Parameters
array $dbResult 2D array.
Returns
array
Definition at line 199 of file utils.func.php.
Referenced by Energine\share\gears\Data\load(), and Energine\share\components\AttachmentEditor\loadData().
{
     $result = array();
     foreach ($dbResult as $row) {
         foreach ($row as $fieldName => $fieldValue) {
             $result[$fieldName][] = $fieldValue;
         }
     }
     return $result;
 }
simple_log ($var)
Simple log function.
Parameters
string $var Variable.
Definition at line 81 of file utils.func.php.
{
     static $simpleLog;
     if(!isset($simpleLog)){
         $simpleLog = 'logs/simple.log';
         file_put_contents($simpleLog,'');
     }
     if(file_exists($simpleLog)){
        $flag =  FILE_APPEND;
     }
     $flag = (file_exists($simpleLog))? FILE_APPEND : null;
     file_put_contents(
        $simpleLog,
        str_replace("\n", ' ', $var)."\n",
        $flag
     );
 }
simplifyClassName ($fullyQualifiedClassName)
Parameters
$fullyQualifiedClassName string
Returns
string
Definition at line 388 of file utils.func.php.
Referenced by Energine\share\gears\ComponentConfig\__construct(), Energine\share\gears\Component\__construct(), Energine\share\gears\Component\build(), and Energine\share\components\Grid\defineParams().
{
     $className = explode('\\', $fullyQualifiedClassName);
     return array_pop($className);
 }
simplifyDBResult ($dbResult, $fieldName, $singleRow = false)
Simplify data base result.
It selects the values at the defined field from the result of SELECT request.
Parameters
mixed $dbResult Result of SELECT request.
string $fieldName Field name that will be selected from result.
boolean $singleRow Return only the first value at defined field name?
Returns
mixed
Definition at line 154 of file utils.func.php.
Referenced by Energine\apps\components\NewsCalendar\__construct(), Energine\forms\components\Form\__construct(), Energine\apps\components\TagCloud\__construct(), Energine\share\components\DivisionEditor\add(), Energine\share\gears\AuthUser\authenticate(), Energine\share\components\DivisionEditor\changeOrder(), Energine\share\components\Grid\changeOrder(), Energine\user\components\Register\checkLogin(), Energine\share\components\DBDataSet\commonLoadData(), Energine\share\gears\User\create(), Energine\share\components\Grid\deleteData(), Energine\comments\components\CommentsEditor\edit(), Energine\share\components\DivisionEditor\edit(), Energine\share\gears\User\getFBUser(), Energine\share\gears\TagManager\getFilter(), Energine\share\gears\UserGroup\getMembers(), Energine\apps\components\SimilarNews\getNewsTagIDs(), Energine\share\gears\User\getOKUser(), Energine\comments\gears\Comments\getPageCount(), Energine\forms\components\Form\getRecipientEmail(), Energine\apps\components\SimilarNews\getSimilarNewsIDs(), Energine\share\gears\Sitemap\getSiteID(), Energine\share\gears\TagManager\getTagStartedWith(), Energine\share\components\TextBlock\getTextBlockID(), Energine\share\gears\UserGroup\getUserGroups(), Energine\share\gears\User\getVKUser(), Energine\share\components\SiteEditor\go(), Energine\share\gears\User\linkFBUserByEmail(), Energine\share\components\DBDataSet\modify(), Energine\share\components\DBDataSet\multiLoadData(), Energine\share\components\DivisionEditor\resetTemplates(), Energine\share\components\WidgetsRepository\revertTemplate(), Energine\share\gears\SiteSaver\save(), Energine\share\components\WidgetsRepository\saveTemplate(), Energine\user\components\RestorePassword\send(), Energine\forms\components\Form\send(), and Energine\forms\components\Form\success().
{
     $result = false;
     $fieldName = strtolower($fieldName);
     if (is_array($dbResult)) {
         if ($singleRow) {
             $result = $dbResult[0][$fieldName];
         }
         else {
             foreach ($dbResult as $row) {
                 if (array_key_exists($fieldName, $row)) {
                     $result[] = $row[$fieldName];
                 }
             }
         }
     }
     return $result;
 }
splitDate ($date)
Split date.
It splits the date into the year, month, month day and time (hours, minutes, seconds).
Parameters
string $date Date.
Returns
array
Definition at line 43 of file utils.func.php.
Referenced by Energine\apps\components\SimilarNews\main().
{
     $timeInfo =
         $dateInfo = array('','','');
     $dateArray = explode(' ',$date);
     if(is_array($dateArray)){
         $dateInfo = explode('-',$dateArray[0]);
         if(isset($dateArray[1])){
             $timeInfo = explode(':',$dateArray[1]);
         }
     }
     return array(
                 'year' => $dateInfo[0],
                 'month' => $dateInfo[1],
                 'day' => $dateInfo[2],
                 'time' => array(
                     'h' => $timeInfo[0],
                     'm' => $timeInfo[1],
                     's' => $timeInfo[2]
                 )
             );
 }
stop ()
Terminate program.
This is an analogue of inspect() with program termination.
Definition at line 70 of file utils.func.php.
Referenced by Energine\user\components\UserProfile\save().
                 {
     $args = func_get_args();
     call_user_func_array('inspect', $args);
     die();
 }
str_replace_opt ($from, $to, $src)
Optimized for large strings str_replace.
Parameters
$from char
$to char
$src string
Returns
string
Definition at line 375 of file utils.func.php.
Referenced by Energine\share\components\FileRepository\cleanFileData().
{
     for ($i = 0; $i < strlen($src); $i++) {
         if($src[$i] == $from){
             $src[$i] = $to;
         }
     }
     return $src;
 }